syntax = "proto3";

package tast.cros.uwb;

import "google/protobuf/empty.proto";
import "uwb_service.proto";
import "uwb_report.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/uwb";

service UwbService {
    rpc NewClient(google.protobuf.Empty) returns (NewClientResponse) {}
    rpc Enable(google.protobuf.Empty) returns (EnableResponse) {}
    rpc Disable(google.protobuf.Empty) returns (DisableResponse) {}
    rpc InitSession(InitSessionRequest) returns (InitSessionResponse) {}
    rpc DeinitSession(DeinitSessionRequest) returns (DeinitSessionResponse) {}
    rpc StartRanging(StartRangingRequest) returns (StartRangingResponse) {}
    rpc StopRanging(StopRangingRequest) returns (StopRangingResponse) {}
    rpc SetLoggerMode(SetLoggerModeRequest) returns (SetLoggerModeResponse) {}
    rpc SessionParams(SessionParamsRequest) returns (SessionParamsResponse) {}
    rpc Reconfigure(ReconfigureRequest) returns (ReconfigureResponse) {}
    rpc UpdateControllerMulticastList(UpdateControllerMulticastListRequest) returns (UpdateControllerMulticastListResponse) {}
    rpc GetFiraRangingReports(FiraReportRequest) returns (FiraReportResponse) {}
}

message FiraReportRequest {
    uint32 sessionID = 1;
    uint32 timeInSeconds =  2;
}

message FiraReportResponse {
    map<uint64, RangingResult> rangingResults = 1;
}

message NewClientResponse {
    bool success = 1;
}