syntax = "proto3";

package tast.cros.enterpriseconnectors;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/enterpriseconnectors";

message EnrollRequest {
  string user = 1;
  string pass = 2;
  string signinProfileTestExtensionManifestKey = 3;
}

message VerifyDeviceTrustPolicyRequest { string expectedIdPURL = 1; }

message InitiateSamlLoginRequest {
  string signinProfileTestExtensionManifestKey = 1;
}

message GaiaLoginRequest {
  string user = 1;
  string pass = 2;
}

message CheckFakeIdPStatusRequest {
  bool expected = 1;
  bool isInSession = 2;
}

// DeviceTrustService provides RPC methods to run device trust related
// operations
service DeviceTrustService {
  rpc Enroll(EnrollRequest) returns (google.protobuf.Empty) {}
  rpc VerifyDeviceTrustPolicy(VerifyDeviceTrustPolicyRequest)
      returns (google.protobuf.Empty) {}
  rpc InitiateSamlLogin(InitiateSamlLoginRequest)
      returns (google.protobuf.Empty) {}
  rpc GaiaLogin(GaiaLoginRequest) returns (google.protobuf.Empty) {}
  rpc StartAttestationFlow(google.protobuf.Empty)
      returns (google.protobuf.Empty) {}
  rpc CheckFakeIdPStatus(CheckFakeIdPStatusRequest)
      returns (google.protobuf.Empty) {}
  rpc StopChrome(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}
