# Copyright 2020 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

android_apk("ArcNotificationTest") {
  manifest = "AndroidManifest.xml"
  source_dirs = [ "src" ]
  resource_dirs = [ "res" ]

  # TODO(b/323115785): Update the target sdk to 33+ which requires the explicit
  # permission handling.
  target_sdk_version = "32"
}
