syntax = "proto3";

package tast.cros.enterpriseconnectors;

import "google/protobuf/empty.proto";

option go_package = "chromiumos/tast/services/cros/enterpriseconnectors";

message EnrollRequest {
  string user = 1;
  string pass = 2;
}

message LoginWithFakeIdPRequest {
  string signinProfileTestExtensionManifestKey = 1;
}

message ConnectToFakeIdPRequest {
  string user = 1;
  string pass = 2;
}

message CheckFakeIdPStatusRequest {
  bool expected = 1;
}

// DeviceTrustService provides RPC methods to run device trust related operations
service DeviceTrustService {
  rpc Enroll(EnrollRequest) returns (google.protobuf.Empty) {}
  rpc LoginWithFakeIdP(LoginWithFakeIdPRequest) returns (google.protobuf.Empty) {}
  rpc ConnectToFakeIdP(ConnectToFakeIdPRequest) returns (google.protobuf.Empty) {}
  rpc CheckFakeIdPStatus(CheckFakeIdPStatusRequest) returns (google.protobuf.Empty) {}
  rpc StopChrome(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}
