// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.feedback;

option go_package = "chromiumos/tast/services/cros/feedback";

// UserFeedbackService provides functionalities to retrieve user feedback report.
service UserFeedbackService {
  //  GetUserFeedback retrieves user feedback report.
  rpc GetUserFeedback(GetUserFeedbackRequest) returns (GetUserFeedbackResponse) {}
}

message GetUserFeedbackRequest {
}

message GetUserFeedbackResponse {
  string user_feedback = 1;
}