// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.networkui;

import "google/protobuf/any.proto";
import "google/protobuf/wrappers.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/networkui";

// CrosNetworkConfigService provides functionality to interact with the mojo
// connection of the cros_network_config.
service CrosNetworkConfigService {
  // ConfigureNetwork either configures a new network or updates an existing
  // network configuration.
  rpc ConfigureNetwork(ConfigureNetworkRequest)
      returns (ConfigureNetworkResponse) {}

  // GetNetworkStateList returns an array of states of networks based on the
  // filter.
  rpc GetNetworkStateList(NetworkFilter) returns (GetNetworkStateListResponse) {
  }
}

message ConfigureNetworkRequest {
  // config_properties specifies the configuration of a network
  NetworkTypeConfigProperties config_properties = 1;
  bool shared = 2;
}

message ConfigureNetworkResponse { string guid = 1; }

// NetworkTypeConfigProperties contains properties of a network.
// Currently only the WiFi network is supported.
// It can be further extended by adding other types of network: VPN/Ethernet,
// see: netconfig.NetworkTypeConfigProperties.
message NetworkTypeConfigProperties {
  oneof config_properties { WiFiConfigProperties wifi_config_properties = 1; }

  google.protobuf.BoolValue auto_connect = 2;
}

// WiFiConfigProperties describes properties of WiFi network.
message WiFiConfigProperties {
  string ssid = 1;
  HiddenSSIDMode hidden_ssid_mode = 2;

  // Currently only none/psk are supported.
  // It can be further extended by adding other types of security: EAP,
  // see: netconfig.WiFiConfigProperties.
  oneof security {
    google.protobuf.Any none = 3;
    string psk = 4;
  }
}

// HiddenSSIDMode is the hidden mode of the WiFi network.
enum HiddenSSIDMode {
  Automatic = 0;
  Disabled = 1;
  Enabled = 2;
}

enum NetworkType {
  ALL_NETWORK_TYPE = 0;
  CELLULAR = 1;
  ETHERNET = 2;
  MOBILE = 3;
  TETHER = 4;
  VPN = 5;
  WIRELESS = 6;
  WIFI = 7;
}

enum FilterType {
  ALL_FILTER_TYPE = 0;
  // ACTIVE indicates return active networks. A network is active when its
  // ConnectionStateType != NotConnected.
  ACTIVE = 1;
  // VISIBLE indicates return visible (active, physically connected or
  // in-range) networks. Active networks will be listed first.
  VISIBLE = 2;
  // CONFIGURED indicates return configured (saved) networks.
  CONFIGURED = 3;
}

// NetworkFilter is passed to GetNetworkStateList to filter the list of networks
// returned.
message NetworkFilter {
  NetworkType network = 1;
  FilterType filter = 2;
  int32 limit = 3;
}

message GetNetworkStateListResponse {
  repeated NetworkStateProperties properties = 1;
}

// NetworkStateProperties describes the network state property.
// It can be further extended by adding other properties stated in the netconfig
// package. see: netconfig.NetworkStateProperties.
message NetworkStateProperties {
  string name = 1;
  ConnectionState connection_state = 2;
}

enum ConnectionState {
  // ONLINE indicates the network is connected and internet connectivity is
  // available.
  ONLINE = 0;
  // CONNECTED indicates the network is connected and not in a detected portal
  // state, but internet connectivity may not be available.
  CONNECTED = 1;
  // PORTAL indicates the network is connected but a portal state was
  // detected. Internet connectivity may be limited. Additional details are in
  // PortalState.
  PORTAL = 2;
  // CONNECTING indicates the network is in the process of connecting.
  CONNECTING = 3;
  // NOT_CONNECTED indicates the network is not connected.
  NOT_CONNECTED = 4;
}