// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.networkui;

import "google/protobuf/any.proto";
import "google/protobuf/wrappers.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/networkui";

// CrosNetworkConfigService provides functionality to interact with the mojo
// connection of the cros_network_config.
service CrosNetworkConfigService {
  // ConfigureNetwork either configures a new network or updates an existing
  // network configuration.
  rpc ConfigureNetwork(ConfigureNetworkRequest)
      returns (ConfigureNetworkResponse) {}
}

message ConfigureNetworkRequest {
  // config_properties specifies the configuration of a network
  NetworkTypeConfigProperties config_properties = 1;
  bool shared = 2;
}

message ConfigureNetworkResponse { string guid = 1; }

// NetworkTypeConfigProperties contains properties of a network.
// Currently only the WiFi network is supported.
// It can be further extended by adding other types of network: VPN/Ethernet,
// see: netconfig.NetworkTypeConfigProperties.
message NetworkTypeConfigProperties {
  oneof config_properties { WiFiConfigProperties wifi_config_properties = 1; }

  google.protobuf.BoolValue auto_connect = 2;
}

// WiFiConfigProperties describes properties of WiFi network.
message WiFiConfigProperties {
  string ssid = 1;
  HiddenSSIDMode hidden_ssid_mode = 2;

  // Currently only none/psk are supported.
  // It can be further extended by adding other types of security: EAP,
  // see: netconfig.WiFiConfigProperties.
  oneof security {
    google.protobuf.Any none = 3;
    string psk = 4;
  }
}

// HiddenSSIDMode is the hidden mode of the WiFi network.
enum HiddenSSIDMode {
  Automatic = 0;
  Disabled = 1;
  Enabled = 2;
}
