// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package hwsec

import (
	"context"

	"go.chromium.org/tast-tests/cros/common/hwsec"
	"go.chromium.org/tast-tests/cros/local/bundles/cros/hwsec/fixture"
	"go.chromium.org/tast-tests/cros/local/bundles/cros/hwsec/util"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         CrossVersionChromeLogin,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Verifies chrome login functionality across the version",
		Contacts: []string{
			"cros-hwsec@chromium.org",
			"chingkang@google.com",
		},
		// ChromeOS > Platform > System > Hardware Security > HwSec AP
		BugComponent: "b:1188704",
		Attr:         []string{"group:hw_agnostic"},
		// TODO(b/249934249): Add the gsc version test after we enabled the ti50-emulator.
		SoftwareDeps: []string{"chrome", "tpm2_simulator"},
		Params: []testing.Param{
			// Parameters generated by cross_version_test.go. DO NOT EDIT.
			{
				Name:      "current",
				Fixture:   "crossVersionCurrent",
				ExtraAttr: []string{"group:mainline", "informational"},
			}, {
				Name:              "ti50_r112",
				Fixture:           "crossVersionTi50R112",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "gsc"},
			}, {
				Name:              "ti50_r113",
				Fixture:           "crossVersionTi50R113",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "gsc"},
			}, {
				Name:              "ti50_r114",
				Fixture:           "crossVersionTi50R114",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "gsc"},
			}, {
				Name:              "tpm2_r88",
				Fixture:           "crossVersionTpm2R88",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r89",
				Fixture:           "crossVersionTpm2R89",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r90",
				Fixture:           "crossVersionTpm2R90",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r91",
				Fixture:           "crossVersionTpm2R91",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r92",
				Fixture:           "crossVersionTpm2R92",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r93",
				Fixture:           "crossVersionTpm2R93",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r94",
				Fixture:           "crossVersionTpm2R94",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r96",
				Fixture:           "crossVersionTpm2R96",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r97",
				Fixture:           "crossVersionTpm2R97",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r98",
				Fixture:           "crossVersionTpm2R98",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r99",
				Fixture:           "crossVersionTpm2R99",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r100",
				Fixture:           "crossVersionTpm2R100",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r101",
				Fixture:           "crossVersionTpm2R101",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r102",
				Fixture:           "crossVersionTpm2R102",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r103",
				Fixture:           "crossVersionTpm2R103",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r104",
				Fixture:           "crossVersionTpm2R104",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r105",
				Fixture:           "crossVersionTpm2R105",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r106",
				Fixture:           "crossVersionTpm2R106",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r107",
				Fixture:           "crossVersionTpm2R107",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r108",
				Fixture:           "crossVersionTpm2R108",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r109",
				Fixture:           "crossVersionTpm2R109",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r110",
				Fixture:           "crossVersionTpm2R110",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r111",
				Fixture:           "crossVersionTpm2R111",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r112",
				Fixture:           "crossVersionTpm2R112",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r113",
				Fixture:           "crossVersionTpm2R113",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm2_r114",
				Fixture:           "crossVersionTpm2R114",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"no_tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r96",
				Fixture:           "crossVersionTpmDynamicR96",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r97",
				Fixture:           "crossVersionTpmDynamicR97",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r98",
				Fixture:           "crossVersionTpmDynamicR98",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r99",
				Fixture:           "crossVersionTpmDynamicR99",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r100",
				Fixture:           "crossVersionTpmDynamicR100",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r101",
				Fixture:           "crossVersionTpmDynamicR101",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r102",
				Fixture:           "crossVersionTpmDynamicR102",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r103",
				Fixture:           "crossVersionTpmDynamicR103",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r104",
				Fixture:           "crossVersionTpmDynamicR104",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r105",
				Fixture:           "crossVersionTpmDynamicR105",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r106",
				Fixture:           "crossVersionTpmDynamicR106",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r107",
				Fixture:           "crossVersionTpmDynamicR107",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r108",
				Fixture:           "crossVersionTpmDynamicR108",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r109",
				Fixture:           "crossVersionTpmDynamicR109",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r110",
				Fixture:           "crossVersionTpmDynamicR110",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r111",
				Fixture:           "crossVersionTpmDynamicR111",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r112",
				Fixture:           "crossVersionTpmDynamicR112",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r113",
				Fixture:           "crossVersionTpmDynamicR113",
				ExtraAttr:         []string{"group:mainline", "informational"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			}, {
				Name:              "tpm_dynamic_r114",
				Fixture:           "crossVersionTpmDynamicR114",
				ExtraAttr:         []string{"group:mainline"},
				ExtraSoftwareDeps: []string{"tpm_dynamic", "no_gsc"},
			},
		},
	})
}

// testChromeLogin verifies the login functionality via Chrome Login Screen.
func testChromeLogin(ctx context.Context, config *util.CrossVersionLoginConfig) error {
	authConfig := config.AuthConfig
	username := authConfig.Username

	// The smart card authentication is not currently supported in this subtest,
	// as it'd require loading fake smart card middleware extensions in Chrome.
	if authConfig.AuthType != hwsec.PassAuth {
		return nil
	}

	// Check password login.
	opts := []chrome.Option{
		chrome.FakeLogin(chrome.Creds{User: username, Pass: authConfig.Password}),
		chrome.KeepState(),
	}
	cr, err := chrome.New(ctx, opts...)
	if err != nil {
		return errors.Wrap(err, "failed to log in with password")
	}
	// TODO(b/237120336): Check cryptohome was not recreated, by reading some file
	// that was previously put into the snapshot.
	if err := cr.Close(ctx); err != nil {
		return errors.Wrap(err, "failed to log out after password login")
	}
	// TODO(b/237120336): Check PIN login as well.

	return nil
}

func CrossVersionChromeLogin(ctx context.Context, s *testing.State) {
	fixtureData := s.FixtValue().(*fixture.CrossVersionLoginFixture)
	for _, config := range fixtureData.ConfigList {
		if config.VaultFSType == util.NoVaultFS {
			continue
		}
		if err := testChromeLogin(ctx, &config); err != nil {
			s.Fatal("Failed to test chrome login: ", err)
		}
	}
}
