// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.common.perf.perfpb;
import "google/protobuf/timestamp.proto";

option go_package = "go.chromium.org/tast-tests/cros/common/perf/perfpb";

enum Direction {
  SMALLER_IS_BETTER = 0;
  BIGGER_IS_BETTER = 1;
}

message Value {
  string name = 1;
  string variant = 2;
  string unit = 3;
  Direction direction = 4;
  bool multiple = 5;
  repeated double value = 6;
  string interval = 7;
  bool has_start_ts = 8;
  google.protobuf.Timestamp start_ts = 9;
}

message Values {
  repeated Value values = 1;
}