// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package video

import (
	"context"
	"os"
	"time"

	"chromiumos/tast/local/bundles/cros/video/videovars"
	"chromiumos/tast/local/coords"
	"chromiumos/tast/local/media/encoding"
	"chromiumos/tast/local/media/videotype"
	"chromiumos/tast/shutil"
	"chromiumos/tast/testing"
	"chromiumos/tast/testing/hwdep"
)

// platformInteropParam is used to describe the config used to run each test.
type platformInteropParam struct {
	filename              string                 // Input file name. This will be decoded to produce the uncompressed input to the encoder binary, so it can come in any format/container.
	size                  coords.Size            // Width x Height in pixels of the input file.
	fps                   int                    // FPS of the input file.
	encoderCommand        string                 // The encoder to be used. This should be relative to /usr/local/bin.
	encoderCommandBuilder commandBuilderFn       // Function to create the encoder command line.
	decoderCommand        string                 // Command line decoder binary
	decoderArgsBuilder    commandBuilderDecodeFn // Function to create the decoder command line arguments.
}

func init() {
	testing.AddTest(&testing.Test{
		Func:         PlatformInterop,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Verifies interoperability of sw/hw encoder/decoder combinations at the platform (i.e. ChromeOS drivers) level",
		Contacts: []string{
			"mcasas@chromium.org",
			"chromeos-gfx-video@google.com",
		},
		Fixture: "graphicsNoChrome",
		Attr:    []string{"group:graphics", "graphics_video", "graphics_perbuild"},
		Timeout: 30 * time.Minute,
		Params: []testing.Param{
			// Parameters generated by platform_interop_test.go. DO NOT EDIT.
			{
				Name: "vp8_180_sw_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vpxenc",
					encoderCommandBuilder: argsVpxenc,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    vp8decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_dec_vp8_1080_30"},
			},
			{
				Name: "vp8_180_sw_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vpxenc",
					encoderCommandBuilder: argsVpxenc,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_dec_vp8_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
			{
				Name: "vp8_180_vaapi_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vp8enc",
					encoderCommandBuilder: vp8argsVAAPI,
					decoderCommand:        "vpxdec",
					decoderArgsBuilder:    vpxDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_vp8_1080_30"},
			},
			{
				Name: "vp8_180_vaapi_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vp8enc",
					encoderCommandBuilder: vp8argsVAAPI,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    vp8decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_vp8_1080_30", "autotest-capability:hw_dec_vp8_1080_30"},
			},
			{
				Name: "vp8_180_v4l2sf_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "vpxdec",
					decoderArgsBuilder:    vpxDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_vp8_1080_30"},
			},
			{
				Name: "vp8_180_v4l2sf_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_vp8_1080_30", "autotest-capability:hw_dec_vp8_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
			{
				Name: "vp9_180_sw_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vpxenc",
					encoderCommandBuilder: argsVpxenc,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    vp9decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_dec_vp9_1080_30"},
			},
			{
				Name: "vp9_180_sw_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vpxenc",
					encoderCommandBuilder: argsVpxenc,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_dec_vp9_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
			{
				Name: "vp9_180_vaapi_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vp9enc",
					encoderCommandBuilder: vp9argsVAAPI,
					decoderCommand:        "vpxdec",
					decoderArgsBuilder:    vpxDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_vp9_1080_30"},
			},
			{
				Name: "vp9_180_vaapi_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "vp9enc",
					encoderCommandBuilder: vp9argsVAAPI,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    vp9decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_vp9_1080_30", "autotest-capability:hw_dec_vp9_1080_30"},
			},
			{
				Name: "vp9_180_v4l2sf_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "vpxdec",
					decoderArgsBuilder:    vpxDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_vp9_1080_30"},
			},
			{
				Name: "vp9_180_v4l2sf_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_vp9_1080_30", "autotest-capability:hw_dec_vp9_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
			{
				Name: "h264_180_sw_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "openh264enc",
					encoderCommandBuilder: argsOpenh264enc,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    h264decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_dec_h264_1080_30"},
			},
			{
				Name: "h264_180_sw_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "openh264enc",
					encoderCommandBuilder: argsOpenh264enc,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_dec_h264_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
			{
				Name: "h264_180_vaapi_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "h264encode",
					encoderCommandBuilder: h264argsVAAPI,
					decoderCommand:        "openh264dec",
					decoderArgsBuilder:    openh264DecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_h264_1080_30"},
			},
			{
				Name: "h264_180_vaapi_to_vaapi",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "h264encode",
					encoderCommandBuilder: h264argsVAAPI,
					decoderCommand:        "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder:    h264decodeVAAPIargs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"vaapi", "autotest-capability:hw_enc_h264_1080_30", "autotest-capability:hw_dec_h264_1080_30"},
			},
			{
				Name: "h264_180_v4l2sf_to_sw",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "openh264dec",
					decoderArgsBuilder:    openh264DecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_h264_1080_30"},
			},
			{
				Name: "h264_180_v4l2sf_to_v4l2sf",
				Val: platformInteropParam{
					filename:              "gipsrestat-320x180.vp9.webm",
					size:                  coords.NewSize(320, 180),
					fps:                   50,
					encoderCommand:        "v4l2_stateful_encoder",
					encoderCommandBuilder: argsV4L2,
					decoderCommand:        "v4l2_stateful_decoder",
					decoderArgsBuilder:    v4l2StatefulDecodeArgs,
				},
				ExtraData:         []string{"gipsrestat-320x180.vp9.webm"},
				ExtraSoftwareDeps: []string{"v4l2_codec", "autotest-capability:hw_enc_h264_1080_30", "autotest-capability:hw_dec_h264_1080_30"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding()),
			},
		},
	})
}

// PlatformInterop verifies interoperability of combinations of SW/HW encoders
// and decoders.The encoder input is an uncompressed YUV file which would be
// too large to be stored, so it is produced on the fly from
// platformInteropParam.filename. The result YUV file is compressed using
// platformInteropParam.encoderCommand and the decoded using
// platformInteropParam.decoderCommand.
func PlatformInterop(ctx context.Context, s *testing.State) {
	testOpt := s.Param().(platformInteropParam)

	yuvFile, err := encoding.PrepareYUV(ctx, s.DataPath(testOpt.filename), videotype.I420, coords.NewSize(0, 0) /* placeholder size */)
	if err != nil {
		s.Fatal("Failed to prepare YUV file: ", err)
	} else if videovars.ShouldRemoveArtifacts(ctx) {
		defer os.Remove(yuvFile)
	}

	encoderCommand, encodedFile, _, err := testOpt.encoderCommandBuilder(ctx, s.TestName(), testOpt.encoderCommand, yuvFile, testOpt.size, testOpt.fps)
	if err != nil {
		s.Fatal("Failed to construct the encoder command line: ", err)
	}

	s.Log("Running: ", shutil.EscapeSlice(encoderCommand))
	_, err = runBinary(ctx, s.OutDir(), encoderCommand[0], encoderCommand[1:]...)
	if err != nil {
		s.Fatal("Failed to run binary: ", err)
	} else if videovars.ShouldRemoveArtifacts(ctx) {
		defer os.Remove(encodedFile)
	}

	// Create a temporary md5 checksum log file. This is needed for decoding.
	// TODO(b/251256531): Compare the resulting MD5SUM values with the reference
	// ones, i.e. those decoded by a SW decoder like e.g. vpxdec.
	f, err := os.CreateTemp("", "frame_checksums.*.md5")
	if err != nil {
		s.Fatal("Failed to create md5 checksum log: ", err)
	}
	md5LogPath := f.Name()
	if err := f.Close(); err != nil {
		s.Fatal("Failed to close md5 checksum log: ", err)
	}
	defer os.Remove(md5LogPath)

	decoderCommandArgs := testOpt.decoderArgsBuilder(ctx, encodedFile, md5LogPath)
	if err != nil {
		s.Fatal("Failed to construct the decoder command line: ", err)
	}

	s.Logf("Running: %s %s ", testOpt.decoderCommand, shutil.EscapeSlice(decoderCommandArgs))
	_, err = runBinary(ctx, s.OutDir(), testOpt.decoderCommand, decoderCommandArgs...)
	if err != nil {
		s.Fatal("Failed to run binary: ", err)
	}
}

// vpxDecodeArgs provides the arguments to use with vpxdec decoding binary exe.
func vpxDecodeArgs(ctx context.Context, filename, md5OutputPath string) []string {
	// With --md5 and -o options the md5 of each frame is calculated but frame
	// files are not created.
	return []string{"-o", "output%w_%h_%4.yuv", "--i420", "--md5", filename}
}

// openh264DecodeArgs provides the arguments to use with openh264dec decoding binary exe.
func openh264DecodeArgs(ctx context.Context, filename, md5OutputPath string) []string {
	return []string{filename, filename + ".yuv"}
}
