// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.tape;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/tape";

// TapeService provides functions for use with the TAPE GCP.
service Service {
  // GetDeviceID retrieves the deviceID used for deprovisioning from the DuT.
  rpc GetDeviceID(google.protobuf.Empty) returns (GetDeviceIDResponse) {}
}

message GetDeviceIDResponse {
  string deviceID = 1;
  string customerID = 2;
}
