// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Package metadata contains two json files: autogenerated-metadata.json, and
// tests-info.json. tests-info.json contains user defined metadata for each
// performance CUJ test variant. On every update to a CUJ that would affect the
// metadata (name changes, fixture changes, variant additions, version changes),
// we need to run `python3 tools/generate_cuj_metadata.py`, which will scrape
// our CUJ go files, and combine the scraped information with the information
// found in tests-info.json, and output the result to
// autogenerated-metadata.json. The goal is the use autogenerated-metadata.json
// to add important test context to our testing dashboard at go/tps-dashboard.
package metadata
