// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Package mitmproxy implements mitmproxy on Chrome for testing.
package mitmproxy

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"go.chromium.org/tast-tests/cros/common/action"
	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/cryptohome"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

const (
	// DefaultListenPort is the default port that the proxy is listening.
	DefaultListenPort = 4040
	// DefaultBinaryPath is the default binary path to be used.
	DefaultBinaryPath = "/usr/local/bin/mitmdump"
)

const (
	defaultConfDir = "/usr/local/tmp/mitmproxy"
	certFile       = "mitmproxy-ca-cert.pem"
	defaultDumpDir = "/usr/local/tmp/mitmproxy"
)

// MitmProxy represents a structure of mitmproxy.
type MitmProxy struct {
	binaryPath   string
	port         int
	dumpDir      string
	confDir      string
	compressDump bool
}

// New creates a new MitmDump instance with default configuration.
func New() *MitmProxy {
	return &MitmProxy{
		binaryPath:   DefaultBinaryPath,
		port:         DefaultListenPort,
		confDir:      defaultConfDir,
		dumpDir:      defaultDumpDir,
		compressDump: true,
	}
}

// SetBinaryPath sets the binary path of mitmproxy.
func (mp *MitmProxy) SetBinaryPath(binaryPath string) *MitmProxy {
	mp.binaryPath = binaryPath
	return mp
}

// SetListenPort sets the listening port of mitmproxy.
func (mp *MitmProxy) SetListenPort(port int) *MitmProxy {
	mp.port = port
	return mp
}

// ListenPort returns the port mitmproxy intends to listen on.
func (mp *MitmProxy) ListenPort() int {
	return mp.port
}

// SetDumpDir sets the traffic dumping path.
func (mp *MitmProxy) SetDumpDir(path string) *MitmProxy {
	mp.dumpDir = path
	return mp
}

// SetConfDir sets the mitmproxy config path.
func (mp *MitmProxy) SetConfDir(confDir string) *MitmProxy {
	mp.confDir = confDir
	return mp
}

// Start launches the mitmproxy and returns a cleanup function and root certificate file path.
func (mp *MitmProxy) Start(ctx context.Context) (action.Action, string, error) {
	nowStr := time.Now().Format("20230731-150405")
	dumpFileName := fmt.Sprintf("mitmproxy_%s.dump", nowStr)
	dumpFilePath := filepath.Join(mp.dumpDir, dumpFileName)

	if err := os.MkdirAll(mp.confDir, 0700); err != nil {
		return nil, "", errors.Wrapf(err, "failed to create %q for mitmdump config", mp.confDir)
	}
	if err := os.MkdirAll(mp.dumpDir, 0700); err != nil {
		return nil, "", errors.Wrapf(err, "failed to create %q for mitmdump dumping", mp.dumpDir)
	}

	cmd := testexec.CommandContext(ctx, mp.binaryPath,
		"--set", fmt.Sprintf("listen_port=%d", mp.port),
		"--set", fmt.Sprintf("confdir=%s", mp.confDir),
		"-w", dumpFilePath)

	if err := cmd.Start(); err != nil {
		return nil, "", errors.Wrap(err, "failed to launch proxy server")
	}

	// The certificate is generated on first time launching mitmproxy.
	certFilePath := mp.RootCACertPath()
	if err := testing.Poll(ctx, func(ctx context.Context) error {
		if _, err := os.Stat(certFilePath); err != nil {
			return errors.Wrapf(err, "%s is unavailable", certFilePath)
		}
		return nil
	}, &testing.PollOptions{Timeout: 20 * time.Second}); err != nil {
		return nil, "", errors.Wrapf(err, "failed to locate cert file at %q, maybe the proxy server is not launched successfully", certFilePath)
	}

	testing.ContextLog(ctx, "Mitmproxy is successfully launched. Streaming to ", dumpFilePath)

	cleanupFunc := func(ctx context.Context) error {
		var cleanupErrs []error
		// Terminate mitmproxy.
		if err := cmd.Kill(); err != nil {
			cleanupErrs = append(cleanupErrs, errors.Wrap(err, "failed to terminate mitmproxy"))
		}

		// Compress dump file.
		if mp.compressDump {
			targetTar := dumpFilePath + ".tar.gz"
			if err := testexec.CommandContext(ctx, "tar", "-czf", targetTar, "-C", mp.dumpDir, dumpFileName, "--remove-files").Run(testexec.DumpLogOnError); err != nil {
				cleanupErrs = append(cleanupErrs, errors.Wrap(err, "failed to compress mitmproxy dump"))
			}
		}

		// Remove config files, such as certificates generated by Mitmproxy launch.
		if err := os.RemoveAll(mp.confDir); err != nil {
			cleanupErrs = append(cleanupErrs, errors.Wrap(err, "failed to clean mitmproxy config"))
		}
		return errors.Join(cleanupErrs...)
	}

	return cleanupFunc, certFilePath, nil
}

// RootCACertPath returns the root CA certificate file path of the launched mitmproxy.
func (mp *MitmProxy) RootCACertPath() string {
	return filepath.Join(mp.confDir, certFile)
}

// ImportRootCertificate imports the proxy root certificate to user trusted cert store using certutil cmd.
func ImportRootCertificate(ctx context.Context, normalizedUser, certFilePath string) error {
	userHome, err := cryptohome.UserPath(ctx, normalizedUser)
	if err != nil {
		return errors.Wrap(err, "failed to get user path")
	}

	cmd := testexec.CommandContext(ctx, "certutil", "-d", fmt.Sprintf("sql:%s/.pki/nssdb", userHome),
		"-A", "-t", "C,C,C", "-n", "mitmproxy", "-i", certFilePath)
	if err := cmd.Run(); err != nil {
		cmd.DumpLog(ctx)
		return errors.Wrap(err, "failed to import certificate")
	}
	return nil
}
