// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package inputs

import (
	"bufio"
	"context"
	"os"
	"strconv"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/common/action"
	"go.chromium.org/tast-tests/cros/common/xmlrpc"
	"go.chromium.org/tast/core/dut"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/ssh"
	"go.chromium.org/tast/core/testing"
)

const (
	xIdx        = 0
	yIdx        = 1
	pressureIdx = 2
	timeIdx     = 3

	maxNumParts = 5
)

// TouchHostConnectionManager manages ssh connection information between the drone and touchhost.
type TouchHostConnectionManager struct {
	SSHConn                *ssh.Conn
	SSHOptions             *ssh.Options
	TouchhostPortForwarder *ssh.Forwarder
}

// CalibrationData contains data generated by a calibration test run on each HMR setup. It is used by the full image analyser to correct data errors.
type CalibrationData struct {
	RotationError                  float64 // angle in radians. Positive = anti-clockwise, negative = clockwise.
	SkewErrorRelativeToScreenWidth float64 // % of screen width that x axis is shifted when y = ymax. Positive = right shift, negative = left shift.
	ScaleFactorX                   float64 // ratio of pixel width/mm width.
	ScaleFactorY                   float64 // ratio of pixel height/mm height.
	OffsetX                        float64 // in mm.
	OffsetY                        float64 // in mm.
}

// physicalScreenSize contains the dimensions of a DUT's screen in mm.
type physicalScreenSize struct {
	height float64
	width  float64
}

var (
	hmrTouchhostHostname = testing.RegisterVarString(
		"inputs.hmr_touchhost_hostname",
		"",
		"Hostname for HMR Touchhost Device")

	hmrTouchhostPort = testing.RegisterVarString(
		"inputs.hmr_touchhost_port",
		"9992",
		"Port for xmlrpc server on HMR Touchhost")

	// Retrieving the dimensions of the DUT's screen directly from it is sometimes
	// inaccurate. DUT dimensions should be added to this list as HMR's are
	// onboarded that use them.
	screenSizesInMM = map[string]physicalScreenSize{
		"morphius": physicalScreenSize{height: 167.2, width: 292.6},
		"kodama":   physicalScreenSize{height: 217.3, width: 135.3},
		"kohaku":   physicalScreenSize{height: 165.2, width: 293.8},
	}
)

// GetScreenDimensions queries the screen size map, and returns the height and
// width, respectively, of the model's screen.
func GetScreenDimensions(model string) (float64, float64, error) {
	screenSize, exists := screenSizesInMM[model]
	if !exists {
		return -1, -1, errors.Errorf("model: %v does not exist in the screen size map", model)
	}
	return screenSize.height, screenSize.width, nil
}

// ParseHMRRuntimeVariables parses and returns the Touchhost hostname and port runtime variables for HMR tests.
func ParseHMRRuntimeVariables(d *dut.DUT) (string, int, error) {
	var touchhostHostname string
	if hmrTouchhostHostname.Value() == "" {
		hostName := d.HostName()
		splitName := strings.Split(hostName, ".")
		splitName[0] = strings.Split(splitName[0], ":")[0]
		splitName[0] = splitName[0] + "-touchhost"
		touchhostHostname = strings.Join(splitName, ".")
	} else {
		touchhostHostname = hmrTouchhostHostname.Value()
	}

	touchhostPort, err := strconv.Atoi(hmrTouchhostPort.Value())
	if err != nil {
		return "", 0, errors.Wrapf(err, "failed to convert inputs.hmr_touchhost_port with value: %s to integer", hmrTouchhostPort.Value())
	}

	return touchhostHostname, touchhostPort, nil
}

// NewHMRInterface creates an XMLRPC interface through which RPC calls can be made to the HMR Touchhost.
func NewHMRInterface(ctx context.Context, host string, port int) (*xmlrpc.CommonRPCInterface, error) {
	hmrInterface := xmlrpc.NewCommonRPCInterface(xmlrpc.New(host, port), "")

	err := action.Retry(5, func(ctx context.Context) error {
		testing.ContextLogf(ctx, "Attempting to connect to HMR Touchhost: %s:%d", host, port)
		deadline, _ := ctx.Deadline()
		timeUntil := time.Until(deadline)
		testing.ContextLogf(ctx, "time until deadline: %s", timeUntil)
		err := hmrInterface.RPC("TestConnection").Timeout(30 * time.Second).Call(ctx)
		if err != nil {
			return errors.Wrap(err, "failed to communicate with HMR device with a call to TestConnection on HMR Touchhost")
		}
		return nil
	}, 30*time.Second)(ctx)

	return hmrInterface, err
}

// RemoveCommonDataErrorsFromStylusLogFile checks for common touch log data errors and generates a cleaned touch log file with these errors removed.
func RemoveCommonDataErrorsFromStylusLogFile(rawFilePath, cleanedFilePath string) error {
	readFile, err := os.Open(rawFilePath)
	if err != nil {
		return err
	}
	defer readFile.Close()

	writeFile, err := os.Create(cleanedFilePath)
	if err != nil {
		return err
	}
	defer writeFile.Close()

	scanner := bufio.NewScanner(readFile)
	writer := bufio.NewWriter(writeFile)

	// All touch log csv files must contain "x,y,pressure,time" as their header.
	scanner.Scan()
	line := scanner.Text()
	if line != "x,y,pressure,time" {
		return errors.New(rawFilePath + " does not contain csv header")
	}
	if _, err = writer.WriteString(line + "\n"); err != nil {
		return err
	}

	// There are two common data errors that are being checked for:

	// The prefix error occurs when an number of rows at the start of a touch log file are missing elements.
	// Example:
	// 	10216,5164,,1691552057.683170,
	//	10216,,,1691552067.683172,
	// These errors must occur before the first row with all elements.
	// prefixDataChecked refers to whether a row with all elements has been read yet.
	// If a row missing elements is read after a row with all elements has been read, a fatal error is triggered.

	// The suffix error occurs when the final row at the end of a touch log file excludes some delimiters & elements. (The last element may also be only partially written)
	// Example:
	// 8200,680
	// suffixDataChecked refers to whether this row has been read yet.
	// If any row is read after this row, a fatal error is triggered.

	prefixDataChecked := false
	suffixDataChecked := false
	for scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return err
		}
		line := scanner.Text()
		splitLine := strings.Split(line, ",")
		if len(splitLine) == maxNumParts {
			if splitLine[xIdx] == "" || splitLine[yIdx] == "" || splitLine[pressureIdx] == "" || splitLine[timeIdx] == "" {
				if !prefixDataChecked {
					continue
				} else {
					return errors.New(rawFilePath + " contains rows with empty elements")
				}
			} else {
				prefixDataChecked = true
			}
		} else if len(splitLine) < maxNumParts {
			if !suffixDataChecked {
				suffixDataChecked = true
				continue
			} else {
				return errors.New(rawFilePath + " contains rows with less than 4 elements")
			}
		} else {
			return errors.New(rawFilePath + " contains a row with excess columns")
		}
		if _, err = writer.WriteString(line + "\n"); err != nil {
			return err
		}
	}
	writer.Flush()
	return nil
}

// CreateSSHTunnelToTouchhost creates a ssh tunnel between localhost port 9992 to TouchhostD's port on the Touchhost.
func CreateSSHTunnelToTouchhost(ctx context.Context, touchhostHostname string, touchhostPort int, d *dut.DUT) (*TouchHostConnectionManager, error) {
	sshOptions := &ssh.Options{
		KeyDir:  d.KeyDir(),
		KeyFile: d.KeyFile(),
	}

	err := ssh.ParseTarget(touchhostHostname, sshOptions)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to parse ssh target touchhost host (%s)", touchhostHostname)
	}
	sshConn, err := ssh.New(ctx, sshOptions)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to connect to touchhost host (%s) over ssh", touchhostHostname)
	}

	onFwdError := func(err error) {
		testing.ContextLogf(ctx, "ssh forwarding error for touchhostd host %s: %s", touchhostHostname, err)
	}

	// TODO: b/343532845 - Handle finding a new local port if a port collision occurs.
	// Forwards TouchHostD's port on TouchHost to 9992 on localhost.
	touchhostPortForwarder, err := sshConn.ForwardLocalToRemote("tcp", "127.0.0.1:9992", "127.0.0.1:"+strconv.Itoa(touchhostPort), onFwdError)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to port forward touchhost (%s) port (%d)", touchhostHostname, touchhostPort)
	}
	return &TouchHostConnectionManager{SSHConn: sshConn, SSHOptions: sshOptions, TouchhostPortForwarder: touchhostPortForwarder}, nil
}
