// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package inputs

import "math"

const (
	minReferencePathSize = 10
)

// FullImageResult contains the output of the HMR full image sliding analysis.
type FullImageResult struct {
	Passed      bool
	TotalMSE    float64 // total mean squared error of all paths.
	Epsilon     float64 // maximum distance between start points on reference and result paths in mm.
	PathResults []*PathResult
}

// PathResult contains the output of the HMR full image sliding analysis over a single path.
type PathResult struct {
	PathMSE              float64 // average mean squared error for all calculations on path.
	SuccessfulFitRate    float64 // percentage of curve fittings performed with an r2 value greater than the threshold.
	NumberOfCalculations float64 // number of curve fitting calculations performed.
	ReferencePathLength  int
	ResultPathLength     int
	BubbleRadius         float64 // value in (mm) used in the sliding window analysis for this path.
}

func euclideanDistance(pointA, pointB *hmrNode) float64 {
	return math.Sqrt(math.Pow(pointA.coorX-pointB.coorX, 2) + math.Pow(pointA.coorY-pointB.coorY, 2))
}

// extractReferencePaths extracts a set of paths from reference point data.
// A path is a contiguous sets of points where pressure > 0.
// The reference dataset is generated by manually running a script on a DUT,
// which collects its touch events. It is always expected that the reference
// dataset ends with a point with pressure == 0.
func extractReferencePaths(points []*hmrNode) [][]*hmrNode {
	var paths [][]*hmrNode
	var path []*hmrNode

	for _, point := range points {
		if point.pressure > 0 {
			if len(path) > 0 {
				// If pressure > 0 and an existing path is open, add this point to it.
				previousPoint := path[len(path)-1]
				if previousPoint.coorX != point.coorX || previousPoint.coorY != point.coorY {
					path = append(path, point)
				}
			} else {
				// If pressure > 0 and there is not an existing path open. Create a new one.
				path = append(path, point)
			}
		} else {
			if len(path) > 0 {
				if len(path) > minReferencePathSize {
					// If pressure == 0, and an existing path is open. Close the path, and add it to list of paths.
					paths = append(paths, path)
				}
				path = []*hmrNode{}
			} else {
				// If pressure == 0, and there isn't a path open. Do nothing.
				continue
			}
		}
	}

	return paths
}
