syntax = "proto3";

package tast.cros.printer;

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/printer";

service ChromePrintingService {
  // GetPrinters returns the list of available printers using the
  // chrome.printing.getPrinters API method.
  rpc GetPrinters(google.protobuf.Empty) returns (GetPrintersResponse) {}

  // SubmitJob calls the chrome.printing.submitJob() API method. It takes a
  // submitJobRequest and returns the jobID of the submitted job.
  rpc SubmitJob(SubmitJobRequest) returns (SubmitJobResponse) {}

  // GetJobStatus calls the chrome.printing.getJobStatus(jobId) API method, it
  // takes the jobId returned by SubmitJob. Returns an error if the jobId
  // doesn't exist, otherwise returns the status of the job.
  rpc GetJobStatus(GetJobStatusRequest) returns (GetJobStatusResponse) {}

  // CancelJob calls the chrome.printing.CancelJob(jobId) to cancel a submitted
  // job. It takes the jobId returned by SubmitJob, returns an error if there
  // are no active print jobs with the given jobId.
  rpc CancelJob(CancelJobRequest) returns (google.protobuf.Empty) {}

  // GetPrinterInfo retrieves the capabilities and status for a specified
  // printer.
  //
  // Takes a GetPrinterInfoRequest containing the printer's ID and returns a
  // GetPrinterInfoResponse with its printer status and capabilities.
  rpc GetPrinterInfo(GetPrinterInfoRequest) returns (GetPrinterInfoResponse) {}

  // Close releases the Chrome instance initialized after calling any other
  // ChromePrintingService method.
  rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

// GetPrintersResponse contains a list of available printers.
message GetPrintersResponse { repeated Printer printers = 1; }

// Printer represents a single printer with its properties.
message Printer {
  string description = 1;
  string id = 2;
  bool isDefault = 3;
  string name = 4;
  string uri = 5;
  int32 recentlyUsedRank = 6;
  string source = 7;
}

// ---------------------------------------------------------------------------
// NOTE: The following messages related to the print ticket (Job, Ticket, Print,
// etc.) use snake_case for their field names (e.g., `media_size`).
// This is a deliberate choice to directly map to the JSON format expected by
// the chrome.printing.submitJob API, simplifying integration.
// Cloud Job Ticket: https://developers.google.com/cloud-print/docs/cdd#cjt
//
// Other messages in this file follow the standard camelCase convention.
// ---------------------------------------------------------------------------

message SubmitJobRequest { Job job = 1; }

message Job {
  string title = 1;
  Ticket ticket = 2;
  string contentType = 3;
  string document = 4;
  string printerId = 5;
}

message Ticket {
  string version = 1;
  Print print = 2;
}

message Print {
  MediaSize media_size = 1;
  Copies copies = 2;
  PageOrientation page_orientation = 3;
  Color color = 4;
  FitToPage fit_to_page = 5;
  Collate collate = 6;
  Duplex duplex = 7;
  Dpi dpi = 8;
  ReverseOrder reverse_order = 9;
}

message Color {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    STANDARD_MONOCHROME = 1;
    STANDARD_COLOR = 2;
  }
  optional Type type = 1;
}

message PageOrientation {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    PORTRAIT = 1;
    LANDSCAPE = 2;
  }
  optional Type type = 1;
}

message Copies { int32 copies = 1; }

message MediaSize {
  int32 height_microns = 1;
  int32 width_microns = 2;
}

message FitToPage {
  enum Type {
    NO_FITTING = 0;
    FIT_TO_PAGE = 1;
    GROW_TO_PAGE = 2;
    SHRINK_TO_PAGE = 3;
    FILL_PAGE = 4;
    AUTO = 5;
  }
  optional Type type = 1;
}

message Collate { optional bool collate = 1; }

message Duplex {
  enum Type {
    NO_DUPLEX = 0;
    LONG_EDGE = 1;
    SHORT_EDGE = 2;
  }
  optional Type type = 1;
}

message Dpi {
  int32 horizontal_dpi = 1;
  int32 vertical_dpi = 2;
}

message ReverseOrder { optional bool reverse_order = 1; }

message SubmitJobResponse { string jobId = 1; }

message GetJobStatusRequest { string jobId = 1; }

message GetJobStatusResponse { JobStatus status = 1; }

enum JobStatus {
  JOB_STATUS_UNSPECIFIED = 0;
  PENDING = 1;
  IN_PROGRESS = 2;
  FAILED = 3;
  CANCELED = 4;
  PRINTED = 5;
}

message CancelJobRequest { string jobId = 1; }

message GetPrinterInfoRequest { string printerId = 1; }

message GetPrinterInfoResponse {
  Capabilities capabilities = 1;
  PrinterStatus status = 2;
}

message Capabilities {
  string version = 1;
  google.protobuf.Struct printer = 2;
}

// See Chrome Printing API PrinterStatus:
// https://developer.chrome.com/docs/extensions/reference/api/printing#type-PrinterStatus
enum PrinterStatus {
  PRINTER_STATUS_UNKNOWN = 0;
  PRINTER_STATUS_AVAILABLE = 1;
  PRINTER_STATUS_DOOR_OPEN = 2;
  PRINTER_STATUS_TRAY_MISSING = 3;
  PRINTER_STATUS_OUT_OF_INK = 4;
  PRINTER_STATUS_OUT_OF_PAPER = 5;
  PRINTER_STATUS_OUTPUT_FULL = 6;
  PRINTER_STATUS_PAPER_JAM = 7;
  PRINTER_STATUS_STOPPED = 8;
  PRINTER_STATUS_GENERIC_ISSUE = 9;
  PRINTER_STATUS_UNREACHABLE = 10;
  PRINTER_STATUS_EXPIRED_CERTIFICATE = 11;
}
