// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package printer

import (
	"context"

	"go.chromium.org/tast-tests/cros/local/bundles/cros/printer/ippprint"
	"go.chromium.org/tast-tests/cros/local/bundles/cros/printer/pre"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/testing/hwdep"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:     Add,
		Desc:     "Verifies the lp command enqueues print jobs using printscanmgr",
		Contacts: []string{"project-bolton@google.com", "pmoy@chromium.org"},
		// ChromeOS > Platform > baseOS > Printing
		BugComponent: "b:167231",
		Attr: []string{
			"group:mainline",
			"group:paper-io",
			"paper-io_printing",
		},
		SoftwareDeps: []string{"cups", "ghostscript"},
		HardwareDeps: hwdep.D(pre.PrinterSkipUnstableModels),
		Fixture:      "ensureUI",
		Params: []testing.Param{
			// Parameters generated by add_test.go. DO NOT EDIT.
			{
				Name: "epson_software_collate",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonWF3620.ppd",
					PrintFile:    "2page.pdf",
					ExpectedFile: "printer_collate_epson_software_collate_golden.bin",
					Options:      []string{"copies=2", "multiple-document-handling=separate-documents-collated-copies"},
				},
				ExtraData: []string{"2page.pdf", "printer_EpsonWF3620.ppd", "printer_collate_epson_software_collate_golden.bin"},
			}, {
				Name: "epson_software_uncollated",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonWF3620.ppd",
					PrintFile:    "2page.pdf",
					ExpectedFile: "printer_collate_epson_software_uncollated_golden.bin",
					Options:      []string{"copies=2"},
				},
				ExtraData: []string{"2page.pdf", "printer_EpsonWF3620.ppd", "printer_collate_epson_software_uncollated_golden.bin"},
			}, {
				Name: "epson_hardware_collate",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonWFC20590.ppd",
					PrintFile:    "2page.pdf",
					ExpectedFile: "printer_collate_epson_hardware_collate_golden.ps",
					Options:      []string{"copies=2", "multiple-document-handling=separate-documents-collated-copies"},
				},
				ExtraData: []string{"2page.pdf", "printer_EpsonWFC20590.ppd", "printer_collate_epson_hardware_collate_golden.ps"},
			}, {
				Name: "epson_hardware_uncollated",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonWFC20590.ppd",
					PrintFile:    "2page.pdf",
					ExpectedFile: "printer_collate_epson_hardware_uncollated_golden.ps",
					Options:      []string{"copies=2"},
				},
				ExtraData: []string{"2page.pdf", "printer_EpsonWFC20590.ppd", "printer_collate_epson_hardware_uncollated_golden.ps"},
			}, {
				Name: "brother_300dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_brother_printer.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_brother_300dpi_golden.bin",
					Options:      []string{"printer-resolution=300dpi"},
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_brother_printer.ppd", "printer_resolution_brother_300dpi_golden.bin"},
				ExtraSoftwareDeps: []string{"cros_internal"},
			}, {
				Name: "brother_1200dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_brother_printer.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_brother_1200dpi_golden.bin",
					Options:      []string{"printer-resolution=1200dpi"},
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_brother_printer.ppd", "printer_resolution_brother_1200dpi_golden.bin"},
				ExtraSoftwareDeps: []string{"cros_internal"},
			}, {
				Name: "brother_2400x600dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_brother_printer.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_brother_2400x600dpi_golden.bin",
					Options:      []string{"printer-resolution=2400x600dpi"},
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_brother_printer.ppd", "printer_resolution_brother_2400x600dpi_golden.bin"},
				ExtraSoftwareDeps: []string{"cros_internal"},
			}, {
				Name: "lexmark_600dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_Lexmark.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_lexmark_600dpi_golden.ps",
					Options:      []string{"printer-resolution=600dpi"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Lexmark.ppd", "printer_resolution_lexmark_600dpi_golden.ps"},
			}, {
				Name: "lexmark_1200dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_Lexmark.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_lexmark_1200dpi_golden.ps",
					Options:      []string{"printer-resolution=1200dpi"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Lexmark.ppd", "printer_resolution_lexmark_1200dpi_golden.ps"},
			}, {
				Name: "lexmark_2400x600dpi",
				Val: &ippprint.Params{
					PPDFile:      "printer_Lexmark.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_resolution_lexmark_2400x600dpi_golden.ps",
					Options:      []string{"printer-resolution=2400x600dpi"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Lexmark.ppd", "printer_resolution_lexmark_2400x600dpi_golden.ps"},
			}, {
				Name: "media_source_by_pass_tray",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_generic_printer_GenericPostScript.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_media_source_bypass_golden.ps",
					Options:      []string{"media-source=by-pass-tray"},
				},
				ExtraData: []string{"to_print.pdf", "printer_add_generic_printer_GenericPostScript.ppd.gz", "printer_add_media_source_bypass_golden.ps"},
			}, {
				Name: "media_source_bottom",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_generic_printer_GenericPostScript.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_media_source_bottom_golden.ps",
					Options:      []string{"media-source=bottom"},
				},
				ExtraData: []string{"to_print.pdf", "printer_add_generic_printer_GenericPostScript.ppd.gz", "printer_add_media_source_bottom_golden.ps"},
			}, {
				Name: "oki_tray4",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_oki.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_oki_tray4_golden.ps",
					Options:      []string{"media-source=tray-4"},
				},
				ExtraData: []string{"to_print.pdf", "printer_add_oki.ppd.gz", "printer_add_oki_tray4_golden.ps"},
			}, {
				Name: "brother_mlaser",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_brother_printer.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_brother_printer_golden.bin",
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_brother_printer.ppd", "printer_add_brother_printer_golden.bin"},
				ExtraSoftwareDeps: []string{"cros_internal"},
			}, {
				Name: "brother_ql820nwb",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_brother_ql820nwb_printer.ppd.gz",
					PrintFile:    "label_29x90mm.pdf",
					ExpectedFile: "printer_add_brother_ql820nwb_printer.bin",
				},
				ExtraData:         []string{"label_29x90mm.pdf", "printer_add_brother_ql820nwb_printer.ppd.gz", "printer_add_brother_ql820nwb_printer.bin"},
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"print_brother_ql800_subset", "cros_internal"},
			}, {
				Name: "canon",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_canonmg2900.ppd",
					PrintFile:    "2page.pdf",
					ExpectedFile: "printer_add_canonmg2900_golden.bin",
					Options:      []string{"print-color-mode=rgb"},
				},
				ExtraData: []string{"2page.pdf", "printer_add_canonmg2900.ppd", "printer_add_canonmg2900_golden.bin"},
			}, {
				Name: "dymo_lw",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_dymo_printer_lw450.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_dymo_lw_printer_golden.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_dymo_printer_lw450.ppd", "printer_add_dymo_lw_printer_golden.bin"},
			}, {
				Name: "dymo_lm",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_dymo_printer_lm450.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_dymo_lm_printer_golden.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_dymo_printer_lm450.ppd", "printer_add_dymo_lm_printer_golden.bin"},
			}, {
				Name: "epson",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonWF3620.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_epson_printer_golden.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_EpsonWF3620.ppd", "printer_add_epson_printer_golden.bin"},
			}, {
				Name: "epson_color",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonGenericColorModel.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_epson_printer_color_golden.bin",
					Options:      []string{"print-color-mode=color"},
				},
				ExtraData: []string{"to_print.pdf", "printer_EpsonGenericColorModel.ppd", "printer_add_epson_printer_color_golden.bin"},
			}, {
				Name: "epson_colorworks_c4000",
				Val: &ippprint.Params{
					PPDFile:      "printer_EPSON_CW_C4000u.ppd.gz",
					PrintFile:    "label_97x76mm.pdf",
					ExpectedFile: "printer_add_epson_colorworks_c4000.bin",
				},
				ExtraData: []string{"label_97x76mm.pdf", "printer_EPSON_CW_C4000u.ppd.gz", "printer_add_epson_colorworks_c4000.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "epson_colorworks_c6500",
				Val: &ippprint.Params{
					PPDFile:      "printer_EPSON_CW_C6550A.ppd.gz",
					PrintFile:    "label_97x76mm.pdf",
					ExpectedFile: "printer_add_epson_colorworks_c6500.bin",
				},
				ExtraData: []string{"label_97x76mm.pdf", "printer_EPSON_CW_C6550A.ppd.gz", "printer_add_epson_colorworks_c6500.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "epson_monochrome",
				Val: &ippprint.Params{
					PPDFile:      "printer_EpsonGenericColorModel.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_epson_printer_monochrome_golden.bin",
					Options:      []string{"print-color-mode=monochrome"},
				},
				ExtraData: []string{"to_print.pdf", "printer_EpsonGenericColorModel.ppd", "printer_add_epson_printer_monochrome_golden.bin"},
			}, {
				Name: "generic",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_generic_printer_GenericPostScript.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_generic_printer_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_generic_printer_GenericPostScript.ppd.gz", "printer_add_generic_printer_golden.ps"},
			}, {
				Name: "hp_hpcups_hbpl1",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_printer_pclm.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_printer_pclm_out.pclm",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_printer_pclm.ppd.gz", "printer_add_hp_printer_pclm_out.pclm"},
			}, {
				Name: "hp_hpcups_lidil",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_lidil.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_lidil_out.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_lidil.ppd.gz", "printer_add_hp_hpcups_lidil_out.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_ljcolor",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_ljcolor.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_printer_ljcolor_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_ljcolor.ppd.gz", "printer_add_hp_printer_ljcolor_out.pcl"},
			}, {
				Name: "hp_hpcups_ljfastraster",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_ljfastraster.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_ljfastraster_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_ljfastraster.ppd.gz", "printer_add_hp_hpcups_ljfastraster_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_ljjetready",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_ljjetready.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_ljjetready_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_ljjetready.ppd.gz", "printer_add_hp_hpcups_ljjetready_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_ljmono",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_ljmono.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_ljmono_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_ljmono.ppd.gz", "printer_add_hp_hpcups_ljmono_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_ljzjstream",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_ljzjstream.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_ljzjstream_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_ljzjstream.ppd.gz", "printer_add_hp_hpcups_ljzjstream_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_ljzxstream",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_ljzxstream.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_ljzxstream_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_ljzxstream.ppd.gz", "printer_add_hp_hpcups_ljzxstream_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_pcl3",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_pcl3.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_pcl3_out.pcl",
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_hp_hpcups_pcl3.ppd.gz", "printer_add_hp_hpcups_pcl3_out.pcl"},
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"amd64"},
			}, {
				Name: "hp_hpcups_pcl3gui",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_pcl3gui.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_pcl3gui_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_pcl3gui.ppd.gz", "printer_add_hp_hpcups_pcl3gui_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_pcl3gui2",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_pcl3gui2.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_pcl3gui2_out.pcl",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpcups_pcl3gui2.ppd.gz", "printer_add_hp_hpcups_pcl3gui2_out.pcl"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_hpcups_quickconnect",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpcups_quickconnect.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpcups_quickconnect_out.bin",
				},
				ExtraData:         []string{"to_print.pdf", "printer_add_hp_hpcups_quickconnect.ppd.gz", "printer_add_hp_hpcups_quickconnect_out.bin"},
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"amd64"},
			}, {
				Name: "hp_hpps",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hp_hpps.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_hpps_out.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_hp_hpps.ppd.gz", "printer_add_hp_hpps_out.ps"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hp_pwg_raster_color",
				Val: &ippprint.Params{
					PPDFile:      "hp_ipp_everywhere.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_ipp_everywhere_golden.pwg",
				},
				ExtraData: []string{"to_print.pdf", "hp_ipp_everywhere.ppd", "printer_add_hp_ipp_everywhere_golden.pwg"},
			}, {
				Name: "hp_pwg_raster_monochrome",
				Val: &ippprint.Params{
					PPDFile:      "hp_ipp_everywhere.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_hp_pwg_raster_monochrome_golden.pwg",
					Options:      []string{"print-color-mode=monochrome"},
				},
				ExtraData: []string{"to_print.pdf", "hp_ipp_everywhere.ppd", "printer_add_hp_pwg_raster_monochrome_golden.pwg"},
			}, {
				Name: "nec",
				Val: &ippprint.Params{
					PPDFile:      "printer_nec_npdl.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_nec_golden.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_nec_npdl.ppd", "printer_add_nec_golden.bin"},
			}, {
				Name: "star",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_star_printer_rastertostar.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_star_printer_rastertostar.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_star_printer_rastertostar.ppd.gz", "printer_add_star_printer_rastertostar.bin"},
			}, {
				Name: "star_m",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_star_printer_rastertostarm.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_star_printer_rastertostarm.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_star_printer_rastertostarm.ppd.gz", "printer_add_star_printer_rastertostarm.bin"},
			}, {
				Name: "star_lm",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_star_printer_rastertostarlm.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_add_star_printer_rastertostarlm.bin",
				},
				ExtraData: []string{"to_print.pdf", "printer_add_star_printer_rastertostarlm.ppd.gz", "printer_add_star_printer_rastertostarlm.bin"},
			}, {
				Name: "hp_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_HP.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_hp_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_HP.ppd", "printer_pin_print_hp_no_pin_golden.ps"},
			}, {
				Name: "hp_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_HP.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_hp_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_HP.ppd", "printer_pin_print_hp_pin_golden.ps"},
			}, {
				Name: "lexmark_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Lexmark.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_lexmark_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_Lexmark.ppd", "printer_pin_print_lexmark_no_pin_golden.ps"},
			}, {
				Name: "lexmark_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Lexmark.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_lexmark_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Lexmark.ppd", "printer_pin_print_lexmark_pin_golden.ps"},
			}, {
				Name: "ricoh_jobpassword_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_JobPassword.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_JobPassword_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_JobPassword.ppd", "printer_pin_print_ricoh_JobPassword_no_pin_golden.ps"},
			}, {
				Name: "ricoh_jobpassword_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_JobPassword.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_JobPassword_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_JobPassword.ppd", "printer_pin_print_ricoh_JobPassword_pin_golden.ps"},
			}, {
				Name: "ricoh_lockedprintpassword_nopin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_LockedPrintPassword.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_LockedPrintPassword_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_LockedPrintPassword.ppd", "printer_pin_print_ricoh_LockedPrintPassword_no_pin_golden.ps"},
			}, {
				Name: "ricoh_lockedprintpassword_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_LockedPrintPassword.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_LockedPrintPassword_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_LockedPrintPassword.ppd", "printer_pin_print_ricoh_LockedPrintPassword_pin_golden.ps"},
			}, {
				Name: "ricoh_password_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_password.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_password_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_password.ppd", "printer_pin_print_ricoh_password_no_pin_golden.ps"},
			}, {
				Name: "ricoh_password_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Ricoh_password.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_ricoh_password_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Ricoh_password.ppd", "printer_pin_print_ricoh_password_pin_golden.ps"},
			}, {
				Name: "sharp_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Sharp.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_sharp_no_pin_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_Sharp.ppd", "printer_pin_print_sharp_no_pin_golden.ps"},
			}, {
				Name: "sharp_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_Sharp.ppd",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_sharp_pin_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_Sharp.ppd", "printer_pin_print_sharp_pin_golden.ps"},
			}, {
				Name: "unsupported_no_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_unsupported_GenericPostScript.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_unsupported_golden.ps",
				},
				ExtraData: []string{"to_print.pdf", "printer_unsupported_GenericPostScript.ppd.gz", "printer_pin_print_unsupported_golden.ps"},
			}, {
				Name: "unsupported_pin",
				Val: &ippprint.Params{
					PPDFile:      "printer_unsupported_GenericPostScript.ppd.gz",
					PrintFile:    "to_print.pdf",
					ExpectedFile: "printer_pin_print_unsupported_golden.ps",
					Options:      []string{"job-password=1234"},
				},
				ExtraData: []string{"to_print.pdf", "printer_unsupported_GenericPostScript.ppd.gz", "printer_pin_print_unsupported_golden.ps"},
			}, {
				Name: "custom_h400_h350",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_h400_h350_printer_rastertoH400_H350.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_h400_h350_printer_rastertoH400_H350.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_h400_h350_printer_rastertoH400_H350.ppd.gz", "printer_add_custom_h400_h350_printer_rastertoH400_H350.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_k3",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_k3_printer_rastertoK3.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_k3_printer_rastertoK3.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_k3_printer_rastertoK3.ppd.gz", "printer_add_custom_k3_printer_rastertoK3.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_kpm180h",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_kpm180h_printer_rastertoKPM180H.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_kpm180h_printer_rastertoKPM180H.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_kpm180h_printer_rastertoKPM180H.ppd.gz", "printer_add_custom_kpm180h_printer_rastertoKPM180H.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_kpm300h3",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_kpm300h3_printer_rastertoKPM300H3.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_kpm300h3_printer_rastertoKPM300H3.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_kpm300h3_printer_rastertoKPM300H3.ppd.gz", "printer_add_custom_kpm300h3_printer_rastertoKPM300H3.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_kpm862",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_kpm862_printer_rastertoKPM862.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_kpm862_printer_rastertoKPM862.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_kpm862_printer_rastertoKPM862.ppd.gz", "printer_add_custom_kpm862_printer_rastertoKPM862.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_kube",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_kube_printer_rastertoKUBE.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_kube_printer_rastertoKUBE.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_kube_printer_rastertoKUBE.ppd.gz", "printer_add_custom_kube_printer_rastertoKUBE.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_modus3_ca",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_modus3_ca_printer_rasterToMODUS3_CA.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_modus3_ca_printer_rasterToMODUS3_CA.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_modus3_ca_printer_rasterToMODUS3_CA.ppd.gz", "printer_add_custom_modus3_ca_printer_rasterToMODUS3_CA.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_p3",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_p3_printer_rastertoP3.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_p3_printer_rastertoP3.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_p3_printer_rastertoP3.ppd.gz", "printer_add_custom_p3_printer_rastertoP3.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_tg2460_h_ej",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_tg2460_h_ej_printer_rastertoTG2460-H-EJ.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_tg2460_h_ej_printer_rastertoTG2460-H-EJ.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_tg2460_h_ej_printer_rastertoTG2460-H-EJ.ppd.gz", "printer_add_custom_tg2460_h_ej_printer_rastertoTG2460-H-EJ.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_tg2460h",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_tg2460h_printer_rastertoTG2460H.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_tg2460h_printer_rastertoTG2460H.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_tg2460h_printer_rastertoTG2460H.ppd.gz", "printer_add_custom_tg2460h_printer_rastertoTG2460H.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_tg2480h",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_tg2480h_printer_rastertoTG2480H.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_tg2480h_printer_rastertoTG2480H.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_tg2480h_printer_rastertoTG2480H.ppd.gz", "printer_add_custom_tg2480h_printer_rastertoTG2480H.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "custom_vkp80iii",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_custom_vkp80iii_printer_rastertoVKP80III.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_custom_vkp80iii_printer_rastertoVKP80III.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_custom_vkp80iii_printer_rastertoVKP80III.ppd.gz", "printer_add_custom_vkp80iii_printer_rastertoVKP80III.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "epson_thermal_receipt",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_epson_thermal_receipt.ppd",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "receipt_70mmx80mm.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_epson_thermal_receipt.ppd", "receipt_70mmx80mm.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "generic_escpos_receipt",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_generic_escpos_receipt.ppd",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_generic_escpos_receipt.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_generic_escpos_receipt.ppd", "printer_add_generic_escpos_receipt.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "hwasung",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_hwasung_printer_rastertohwasung.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_hwasung_printer_rastertohwasung.bin",
				},
				ExtraData: []string{"receipt_70mmx80mm.pdf", "printer_add_hwasung_printer_rastertohwasung.ppd.gz", "printer_add_hwasung_printer_rastertohwasung.bin"},
				ExtraAttr: []string{"informational"},
			}, {
				Name: "tsc",
				Val: &ippprint.Params{
					PPDFile:      "printer_add_tsc_printer_rastertobarcodetspl.ppd.gz",
					PrintFile:    "receipt_70mmx80mm.pdf",
					ExpectedFile: "printer_add_tsc_printer_rastertobarcodetspl.bin",
				},
				ExtraData:         []string{"receipt_70mmx80mm.pdf", "printer_add_tsc_printer_rastertobarcodetspl.ppd.gz", "printer_add_tsc_printer_rastertobarcodetspl.bin"},
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"no_arm"},
			},
		},
	})
}

func Add(ctx context.Context, s *testing.State) {
	ippprint.Run(ctx, s, s.Param().(*ippprint.Params))
}
