// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package video

import (
	"context"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/common/media/caps"
	"go.chromium.org/tast-tests/cros/local/graphics"
	"go.chromium.org/tast-tests/cros/local/graphics/expectations"
	"go.chromium.org/tast-tests/cros/local/media/decoding"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/testing/hwdep"
)

// These are invalid bistreams one way or another that are decoded correctly
// (no artifacts) with a software decoder but not when using certain hardware
// decoder implementations. These tests are expected to fail long-term, but it's
// interesting to have them to verify that e.g. the driver doesn't crash.
var h264InvalidBitstreams = []string{
	"test_vectors/h264/files_from_bugs/b_234651916_big_buck_bunny_artifacts_rk3399.h264",
	"test_vectors/h264/files_from_bugs/b_184041918_Webex_out_of_order_h264_frames.h264",
	"test_vectors/h264/files_from_bugs/b_277849540__malformed_h264_vlct_16x16.h264",
	"test_vectors/h264/files_from_bugs/b_277849540__malformed_h264_vlct_4x4.h264",
	"test_vectors/h264/files_from_bugs/b_277849540__malformed_h264_vlct_8x8.h264",
}

var h264Files = map[string][]string{
	"baseline": {
		"test_vectors/h264/baseline/AUD_MW_E.h264",
		"test_vectors/h264/baseline/BA1_Sony_D.h264",
		"test_vectors/h264/baseline/BA2_Sony_F.h264",
		"test_vectors/h264/baseline/BAMQ1_JVC_C.h264",
		"test_vectors/h264/baseline/BAMQ2_JVC_C.h264",
		"test_vectors/h264/baseline/BANM_MW_D.h264",
		"test_vectors/h264/baseline/BA_MW_D.h264",
		"test_vectors/h264/baseline/CI_MW_D.h264",
		"test_vectors/h264/baseline/CVSE2_Sony_B.h264",
		"test_vectors/h264/baseline/HCBP1_HHI_A.h264",
		"test_vectors/h264/baseline/HCBP2_HHI_A.h264",
		"test_vectors/h264/baseline/LS_SVA_D.h264",
		"test_vectors/h264/baseline/MIDR_MW_D.h264",
		"test_vectors/h264/baseline/MPS_MW_A.h264",
		"test_vectors/h264/baseline/MR1_MW_A.h264",
		"test_vectors/h264/baseline/MR2_MW_A.h264",
		"test_vectors/h264/baseline/NL1_Sony_D.h264",
		"test_vectors/h264/baseline/NL2_Sony_H.h264",
		"test_vectors/h264/baseline/NLMQ1_JVC_C.h264",
		"test_vectors/h264/baseline/NLMQ2_JVC_C.h264",
		"test_vectors/h264/baseline/NRF_MW_E.h264",
		"test_vectors/h264/baseline/SVA_BA1_B.h264",
		"test_vectors/h264/baseline/SVA_BA2_D.h264",
		"test_vectors/h264/baseline/SVA_NL1_B.h264",
		"test_vectors/h264/baseline/SVA_NL2_E.h264",

		// The following test vectors are disabled because they don't verify that
		// |max_num_reorder_frames| is smaller or equal to the DPB size, see
		// b/216179527.
		//"test_vectors/h264/baseline/MR2_TANDBERG_E.h264",
		//"test_vectors/h264/baseline/MR3_TANDBERG_B.h264",
		//"test_vectors/h264/baseline/MR4_TANDBERG_C.h264",
		//"test_vectors/h264/baseline/MR5_TANDBERG_C.h264",
	},
	"main": {
		"test_vectors/h264/main/CABA1_SVA_B.h264",
		"test_vectors/h264/main/CABA1_Sony_D.h264",
		"test_vectors/h264/main/CABA2_SVA_B.h264",
		"test_vectors/h264/main/CABA2_Sony_E.h264",
		"test_vectors/h264/main/CABA3_SVA_B.h264",
		"test_vectors/h264/main/CABA3_Sony_C.h264",
		"test_vectors/h264/main/CABA3_TOSHIBA_E.h264",
		"test_vectors/h264/main/CACQP3_Sony_D.h264",
		"test_vectors/h264/main/CANL1_SVA_B.h264",
		"test_vectors/h264/main/CANL1_Sony_E.h264",
		"test_vectors/h264/main/CANL1_TOSHIBA_G.h264",
		"test_vectors/h264/main/CANL2_SVA_B.h264",
		"test_vectors/h264/main/CANL2_Sony_E.h264",
		"test_vectors/h264/main/CANL3_SVA_B.h264",
		"test_vectors/h264/main/CANL3_Sony_C.h264",
		"test_vectors/h264/main/CANL4_SVA_B.h264",
		"test_vectors/h264/main/CAPCM1_Sand_E.h264",
		"test_vectors/h264/main/CAPCMNL1_Sand_E.h264",
		"test_vectors/h264/main/CAPM3_Sony_D.h264",
		"test_vectors/h264/main/CAQP1_Sony_B.h264",
		"test_vectors/h264/main/CAWP1_TOSHIBA_E.h264",
		"test_vectors/h264/main/CAWP5_TOSHIBA_E.h264",
		"test_vectors/h264/main/CVBS3_Sony_C.h264",
		"test_vectors/h264/main/CVPCMNL1_SVA_C.h264",
		"test_vectors/h264/main/CVPCMNL2_SVA_C.h264",
		"test_vectors/h264/main/CVSE3_Sony_H.h264",
		"test_vectors/h264/main/CVSEFDFT3_Sony_E.h264",
		"test_vectors/h264/main/CVWP1_TOSHIBA_E.h264",
		"test_vectors/h264/main/CVWP2_TOSHIBA_E.h264",
		"test_vectors/h264/main/CVWP3_TOSHIBA_E.h264",
		"test_vectors/h264/main/CVWP5_TOSHIBA_E.h264",
		"test_vectors/h264/main/NL3_SVA_E.h264",
		"test_vectors/h264/main/camp_mot_frm0_full.h264",
		"test_vectors/h264/main/cvmp_mot_frm0_full_B.h264",
		"test_vectors/h264/main/src19td.IBP.h264",
		"test_vectors/h264/main/HCMP1_HHI_A.h264",

		// The following test vectors are disabled because they don't verify the
		// SPS's |frame_mbs_only_flag|, i.e. they contain interlaced macroblocks
		// which are not supported, see b/216319263.
		//"test_vectors/h264/main/CAMA1_Sony_C.h264",
		//"test_vectors/h264/main/CAMA1_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CAMA3_Sand_E.h264",
		//"test_vectors/h264/main/CAMACI3_Sony_C.h264",
		//"test_vectors/h264/main/CAMANL1_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CAMANL2_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CAMANL3_Sand_E.h264",
		//"test_vectors/h264/main/CAMASL3_Sony_B.h264",
		//"test_vectors/h264/main/CAMP_MOT_MBAFF_L30.h264",
		//"test_vectors/h264/main/CAMP_MOT_MBAFF_L31.h264",
		//"test_vectors/h264/main/CANLMA2_Sony_C.h264",
		//"test_vectors/h264/main/CANLMA3_Sony_C.h264",
		//"test_vectors/h264/main/CVCANLMA2_Sony_C.h264",
		//"test_vectors/h264/main/CVMA1_Sony_D.h264",
		//"test_vectors/h264/main/CVMA1_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CVMANL1_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CVMANL2_TOSHIBA_B.h264",
		//"test_vectors/h264/main/CVMAQP2_Sony_G.h264",
		//"test_vectors/h264/main/CVMAQP3_Sony_D.h264",
		//"test_vectors/h264/main/camp_mot_mbaff0_full.h264",
		//"test_vectors/h264/main/cvmp_mot_mbaff0_full_B.h264",
	},
	// The following test vectors are separated because they don't verify that all
	// slice header's |first_mb_in_slice| is zero, which is not supported by
	// Chromium's parsers (see b/216179527). Stateful decoders, who have their own
	// H.264 parsers, might support them, though.
	"first_mb_in_slice": {
		"test_vectors/h264/baseline/BA1_FT_C.h264",
		"test_vectors/h264/baseline/BASQP1_Sony_C.h264",
		"test_vectors/h264/baseline/CI1_FT_B.h264",
		"test_vectors/h264/baseline/SVA_Base_B.h264",
		"test_vectors/h264/baseline/SVA_CL1_E.h264",
		"test_vectors/h264/baseline/SVA_FM1_E.h264",
		"test_vectors/h264/baseline/MR1_BT_A.h264",
		"test_vectors/h264/main/CABACI3_Sony_B.h264",
		"test_vectors/h264/main/CABAST3_Sony_E.h264",
		"test_vectors/h264/main/CABASTBR3_Sony_B.h264",
		"test_vectors/h264/main/SL1_SVA_B.h264",
	},
	"high": {
		"test_vectors/h264/high/FREH12_B.h264",
		"test_vectors/h264/high/FREH1_B.h264",
		"test_vectors/h264/high/FREH2_B.h264",
		"test_vectors/h264/high/FREH3.h264",
		"test_vectors/h264/high/FREH8.h264",
		"test_vectors/h264/high/FREH9.h264",
		"test_vectors/h264/high/HCAFR1_HHI.h264",
		"test_vectors/h264/high/HCAFR2_HHI.h264",
		"test_vectors/h264/high/HCAFR3_HHI.h264",
		"test_vectors/h264/high/HCAFR4_HHI.h264",
		"test_vectors/h264/high/HCHP1_HHI_B.h264",
		"test_vectors/h264/high/HCHP2_HHI_A.h264",
		"test_vectors/h264/high/HPCADQ_BRCM_B.h264",
		"test_vectors/h264/high/HPCALQ_BRCM_B.h264",
		"test_vectors/h264/high/HPCANL_BRCM_C.h264",
		"test_vectors/h264/high/HPCAQ2LQ_BRCM_B.h264",
		"test_vectors/h264/high/HPCA_BRCM_C.h264",
		"test_vectors/h264/high/HPCVNL_BRCM_A.h264",
		"test_vectors/h264/high/HPCV_BRCM_A.h264",

		// The following test vectors are disabled as they are interlaced
		// bitstreams indicated by the |frame_mbs_only_flag| being set to 0.
		// Since interlaced H.264 bitstreams are not supported and is not
		// planned on being supported, these bitstreams are disabled.
		// "test_vectors/h264/high/FREH10.h264",
		// "test_vectors/h264/high/FREH11.h264",
		// "test_vectors/h264/high/FREH4.h264",
		// "test_vectors/h264/high/FREH5.h264",
		// "test_vectors/h264/high/FREH6.h264",
		// "test_vectors/h264/high/FREH7_B.h264",
		// "test_vectors/h264/high/FREXT01_JVC_D.h264",
		// "test_vectors/h264/high/FREXT02_JVC_C.h264",
		// "test_vectors/h264/high/FRExt_MMCO4_Sony_B.h264",
		// "test_vectors/h264/high/HCAFF1_HHI.h264",
		// "test_vectors/h264/high/HCAMFF1_HHI.h264",
		// "test_vectors/h264/high/HCHP3_HHI_A.h264",
		// "test_vectors/h264/high/HPCAFLNL_BRCM_C.h264",
		// "test_vectors/h264/high/HPCAFL_BRCM_C.h264",
		// "test_vectors/h264/high/HPCAMAPALQ_BRCM_B.h264",
		// "test_vectors/h264/high/HPCAMOLQ_BRCM_B.h264",
		// "test_vectors/h264/high/HPCVFLNL_BRCM_A.h264",
		// "test_vectors/h264/high/HPCVFL_BRCM_A.h264",
		// "test_vectors/h264/high/HPCVMOLQ_BRCM_B.h264",
		// "test_vectors/h264/high/HVLCFI0_Sony_B.h264",
		// "test_vectors/h264/high/HVLCMFF0_Sony_B.h264",
		// "test_vectors/h264/high/HVLCPFF0_Sony_B.h264",
	},
}

func appendJSONFiles(videoFiles []string) []string {
	var tf []string
	for _, file := range videoFiles {
		tf = append(tf, file)
		tf = append(tf, file+".json")
	}
	return tf
}

const defaultPerVideoTimeoutHD = time.Minute
const defaultPerVideoTimeout4K = 4 * time.Minute

// videoTimeoutOverrides are used to allow for longer timeouts for particular
// video files. Otherwise the default timeouts will be used.
var videoTimeoutOverrides = map[string]time.Duration{
	"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264": 3 * time.Minute, // 3 minutes because the video is long. b/311840410
}

func calculateTestTimeout(videoFiles []string, testName string) time.Duration {
	defaultPerVideoTimeout := defaultPerVideoTimeoutHD
	if strings.Contains(testName, "4k") {
		defaultPerVideoTimeout = defaultPerVideoTimeout4K
	}

	var timeout time.Duration

	for _, f := range videoFiles {
		t, ok := videoTimeoutOverrides[f]
		if !ok {
			t = defaultPerVideoTimeout
		}
		timeout = timeout + t
	}
	return timeout
}

// chromeStackDecoderVerificationTestParam is used to describe the options used
// to run each test.
type chromeStackDecoderVerificationTestParam struct {
	videoFiles      []string                  // The paths of video files to be tested.
	validatorType   decoding.ValidatorType    // The frame validation type of video_decode_accelerator_tests.
	mustFail        bool                      // If set, verify that MD5SUM verification is not successful.
	ignoredSysLogs  []graphics.SysLogCategory // optional list of syslog categories to ignore
	enabledFeatures []string                  // List of Chrome Features to enable, if any.
}

func init() {
	testing.AddTest(&testing.Test{
		Func:         ChromeStackDecoderVerification,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Verifies video decoding using Chrome's stack (via the video_decode_accelerator_tests binary) and either MD5 or SSIM criteria",
		Contacts: []string{
			"chromeos-gfx-video@google.com",
			"mcasas@chromium.org",
			"hiroh@chromium.org", // Underlying binary author.
		},
		BugComponent: "b:168352", // ChromeOS > Platform > Graphics > Video
		Fixture:      "graphicsNoChrome",
		SoftwareDeps: []string{"chrome"},
		Params: []testing.Param{
			// Parameters generated by chrome_stack_decoder_verification_test.go. DO NOT EDIT.
			{
				Name:              "av1_common",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Files["8bit"]),
				Timeout:           calculateTestTimeout(av1Files["8bit"], "av1_common"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["8bit"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_quantizer",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["quantizer"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["quantizer"], "av1_8bit_quantizer"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["quantizer"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_size_under_64x64",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipCPUSocFamily("mediatek"), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["size_under_64x64"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["size_under_64x64"], "av1_8bit_size_under_64x64"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["size_under_64x64"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["size"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["size"], "av1_8bit_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_allintra",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["allintra"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["allintra"], "av1_8bit_allintra"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["allintra"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_cdfupdate",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["cdfupdate"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["cdfupdate"], "av1_8bit_cdfupdate"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["cdfupdate"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_8bit_motionvec",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["motionvec"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["motionvec"], "av1_8bit_motionvec"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["motionvec"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name: "av1_film_grain",
				// Different decoders may use different film grain synthesis methods while producing a visually correct output (AV1 spec 7.2). Thus we validate the decoding of film-grain streams using SSIM.
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles(av1FilmGrainFiles),
				Timeout:           calculateTestTimeout(av1FilmGrainFiles, "av1_film_grain"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1FilmGrainFiles,
					validatorType:   decoding.SSIM,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_10bit_common",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP},
				ExtraData:         appendJSONFiles(av1Files["10bit"]),
				Timeout:           calculateTestTimeout(av1Files["10bit"], "av1_10bit_common"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["10bit"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_10bit_common_quantizer",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP},
				ExtraData:         appendJSONFiles(av1Files["10bit_quantizer"]),
				Timeout:           calculateTestTimeout(av1Files["10bit_quantizer"], "av1_10bit_common_quantizer"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["10bit_quantizer"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name: "av1_10bit_film_grain",
				// Different decoders may use different film grain synthesis methods while producing a visually correct output (AV1 spec 7.2). Thus, for volteer, don't validate the decoding of film-grain streams using MD5. Instead, validate them using SSIM (see the av1_10bit_ssim test).
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP},
				ExtraData:         appendJSONFiles(av110BitFilmGrainFiles),
				Timeout:           calculateTestTimeout(av110BitFilmGrainFiles, "av1_10bit_film_grain"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av110BitFilmGrainFiles,
					validatorType:   decoding.SSIM,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_invalid_bitstreams",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles(h264InvalidBitstreams),
				Timeout:           calculateTestTimeout(h264InvalidBitstreams, "h264_invalid_bitstreams"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264InvalidBitstreams,
					validatorType:   decoding.MD5,
					mustFail:        true,
					enabledFeatures: []string{},
					ignoredSysLogs:  []graphics.SysLogCategory{graphics.SysLogMediatekVideoErrors},
				},
			},
			{
				Name:              "h264_baseline",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles(h264Files["baseline"]),
				Timeout:           calculateTestTimeout(h264Files["baseline"], "h264_baseline"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["baseline"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_main",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles(h264Files["main"]),
				Timeout:           calculateTestTimeout(h264Files["main"], "h264_main"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["main"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_high",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles(h264Files["high"]),
				Timeout:           calculateTestTimeout(h264Files["high"], "h264_high"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["high"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_first_mb_in_slice",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles(h264Files["first_mb_in_slice"]),
				Timeout:           calculateTestTimeout(h264Files["first_mb_in_slice"], "h264_first_mb_in_slice"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["first_mb_in_slice"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_comprehensive",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["comprehensive"]),
				Timeout:           calculateTestTimeout(vp8Files["comprehensive"], "vp8_comprehensive"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["comprehensive"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_inter",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["inter"]),
				Timeout:           calculateTestTimeout(vp8Files["inter"], "vp8_inter"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_inter_multi_coeff",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["inter_multi_coeff"]),
				Timeout:           calculateTestTimeout(vp8Files["inter_multi_coeff"], "vp8_inter_multi_coeff"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter_multi_coeff"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_inter_segment",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["inter_segment"]),
				Timeout:           calculateTestTimeout(vp8Files["inter_segment"], "vp8_inter_segment"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter_segment"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_intra",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["intra"]),
				Timeout:           calculateTestTimeout(vp8Files["intra"], "vp8_intra"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_intra_multi_coeff",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["intra_multi_coeff"]),
				Timeout:           calculateTestTimeout(vp8Files["intra_multi_coeff"], "vp8_intra_multi_coeff"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra_multi_coeff"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp8_intra_segment",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8},
				ExtraData:         appendJSONFiles(vp8Files["intra_segment"]),
				Timeout:           calculateTestTimeout(vp8Files["intra_segment"], "vp8_intra_segment"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra_segment"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_buf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["buf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["buf"], "vp9_0_group1_buf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["buf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_frm_resize",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["frm_resize"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["frm_resize"], "vp9_0_group1_frm_resize"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["frm_resize"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_gf_dist",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["gf_dist"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["gf_dist"], "vp9_0_group1_gf_dist"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["gf_dist"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_odd_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["odd_size"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["odd_size"], "vp9_0_group1_odd_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["odd_size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_sub8x8",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["sub8x8"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["sub8x8"], "vp9_0_group1_sub8x8"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["sub8x8"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_group1_sub8x8_sf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"], "vp9_0_group1_sub8x8_sf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_buf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["buf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["buf"], "vp9_2_group1_buf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["buf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_frm_resize",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["frm_resize"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["frm_resize"], "vp9_2_group1_frm_resize"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["frm_resize"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_gf_dist",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["gf_dist"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["gf_dist"], "vp9_2_group1_gf_dist"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["gf_dist"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_odd_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["odd_size"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["odd_size"], "vp9_2_group1_odd_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["odd_size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_sub8x8",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["sub8x8"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["sub8x8"], "vp9_2_group1_sub8x8"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["sub8x8"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_2_group1_sub8x8_sf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"], "vp9_2_group1_sub8x8_sf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_0_svc",
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles(vp9SVCFiles),
				Timeout:           calculateTestTimeout(vp9SVCFiles, "vp9_0_svc"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9SVCFiles,
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "hevc_main_part_1",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_1"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_1"], "hevc_main_part_1"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_1"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "hevc_main_part_2",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_2"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_2"], "hevc_main_part_2"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_2"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "hevc_main_part_3",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_3"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_3"], "hevc_main_part_3"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_3"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "hevc_main_part_4",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_4"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_4"], "hevc_main_part_4"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_4"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_149068426",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"}, "h264_files_from_bugs_149068426"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_172838252",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"}, "h264_files_from_bugs_172838252"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_174733646",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"}, "h264_files_from_bugs_174733646"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_210895987",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"}, "h264_files_from_bugs_210895987"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_276358257",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"}, "h264_files_from_bugs_276358257"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_files_from_bugs_299320432",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"}, "h264_files_from_bugs_299320432"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "h264_4k_files_from_bugs_22704778",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264_4K, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"}, "h264_4k_files_from_bugs_22704778"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_files_from_bugs_177839888",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles([]string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"}, "vp9_files_from_bugs_177839888"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "vp9_files_from_bugs_251040563",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9},
				ExtraData:         appendJSONFiles([]string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"}, "vp9_files_from_bugs_251040563"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_files_from_bugs_235138734",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles([]string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"}, "av1_files_from_bugs_235138734"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "av1_files_from_bugs_346405213",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1},
				ExtraData:         appendJSONFiles([]string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"}, "av1_files_from_bugs_346405213"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "hevc_files_from_bugs_321622872",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue")),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "proprietary_codecs"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"}, "hevc_files_from_bugs_321622872"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{},
				},
			},
			{
				Name:              "v4l2_flat_av1_common",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Files["8bit"]),
				Timeout:           calculateTestTimeout(av1Files["8bit"], "v4l2_flat_av1_common"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["8bit"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_quantizer",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["quantizer"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["quantizer"], "v4l2_flat_av1_8bit_quantizer"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["quantizer"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_size_under_64x64",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipCPUSocFamily("mediatek"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["size_under_64x64"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["size_under_64x64"], "v4l2_flat_av1_8bit_size_under_64x64"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["size_under_64x64"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["size"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["size"], "v4l2_flat_av1_8bit_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_allintra",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["allintra"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["allintra"], "v4l2_flat_av1_8bit_allintra"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["allintra"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_cdfupdate",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["cdfupdate"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["cdfupdate"], "v4l2_flat_av1_8bit_cdfupdate"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["cdfupdate"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_8bit_motionvec",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Aom8bitFiles["motionvec"]),
				Timeout:           calculateTestTimeout(av1Aom8bitFiles["motionvec"], "v4l2_flat_av1_8bit_motionvec"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Aom8bitFiles["motionvec"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name: "v4l2_flat_av1_film_grain",
				// Different decoders may use different film grain synthesis methods while producing a visually correct output (AV1 spec 7.2). Thus we validate the decoding of film-grain streams using SSIM.
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1FilmGrainFiles),
				Timeout:           calculateTestTimeout(av1FilmGrainFiles, "v4l2_flat_av1_film_grain"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1FilmGrainFiles,
					validatorType:   decoding.SSIM,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_10bit_common",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Files["10bit"]),
				Timeout:           calculateTestTimeout(av1Files["10bit"], "v4l2_flat_av1_10bit_common"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["10bit"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder", "V4L2FlatVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_10bit_common_quantizer",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av1Files["10bit_quantizer"]),
				Timeout:           calculateTestTimeout(av1Files["10bit_quantizer"], "v4l2_flat_av1_10bit_common_quantizer"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av1Files["10bit_quantizer"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name: "v4l2_flat_av1_10bit_film_grain",
				// Different decoders may use different film grain synthesis methods while producing a visually correct output (AV1 spec 7.2). Thus, for volteer, don't validate the decoding of film-grain streams using MD5. Instead, validate them using SSIM (see the av1_10bit_ssim test).
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1_10BPP, "v4l2_codec"},
				ExtraData:         appendJSONFiles(av110BitFilmGrainFiles),
				Timeout:           calculateTestTimeout(av110BitFilmGrainFiles, "v4l2_flat_av1_10bit_film_grain"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      av110BitFilmGrainFiles,
					validatorType:   decoding.SSIM,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_invalid_bitstreams",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles(h264InvalidBitstreams),
				Timeout:           calculateTestTimeout(h264InvalidBitstreams, "v4l2_flat_h264_invalid_bitstreams"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264InvalidBitstreams,
					validatorType:   decoding.MD5,
					mustFail:        true,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
					ignoredSysLogs:  []graphics.SysLogCategory{graphics.SysLogMediatekVideoErrors},
				},
			},
			{
				Name:              "v4l2_flat_h264_baseline",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles(h264Files["baseline"]),
				Timeout:           calculateTestTimeout(h264Files["baseline"], "v4l2_flat_h264_baseline"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["baseline"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_main",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles(h264Files["main"]),
				Timeout:           calculateTestTimeout(h264Files["main"], "v4l2_flat_h264_main"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["main"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_high",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles(h264Files["high"]),
				Timeout:           calculateTestTimeout(h264Files["high"], "v4l2_flat_h264_high"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["high"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_first_mb_in_slice",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2StatefulVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles(h264Files["first_mb_in_slice"]),
				Timeout:           calculateTestTimeout(h264Files["first_mb_in_slice"], "v4l2_flat_h264_first_mb_in_slice"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      h264Files["first_mb_in_slice"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_comprehensive",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["comprehensive"]),
				Timeout:           calculateTestTimeout(vp8Files["comprehensive"], "v4l2_flat_vp8_comprehensive"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["comprehensive"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_inter",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["inter"]),
				Timeout:           calculateTestTimeout(vp8Files["inter"], "v4l2_flat_vp8_inter"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_inter_multi_coeff",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["inter_multi_coeff"]),
				Timeout:           calculateTestTimeout(vp8Files["inter_multi_coeff"], "v4l2_flat_vp8_inter_multi_coeff"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter_multi_coeff"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_inter_segment",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["inter_segment"]),
				Timeout:           calculateTestTimeout(vp8Files["inter_segment"], "v4l2_flat_vp8_inter_segment"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["inter_segment"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_intra",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["intra"]),
				Timeout:           calculateTestTimeout(vp8Files["intra"], "v4l2_flat_vp8_intra"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_intra_multi_coeff",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["intra_multi_coeff"]),
				Timeout:           calculateTestTimeout(vp8Files["intra_multi_coeff"], "v4l2_flat_vp8_intra_multi_coeff"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra_multi_coeff"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp8_intra_segment",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP8, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp8Files["intra_segment"]),
				Timeout:           calculateTestTimeout(vp8Files["intra_segment"], "v4l2_flat_vp8_intra_segment"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp8Files["intra_segment"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_buf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["buf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["buf"], "v4l2_flat_vp9_0_group1_buf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["buf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_frm_resize",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["frm_resize"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["frm_resize"], "v4l2_flat_vp9_0_group1_frm_resize"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["frm_resize"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_gf_dist",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["gf_dist"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["gf_dist"], "v4l2_flat_vp9_0_group1_gf_dist"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["gf_dist"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_odd_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["odd_size"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["odd_size"], "v4l2_flat_vp9_0_group1_odd_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["odd_size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_sub8x8",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["sub8x8"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["sub8x8"], "v4l2_flat_vp9_0_group1_sub8x8"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["sub8x8"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_group1_sub8x8_sf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"], "v4l2_flat_vp9_0_group1_sub8x8_sf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_0"]["group1"]["sub8x8_sf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_buf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["buf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["buf"], "v4l2_flat_vp9_2_group1_buf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["buf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_frm_resize",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["frm_resize"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["frm_resize"], "v4l2_flat_vp9_2_group1_frm_resize"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["frm_resize"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_gf_dist",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["gf_dist"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["gf_dist"], "v4l2_flat_vp9_2_group1_gf_dist"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["gf_dist"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_odd_size",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["odd_size"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["odd_size"], "v4l2_flat_vp9_2_group1_odd_size"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["odd_size"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_sub8x8",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["sub8x8"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["sub8x8"], "v4l2_flat_vp9_2_group1_sub8x8"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["sub8x8"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_2_group1_sub8x8_sf",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9_2, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"]),
				Timeout:           calculateTestTimeout(vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"], "v4l2_flat_vp9_2_group1_sub8x8_sf"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9WebmFiles["profile_2"]["group1"]["sub8x8_sf"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_0_svc",
				ExtraHardwareDeps: hwdep.D(hwdep.SkipOnV4L2StatelessVideoDecoding(), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles(vp9SVCFiles),
				Timeout:           calculateTestTimeout(vp9SVCFiles, "v4l2_flat_vp9_0_svc"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      vp9SVCFiles,
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_hevc_main_part_1",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "v4l2_codec"},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_1"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_1"], "v4l2_flat_hevc_main_part_1"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_1"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_hevc_main_part_2",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "v4l2_codec"},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_2"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_2"], "v4l2_flat_hevc_main_part_2"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_2"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_hevc_main_part_3",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "v4l2_codec"},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_3"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_3"], "v4l2_flat_hevc_main_part_3"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_3"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_hevc_main_part_4",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "v4l2_codec"},
				ExtraData:         appendJSONFiles(hevcFiles["main_part_4"]),
				Timeout:           calculateTestTimeout(hevcFiles["main_part_4"], "v4l2_flat_hevc_main_part_4"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      hevcFiles["main_part_4"],
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_149068426",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"}, "v4l2_flat_h264_files_from_bugs_149068426"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_149068426_invalid_video_layout_mtk_8183_with_direct_videodecoder.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_172838252",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"}, "v4l2_flat_h264_files_from_bugs_172838252"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_172838252_pixelated_video_on_rk3399.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_174733646",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"}, "v4l2_flat_h264_files_from_bugs_174733646"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_174733646_video_with_out_of_order_frames_mtk_8173.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_210895987",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"}, "v4l2_flat_h264_files_from_bugs_210895987"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_210895987_still-colors-360p.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_276358257",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"}, "v4l2_flat_h264_files_from_bugs_276358257"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_276358257__amd_gpu_gen3_lockup.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_files_from_bugs_299320432",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"}, "v4l2_flat_h264_files_from_bugs_299320432"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_299320432__amd_skyrim_system_hang.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_h264_4k_files_from_bugs_22704778",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeH264_4K, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"}, "v4l2_flat_h264_4k_files_from_bugs_22704778"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/h264/files_from_bugs/b_227047778_mtk_8195_artifacts.h264"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_files_from_bugs_177839888",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"}, "v4l2_flat_vp9_files_from_bugs_177839888"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/vp9/files_from_bugs/b_177839888__rk3399_vp9_artifacts_with_video_decoder_japanews24.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_vp9_files_from_bugs_251040563",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeVP9, "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"}, "v4l2_flat_vp9_files_from_bugs_251040563"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/vp9/files_from_bugs/b_251040563_webrtc_libvpx.vp9.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_files_from_bugs_235138734",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"}, "v4l2_flat_av1_files_from_bugs_235138734"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/av1/files_from_bugs/b_235138734_test-25fps-one-to-four-tiles.av1.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_av1_files_from_bugs_346405213",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeAV1, "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"}, "v4l2_flat_av1_files_from_bugs_346405213"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/av1/files_from_bugs/b_346405213_reference-frame-scaling-test.ivf"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
			{
				Name:              "v4l2_flat_hevc_files_from_bugs_321622872",
				ExtraAttr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_chromestackdecoding"},
				ExtraHardwareDeps: hwdep.D(hwdep.SkipGPUFamily("rogue"), hwdep.SupportsV4L2FlatVideoDecoding()),
				ExtraSoftwareDeps: []string{caps.HWDecodeHEVC, "proprietary_codecs", "v4l2_codec"},
				ExtraData:         appendJSONFiles([]string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"}),
				Timeout:           calculateTestTimeout([]string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"}, "v4l2_flat_hevc_files_from_bugs_321622872"),
				Val: chromeStackDecoderVerificationTestParam{
					videoFiles:      []string{"test_vectors/hevc/files_from_bugs/b_321622872__bands_across_screen_4k.hevc"},
					validatorType:   decoding.MD5,
					mustFail:        false,
					enabledFeatures: []string{"V4L2FlatStatefulVideoDecoder"},
				},
			},
		},
	})
}

func ChromeStackDecoderVerification(ctx context.Context, s *testing.State) {
	expectation, err := expectations.GetTestExpectation(ctx, s.TestName())
	if err != nil {
		s.Fatal("Failed to load test expectation: ", err)
	}
	// Schedules a post-test expectations handling. If the test is expected to
	// fail, but did not, then this generates an error.
	defer func() {
		if err := expectation.HandleFinalExpectation(); err != nil {
			s.Error("Unmet expectation: ", err)
		}
	}()

	var tv []string
	param := s.Param().(chromeStackDecoderVerificationTestParam)
	for _, file := range param.videoFiles {
		tv = append(tv, s.DataPath(file))
	}

	if len(param.ignoredSysLogs) > 0 {
		graphics.DisableSysLogCheck(s.TestName(), param.ignoredSysLogs...)
	}

	if err := decoding.RunAccelVideoTestWithTestVectors(ctx, s.OutDir(), tv, param.validatorType, param.mustFail, param.enabledFeatures); err != nil {
		if expErr := expectation.ReportError("test failed: ", err); expErr != nil {
			s.Fatal("Unexpected error: ", expErr)
		}
	}
}
