// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package video

import (
	"context"
	"time"

	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
	"golang.org/x/sync/errgroup"

	"go.chromium.org/tast-tests/cros/common/perf"
	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/bundles/cros/video/platform"
	"go.chromium.org/tast-tests/cros/local/graphics"
)

const (
	// Time to sleep while collecting data.
	// The time to wait just after stating to play video so that CPU usage gets stable.
	stabilizationDuration = 5 * time.Second
	// The time to wait after CPU is stable so as to measure solid metric values.
	measurementDuration = 25 * time.Second
	// The number of times to loop decode.
	measurementIterations = 5
	// The number of frames to decode per loop, should be less than total in the stream.
	framesPerIteration = 200
)

type platformDecodingPerfParams struct {
	filename           string
	decoder            string
	decoderArgsBuilder platform.DecoderArgsBuilderFn
}

func init() {
	testing.AddTest(&testing.Test{
		Func: PlatformDecodingPerf,
		Desc: "Perf tests to track changes at the platform level by running the media/gpu/vaapi/test:decode_test binary for VAAPI decoding",
		Contacts: []string{
			"chromeos-gfx-video@google.com",
			"jchinlee@chromium.org",
		},
		BugComponent: "b:168352", // ChromeOS > Platform > Graphics > Video
		Attr:         []string{"group:graphics", "graphics_video", "graphics_perbuild", "graphics_video_platformdecoding"},
		Fixture:      "graphicsNoChrome",
		Params: []testing.Param{
			// Parameters generated by platform_decoding_perf_test.go. DO NOT EDIT.
			{
				Name: "vaapi_av1_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/1080p_30fps_300frames.av1.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.AV1DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_av1_1080_30", "vaapi"},
				ExtraData:         []string{"perf/av1/1080p_30fps_300frames.av1.ivf"},
				ExtraAttr:         []string{"graphics_video_av1"},
			},
			{
				Name: "dav1d_av1_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/1080p_30fps_300frames.av1.ivf",
					decoder:            "/usr/local/bin/dav1d",
					decoderArgsBuilder: platform.Dav1dDecodeArgs,
				},
				ExtraData: []string{"perf/av1/1080p_30fps_300frames.av1.ivf"},
				ExtraAttr: []string{"graphics_video_av1"},
			},
			{
				Name: "vaapi_av1_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/1080p_60fps_600frames.av1.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.AV1DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_av1_1080_60", "vaapi"},
				ExtraData:         []string{"perf/av1/1080p_60fps_600frames.av1.ivf"},
				ExtraAttr:         []string{"graphics_video_av1"},
			},
			{
				Name: "dav1d_av1_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/1080p_60fps_600frames.av1.ivf",
					decoder:            "/usr/local/bin/dav1d",
					decoderArgsBuilder: platform.Dav1dDecodeArgs,
				},
				ExtraData: []string{"perf/av1/1080p_60fps_600frames.av1.ivf"},
				ExtraAttr: []string{"graphics_video_av1"},
			},
			{
				Name: "vaapi_av1_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/2160p_30fps_300frames.av1.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.AV1DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_av1_2160_30", "vaapi"},
				ExtraData:         []string{"perf/av1/2160p_30fps_300frames.av1.ivf"},
				ExtraAttr:         []string{"graphics_video_av1"},
			},
			{
				Name: "dav1d_av1_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/2160p_30fps_300frames.av1.ivf",
					decoder:            "/usr/local/bin/dav1d",
					decoderArgsBuilder: platform.Dav1dDecodeArgs,
				},
				ExtraData: []string{"perf/av1/2160p_30fps_300frames.av1.ivf"},
				ExtraAttr: []string{"graphics_video_av1"},
			},
			{
				Name: "vaapi_av1_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/2160p_60fps_600frames.av1.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.AV1DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_av1_2160_60", "vaapi"},
				ExtraData:         []string{"perf/av1/2160p_60fps_600frames.av1.ivf"},
				ExtraAttr:         []string{"graphics_video_av1"},
			},
			{
				Name: "dav1d_av1_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/av1/2160p_60fps_600frames.av1.ivf",
					decoder:            "/usr/local/bin/dav1d",
					decoderArgsBuilder: platform.Dav1dDecodeArgs,
				},
				ExtraData: []string{"perf/av1/2160p_60fps_600frames.av1.ivf"},
				ExtraAttr: []string{"graphics_video_av1"},
			},
			{
				Name: "vaapi_h264_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/h264/1080p_30fps_300frames.h264",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.H264DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_h264_1080_30", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/h264/1080p_30fps_300frames.h264"},
				ExtraAttr:         []string{"graphics_video_h264"},
			},
			{
				Name: "vaapi_h264_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/h264/1080p_60fps_600frames.h264",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.H264DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_h264_1080_60", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/h264/1080p_60fps_600frames.h264"},
				ExtraAttr:         []string{"graphics_video_h264"},
			},
			{
				Name: "vaapi_h264_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/h264/2160p_30fps_300frames.h264",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.H264DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_h264_2160_30", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/h264/2160p_30fps_300frames.h264"},
				ExtraAttr:         []string{"graphics_video_h264"},
			},
			{
				Name: "vaapi_h264_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/h264/2160p_60fps_600frames.h264",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.H264DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_h264_2160_60", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/h264/2160p_60fps_600frames.h264"},
				ExtraAttr:         []string{"graphics_video_h264"},
			},
			{
				Name: "vaapi_hevc_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/hevc/1080p_30fps_300frames.hevc",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.HEVCDecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_hevc_1080_30", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/hevc/1080p_30fps_300frames.hevc"},
				ExtraAttr:         []string{"graphics_video_hevc"},
			},
			{
				Name: "vaapi_hevc_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/hevc/1080p_60fps_600frames.hevc",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.HEVCDecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_hevc_1080_60", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/hevc/1080p_60fps_600frames.hevc"},
				ExtraAttr:         []string{"graphics_video_hevc"},
			},
			{
				Name: "vaapi_hevc_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/hevc/2160p_30fps_300frames.hevc",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.HEVCDecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_hevc_2160_30", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/hevc/2160p_30fps_300frames.hevc"},
				ExtraAttr:         []string{"graphics_video_hevc"},
			},
			{
				Name: "vaapi_hevc_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/hevc/2160p_60fps_600frames.hevc",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.HEVCDecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_hevc_2160_60", "proprietary_codecs", "vaapi"},
				ExtraData:         []string{"perf/hevc/2160p_60fps_600frames.hevc"},
				ExtraAttr:         []string{"graphics_video_hevc"},
			},
			{
				Name: "vaapi_vp8_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/1080p_30fps_300frames.vp8.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP8DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp8_1080_30", "vaapi"},
				ExtraData:         []string{"perf/vp8/1080p_30fps_300frames.vp8.ivf"},
				ExtraAttr:         []string{"graphics_video_vp8"},
			},
			{
				Name: "vpxdec_vp8_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/1080p_30fps_300frames.vp8.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp8/1080p_30fps_300frames.vp8.ivf"},
				ExtraAttr: []string{"graphics_video_vp8"},
			},
			{
				Name: "vaapi_vp8_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/1080p_60fps_600frames.vp8.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP8DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp8_1080_60", "vaapi"},
				ExtraData:         []string{"perf/vp8/1080p_60fps_600frames.vp8.ivf"},
				ExtraAttr:         []string{"graphics_video_vp8"},
			},
			{
				Name: "vpxdec_vp8_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/1080p_60fps_600frames.vp8.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp8/1080p_60fps_600frames.vp8.ivf"},
				ExtraAttr: []string{"graphics_video_vp8"},
			},
			{
				Name: "vaapi_vp8_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/2160p_30fps_300frames.vp8.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP8DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp8_2160_30", "vaapi"},
				ExtraData:         []string{"perf/vp8/2160p_30fps_300frames.vp8.ivf"},
				ExtraAttr:         []string{"graphics_video_vp8"},
			},
			{
				Name: "vpxdec_vp8_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/2160p_30fps_300frames.vp8.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp8/2160p_30fps_300frames.vp8.ivf"},
				ExtraAttr: []string{"graphics_video_vp8"},
			},
			{
				Name: "vaapi_vp8_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/2160p_60fps_600frames.vp8.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP8DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp8_2160_60", "vaapi"},
				ExtraData:         []string{"perf/vp8/2160p_60fps_600frames.vp8.ivf"},
				ExtraAttr:         []string{"graphics_video_vp8"},
			},
			{
				Name: "vpxdec_vp8_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp8/2160p_60fps_600frames.vp8.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp8/2160p_60fps_600frames.vp8.ivf"},
				ExtraAttr: []string{"graphics_video_vp8"},
			},
			{
				Name: "vaapi_vp9_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/1080p_30fps_300frames.vp9.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP9DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp9_1080_30", "vaapi"},
				ExtraData:         []string{"perf/vp9/1080p_30fps_300frames.vp9.ivf"},
				ExtraAttr:         []string{"graphics_video_vp9"},
			},
			{
				Name: "vpxdec_vp9_1080p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/1080p_30fps_300frames.vp9.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp9/1080p_30fps_300frames.vp9.ivf"},
				ExtraAttr: []string{"graphics_video_vp9"},
			},
			{
				Name: "vaapi_vp9_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/1080p_60fps_600frames.vp9.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP9DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp9_1080_60", "vaapi"},
				ExtraData:         []string{"perf/vp9/1080p_60fps_600frames.vp9.ivf"},
				ExtraAttr:         []string{"graphics_video_vp9"},
			},
			{
				Name: "vpxdec_vp9_1080p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/1080p_60fps_600frames.vp9.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp9/1080p_60fps_600frames.vp9.ivf"},
				ExtraAttr: []string{"graphics_video_vp9"},
			},
			{
				Name: "vaapi_vp9_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/2160p_30fps_300frames.vp9.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP9DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp9_2160_30", "vaapi"},
				ExtraData:         []string{"perf/vp9/2160p_30fps_300frames.vp9.ivf"},
				ExtraAttr:         []string{"graphics_video_vp9"},
			},
			{
				Name: "vpxdec_vp9_2160p_30fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/2160p_30fps_300frames.vp9.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp9/2160p_30fps_300frames.vp9.ivf"},
				ExtraAttr: []string{"graphics_video_vp9"},
			},
			{
				Name: "vaapi_vp9_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/2160p_60fps_600frames.vp9.ivf",
					decoder:            "/usr/local/libexec/chrome-binary-tests/decode_test",
					decoderArgsBuilder: platform.VP9DecodeVAAPIargsNoLogs,
				},
				ExtraSoftwareDeps: []string{"autotest-capability:hw_dec_vp9_2160_60", "vaapi"},
				ExtraData:         []string{"perf/vp9/2160p_60fps_600frames.vp9.ivf"},
				ExtraAttr:         []string{"graphics_video_vp9"},
			},
			{
				Name: "vpxdec_vp9_2160p_60fps",
				Val: platformDecodingPerfParams{
					filename:           "perf/vp9/2160p_60fps_600frames.vp9.ivf",
					decoder:            "/usr/local/bin/vpxdec",
					decoderArgsBuilder: platform.VPxDecodeArgs,
				},
				ExtraData: []string{"perf/vp9/2160p_60fps_600frames.vp9.ivf"},
				ExtraAttr: []string{"graphics_video_vp9"},
			},
		},
	})
}

// measurePerformance collects performance metrics in two runs: one looping for a set amount of time
// and then collecting metrics, and one decoding once and collecting metrics. This is due to
// existing metrics collection operating per time duration.
func measurePerformance(ctx context.Context, filename, exec string, args []string, outDir string) error {
	p := perf.NewValues()
	var decodeCmd *testexec.Cmd

	// TODO(jchinlee): Modify collection of "metrics per time", i.e. GPU/CPU metrics, such that
	// they can be collected in the same run as "metrics per run".
	decodeCmd = testexec.CommandContext(ctx, exec, append(args, platform.LoopArgs(exec, 0, 0)...)...)
	testing.ContextLogf(ctx, "Collecting metrics per time: looping %q on %s", decodeCmd, filename)
	if err := collectMetricsPerTime(ctx, decodeCmd, p); err != nil {
		return err
	}

	testing.ContextLogf(ctx, "Collecting metrics per run: running %q on %s, first %d frames %d times", decodeCmd, filename, framesPerIteration, measurementIterations)
	decodeCmd = testexec.CommandContext(ctx, exec, append(args, platform.LoopArgs(exec, measurementIterations, framesPerIteration)...)...)
	if err := collectMetricsPerRun(ctx, decodeCmd, p); err != nil {
		return err
	}

	p.Save(outDir)
	return nil
}

// collectMetricsPerTime loops decode for a set amount of time, after which it collects the
// specified metrics and terminates the decode.
// Returns the first error encountered while collecting.
func collectMetricsPerTime(ctx context.Context, decodeCmd *testexec.Cmd, p *perf.Values) error {
	// Start looping decode. Don't collect errors, as we anticipate an error from the remote kill.
	go decodeCmd.Run()

	// Start measuring performance.
	wg := new(errgroup.Group)
	wg.Go(func() error {
		if err := graphics.MeasureGPUCounters(ctx, measurementDuration, p); err != nil {
			return errors.Wrap(err, "failed to measure GPU counters")
		}
		return nil
	})
	wg.Go(func() error {
		if err := graphics.MeasureCPUUsageAndPower(ctx, stabilizationDuration, measurementDuration, p); err != nil {
			return errors.Wrap(err, "failed to measure CPU/Package power")
		}
		return nil
	})

	return wg.Wait()
}

// collectMetricsPerRun runs decode a set number of frames and collects metrics based on the runs.
func collectMetricsPerRun(ctx context.Context, decodeCmd *testexec.Cmd, p *perf.Values) error {
	start := time.Now()
	if stdout, stderr, err := decodeCmd.SeparatedOutput(testexec.DumpLogOnError); err != nil {
		output := append(stdout, stderr...)
		testing.ContextLogf(ctx, "decode failed with %v: %s", err, string(output))
		return err
	}
	elapsed := time.Since(start)

	// Get FPS.
	// Note that the calculation will undercount if framesPerIteration is fewer than total
	// frames in the stream, as many more frames will be decoded than the test believes.
	nFrames := framesPerIteration * measurementIterations
	fps := float64(nFrames) / float64(elapsed.Seconds())
	p.Set(perf.Metric{
		Name:      "frames_per_second",
		Unit:      "fps",
		Direction: perf.BiggerIsBetter,
	}, fps)
	testing.ContextLogf(ctx, "frames_per_second: %f fps", fps)

	return nil
}

func PlatformDecodingPerf(ctx context.Context, s *testing.State) {
	testOpt := s.Param().(platformDecodingPerfParams)
	filename := testOpt.filename
	exec := testOpt.decoder
	args := testOpt.decoderArgsBuilder(ctx, s.DataPath(filename))
	if err := measurePerformance(ctx, filename, exec, args, s.OutDir()); err != nil {
		s.Fatal("Error collecting perf metrics: ", err)
	}
}
