metric_bundles {
  row {
    values {
      double_value: 123.0
    }
    dimension {
      string_value: "a"
    }
  }
  specs {
    id: "one_dimension"
    dimensions: "dimension"
    value: "value"
    query {
      inner_query_id: "query2"
    }
    polarity: LOWER_IS_BETTER
    unit: MEGABYTES
  }
}

metric_bundles {
  row {
    values {
      double_value: 2.0
    }
    dimension {
      string_value: "a"
    }
    dimension {
      int64_value: 2
    }
    dimension {
      double_value: 3.14
    }
  }

  row {
    values {
      double_value: 4.0
    }
    dimension {
      string_value: "x"
    }
    dimension {
      string_value: "y"
    }
    dimension {
      bool_value: true
    }
  }

  specs {
    id: "three_dimensions"
    dimensions: "dimension1"
    dimensions: "dimension2"
    dimensions: "dimension3"
    value: "value1"
    query {
      inner_query_id: "query3"
    }
    polarity: HIGHER_IS_BETTER
    unit: COUNT
  }
}
