// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package onedrive

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/common/action"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/ash"
	"go.chromium.org/tast-tests/cros/local/chrome/browser"
	"go.chromium.org/tast-tests/cros/local/chrome/lacros/lacrosfixt"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/filesinternals"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/ms365"
	"go.chromium.org/tast-tests/cros/local/cryptohome"
	"go.chromium.org/tast-tests/cros/local/drivefs"
	"go.chromium.org/tast-tests/cros/local/filesconsts"
	"go.chromium.org/tast-tests/cros/local/sysutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/fsutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddFixture(&testing.Fixture{
		Name:     "onedrive",
		Desc:     "Sets up 3 office files docx, pptx and xlsx. At tear down tries to remove them from the remote service via ODFS",
		Contacts: []string{"lucmult@chromium.org", "chromeos-files-syd@chromum.org"},
		Impl: &fixture{
			bt:            browser.TypeAsh,
			chromeOptions: []chrome.Option{chrome.EnableFeatures("UploadOfficeToCloud")},
			provider:      filesconsts.OneDrive,
		},
		SetUpTimeout:    chrome.LoginTimeout,
		ResetTimeout:    chrome.ResetTimeout,
		TearDownTimeout: 30 * time.Second,
		PreTestTimeout:  60 * time.Second,
		PostTestTimeout: 30 * time.Second,
		Data:            []string{"Sample_DOCX_file_20230704.docx", "Sample_PPTX_file_20230704.pptx", "Sample_XLSX_file_20230724.xlsx"},
	})

	testing.AddFixture(&testing.Fixture{
		Name:     "onedriveLacros",
		Desc:     "Lacros variant of onedrive",
		Contacts: []string{"lucmult@chromium.org", "chromeos-files-syd@chromum.org"},
		Impl: &fixture{
			bt:            browser.TypeLacros,
			chromeOptions: []chrome.Option{chrome.EnableFeatures("UploadOfficeToCloud")},
			provider:      filesconsts.OneDrive,
		},
		SetUpTimeout:    chrome.LoginTimeout,
		ResetTimeout:    chrome.ResetTimeout,
		TearDownTimeout: 30 * time.Second,
		PreTestTimeout:  60 * time.Second,
		PostTestTimeout: 30 * time.Second,
		Data:            []string{"Sample_DOCX_file_20230704.docx", "Sample_PPTX_file_20230704.pptx", "Sample_XLSX_file_20230724.xlsx"},
	})

	testing.AddFixture(&testing.Fixture{
		Name:     "onedriveAndGoogleDrive",
		Desc:     "Sets up 3 office files docx, pptx and xlsx. At tear down tries to remove them from the remote service via ODFS",
		Contacts: []string{"lucmult@chromium.org", "chromeos-files-syd@chromum.org"},
		Impl: &fixture{
			bt:       browser.TypeAsh,
			provider: filesconsts.DriveFs,
		},
		SetUpTimeout:    chrome.LoginTimeout,
		ResetTimeout:    chrome.ResetTimeout,
		TearDownTimeout: 30 * time.Second,
		PreTestTimeout:  60 * time.Second,
		PostTestTimeout: 30 * time.Second,
		Parent:          "driveFsStartedWithOfficeEnabled", // TODO(b/291524698): Create more DriveFS accounts.
		Data:            []string{"Sample_DOCX_file_20230704.docx", "Sample_PPTX_file_20230704.pptx", "Sample_XLSX_file_20230724.xlsx"},
	})
}

// TestFile generated by the fixture.
type TestFile struct {
	// File name auto-generated as part of the fixture with a random suffix.
	FileName string
	// This is the whole path for the original file from the repo, it doesn't have the random suffix.
	SrcFile string
	// File type: docx, pptx or xlsx.
	FileType string
}

// FixtureData is the struct exposed to tests.
type FixtureData struct {
	Chrome      *chrome.Chrome
	TestAPIConn *chrome.TestConn

	// Generated folder in MyFiles.
	TargetFolder string

	// A list of the generated files, the test is expected to iterate over those files.
	GeneratedFiles []TestFile

	// The DriveFS helper, reused by tests.
	DriveFs *drivefs.DriveFs
}

type fixture struct {
	cr            *chrome.Chrome
	tconn         *chrome.TestConn
	chromeOptions []chrome.Option
	bt            browser.Type
	cleanUpFiles  []TestFile
	// Full path to the new folder created in Downloads to host the office files used by the test.
	downloadSubFolder string
	screenRecorder    *uiauto.ScreenRecorder
	provider          filesconsts.Provider
	// Holds a pointer to the FixtureData so the PreTest() can push new files to the test.
	data *FixtureData
	// Maps the keys docx, xlsx and pptx to the full local path in the  Data directory.
	// Used to share the path between SetUp() and PreTest().
	srcFiles map[string]string
}

// generateTestFileName generates a unique-ish file name based on a provided
// prefix, the current time, and a random number.
func generateTestFileName(fName string) string {
	ext := filepath.Ext(fName)
	baseName := strings.TrimSuffix(fName, ext)
	return fmt.Sprintf("%s-%d-%d%s", baseName, time.Now().UnixNano(), rand.Intn(10000), ext)
}

// prepareOfficeFile copies the test file to a sub-folder of downloads with a unique name.
func prepareOfficeFile(srcPath, targetFolder string) (testFile TestFile, err error) {
	testFile.FileName = generateTestFileName(filepath.Base(srcPath))
	testFile.SrcFile = srcPath
	testFile.FileType = strings.Replace(filepath.Ext(testFile.FileName), ".", "", 1)

	dst := filepath.Join(targetFolder, testFile.FileName)
	if err := fsutil.CopyFile(srcPath, dst); err != nil {
		return TestFile{}, errors.Wrapf(err, "failed to copy the file %s  to: %s", srcPath, dst)

	}
	if err := os.Chown(dst, int(sysutil.ChronosUID), int(sysutil.ChronosGID)); err != nil {
		return TestFile{}, errors.Wrapf(err, "failed to chown test file %s", dst)
	}

	return testFile, nil
}

func (f *fixture) SetUp(ctx context.Context, s *testing.FixtState) interface{} {
	var cr *chrome.Chrome
	var err error
	var driveFsClient *drivefs.DriveFs
	if f.provider == filesconsts.DriveFs {
		cr = s.ParentValue().(*drivefs.FixtureData).Chrome
		f.tconn = s.ParentValue().(*drivefs.FixtureData).TestAPIConn
		driveFsClient = s.ParentValue().(*drivefs.FixtureData).DriveFs
	} else if f.provider == filesconsts.OneDrive {
		opts := f.chromeOptions

		if f.bt == browser.TypeLacros {
			var err error
			opts, err = lacrosfixt.NewConfig(lacrosfixt.ChromeOptions(opts...)).Opts()
			if err != nil {
				s.Fatal("Failed to get lacros options: ", err)
			}
		}

		ctx, cancel := context.WithTimeout(ctx, chrome.LoginTimeout)
		defer cancel()

		cr, err = chrome.New(ctx, opts...)
		if err != nil {
			s.Fatal("Failed to start Chrome: ", err)
		}
		tconn, err := cr.TestAPIConn(ctx)
		if err != nil {
			s.Fatal("Failed creating test API connection: ", err)
		}
		f.tconn = tconn
	}
	f.cr = cr

	// Prepare folder to receive files for tests.
	targetBaseName := "odfs_files"
	myFilesPath, err := cryptohome.MyFilesPath(ctx, cr.NormalizedUser())
	if err != nil {
		s.Fatal("Failed to retrieve user's MyFiles path: ", err)
	}
	targetFolder := filepath.Join(myFilesPath, targetBaseName)
	if err := os.MkdirAll(targetFolder, 0755); err != nil {
		s.Fatal("Failed to create target dir: ", err, targetFolder)
	}
	if err := os.Chown(targetFolder, int(sysutil.ChronosUID), int(sysutil.ChronosGID)); err != nil {
		s.Fatal("Failed to chown the test folder: ", err, targetFolder)
	}
	f.downloadSubFolder = targetFolder

	f.srcFiles = make(map[string]string)

	f.srcFiles["docx"] = s.DataPath("Sample_DOCX_file_20230704.docx")
	f.srcFiles["pptx"] = s.DataPath("Sample_PPTX_file_20230704.pptx")
	f.srcFiles["xlsx"] = s.DataPath("Sample_XLSX_file_20230724.xlsx")

	f.data = &FixtureData{
		Chrome:       cr,
		TestAPIConn:  f.tconn,
		TargetFolder: targetBaseName,
		DriveFs:      driveFsClient,
	}
	return f.data
}

func (f *fixture) TearDown(ctx context.Context, s *testing.FixtState) {
	// The deletion in the loop below often fails, here we delete files from previous runs.
	if len(f.cleanUpFiles) > 0 {
		DeleteOldRemoteFiles(ctx, f.cleanUpFiles[0].FileName)
	}

	// NOTE: The deletion below fails if the files are still open in the UI (Office 365 PWA).
	for _, testFile := range f.cleanUpFiles {
		name := testFile.FileName
		files, err := filepath.Glob("/media/fuse/fusebox/fsp.*/" + name)
		if err != nil {
			s.Logf("Failed cleaning up file: %s. %v", name, err)
		} else {
			for _, file := range files {
				s.Log("Deleting: ", file)
				if err := deleteFileRetrying(ctx, file); err != nil {
					s.Logf("Failed deleting the remote file: %s. %v", file, err)
				}
			}
		}
	}

	f.cleanUpFiles = []TestFile{}
	// For DriveFS the parent fixture takes care of closing it.
	if f.provider == filesconsts.OneDrive {
		if err := f.cr.Close(ctx); err != nil {
			s.Log("Failed closing chrome: ", err)
		}
		f.cr = nil
	}
}

func (f *fixture) Reset(ctx context.Context) error {
	if err := ash.CloseAllWindows(ctx, f.tconn); err != nil {
		testing.ContextLog(ctx, "Failed trying to close all windows: ", err)
	}
	return nil
}

func (f *fixture) PreTest(ctx context.Context, s *testing.FixtTestState) {
	recorder, err := uiauto.NewScreenRecorder(ctx, f.tconn)
	if err != nil {
		s.Log("Failed to create screen recorder: ", err)
	}
	if recorder != nil {
		if err := recorder.Start(ctx, f.tconn); err != nil {
			s.Log("Failed to start screen recorder: ", err)
		}
		f.screenRecorder = recorder
	}

	// Copy the docx, pptx and xlsx to MyFiles to be used in the tests.
	var docx, pptx, xlsx TestFile
	var generatedFiles []TestFile

	if docx, err = prepareOfficeFile(f.srcFiles["docx"], f.downloadSubFolder); err != nil {
		s.Fatal("Failed to prepare file: ", err)
	}
	if pptx, err = prepareOfficeFile(f.srcFiles["pptx"], f.downloadSubFolder); err != nil {
		s.Fatal("Failed to prepare file: ", err)
	}
	if xlsx, err = prepareOfficeFile(f.srcFiles["xlsx"], f.downloadSubFolder); err != nil {
		s.Fatal("Failed to prepare file: ", err)
	}
	generatedFiles = []TestFile{
		docx,
		pptx,
		xlsx,
	}
	f.data.GeneratedFiles = generatedFiles
	f.cleanUpFiles = append(f.cleanUpFiles, generatedFiles...)

	fi, err := filesinternals.Start(ctx, f.tconn, f.cr)
	if err != nil {
		s.Fatal("Failed to start chrome://files-internals: ", err)
	}

	if err := action.Combine("Clear prefs on chrome://files-internals",
		fi.ClearOfficeFileHandlers(),
		fi.ClearAlwaysMoveOneDrive(),
		fi.ClearAlwaysMoveGoogleDrive(),
	)(ctx); err != nil {
		s.Fatal("Failed to clear prefs on chrome://files-internals: ", err)
	}

	if err := fi.Close(ctx); err != nil {
		s.Fatal("Failed to close chrome://files-internals: ", err)
	}

	if err := MaybeUnmountOdfs(ctx, f.tconn, f.cr); err != nil {
		s.Fatal("Failed to unmount ODFS: ", err)
	}

	if err := ms365.MaybeUninstallPwa(ctx, f.cr, f.tconn); err != nil {
		s.Fatal("Failed to uninstall MS365 PWA: ", err)
	}

	if err = ms365.ClearBrowserCookiesForOffice(ctx, f.cr); err != nil {
		s.Fatal("Failed to clear browser cookies for office website: ", err)
	}
}

// PostTests makes a best effort attempt to restore the state to where it was pretest.
func (f *fixture) PostTest(ctx context.Context, s *testing.FixtTestState) {
	// Local Files.
	dirEntries, err := os.ReadDir(f.downloadSubFolder)
	if err != nil {
		s.Logf("Failed to list local directory: %q - %v", f.downloadSubFolder, err)
	} else {
		for _, e := range dirEntries {
			info, err := e.Info()
			if (err == nil) && info.Mode().IsRegular() {
				if err := os.Remove(filepath.Join(f.downloadSubFolder, info.Name())); err != nil {
					s.Logf("Failed to remove local file: %q - %v", info.Name(), err)
				}
			}
		}
	}

	if f.screenRecorder != nil {
		f.screenRecorder.StopAndSaveOnError(ctx, filepath.Join(s.OutDir(), "record.webm"), s.HasError)
	}
}

func deleteFileRetrying(ctx context.Context, file string) error {
	return action.RetryWithExponentialBackoff(5, func(ctx context.Context) error {
		return os.Remove(file)
	}, 500*time.Millisecond, 2)(ctx)
}
