// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package arc

import (
	"context"
	"fmt"
	"time"

	"go.chromium.org/tast-tests/cros/local/arc"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/ash"
	"go.chromium.org/tast-tests/cros/local/chrome/display"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/mouse"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/pointer"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/quicksettings"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/coords"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

const (
	arcNotificationTest2ApkFilename  = "ArcNotificationTest2.apk"
	arcNotificationTest2PackageName  = "org.chromium.arc.testapp.notification2"
	arcNotificationTest2ActivityName = ".MainActivity"
	arcNotificationTest2StartCommand = arcNotificationTest2PackageName + ".SHOW_NOTIFICATION"
	// Notification ID on Android is composed of many components.
	// So this is just the substring to match the notification generated by the test app.
	arcNotificationTest2NotificationID    = "|" + arcNotificationTest2PackageName + "|"
	arcNotificationTest2PermissionAllowID = "com.android.permissioncontroller:id/permission_allow_button"

	// allowedHeightError is the allowed error for notification height.
	allowedHeightError = 5
)

type closeMethod string

const (
	closeMethodSwipeOut       closeMethod = "swipeOut"
	closeMethodClickEvent                 = "clickEvent"
	closeMethodClearAllButton             = "clearAllButton"
	closeMethodCloseButton                = "closeButton"
)

var (
	arcNotificationContentView = nodewith.HasClass("ArcNotificationContentView")
	arcNotificationSurface     = nodewith.HasClass("ArcNotificationSurface")
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         NotificationExperimental,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Launches a testing APK to generate various kinds of notifications and verifies its state",
		Contacts: []string{
			"arc-framework+tast@google.com",
			"yhanada@chromium.org",
			"toshikikikuchi@chromium.org",
		},
		// ChromeOS > Software > ARC++ > Framework > Notifications
		BugComponent: "b:537324",
		Attr:         []string{"group:mainline", "informational"},
		Data:         []string{arcNotificationTest2ApkFilename},
		SoftwareDeps: []string{"chrome"},
		Timeout:      4 * time.Minute,
		Params: []testing.Param{{
			Fixture:           "arcBooted",
			ExtraSoftwareDeps: []string{"android_container"},
		}, {
			Name:              "vm",
			Fixture:           "arcBooted",
			ExtraSoftwareDeps: []string{"android_vm"},
		}, {
			// TODO(b/290289663): Remove this variant once qsRevamp is launched.
			Name:              "qsrevamp",
			Fixture:           "arcBootedQsRevampEnabled",
			ExtraSoftwareDeps: []string{"android_p"},
		}, {
			// TODO(b/290289663): Remove this variant once qsRevamp is launched.
			Name:              "qsrevamp_vm",
			Fixture:           "arcBootedQsRevampEnabled",
			ExtraSoftwareDeps: []string{"android_vm"},
		}},
	})
}

func closeNotification(ctx context.Context, tconn *chrome.TestConn, ui *uiauto.Context, mousePC, touchPC pointer.Context, close closeMethod) error {
	notificationBounds, err := ui.Location(ctx, arcNotificationContentView)
	if err != nil {
		return errors.Wrap(err, "failed to get the notification bounds")
	}

	switch close {
	case closeMethodSwipeOut:
		if err := touchPC.Drag(
			notificationBounds.CenterPoint(),
			touchPC.DragTo(coords.NewPoint(0, notificationBounds.CenterPoint().Y), 500*time.Millisecond))(ctx); err != nil {
			return errors.Wrap(err, "failed to swipe out the notification")
		}
	case closeMethodClickEvent:
		if err := mousePC.ClickAt(notificationBounds.CenterPoint())(ctx); err != nil {
			return errors.Wrap(err, "failed to click the notification")
		}
	case closeMethodClearAllButton:
		if err := ui.LeftClick(nodewith.Role(role.StaticText).Name("Clear all"))(ctx); err != nil {
			return errors.Wrap(err, "failed to click 'Clear all' button")
		}
	case closeMethodCloseButton:
		if err := mouse.Move(tconn, notificationBounds.CenterPoint(), time.Second)(ctx); err != nil {
			return errors.Wrap(err, "failed to move mouse on the notification")
		}
		if err := ui.LeftClick(nodewith.Role(role.Button).Name("Notification close"))(ctx); err != nil {
			return errors.Wrap(err, "failed to click notification close button")
		}
	}

	return nil
}

func composeNotification(ctx context.Context, tconn *chrome.TestConn, a *arc.ARC, ui *uiauto.Context, style string) (*ash.Notification, error) {
	if _, err := a.BroadcastIntent(ctx, arcNotificationTest2StartCommand, "-p", arcNotificationTest2PackageName, "--es", "style", style, "--ez", "autoCancel", "true", "--esn", "notify"); err != nil {
		return nil, errors.Wrap(err, "failed to send a broadcast")
	}

	notification, err := ash.WaitForNotification(ctx, tconn, 5*time.Second, ash.WaitIDContains(arcNotificationTest2NotificationID))
	if err != nil {
		return nil, errors.Wrap(err, "failed to wait until the notification appears")
	}

	return notification, nil
}

func clickExpandButtonAndWaitForAnimation(ctx context.Context, ui *uiauto.Context, mousePC pointer.Context) error {
	bounds, err := ui.Location(ctx, arcNotificationContentView)
	if err != nil {
		return errors.Wrap(err, "failed to get the notification bounds")
	}

	// TODO(b/224685870): Use UIAutomator to get the button position dynamically when it supports multi-display.
	expandButtonOffset := coords.NewPoint(-28, 44)
	if err := mousePC.ClickAt(bounds.TopRight().Add(expandButtonOffset))(ctx); err != nil {
		return errors.Wrap(err, "failed to click the notification")
	}

	// Wait until animation finished.
	if err := ui.WithInterval(2 * time.Second).WaitForLocation(arcNotificationContentView)(ctx); err != nil {
		return errors.Wrap(err, "the notification did not stop animating")
	}

	return nil
}

// testExpandButton verifies the notification bounds should be "toggled" (i.e., be changed and reverted) by clicking the expand button twice.
// Here we're not interested whether the notification is expanded/collapsed by default which is the Android framework's decision.
func testExpandButton(ctx context.Context, ui *uiauto.Context, mousePC pointer.Context) error {
	initialBounds, err := ui.Location(ctx, arcNotificationContentView)
	if err != nil {
		return errors.Wrap(err, "failed to get the notification bounds")
	}

	if err := clickExpandButtonAndWaitForAnimation(ctx, ui, mousePC); err != nil {
		return errors.Wrap(err, "failed to click the expand button to collapse")
	}

	changedBounds, err := ui.Location(ctx, arcNotificationContentView)
	if err != nil {
		return errors.Wrap(err, "failed to get the notification bounds")
	}

	if changedBounds.Width != initialBounds.Width {
		return errors.Wrapf(err, "changed width is different from initial width unexpectedly: want %v, got %v", initialBounds.Width, changedBounds.Width)
	}
	if changedBounds.Height == initialBounds.Height {
		return errors.Wrapf(err, "changed height is the same as initial height unexpectedly: got %v", changedBounds.Height)
	}

	if err := clickExpandButtonAndWaitForAnimation(ctx, ui, mousePC); err != nil {
		return errors.Wrap(err, "failed to click the expand button to expand")
	}

	revertedBounds, err := ui.Location(ctx, arcNotificationContentView)
	if err != nil {
		return errors.Wrap(err, "failed to get the notification bounds")
	}

	// Android may relayout the notification, which can result in a slightly different height.
	if !coords.CompareBoundsWithMargins(*revertedBounds, *initialBounds, 0, allowedHeightError, 0, allowedHeightError) {
		return errors.Wrapf(err, "reverted bounds is different from initial bounds within height margin (%d) unexpectedly: want %v, got %v", allowedHeightError, initialBounds, revertedBounds)
	}

	return nil
}

func testExpandNotification(ctx, cleanupCtx context.Context, tconn *chrome.TestConn, a *arc.ARC, ui *uiauto.Context, mousePC pointer.Context, style string) error {
	if _, err := composeNotification(ctx, tconn, a, ui, style); err != nil {
		return errors.Wrap(err, "failed to compose a notification")
	}

	// TODO(b/290289663): Remove this check once qsRevamp is launched.
	qsRevampEnabled, err := quicksettings.QsRevampEnabled(ctx, tconn)
	if err != nil {
		return errors.Wrap(err, "failed to get QsRevamp state")
	}
	if qsRevampEnabled {
		// Open the notification center to ensure the notification is showing.
		if err := quicksettings.ShowNotificationCenter(ctx, tconn); err != nil {
			return errors.Wrap(err, "failed to show notification center")
		}
	} else {
		if err := quicksettings.ShowWithRetry(ctx, tconn, 10*time.Second); err != nil {
			return errors.Wrap(err, "failed to open Quick Settings")
		}
		defer quicksettings.Hide(cleanupCtx, tconn)
	}

	// Wait until the ARC notification surface gets ready
	if err := ui.WaitUntilExists(arcNotificationSurface)(ctx); err != nil {
		return errors.Wrap(err, "failed to wait until the surface gets ready")
	}

	// Wait until animation finished.
	if err := ui.WithInterval(2 * time.Second).WaitForLocation(arcNotificationContentView)(ctx); err != nil {
		return errors.Wrap(err, "the notification did not stop animating")
	}

	if err := testExpandButton(ctx, ui, mousePC); err != nil {
		return errors.Wrap(err, "failed to test expand button")
	}

	return nil
}

func testCloseNotification(ctx, cleanupCtx context.Context, tconn *chrome.TestConn, a *arc.ARC, ui *uiauto.Context, mousePC, touchPC pointer.Context, style string, close closeMethod) error {
	notification, err := composeNotification(ctx, tconn, a, ui, style)
	if err != nil {
		return errors.Wrap(err, "failed to compose a notification")
	}

	// TODO(b/290289663): Remove this check once qsRevamp is launched.
	qsRevampEnabled, err := quicksettings.QsRevampEnabled(ctx, tconn)
	if err != nil {
		return errors.Wrap(err, "failed to get QsRevamp state")
	}
	if qsRevampEnabled {
		// Open the notification center to ensure the notification is showing.
		if err := quicksettings.ShowNotificationCenter(ctx, tconn); err != nil {
			return errors.Wrap(err, "failed to show notification center")
		}
	} else {
		if err := quicksettings.ShowWithRetry(ctx, tconn, 10*time.Second); err != nil {
			return errors.Wrap(err, "failed to open Quick Settings")
		}
		defer quicksettings.Hide(cleanupCtx, tconn)
	}

	// Wait until the ARC notification surface gets ready
	if err := ui.WaitUntilExists(arcNotificationSurface)(ctx); err != nil {
		return errors.Wrap(err, "failed to wait until the surface gets ready")
	}

	// Wait until animation finished.
	if err := ui.WithInterval(2 * time.Second).WaitForLocation(arcNotificationContentView)(ctx); err != nil {
		return errors.Wrap(err, "the notification did not stop animating")
	}

	if err := closeNotification(ctx, tconn, ui, mousePC, touchPC, close); err != nil {
		return errors.Wrap(err, "failed to close the notification")
	}

	if err := ash.WaitUntilNotificationGone(ctx, tconn, 5*time.Second, ash.WaitIDContains(notification.ID)); err != nil {
		return errors.Wrap(err, "failed to wait until the notification disappears")
	}

	return nil
}

func NotificationExperimental(ctx context.Context, s *testing.State) {
	// Reserve ten seconds for various cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, time.Second*10)
	defer cancel()

	cr := s.FixtValue().(*arc.PreData).Chrome
	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed to create Test API connection: ", err)
	}
	a := s.FixtValue().(*arc.PreData).ARC
	d := s.FixtValue().(*arc.PreData).UIDevice
	uia := uiauto.New(tconn).WithTimeout(5 * time.Second)

	mousePC := pointer.NewMouse(tconn)
	defer mousePC.Close(ctx)

	touchPC, err := pointer.NewTouch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to set up the touch context: ", err)
	}
	defer touchPC.Close(ctx)

	// Install the test app.
	if err := a.Install(ctx, s.DataPath(arcNotificationTest2ApkFilename)); err != nil {
		s.Fatal("Failed to install app: ", err)
	}

	if err := arc.EnsureNotificationPermission(ctx, a, arcNotificationTest2PackageName); err != nil {
		s.Fatal("Failed to ensure the permission: ", err)
	}

	act, err := arc.NewActivity(a, arcNotificationTest2PackageName, arcNotificationTest2ActivityName)
	if err != nil {
		s.Fatal("Failed to create a new activity: ", err)
	}

	if err := act.StartWithDefaultOptions(ctx, tconn); err != nil {
		s.Fatal("Failed to start the activity: ", err)
	}

	if err := d.WaitForIdle(ctx, 10*time.Second); err != nil {
		s.Fatal("Failed to wait for Android to be idle: ", err)
	}

	info, err := display.GetPrimaryInfo(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to get primary display info: ", err)
	}
	hasTouchSupport := info.HasTouchSupport

	// Test notification closing.
	for _, style := range []string{"basic", "big_text", "big_picture", "inbox", "messaging"} {
		for _, close := range []closeMethod{closeMethodSwipeOut, closeMethodClickEvent, closeMethodClearAllButton, closeMethodCloseButton} {
			s.Run(ctx, fmt.Sprintf("Close notification (style=%s closeMethod=%s)", style, close), func(ctx context.Context, s *testing.State) {
				if close == closeMethodSwipeOut && !hasTouchSupport {
					testing.ContextLog(ctx, "Skipping closeMethodSwipeOut because the device doesn't have touch support")
					return
				}

				// Cleanup
				defer ash.CloseNotifications(cleanupCtx, tconn)

				if err := testCloseNotification(ctx, cleanupCtx, tconn, a, uia, mousePC, touchPC, style, close); err != nil {
					s.Fatal("Failed to test to close a notification: ", err)
				}
			})
		}
	}

	// Test notification expanding.
	for _, style := range []string{"big_text", "big_picture", "inbox"} {
		s.Run(ctx, fmt.Sprintf("Expand notification (style=%s)", style), func(ctx context.Context, s *testing.State) {
			// Cleanup
			defer ash.CloseNotifications(cleanupCtx, tconn)

			if err := testExpandNotification(ctx, cleanupCtx, tconn, a, uia, mousePC, style); err != nil {
				s.Fatal("Failed to test to expand a notification: ", err)
			}
		})
	}
}
