// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.autoupdate;

import "google/protobuf/empty.proto";

option go_package = "chromiumos/tast/services/cros/autoupdate";

// UpdateService provides functions to interact with the update client on the test device,
// and get data needed for the update.
service UpdateService {
  rpc CheckForUpdate (UpdateRequest) returns (google.protobuf.Empty) {}
  rpc PeriodicCheckForUpdate (google.protobuf.Empty) returns (StatusResult) {}
  rpc LSBReleaseContent (google.protobuf.Empty) returns (LSBRelease) {}
  rpc StatefulLSBReleaseContent (google.protobuf.Empty) returns (LSBRelease) {}
  rpc OverwriteStatefulLSBRelease (LSBRelease) returns (google.protobuf.Empty) {}
  rpc ResetUpdateEngine (google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc EnsureUpdateEngineReady (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message UpdateRequest {
  string omaha_url = 1;
  string app_version = 2;
  bool check_only = 3;
}

message LSBRelease {
  bytes content_json = 1;
}

message StatusResult {
  int64 last_checked_time = 1;
  double progress = 2;
  string current_operation = 3;
}