// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.camerabox;

import "camerabox/common.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/camerabox";

// OrientationService provides RPC methods verifying orientation on DUT in camerabox
// setup.
service OrientationService {
  rpc CheckOrientation(CheckOrientationRequest) returns (CheckOrientationResponse) {}
}

message CheckOrientationRequest {
  // Absolute path for saving data used on DUT.
  string data_path = 1;
  // DUT's target camera facing to be aligned.
  Facing facing = 2;
}

message CheckOrientationResponse {
  // Check result.
  TestResult result = 1;
  // Error message from running check.
  string error = 2;
}
