// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package setup

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"os/user"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome/internal/config"
	"go.chromium.org/tast-tests/cros/local/chrome/internal/driver"
	"go.chromium.org/tast-tests/cros/local/session"
	"go.chromium.org/tast-tests/cros/local/upstart"

	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/fsutil"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/timing"
)

// Obfuscated username is generated by SHA1, which has a digest length of 20 bytes.
// https://source.corp.google.com/chromeos_public/src/platform2/libbrillo/brillo/cryptohome.cc;l=83
var obfuscatedUsernameRegexp = regexp.MustCompile(`^[\da-f]{40}$`)

// Experiements in fieldtrial_testing_config.json are enabled in certain builds.
// https://source.chromium.org/chromium/chromium/src/+/main:testing/variations/README.md
// This var allows you to enable, disable or use the default for your build. Tests can
// also set enable or disable via `chrome.FieldTrialConfig()` which overrides this var.
var fieldTrialConfig = testing.RegisterVarString(
	"setup.FieldTrialConfig",
	"default",
	"[enable|disable|default] Whether to force enable / disable fieldtrial_testing_config experiements, or use default.")

// RestartChromeForTesting restarts the ui job, asks session_manager to enable Chrome testing,
// and waits for Chrome to listen on its debugging port.
func RestartChromeForTesting(ctx context.Context, cfg *config.Config, extArgs, lacrosExtArgs []string) error {
	ctx, st := timing.Start(ctx, "restart")
	defer st.End()

	if err := restartSession(ctx, cfg); err != nil {
		return err
	}

	sm, err := session.NewSessionManager(ctx)
	if err != nil {
		return err
	}

	// Remove the file where Chrome will write its debugging port after it's restarted.
	if err := driver.PrepareForRestart(); err != nil {
		return err
	}

	testing.ContextLog(ctx, "Asking session_manager to enable Chrome testing")
	args := []string{
		"--remote-debugging-port=0",                   // Let Chrome choose its own debugging port.
		"--disable-logging-redirect",                  // Disable redirection of Chrome logging into cryptohome.
		"--ash-disable-system-sounds",                 // Disable system startup sound.
		"--ash-no-nudges",                             // Disable first-login educational nudges.
		"--enable-experimental-extension-apis",        // Allow Chrome to use the Chrome Automation API.
		"--redirect-libassistant-logging",             // Redirect libassistant logging to /var/log/chrome/.
		"--no-first-run",                              // Prevent showing up offer pages, e.g. google.com/chromebooks.
		"--cros-region=" + cfg.Region(),               // Force the region.
		"--cros-regions-mode=hide",                    // Ignore default values in VPD.
		"--enable-oobe-test-api",                      // Enable OOBE helper functions for authentication.
		"--keep-login-events-for-testing",             // Keep LoginEventRecorder data for later retrieval by tests.
		"--disable-input-event-activation-protection", // Don't try to detect and ignore unintended clicks.
		"--force-raster-color-profile=srgb",           // Force rendering to run in the sRGB color space. See b/221643955 for details.
		"--propagate-iph-for-testing",                 // Disable In Product Help notifications and UI. Pass additional parameters to enable. See https://chromium.googlesource.com/chromium/src/+/main/components/feature_engagement/README.md#Automated-External-Testing-Tast and b/296141011 for details.
	}
	if !cfg.EnableHDR() {
		args = append(args, "--force-color-profile=srgb") // Force chrome to treat the display as sRGB. See b/221643955 for details.
	}

	if !cfg.EnableRestoreTabs() {
		args = append(args, "--no-startup-window") // Do not start up chrome://newtab by default to avoid unexpected patterns (doodle etc.)
	}
	if cfg.HideCrashRestoreBubble() {
		// Do not show "Chrome did not shut down correctly" bubble.
		// --hide-crash-restore-bubble is used when full session restore is disabled.
		args = append(args, "--hide-crash-restore-bubble")
		args = append(args, "--force-full-restore-and-session-restore-after-crash")
	}

	if cfg.SkipOOBEAfterLogin() {
		args = append(args, "--oobe-skip-postlogin")
	}

	if !cfg.InstallWebApp() {
		args = append(args, "--disable-features=DefaultWebAppInstallation")
	}

	if cfg.VKEnabled() {
		args = append(args, "--enable-virtual-keyboard")
	}

	if cfg.ForceLaunchBrowser() {
		args = append(args, "--force-launch-browser")
	}

	// Enable verbose logging on some enrollment related files.
	if cfg.EnableLoginVerboseLogs() {
		args = append(args,
			"--vmodule="+strings.Join([]string{
				"*auto_enrollment_check_screen*=1",
				"*gaia_screen_handler*=1",
				"*oobe_test_api_handler*=1",
				"*enrollment_screen*=1",
				"*login_display_host_common*=1",
				"*wizard_controller*=1",
				"*auto_enrollment_controller*=1"}, ","))
	}

	if cfg.EnrollMode() != config.GAIAZTEEnroll {
		if cfg.LoginMode() != config.GAIALogin && cfg.EnrollMode() != config.GAIAEnroll && cfg.EnrollMode() != config.SAMLTestIdPEnroll {
			args = append(args, "--disable-gaia-services")
		}
	}

	if cfg.SkipAutoEnrollmentCheck() {
		args = append(args, "--enterprise-enable-forced-re-enrollment=never", "--enterprise-enable-initial-enrollment=never")
	}

	if cfg.ForceManualEnrollment() {
		args = append(args, "--enterprise-force-manual-enrollment")
	}

	// Enable verbose logging on gaia_auth_fetcher to help debug some login failures. See crbug.com/1166530
	if cfg.LoginMode() == config.GAIALogin {
		args = append(args, "--vmodule=gaia_auth_fetcher=1")
		if cfg.UseSandboxGaia() {
			args = append(args, "--gaia-url=https://accounts.sandbox.google.com")
		}
	}

	if cfg.SkipForceOnlineSignInForTesting() {
		args = append(args, "--skip-force-online-signin-for-testing")
	}

	args = append(args, extArgs...)

	if !cfg.EnableHIDScreenOnOOBE() {
		args = append(args, "--disable-hid-detection-on-oobe")
	}
	if cfg.PolicyEnabled() {
		args = append(args, "--profile-requires-policy=true")
	} else {
		args = append(args, "--profile-requires-policy=false")
	}
	if cfg.RealtimeReportingAddr() != "" {
		args = append(args, "--realtime-reporting-url="+cfg.RealtimeReportingAddr())
	}
	if cfg.EncryptedReportingAddr() != "" {
		args = append(args, "--encrypted-reporting-url="+cfg.EncryptedReportingAddr())
	}
	if cfg.DMSAddr() != "" {
		args = append(args, "--device-management-url="+cfg.DMSAddr())

		// crbug.com/1225937
		// When using a fake DMServer, the tokens provided to the device are not
		// valid for reporting and trigger errors on the reporting server.
		if cfg.RealtimeReportingAddr() == "" {
			args = append(args, "--realtime-reporting-url=http://invalid.domain.name:54321/")
		}
		if cfg.EncryptedReportingAddr() == "" {
			args = append(args, "--encrypted-reporting-url=http://invalid.domain.name:54321/")
		}
	}
	if cfg.DisablePolicyKeyVerification() {
		args = append(args, "--disable-policy-key-verification")
	}
	switch cfg.ARCMode() {
	case config.ARCDisabled:
		// Make sure ARC is never enabled.
		args = append(args, "--arc-availability=none")
	case config.ARCEnabled:
		args = append(args,
			// Disable ARC opt-in verification to test ARC with mock GAIA accounts.
			"--disable-arc-opt-in-verification",
			// Always start ARC to avoid unnecessarily stopping mini containers.
			"--arc-start-mode=always-start-with-no-play-store")
	case config.ARCSupported:
		// Allow ARC being enabled on the device to test ARC with real gaia accounts.
		args = append(args, "--arc-availability=officially-supported")
	}
	if cfg.ARCMode() == config.ARCEnabled || cfg.ARCMode() == config.ARCSupported {
		args = append(args,
			// Do not sync the locale with ARC.
			"--arc-disable-locale-sync",
			// Do not update Play Store automatically.
			"--arc-play-store-auto-update=off",
			// Make 1 Android pixel always match 1 Chrome devicePixel.
			"--force-remote-shell-scale=")
		if cfg.UnRestrictARCCPU() {
			args = append(args,
				// Disable CPU restrictions to let tests run faster
				"--disable-arc-cpu-restriction")
		}
	}

	if cfg.ARCMode() == config.ARCEnabled && cfg.ARCUseHugePages() == true {
		args = append(args,
			// Enable huge pages for guest memory
			"--arcvm-use-hugepages")
	}

	enabledFeatures := cfg.EnableFeatures()
	disabledFeatures := cfg.DisableFeatures()

	// Disable downloading of the optimization guide model unless the test has
	// explicitly enabled it. This can take a long time to download and represents
	// a browser feature that is not tested via tast tests. b/297948089
	if !contains(enabledFeatures, "OptimizationGuideModelDownloading") {
		disabledFeatures = append(disabledFeatures, "OptimizationGuideModelDownloading")
	}

	// Force QsRevamp on unless the test has explicitly disabled it. We force
	// the new quick settings UI because many tests have been updated to rely on
	// the new UI to enable and disable features. In general, the tests aren't
	// actually testing the UI. This way we can port the few remaining tests
	// one-by-one, without worrying about the feature flag state in chrome.
	// TODO(b/252870625): Remove this once all tests have been ported to work with QsRevamp.
	if !contains(disabledFeatures, "QsRevamp") {
		enabledFeatures = append(enabledFeatures, "QsRevamp")
	}
	if len(enabledFeatures) != 0 {
		args = append(args, "--enable-features="+strings.Join(enabledFeatures, ","))
	}
	if len(disabledFeatures) != 0 {
		args = append(args, "--disable-features="+strings.Join(disabledFeatures, ","))
	}

	stackProfilerArg := "--disable-stack-profiler"
	if cfg.EnableStackSampledMetrics() {
		// "browser-test" forces the stack profiler into a testing mode, where it
		// will always run, will in run in all renderers, and will sample far more
		// often than normal (once a second). See IsBrowserTestModeEnabled() in
		// chrome/common/profiler/thread_profiler_configuration.cc. This is normally
		// used for Chrome's browser tests, but we want the same behavior for
		// ChromeOS's integration tests.
		stackProfilerArg = "--start-stack-profiler=browser-test"
	}
	args = append(args, stackProfilerArg)

	var fieldTrialConfigValue = cfg.FieldTrialConfig()
	if fieldTrialConfigValue == "" {
		fieldTrialConfigValue = fieldTrialConfig.Value()
	}
	if fieldTrialConfigValue == "enable" {
		args = append(args, "--enable-field-trial-config")
	} else if fieldTrialConfigValue == "disable" {
		args = append(args, "--disable-field-trial-config")
	} else if fieldTrialConfigValue != "default" {
		return errors.Errorf("unexpected value for `%v`: %v", fieldTrialConfig.Name(), fieldTrialConfigValue)
	}

	// Lacros features and additional args used to launch lacros-chrome should be delimited by
	// '####' and passed in from ash-chrome as a single argument with --lacros-chrome-additional-args.
	// See browser_manager.cc in Chrome source.
	// Example:
	//   --lacros-chrome-additional-args=--enable-features=Feature1,Feature2####--disable-features=Feature3####--foo=bar
	// will result in multiple arguments passed to lacros-chrome:
	//   --enable-features=Feature1,Feature2
	//   --disable-features=Feature3
	//   --foo=bar
	var largs []string
	if fs := cfg.LacrosEnableFeatures(); len(fs) != 0 {
		largs = append(largs, "--enable-features="+strings.Join(fs, ","))
	}
	if fs := cfg.LacrosDisableFeatures(); len(fs) != 0 {
		largs = append(largs, "--disable-features="+strings.Join(fs, ","))
	}
	if as := cfg.LacrosExtraArgs(); len(as) != 0 {
		largs = append(largs, as...)
	}
	if len(lacrosExtArgs) != 0 {
		largs = append(largs, lacrosExtArgs...)
	}
	largs = append(largs, stackProfilerArg)
	args = append(args, "--lacros-chrome-additional-args="+strings.Join(largs, "####"))

	if cfg.EnablePersonalizationHub() {
		args = append(args, "--enable-features=PersonalizationHub")
	} else {
		args = append(args, "--disable-features=PersonalizationHub")
	}

	args = append(args, cfg.ExtraArgs()...)
	var envVars []string
	if cfg.BreakpadTestMode() {
		envVars = append(envVars,
			"CHROME_HEADLESS=",
			"BREAKPAD_DUMP_LOCATION=/home/chronos/crash") // Write crash dumps outside cryptohome.
	}

	ctx, st = timing.Start(ctx, "enable_chrome_testing")
	defer st.End()

	_, err = sm.EnableChromeTestingAndWait(ctx, true, args, envVars)
	return err
}

// restartSession stops the "ui" job, clears policy files and the user's cryptohome if requested,
// and restarts the job.
func restartSession(ctx context.Context, cfg *config.Config) error {
	ctx, st := timing.Start(ctx, "restart_ui")
	defer st.End()

	ctx, cancel := context.WithTimeout(ctx, upstart.UIRestartTimeout)
	defer cancel()

	testing.ContextLog(ctx, "Stopping ui job")
	if err := upstart.StopJob(ctx, "ui"); err != nil {
		return err
	}

	// Move crash dumps out of /home/chronos so they don't get lost when deleting stuff in the next step.
	if err := moveUserCrashDumps(); err != nil {
		return err
	}

	if err := clearUserData(ctx, cfg); err != nil {
		return err
	}

	fixLogSymlink(ctx)

	testing.ContextLog(ctx, "Starting ui job")
	return upstart.EnsureJobRunning(ctx, "ui")
}

// moveUserCrashDumps moves the contents of the user crash directory to the
// system crash directory.
func moveUserCrashDumps() error {
	// Normally user crashes are written to /home/user/(hash)/crash as they
	// contain PII, but for test images they are written to /home/chronos/crash.
	// https://crrev.com/c/1986701
	const (
		userCrashDir   = "/home/chronos/crash"
		systemCrashDir = "/var/spool/crash"
		crashGroup     = "crash-access"
	)

	g, err := user.LookupGroup(crashGroup)
	if err != nil {
		return err
	}
	gid, err := strconv.ParseInt(g.Gid, 10, 32)
	if err != nil {
		return errors.Wrapf(err, "failed to parse gid %q", g.Gid)
	}

	if err := os.MkdirAll(systemCrashDir, 02770); err != nil {
		return err
	}

	if err := os.Chown(systemCrashDir, 0, int(gid)); err != nil {
		return err
	}

	fis, err := ioutil.ReadDir(userCrashDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}

	for _, fi := range fis {
		if !fi.Mode().IsRegular() {
			continue
		}

		// As they are in different partitions, os.Rename() doesn't work.
		src := filepath.Join(userCrashDir, fi.Name())
		dst := filepath.Join(systemCrashDir, fi.Name())
		if err := fsutil.MoveFile(src, dst); err != nil {
			return err
		}

		if err := os.Chown(dst, 0, int(gid)); err != nil {
			return err
		}
	}

	return nil
}

func clearUserData(ctx context.Context, cfg *config.Config) error {
	if cfg.KeepState() {
		return nil
	}

	testing.ContextLog(ctx, "Clearing user data")
	ctx, st := timing.Start(ctx, "clear_user_data")
	defer st.End()

	const chronosDir = "/home/chronos"
	const shadowDir = "/home/.shadow"
	// To support login feature, biod also keeps per-user data in this directory. They're
	// removed by cryptohome with a dbus call to biod upon user removal, but in tast where
	// user data isn't cleared using standard cryptohome APIs, we need to delete those files
	// manually.
	const biodDir = "/var/lib/biod"

	if !cfg.KeepOwnership() {
		// This always fails because /home/chronos is a mount point, but all files
		// under the directory should be removed.
		os.RemoveAll(chronosDir)
		fis, err := ioutil.ReadDir(chronosDir)
		if err != nil {
			return err
		}
		// Retry cleanup of remaining files. Don't fail if removal reports an error.
		for _, left := range fis {
			if err := os.RemoveAll(filepath.Join(chronosDir, left.Name())); err != nil {
				testing.ContextLogf(ctx, "Failed to clear %s; failed to remove %q: %v", chronosDir, left.Name(), err)
			} else {
				testing.ContextLogf(ctx, "Failed to clear %s; %q needed repeated removal", chronosDir, left.Name())
			}
		}
	}

	// Delete files from shadow directory.
	shadowFiles, err := ioutil.ReadDir(shadowDir)
	if err != nil {
		return errors.Wrapf(err, "failed to read directory %q", shadowDir)
	}
	for _, file := range shadowFiles {
		// Should not remove folders other than the user profiles.
		if !file.IsDir() || !obfuscatedUsernameRegexp.MatchString(file.Name()) {
			continue
		}
		// Only look for chronos file with names matching u-*.
		chronosName := filepath.Join(chronosDir, "u-"+file.Name())
		shadowName := filepath.Join(shadowDir, file.Name())
		// Remove the shadow directory if it does not have a corresponding chronos directory.
		if _, err := os.Stat(chronosName); err != nil && os.IsNotExist(err) {
			if err := os.RemoveAll(shadowName); err != nil {
				testing.ContextLogf(ctx, "Failed to remove %q: %v", shadowName, err)
			}
			// Remove any LVM partitions that exist, now that shadow dir has been cleaned.
			if err := testexec.CommandContext(ctx, "bash", "-c", "vgchange -ay && lvremove -ff /dev/*/cryptohome-"+file.Name()[0:8]+"-*").Run(testexec.DumpLogOnError); err != nil {
				// Ignore errors on failure, it is possible that the device doesn't support LVM or doesn't have any dm-crypt user crpytohomes.
				testing.ContextLog(ctx, "Failed to remove user logical volumes (this might be expected if the device doesn't support LVM): ", err)
			}
		}
	}

	// Delete user dirs from biod directory.
	biodFiles, err := os.ReadDir(biodDir)
	if os.IsNotExist(err) {
		// Biod directory doesn't exist. Don't need further actions.
	} else if err != nil {
		return errors.Wrapf(err, "failed to read directory %q", biodDir)
	} else {
		for _, file := range biodFiles {
			// Should not remove folders other than the user profiles.
			if !file.IsDir() || !obfuscatedUsernameRegexp.MatchString(file.Name()) {
				continue
			}
			// Only look for chronos file with names matching u-*.
			chronosName := filepath.Join(chronosDir, "u-"+file.Name())
			biodName := filepath.Join(biodDir, file.Name())
			// Remove the biod directory if it does not have a corresponding chronos directory.
			if _, err := os.Stat(chronosName); err != nil && os.IsNotExist(err) {
				if err := os.RemoveAll(biodName); err != nil {
					testing.ContextLogf(ctx, "Failed to remove %q: %v", biodName, err)
				}
			}
		}
	}

	if !cfg.KeepOwnership() {
		// Delete policy files to clear the device's ownership state since the account
		// whose cryptohome we'll delete may be the owner: http://crbug.com/897278
		if err := session.ClearDeviceOwnership(ctx); err != nil {
			return err
		}
	}
	return nil
}

// fixLogSymlink fixes the symlink at /var/log/chrome/chrome.
// This is a workaround for a bug in Chrome that causes the symlink to
// occasionally become a regular file and Chrome logs to stop rotating
// (b/187795771).
// This function must be called while the ui job is stopped.
func fixLogSymlink(ctx context.Context) {
	const (
		logDir          = "/var/log/chrome"
		symlinkName     = "chrome"
		timestampLayout = "20060102-150405"
	)

	if err := func() error {
		// Check if /var/log/chrome/chrome is a symlink.
		st, err := os.Lstat(filepath.Join(logDir, symlinkName))
		if os.IsNotExist(err) {
			return nil
		}
		if err != nil {
			return err
		}
		if st.Mode()&os.ModeType == os.ModeSymlink {
			return nil
		}

		// If the file is not a symlink, rename it so that a new symlink is created
		// later when starting the ui job.
		newName := fmt.Sprintf("%s_%s_b187795771", symlinkName, time.Now().UTC().Format(timestampLayout))
		testing.ContextLogf(ctx, "Warning: %s is not a symlink; renaming it to %s to recover log rotation (b/187795771)", filepath.Join(logDir, symlinkName), newName)
		if err := os.Rename(filepath.Join(logDir, symlinkName), filepath.Join(logDir, newName)); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		// Don't make the whole process fail even if we could not fix
		// the symlink.
		testing.ContextLogf(ctx, "Warning: failed to fix Chrome log symlink: %v; continuing anyway", err)
	}
}

// contains returns whether the slice "list" contains "s".
// This can be replaced with slices.Contains() once Go releases the slices
// package: https://pkg.go.dev/golang.org/x/exp/slices#Contains
func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}
