// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by "stringer -type=fwInfoType"; DO NOT EDIT.

package fingerprint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fwInfoTypeSha256sum-0]
	_ = x[fwInfoTypeRoVersion-1]
	_ = x[fwInfoTypeRwVersion-2]
	_ = x[fwInfoTypeKeyID-3]
}

const _fwInfoType_name = "fwInfoTypeSha256sumfwInfoTypeRoVersionfwInfoTypeRwVersionfwInfoTypeKeyID"

var _fwInfoType_index = [...]uint8{0, 19, 38, 57, 72}

func (i fwInfoType) String() string {
	if i < 0 || i >= fwInfoType(len(_fwInfoType_index)-1) {
		return "fwInfoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fwInfoType_name[_fwInfoType_index[i]:_fwInfoType_index[i+1]]
}
