// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.ui;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/ui";

// ChromeUIService performs the UI operations.
service ChromeUIService {
    // EnsureLoginScreen restarts ui job to ensure starting from logout state, i.e. at login.
    rpc EnsureLoginScreen (google.protobuf.Empty) returns (google.protobuf.Empty) {}

    // DumpUITree dumps the UI tree to the context directory of the test.
    rpc DumpUITree (google.protobuf.Empty) returns (google.protobuf.Empty) {}

    // DumpUITreeWithScreenshotToFile dumps the UI tree with screenshot to the file.
    rpc DumpUITreeWithScreenshotToFile (DumpUITreeWithScreenshotToFileRequest) returns (google.protobuf.Empty) {}

    // WaitForWelcomeScreen waits for welcome screen to be shown in OOBE.
    rpc WaitForWelcomeScreen (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message DumpUITreeWithScreenshotToFileRequest {
    // file_prefix specifies the name prefix of file UI dump and screenshot.
    // For instance, if file_prefix is specified as "ui_dump", the UI dump file and screenshot file will be saved as "ui_dump.txt" and "ui_dump.png".
    string file_prefix = 1;
}
