# Copyright 2020 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("all") {
  deps = [
    "ArcAccessibilityTest:ArcAccessibilityTest",
    "ArcAnimationPerformanceTest:ArcAnimationPerformanceTest",
    "ArcAppManagementTest:ArcAppManagementTest",
    "ArcAppValidityTest:ArcAppValidityTest",
    "ArcAudioTest:ARCAudioTest",
    "ArcBackupTest:ArcBackupTest",
    "ArcBlackFlashTest:ArcBlackFlashTest",
    "ArcCameraIntentTest:ArcCameraIntentTest",
    "ArcChromeIntentPickerTest:ArcChromeIntentPickerTest",
    "ArcChromeSharesheetTest:ArcChromeSharesheetTest",
    "ArcChromeWebApkTest:ArcChromeWebApkTest",
    "ArcClipboardTest:ArcClipboardTest",
    "ArcConfigChangesTest:ArcConfigChangesTest",
    "ArcConnectivityTest:ArcConnectivityTest",
    "ArcDockedMagnifierTest:ArcDockedMagnifierTest",
    "ArcDownloadManagerTest:ArcDownloadManagerTest",
    "ArcDragSourceTest:ArcDragSourceTest",
    "ArcDragTargetTest:ArcDragTargetTest",
    "ArcExternalStorageTest:ArcExternalStorageTest",
    "ArcFileEditorTest:ArcFileEditorTest",
    "ArcGamepadTest:ArcGamepadTest",
    "ArcImagePasteTest:ArcImagePasteTest",
    "ArcImeBlockingTest:ArcImeBlockingTest",
    "ArcInputCompatTest:ArcInputCompatDisabledTest",
    "ArcInputCompatTest:ArcInputCompatGameTest",
    "ArcInputCompatTest:ArcInputCompatMTest",
    "ArcInputLatencyTest:ArcInputLatencyTest",
    "ArcInputMethodTest:ArcInputMethodTest",
    "ArcInputOverlayTest:ArcInputOverlayTest",
    "ArcInstallAppWithAppListSortedTest:ArcInstallAppWithAppListSortedTest",
    "ArcKeyCharacterMapTest:ArcKeyCharacterMapTest",
    "ArcKeyboardTest:ArcKeyboardTest",
    "ArcLaunchIntentTest:ArcLaunchIntentTest",
    "ArcLifecycleTest:ArcLifecycleTest",
    "ArcLinkCapturingTest:ArcLinkCapturingTest",
    "ArcLongPressTest:ArcLongPressTest",
    "ArcManyFilesTest:ArcManyFilesTest",
    "ArcMediaScanPerfTest:ArcMediaScanPerfTest",
    "ArcMidiClientTest:ArcMidiClientTest",
    "ArcMotionInputTest:ArcMotionInputTest",
    "ArcMouseKeyEventTest:ArcMouseKeyEventTest",
    "ArcMultiDisplayTest:ArcMultiDisplayTest",
    "ArcMulticastForwarderTest:ArcMulticastForwarderTest",
    "ArcNotificationTest:ArcNotificationTest",
    "ArcPasspointTest:ArcPasspointTest_P",
    "ArcPasspointTest:ArcPasspointTest_R",
    "ArcPerAppDensityTest:ArcPerAppDensityTest",
    "ArcPipTest:ArcPipTest",
    "ArcPipVideoTest:ArcPipVideoTest",
    "ArcPreImeKeyEventTest:ArcPreImeKeyEventTest",
    "ArcPrintTest:ArcPrintTest",
    "ArcQosMonitorTest:ArcQosMonitorTest",
    "ArcQuarterSizedWindowZoomingTest:ArcQuarterSizedWindowZoomingTest",
    "ArcQuotaProjectIdTest:ArcQuotaProjectIdTest",
    "ArcRandomUIElementsApp:ArcRandomUIElementsApp",
    "ArcResizeLockTest:ArcResizeLockTest",
    "ArcSensorLatencyTest:ArcSensorLatencyTest",
    "ArcShelfIconTest:ArcShelfIconTest",
    "ArcSoftInputModeTest:ArcSoftInputModeTest",
    "ArcStandardizedInputTest:ArcStandardizedInputTest",
    "ArcSurfaceInsetsTest:ArcSurfaceInsetsTest",
    "ArcSwapTest:ArcSwapTest",
    "ArcTtsTest:ArcTtsTest",
    "ArcVpnTest:ArcVpnTest",
    "ArcWMTestApp:ArcWMTestApp_23",
    "ArcWMTestApp:ArcWMTestApp_24",
    "ArcWMTestApp:ArcWMTestApp_24_InMaximizedList",
    "ArcWMTestApp:ArcWMTestApp_24_InPhoneSizeList",
    "ArcWMTestApp:ArcWMTestApp_24_InTabletSizeList",
    "AssistantAndroidAppTest:AssistantAndroidAppTest",
  ]
}
