# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[mypy]
check_untyped_defs = True
warn_unused_configs = True
no_implicit_optional = True
warn_unused_ignores = True

[mypy-click]
ignore_missing_imports = True
