// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.power;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/power";

service DeviceSetupService {
    // Setup device for power test.
    rpc Setup(DeviceSetupRequest) returns (google.protobuf.Empty) {}

    // Cleanup resets device to its original state.
    rpc Cleanup(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message DeviceSetupRequest {
    // Describes this device setup and it is used for logging purposes.
    optional string setup_name = 1;
    UIMode ui = 2;
    ScreenMode screen_brightness = 3;
    KeyboardMode keyboard_brightness= 4;
    WifiMode wifi = 5;
    BluetoothMode bluetooth = 6;
}

enum UIMode {
    DO_NOT_CHANGE_UI = 0;
    DISABLE_UI = 1;
}

enum ScreenMode {
    DEFAULT_SCREEN_BRIGHTNESS = 0;
    DO_NOT_CHANGE_SCREEN_BRIGHTNESS = 1;
    ZERO_SCREEN_BRIGHTNESS = 2;
}

enum KeyboardMode {
    DEFAULT_KEYBOARD_BRIGHTNESS = 0;
    DO_NOT_CHANGE_KEYBOARD_BRIGHTNESS = 1;
    ZERO_KEYBOARD_BRIGHTNESS = 2;
}

enum WifiMode {
    DO_NOT_CHANGE_WIFI = 0;
    DISABLE_WIFI = 1;
}

enum BluetoothMode {
    DISABLE_BLUETOOTH = 0;
    DO_NOT_CHANGE_BLUETOOTH = 1;
}