// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.power;

import "google/protobuf/empty.proto";

import "values.proto";
import "one_time_metrics.proto";
import "device_info.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/power";

service RecorderService {
    rpc Create(RecorderRequest) returns (google.protobuf.Empty) {}
    rpc Start(google.protobuf.Empty) returns (google.protobuf.Empty) {}
    rpc Stop(google.protobuf.Empty) returns (RecorderResult) {}
    rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message RecorderRequest {
    string test_name = 1;
    int64 interval_sec = 2;
}

message RecorderResult {
    tast.common.perf.perfpb.Values perf_metrics = 1;
    tast.common.power.powerpb.OneTimeMetrics one_time_metrics = 2;
    tast.common.power.powerpb.DeviceInfo device_info = 3;
}