// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.3
// source: suspend_perf_service.proto

package power

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SuspendRequest is for passing the seconds of suspend duration to Suspend().
type SuspendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds int32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *SuspendRequest) Reset() {
	*x = SuspendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suspend_perf_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendRequest) ProtoMessage() {}

func (x *SuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_suspend_perf_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendRequest.ProtoReflect.Descriptor instead.
func (*SuspendRequest) Descriptor() ([]byte, []int) {
	return file_suspend_perf_service_proto_rawDescGZIP(), []int{0}
}

func (x *SuspendRequest) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

// SuspendResponse is for notifying result of Suspend() if it fails to
// execute command or command failure with its output.
// Since Suspend() will disconnect the network, if it works successfully,
// the caller will receive a network error. But if it fails, Suspend() also
// need to notice it failed to suspend.
type SuspendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failed bool   `protobuf:"varint,1,opt,name=failed,proto3" json:"failed,omitempty"`
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *SuspendResponse) Reset() {
	*x = SuspendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suspend_perf_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendResponse) ProtoMessage() {}

func (x *SuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_suspend_perf_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendResponse.ProtoReflect.Descriptor instead.
func (*SuspendResponse) Descriptor() ([]byte, []int) {
	return file_suspend_perf_service_proto_rawDescGZIP(), []int{1}
}

func (x *SuspendResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *SuspendResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_suspend_perf_service_proto protoreflect.FileDescriptor

var file_suspend_perf_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x66, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x61,
	0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0xa7, 0x01, 0x0a, 0x12, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4e, 0x0a, 0x07, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x74, 0x61,
	0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x53,
	0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x0d, 0x54, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x61, 0x73, 0x74, 0x2d, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x63, 0x72, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_suspend_perf_service_proto_rawDescOnce sync.Once
	file_suspend_perf_service_proto_rawDescData = file_suspend_perf_service_proto_rawDesc
)

func file_suspend_perf_service_proto_rawDescGZIP() []byte {
	file_suspend_perf_service_proto_rawDescOnce.Do(func() {
		file_suspend_perf_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_suspend_perf_service_proto_rawDescData)
	})
	return file_suspend_perf_service_proto_rawDescData
}

var file_suspend_perf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_suspend_perf_service_proto_goTypes = []interface{}{
	(*SuspendRequest)(nil),  // 0: tast.cros.power.SuspendRequest
	(*SuspendResponse)(nil), // 1: tast.cros.power.SuspendResponse
	(*emptypb.Empty)(nil),   // 2: google.protobuf.Empty
}
var file_suspend_perf_service_proto_depIdxs = []int32{
	0, // 0: tast.cros.power.SuspendPerfService.Suspend:input_type -> tast.cros.power.SuspendRequest
	2, // 1: tast.cros.power.SuspendPerfService.TurnOnDisplay:input_type -> google.protobuf.Empty
	1, // 2: tast.cros.power.SuspendPerfService.Suspend:output_type -> tast.cros.power.SuspendResponse
	2, // 3: tast.cros.power.SuspendPerfService.TurnOnDisplay:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_suspend_perf_service_proto_init() }
func file_suspend_perf_service_proto_init() {
	if File_suspend_perf_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_suspend_perf_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suspend_perf_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_suspend_perf_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_suspend_perf_service_proto_goTypes,
		DependencyIndexes: file_suspend_perf_service_proto_depIdxs,
		MessageInfos:      file_suspend_perf_service_proto_msgTypes,
	}.Build()
	File_suspend_perf_service_proto = out.File
	file_suspend_perf_service_proto_rawDesc = nil
	file_suspend_perf_service_proto_goTypes = nil
	file_suspend_perf_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SuspendPerfServiceClient is the client API for SuspendPerfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuspendPerfServiceClient interface {
	Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error)
	TurnOnDisplay(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type suspendPerfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuspendPerfServiceClient(cc grpc.ClientConnInterface) SuspendPerfServiceClient {
	return &suspendPerfServiceClient{cc}
}

func (c *suspendPerfServiceClient) Suspend(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error) {
	out := new(SuspendResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.power.SuspendPerfService/Suspend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suspendPerfServiceClient) TurnOnDisplay(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.power.SuspendPerfService/TurnOnDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuspendPerfServiceServer is the server API for SuspendPerfService service.
type SuspendPerfServiceServer interface {
	Suspend(context.Context, *SuspendRequest) (*SuspendResponse, error)
	TurnOnDisplay(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedSuspendPerfServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSuspendPerfServiceServer struct {
}

func (*UnimplementedSuspendPerfServiceServer) Suspend(context.Context, *SuspendRequest) (*SuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suspend not implemented")
}
func (*UnimplementedSuspendPerfServiceServer) TurnOnDisplay(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurnOnDisplay not implemented")
}

func RegisterSuspendPerfServiceServer(s *grpc.Server, srv SuspendPerfServiceServer) {
	s.RegisterService(&_SuspendPerfService_serviceDesc, srv)
}

func _SuspendPerfService_Suspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuspendPerfServiceServer).Suspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.power.SuspendPerfService/Suspend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuspendPerfServiceServer).Suspend(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuspendPerfService_TurnOnDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuspendPerfServiceServer).TurnOnDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.power.SuspendPerfService/TurnOnDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuspendPerfServiceServer).TurnOnDisplay(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuspendPerfService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.power.SuspendPerfService",
	HandlerType: (*SuspendPerfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Suspend",
			Handler:    _SuspendPerfService_Suspend_Handler,
		},
		{
			MethodName: "TurnOnDisplay",
			Handler:    _SuspendPerfService_TurnOnDisplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "suspend_perf_service.proto",
}
