// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/local/apps"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/ash"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/filesapp"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/crostini/ui/sharedfolders"
	"go.chromium.org/tast-tests/cros/local/cryptohome"
	guestosapps "go.chromium.org/tast-tests/cros/local/guestos/apps"
	"go.chromium.org/tast-tests/cros/local/input"
	"go.chromium.org/tast-tests/cros/local/terminalapp"
	"go.chromium.org/tast-tests/cros/local/uidetection"
	"go.chromium.org/tast-tests/cros/local/vm"

	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

var (
	tmpFilename              = "testfile.txt"
	tmpFileCrostiniMountPath = filepath.Join(sharedfolders.MountPathDownloads, tmpFilename)
	tmpFileContents          = "This is a text string in a text file in the Downloads folder."
	viewContextMenuItem      = "View"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppGeditFilesharing,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Test gedit file sharing in Terminal window",
		Contacts: []string{
			"clumptini+oncall@google.com",
			"ashpakov@google.com", // until Oct 2022
		},
		Attr:         []string{"group:mainline", "group:crostini_app_cq"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}

func AppGeditFilesharing(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	cr := s.FixtValue().(crostini.FixtureData).Chrome
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	downloadsPath, err := cryptohome.DownloadsPath(ctx, cr.NormalizedUser())
	if err != nil {
		s.Fatal("Failed to get users Download path: ", err)
	}
	tmpFileCrosDownloadsPath := filepath.Join(downloadsPath, tmpFilename)

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	geditContextMenuItem, err := guestosapps.GeditAppName(ctx, cont)
	if err != nil {
		s.Fatal("Failed to get gedit app name: ", err)
	}

	// Create a temp text file in the /Downloads folder to use in this test.
	if err := ioutil.WriteFile(tmpFileCrosDownloadsPath, []byte(tmpFileContents), 0644); err != nil {
		s.Fatal("Failed to create text file in Downloads folder: ", err)
	}
	defer func() {
		if err := os.Remove(tmpFileCrosDownloadsPath); err != nil {
			s.Logf("Cleanup: failed to remove file %s on cleanup: %v", tmpFileCrosDownloadsPath, err)
		}
	}()

	filesApp, err := filesapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Files app: ", err)
	}
	defer filesApp.Close(cleanupCtx)

	geditWindow := nodewith.NameContaining(tmpFilename).Role(role.Window).First()
	filesAppShelfButton := nodewith.Name(apps.Files.Name).ClassName("ash/ShelfAppButton")
	ui := uiauto.New(tconn)
	ud := uidetection.NewDefault(tconn)

	// Open tmp file with Gedit.
	err = uiauto.Combine("open tmp file with Gedit",
		filesApp.OpenDownloads(),
		filesApp.ClickContextMenuItemRegex(tmpFilename, filesapp.OpenWith, geditContextMenuItem),
		ui.WaitUntilExists(geditWindow),
		ud.WaitUntilExists(uidetection.TextBlock(strings.Split("text string", " ")).WithinA11yNode(geditWindow)),
	)(ctx)
	if err != nil {
		s.Fatal("Failed to open tmp file in the Downloads folder: ", err)
	}

	// Launch terminal so we can run commands in the container.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		if err := closeGedit(ctx, keyboard, ui, geditWindow); err != nil {
			s.Log("Failed to close Gedit after failing to launch terminal: ", err)
		}
		s.Fatal("Failed to open Crostini Terminal: ", err)
	}
	defer terminalApp.Exit(keyboard)(cleanupCtx)

	err = checkFilesharingBeforeRestart(
		ctx, cont, tconn, ui, ud, filesApp, keyboard, geditWindow, filesAppShelfButton)
	if err != nil {
		s.Fatal("Failed test cases before restart of Crostini: ", err)
	}

	// Restart Crostini. This will start linux and the terminal and then close the terminal, but not Linux.
	s.Log("Restarting Crostini for the rest of this test")
	if err := terminalApp.RestartCrostini(keyboard, cont, cr.NormalizedUser())(ctx); err != nil {
		s.Fatal("Failed to restart Crostini: ", err)
	}

	err = checkFilesharingWorksAfterRestart(
		ctx, cont, tconn, filesApp, keyboard, ui, ud, geditWindow, geditContextMenuItem)
	if err != nil {
		s.Fatal("Failed tests to check whether file sharing  works correctly after restart of Crostini: ", err)
	}
}

func checkFilesharingBeforeRestart(
	ctx context.Context,
	cont *vm.Container,
	tconn *chrome.TestConn,
	ui *uiauto.Context,
	ud *uidetection.Context,
	filesApp *filesapp.FilesApp,
	keyboard *input.KeyboardEventWriter,
	geditWindow,
	filesAppShelfButton *nodewith.Finder) error {

	// Check that file is mounted in the container.
	if err := crostini.VerifyFileInContainer(ctx, cont, tmpFileCrostiniMountPath); err != nil {
		return errors.Wrap(err, "temp file missing from crostini container")
	}

	if err := closeGedit(ctx, keyboard, ui, geditWindow); err != nil {
		return errors.Wrap(err, "failed to close Gedit")
	}

	// Check file remains mounted in container.
	if err := crostini.VerifyFileInContainer(ctx, cont, tmpFileCrostiniMountPath); err != nil {
		return errors.Wrap(err, "failed to find tmp file in crostini container after linux app is closed and before VM rebooted")
	}

	// Bring Downloads folder to foreground, open the file with Chrome (a non-linux app), validate file contents.
	if _, err := ash.BringWindowToForeground(ctx, tconn, "Files - Downloads"); err != nil {
		return errors.Wrap(err, "failed to bring the Filesapp Download window to foreground")
	}

	err := uiauto.Combine("validate contents of text file opened with Chrome (a non-linux app)",
		filesApp.ClickContextMenuItem(tmpFilename, filesapp.OpenWith, viewContextMenuItem),
		ud.WaitUntilExists(uidetection.TextBlock(strings.Split("text string", " "))),
	)(ctx)
	if err != nil {
		return errors.Wrap(err, "failed to right click on text file in Downloads folder and open with default Text app")
	}

	return nil
}

func checkFilesharingWorksAfterRestart(
	ctx context.Context,
	cont *vm.Container,
	tconn *chrome.TestConn,
	filesApp *filesapp.FilesApp,
	keyboard *input.KeyboardEventWriter,
	ui *uiauto.Context,
	ud *uidetection.Context,
	geditWindow *nodewith.Finder,
	geditContextMenuItem string) error {

	// Check that file is no longer mounted in the container after Linux is restarted.
	if err := crostini.VerifyFileNotInContainer(ctx, cont, tmpFileCrostiniMountPath); err != nil {
		return errors.Wrap(err, "error verifying that file is no longer in container")
	}

	// Find and close the Chrome (a non-linux app) window.
	w, err := ash.FindWindow(ctx, tconn, func(w *ash.Window) bool { return w.Title == fmt.Sprintf("Chrome - %s", tmpFilename) })
	if err != nil {
		return errors.Wrap(err, "failed to find Text App Window")
	}
	if err = w.CloseWindow(ctx, tconn); err != nil {
		return errors.Wrap(err, "failed to close Text App Window")
	}

	// Re-open file with Gedit and validate contents.
	err = uiauto.Combine("open downloads folder, open text file with Gedit, validate contents",
		filesApp.OpenDownloads(),
		filesApp.ClickContextMenuItemRegex(tmpFilename, filesapp.OpenWith, geditContextMenuItem),
		ui.WithTimeout(2*time.Minute).WaitUntilExists(geditWindow),
		ud.WaitUntilExists(uidetection.TextBlock(strings.Split("text string", " ")).WithinA11yNode(geditWindow)),
	)(ctx)
	if err != nil {
		return errors.Wrap(err, "failed to re-open Gedit to check file contents")
	}

	if err = closeGedit(ctx, keyboard, ui, geditWindow); err != nil {
		return errors.Wrap(err, "failed to close Gedit after Crostini restart")
	}
	return nil
}

func closeGedit(ctx context.Context, keyboard *input.KeyboardEventWriter, ui *uiauto.Context, geditWindow *nodewith.Finder) error {
	return uiauto.Combine("close out of Gedit",
		// Focus on the Gedit window.
		ui.LeftClick(geditWindow),
		// Close out of Gedit.
		keyboard.AccelAction("ctrl+W"),
		keyboard.AccelAction("ctrl+W"),
	)(ctx)
}
