// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/bundles/cros/crostini/crostiniapps"
	"go.chromium.org/tast-tests/cros/local/bundles/cros/crostini/imetestutil"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/ime"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/input"
	"go.chromium.org/tast-tests/cros/local/screenshot"
	"go.chromium.org/tast-tests/cros/local/terminalapp"
	"go.chromium.org/tast-tests/cros/local/uidetection"
	"go.chromium.org/tast-tests/cros/local/vm"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppVscodeIME,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Opens Visual Studio Code from terminal and type using an IME",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline", "informational"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_clamshell_arabic_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "arabic",
			}, {
				Name:              "bullseye_clamshell_arabic_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "arabic",
			}, {
				Name:              "bullseye_clamshell_english_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "english",
			}, {
				Name:              "bullseye_clamshell_english_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "english",
			}, {
				Name:              "bullseye_clamshell_japanese_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "japanese",
			}, {
				Name:              "bullseye_clamshell_japanese_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshellWithIME",
				Timeout:           15 * time.Minute,
				Val:               "japanese",
			},
		},
	})
}
func AppVscodeIME(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	// Open Terminal app.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Terminal app: ", err)
	}
	defer terminalApp.Exit(keyboard)(cleanupCtx)

	// Switch back to default IME
	defer imetestutil.ResetToDefaultIME(cleanupCtx, tconn)

	// Since defers are executed in a stack, this needs to be the last defer so it doesn't close the window before dumping the tree.
	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	imeName := s.Param().(string)
	imeData := imetestutil.IMETestCases[imeName]
	if err := testUseIMEInVSCode(ctx, terminalApp, keyboard, tconn, cont, imeData); err != nil {
		s.Fatal("Failed to create file with Visual Studio Code in Terminal: ", err)
	}
}

func testUseIMEInVSCode(ctx context.Context, terminalApp *terminalapp.TerminalApp, keyboard *input.KeyboardEventWriter, tconn *chrome.TestConn, cont *vm.Container, imeData imetestutil.IMETestData) error {
	ui := uiauto.New(tconn)
	uda := uidetection.NewDefault(tconn)

	if err := crostiniapps.InitialiseVSCode(ctx, cont, uda, ui, terminalApp, keyboard); err != nil {
		return err
	}

	inputMethod := imeData.InputMethod
	// Open the VSCode again, this time, it won't open the Get Started tab.
	if err := uiauto.Combine("create and compose file with VSCode",
		crostiniapps.LaunchVSCodeForFile(uda, ui, terminalApp, keyboard, crostiniapps.VSCodeTestFile),
		inputMethod.InstallAndActivate(tconn),
		inputMethod.WaitUntilActivated(tconn),
		// VSCode will read the first keypress as English input, even when the input method is set otherwise.
		// Enter two backspaces first so that the testing string is entered correctly.
		// TODO(b/274709150): Remove the following 2 lines after this bug is fixed.
		keyboard.AccelAction("Backspace"),
		keyboard.AccelAction("Backspace"),
		imeData.EnterTestStringActionPK(keyboard, ui),
	)(ctx); err != nil {
		return errors.Wrap(err, "failed to enter test string")
	}

	if imeData.InputMethod == ime.Japanese {
		if err := imetestutil.TestJapaneseCandidatesBoxInEditor(ctx, ui, uda, keyboard); err != nil {
			return err
		}
	}

	if err := uiauto.Combine("save file",
		crostiniapps.SaveFileAndCloseVSCode(ui, keyboard, crostiniapps.VSCodeTestFile))(ctx); err != nil {
		return err
	}

	// Check the content of the test file.
	if err := cont.CheckFileContent(ctx, crostiniapps.VSCodeTestFile, imeData.ExpectedText); err != nil {
		return errors.Wrap(err, "failed to verify the content of the file")
	}

	return nil
}
