// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/launcher"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/coords"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/screenshot"
	"go.chromium.org/tast-tests/cros/local/uidetection"

	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppAudacity,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Opens Audacity from launcher",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline", "group:criticalstaging"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host", "amd64"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "buster_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "buster_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "buster_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "buster_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}
func AppAudacity(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	cr := s.FixtValue().(crostini.FixtureData).Chrome
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont
	d := s.FixtValue().(crostini.FixtureData).Differ()

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "ui_tree")

	// Disable the welcome screen.
	if err := cont.WriteFile(ctx, fmt.Sprintf(".audacity-data/audacity.cfg"), "[GUI]\nShowSplashScreen=0\n"); err != nil {
		s.Fatal("Failed to write Audacity config: ", err)
	}

	if err := uiauto.Retry(3,
		launcher.SearchAndLaunchWithQuery(tconn, keyboard, "au", "Audacity"),
	)(ctx); err != nil {
		s.Fatal("Failed to launch Aduacity: ", err)
	}

	ud := uidetection.NewDefault(tconn)
	ui := uiauto.New(tconn)

	// To avoid matching against the splash screen with title "Audacity is
	// starting up...", also look for the File menu in the window.
	audacityWindow := nodewith.Name("Audacity").Role(role.Window).First()
	if err := uiauto.Combine("wait for Audacity",
		ui.WithTimeout(2*time.Minute).WaitUntilExists(audacityWindow),
		ud.WaitUntilExists(uidetection.Word("File").WithinA11yNode(audacityWindow)),
		ui.MouseClickAtLocation(0, coords.Point{X: 0, Y: 0}),
		d.DiffWindow(ctx, "audacity", screenshot.Retries(5), screenshot.RetryInterval(5*time.Second)),
	)(ctx); err != nil {
		s.Fatal("Failed to find Audacity window: ", err)
	}

	if err := uiauto.Combine("quit Audacity",
		keyboard.AccelAction("ctrl+Q"),
		ui.WaitUntilGone(audacityWindow),
	)(ctx); err != nil {
		s.Fatal("Failed to quit Audacity: ", err)
	}
}
