// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"regexp"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/launcher"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/input"
	"go.chromium.org/tast-tests/cros/local/screenshot"

	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppLibreOffice,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Opens LibreOffice Writer from launcher",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline", "group:crostini_app_cq"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}

func AppLibreOffice(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	d := s.FixtValue().(crostini.FixtureData).Differ()

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()
	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	ui := uiauto.New(tconn)

	appNames := []string{"Writer", "Calc", "Impress", "Draw"}
	nodes := []*nodewith.Finder{
		nodewith.NameRegex(regexp.MustCompile(`Tip of the Day: .*`)).Role(role.Window).HasClass("RootView").First(),
		nil,
		nodewith.NameRegex(regexp.MustCompile(`Select a Template`)).Role(role.Window).HasClass("RootView").First(),
		nil,
	}

	// Then test each application in the LibreOffice suite.
	for idx, appName := range appNames {
		s.Run(ctx, appName, func(ctx context.Context, s *testing.State) {
			if err := verifyLibreOfficeApp(ctx, ui, tconn, keyboard, d, appNames[idx], nodes[idx], s.OutDir()); err != nil {
				s.Fatalf("Failed to verify LibreOffice %s: %v", appName, err)
			}
		})
	}
}

func verifyLibreOfficeApp(ctx context.Context, ui *uiauto.Context, tconn *chrome.TestConn, keyboard *input.KeyboardEventWriter, d screenshot.Differ, appName string, extraNode *nodewith.Finder, outDir string) error {
	fullAppName := fmt.Sprintf("LibreOffice %s", appName)
	appWindow := nodewith.NameRegex(regexp.MustCompile(`.*` + fullAppName)).Role(role.Window).HasClass("RootView").First()

	var closeExtraNode, waitClose uiauto.Action
	if extraNode != nil {
		closeExtraNode = uiauto.IfSuccessThen(
			ui.WithTimeout(15*time.Second).WaitUntilExists(extraNode),
			keyboard.AccelAction("Esc"),
		)
		waitClose = ui.WithTimeout(10 * time.Second).WaitUntilGone(extraNode)
	} else {
		closeExtraNode = func(ctx context.Context) error { return nil }
		waitClose = func(ctx context.Context) error { return nil }
	}

	if err := uiauto.Retry(3,
		launcher.SearchAndLaunchWithQuery(tconn, keyboard, fullAppName, fullAppName),
	)(ctx); err != nil {
		return errors.Wrap(err, "failed to launch "+fullAppName)
	}

	if err := uiauto.Combine("verify "+fullAppName,
		ui.WithTimeout(2*time.Minute).WaitUntilExists(appWindow),
		closeExtraNode,
		waitClose,
		// In tablet mode, the on-screen keyboard warning may cause the
		// screenshot testing to fail.
		ui.WaitUntilGone(nodewith.Name("The on-screen keyboard doesn't work in Linux apps yet").First()),
		screenshot.DiffWindow(ctx, d, fullAppName, screenshot.Retries(3), screenshot.RetryInterval(600*time.Millisecond)),
	)(ctx); err != nil {
		return errors.Wrapf(err, "failed to capture %s window", fullAppName)
	}

	if err := uiauto.Retry(10,
		uiauto.Combine("quit "+fullAppName,
			keyboard.AccelAction("ctrl+Q"),
			ui.WithTimeout(1*time.Second).WaitUntilGone(appWindow),
		),
	)(ctx); err != nil {
		return errors.Wrapf(err, "failed to quit %s window", fullAppName)
	}

	return nil
}
