// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/guestos"
	"go.chromium.org/tast-tests/cros/local/guestos/apps"
	"go.chromium.org/tast-tests/cros/local/screenshot"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppEmacsWindowOperations,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Performs maximize/restore/minimize/close actions on Emacs",
		Contacts:     []string{"clumptini+oncall@google.com", "alvinjia@google.com"},
		Attr:         []string{"group:mainline", "group:crostini_app_cq"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host", "amd64"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "maximize_bookworm_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
				Val:               apps.WindowOperationMaximize,
			}, {
				Name:              "minimize_bookworm_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
				Val:               apps.WindowOperationMinimize,
			}, {
				Name:              "switch_tablet_bookworm_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
				Val:               apps.WindowOperationSwitchTablet,
			},
		},
	})
}

func AppEmacsWindowOperations(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	d := s.FixtValue().(crostini.FixtureData).Differ()
	cont := s.FixtValue().(crostini.FixtureData).Cont
	op := s.Param().(apps.WindowOperation)

	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()
	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	if err := guestos.SetupEmacs(ctx, cont); err != nil {
		s.Fatal("Failed to configure Emacs: ", err)
	}

	if err := apps.TestWindowOperation(ctx, op, "Emacs (GUI)", "GNU Emacs", "File", keyboard, tconn, d, false); err != nil {
		s.Fatal("Window operation failed: ", err)
	}
}
