// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/guestos/apps"
	"go.chromium.org/tast-tests/cros/local/screenshot"
	"go.chromium.org/tast-tests/cros/local/terminalapp"

	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppVscode,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Opens Visual Studio Code from terminal and performs UI interactions",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "clamshell_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}
func AppVscode(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont
	d := s.FixtValue().(crostini.FixtureData).Differ()

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	// Open Terminal app.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Terminal app: ", err)
	}
	defer terminalApp.Exit(keyboard)(cleanupCtx)

	if err := apps.TestCreateFileWithVSCode(ctx, apps.VSCode, terminalApp, keyboard, tconn, cont, d); err != nil {
		s.Fatal("Failed to create file with Visual Studio Code in Terminal: ", err)
	}
}
