// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/screenshot"
	"go.chromium.org/tast-tests/cros/local/terminalapp"

	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppVscodeUninstall,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Uninstall in Terminal app",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_stable",
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bookworm_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"crostini_app", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBookwormLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}
func AppVscodeUninstall(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	// Open Terminal app.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Terminal app: ", err)
	}
	defer terminalApp.Exit(keyboard)(cleanupCtx)

	ui := uiauto.New(tconn)
	errorMsg := "VSCode not found"
	outError := "VSCode: command not found"
	codeError := nodewith.NameContaining(outError).Role(role.StaticText).First()
	if err := uiauto.Combine("uninstall Visual Studio Code",
		// Run the command to uninstall.
		terminalApp.RunCommand(keyboard, "sudo apt purge -y --allow-change-held-packages code"),

		// Wait for the prompt "$ ", which indicates the end of the previous command.
		// There is always only one node with name "$ ".
		// Because all the previous prompts' names are "$ command".
		ui.WithTimeout(90*time.Second).WaitUntilExists(terminalapp.Prompt),

		// Run command "code || echo VSCode not found"
		// to check the uninstallation works.
		terminalApp.RunCommand(keyboard, "code || "+errorMsg),
		ui.WaitUntilExists(codeError),
	)(ctx); err != nil {
		s.Fatal("Failed to test uninstalling Visual Studio Code in Terminal app: ", err)
	}
}
