// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"time"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/terminalapp"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         CommandVim,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Test vim in Terminal window",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "buster_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "buster_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func CommandVim(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont

	// Open Terminal app.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Terminal app: ", err)
	}

	// Check that vim is preinstalled.
	if err := cont.Command(ctx, "vim", "--version").Run(testexec.DumpLogOnError); err != nil {
		s.Fatal("Failed to execute vim")
	}

	const (
		testFile   = "test.txt"
		testString = "This is a test string."
	)

	if err := uiauto.Combine("create a file with vim",
		// Open file through running command vim filename in Terminal.
		terminalApp.RunCommand(keyboard, fmt.Sprintf("vim %s", testFile)),
		// Type i to enter edit mode.
		keyboard.TypeAction("i"),
		// Type test string into the new file.
		keyboard.TypeAction(testString),
		// Press ESC to exit edit mode.
		keyboard.TypeAction(string('\x1b')),
		// Type :x to save.
		keyboard.TypeAction(":x"),
		// Press Enter.
		keyboard.AccelAction("Enter"),
		// Wait for vim to exit
		terminalApp.WaitForPrompt())(ctx); err != nil {
		s.Fatal("Failed to create file with vim in Terminal: ", err)
	}

	// Check the content of the test file.
	if err := cont.CheckFileContent(ctx, testFile, testString+"\n"); err != nil {
		s.Fatal("The content of the file is wrong: ", err)
	}
}
