// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"io/ioutil"
	"regexp"
	"time"

	"github.com/godbus/dbus/v5"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/metrics"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crash"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/dbusutil"
	"go.chromium.org/tast-tests/cros/local/vm"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

const (
	oomAnomalyEventServiceName        = "org.chromium.AnomalyEventService"
	oomAnomalyEventServicePath        = dbus.ObjectPath("/org/chromium/AnomalyEventService")
	oomAnomalyEventServiceInterface   = "org.chromium.AnomalyEventServiceInterface"
	oomAnomalyGuestOOMEventSignalName = "GuestOomEvent"
	crosEventHistogram                = "Platform.CrOSEvent"
	sigRegexp                         = "sig=guest-oom-event-.*tail.*"
	logRegexp                         = ".* Out of memory: Killed process .*tail.*"
	oomEventHistogramEnum             = 34
	killCode                          = 9
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         OOMEvent,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Check that OOM kill by kernel is detected correctly",
		Contacts: []string{
			"clumptini+oncall@google.com",
			// Crosvm
			"drmasquatch@google.com",
			// Telemetry
			"mutexlox@google.com",
			"cros-telemetry@google.com",
		},
		SoftwareDeps: []string{"chrome", "vm_host"},
		Attr:         []string{"group:mainline"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBullseye",
				Timeout:           10 * time.Minute,
			}, {
				Name:              "bullseye_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBullseye",
				Timeout:           10 * time.Minute,
			}, {
				Name:              "bookworm_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBookworm",
				Timeout:           10 * time.Minute,
			}, {
				Name:              "bookworm_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBookworm",
				Timeout:           10 * time.Minute,
			},
		},
	})
}

// OOMEvent sets up the VM and then runs a process which will be killed via
// the kernels OOM killer to check that it is detected correctly.
func OOMEvent(ctx context.Context, s *testing.State) {
	pre := s.FixtValue().(crostini.FixtureData)
	cont := pre.Cont
	tconn := pre.Tconn

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	s.Log("Setting up crash test")
	if err := crash.SetUpCrashTest(ctx, crash.WithMockConsent()); err != nil {
		s.Fatal("Failed to set up crash test: ", err)
	}
	defer func() {
		if err := crash.TearDownCrashTest(cleanupCtx); err != nil {
			s.Error("Failed to tear down crash test fixture: ", err)
		}
	}()

	s.Log("Restarting anomaly-detector with --testonly-send-all flag")
	if err := crash.RestartAnomalyDetectorWithSendAll(ctx, true); err != nil {
		s.Fatal("Could not restart anomaly-detector: ", err)
	}
	// Restart anomaly-detector upon test end to flush --testonly-send-all state
	defer func(ctx context.Context) {
		if err := crash.RestartAnomalyDetector(ctx); err != nil {
			s.Error("Could not restart anomaly-detector: ", err)
		}
	}(cleanupCtx)

	s.Log("Opting in to AppsSync")
	if err := crash.CreatePerUserAppSyncOptin(ctx, true); err != nil {
		s.Fatal("Failed to create per-user AppSync optin: ", err)
	}
	defer func() {
		if err := crash.RemovePerUserAppSyncOptin(ctx); err != nil {
			s.Error("Failed to clean up per-user AppSync optin: ", err)
		}
	}()

	s.Log("Getting baseline metrics histogram")
	histogram, err := metrics.GetHistogram(ctx, tconn, crosEventHistogram)
	if err != nil {
		s.Fatal("Failed to get baseline for histogram: ", err)
	}

	if err := checkDbusSignal(ctx, cont); err != nil {
		s.Fatal("Didn't get an error signal for OOM process: ", err)
	}

	if err := checkOOMHistogram(ctx, tconn, histogram); err != nil {
		s.Fatal("Could not get updated histogram: ", err)
	}

	if err := checkCrashReport(ctx, s.OutDir()); err != nil {
		s.Fatal("Could not find crash report: ", err)
	}
}

func checkCrashReport(ctx context.Context, outDir string) error {
	testing.ContextLog(ctx, "Checking for expected crash reports")

	daemonStorePaths, err := crash.GetDaemonStoreCrashDirs(ctx)
	if err != nil {
		return errors.Wrap(err, "failed to get daemon store crash dir")
	}

	const metaFilePattern = `guest_oom_event.*\.meta`
	const logFilePattern = `guest_oom_event.*\.log`

	files, err := crash.WaitForCrashFiles(ctx, daemonStorePaths,
		[]string{metaFilePattern, logFilePattern})
	if err != nil {
		return errors.Wrap(err, "couldn't find expected files")
	}

	metaFiles := files[metaFilePattern]
	logFiles := files[logFilePattern]

	testing.ContextLog(ctx, "Checking for expected metadata signature")

	fileNamesToRegexps := map[string]string{
		metaFiles[0]: sigRegexp,
		logFiles[0]:  logRegexp,
	}

	for fileName, fileRegexp := range fileNamesToRegexps {
		fileData, err := ioutil.ReadFile(fileName)
		if err != nil {
			return errors.Wrapf(err, "failed to read the file %v", fileName)
		}
		if re := regexp.MustCompile(fileRegexp); !re.Match(fileData) {
			// To ease debugging in automated environments, save files to a convenient-to-debug
			// location if we don't find the expected content.
			if err := crash.MoveFilesToOut(ctx, outDir, append(logFiles, metaFiles...)...); err != nil {
				testing.ContextLogf(ctx, "Failed to move crash files to out directory: %q", err)
			}
			return errors.Errorf("did not find expected line in file %v, expected: %q", fileName, fileRegexp)
		}
	}

	// If the crash report files were as expected, delete
	// them. This stops them from being uploaded to the crash
	// server and polluting the data with fake crashes.
	//
	// Don't die on error, because this is just a cleanup step.
	if err = crash.RemoveAllFiles(ctx, files); err != nil {
		testing.ContextLogf(ctx, "Failed to clean up generated crash files: %q", err)
	}

	return nil
}

func checkOOMHistogram(ctx context.Context, tconn *chrome.TestConn, histogram *metrics.Histogram) error {
	testing.ContextLog(ctx, "Waiting for histogram update with OOM enum")
	err := testing.Poll(ctx, func(ctx context.Context) error {
		newHistogram, err := metrics.GetHistogram(ctx, tconn, crosEventHistogram)
		if err != nil {
			return testing.PollBreak(errors.Wrap(err, "failed to get new value of histogram"))
		}

		diff, err := newHistogram.Diff(histogram)
		if err != nil {
			return testing.PollBreak(errors.Wrap(err, "failed to diff histograms"))
		}

		for _, bucket := range diff.Buckets {
			if bucket.Min == oomEventHistogramEnum {
				// Got an oom event, returning nil signals testing.Poll to finish.
				return nil
			}
		}

		return errors.New("did not find Crostini.OomEvent in " + diff.String())
	}, nil)

	if err != nil {
		return errors.Wrap(err, "failed polling on metrics.GetHistogram")
	}

	testing.ContextLog(ctx, "Found the expected histogram")

	return nil
}

func checkDbusSignal(ctx context.Context, container *vm.Container) (resultError error) {
	match := dbusutil.MatchSpec{
		Type:      "signal",
		Path:      oomAnomalyEventServicePath,
		Interface: oomAnomalyEventServiceInterface,
		Member:    oomAnomalyGuestOOMEventSignalName,
	}
	signalWatcher, err := dbusutil.NewSignalWatcherForSystemBus(ctx, match)
	if err != nil {
		return errors.Wrap(err, "failed to listen for DBus signals")
	}
	defer func() {
		if err := signalWatcher.Close(ctx); err != nil {
			if resultError == nil {
				resultError = err
			} else {
				testing.ContextLog(ctx, "Failed to close signal watcher: ", err)
			}
		}
	}()

	testing.ContextLog(ctx, "Starting tail process")
	// tail will buffer input in-memory until it reaches a newline, so it can
	// print at least one line at a time. Since /dev/zero by definition has no
	// newlines, the memory of the process should expand until eventually the
	// kernel will be forced to kill it.
	cmd := container.VM.Command(ctx, "tail", "/dev/zero")
	code, extracted := testexec.ExitCode(cmd.Run())
	if !extracted {
		return errors.New("failed to extract exit code from running tail")
	}
	if code != killCode {
		return errors.Errorf("process did not end with the proper exit code: got: %v; expected: %v", code, killCode)
	}

	testing.ContextLog(ctx, "Waiting for signal from anomaly_detector")
	signalCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if _, err := waitForAnomalyDetectorSignal(signalCtx, signalWatcher); err != nil {
		return errors.Wrap(err, "didn't get expected DBus signal")
	}
	testing.ContextLog(ctx, "Got expected signal from anomaly_detector")

	return nil
}

func waitForAnomalyDetectorSignal(ctx context.Context, signalWatcher *dbusutil.SignalWatcher) (*dbus.Signal, error) {
	select {
	case signal := <-signalWatcher.Signals:
		return signal, nil
	case <-ctx.Done():
		return nil, errors.New("Context deadline expired")
	}
}
