// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/crostini/ui/settings"
	"go.chromium.org/tast-tests/cros/local/terminalapp"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:     ResizeRestart,
		Desc:     "Test resizing disk of Crostini from the Settings app while Crostini is shutdown",
		Contacts: []string{"clumptini+oncall@google.com"},
		// TODO(b/442664131): Re-enable once the ResetAutomation is available for MV3.
		// Attr:         []string{"group:mainline"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bookworm_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBookworm",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func ResizeRestart(ctx context.Context, s *testing.State) {
	pre := s.FixtValue().(crostini.FixtureData)
	cr := pre.Chrome
	tconn := pre.Tconn
	cont := pre.Cont

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	// Open the Linux settings.
	st, err := settings.OpenLinuxSettings(ctx, tconn, cr)
	if err != nil {
		s.Fatal("Failed to open Linux Settings: ", err)
	}

	// Shutdown Crostini.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to launch terminal: ", err)
	}
	if err := terminalApp.ShutdownCrostini(cont)(ctx); err != nil {
		s.Fatal("Failed to shutdown crostini: ", err)
	}

	curSize, targetSize, err := st.GetCurAndTargetDiskSize(ctx)
	if err != nil {
		s.Fatal("Failed to get current or target size: ", err)
	}

	// Resize.
	sizeOnSlider, size, err := st.Resize(ctx, targetSize)
	if err != nil {
		s.Fatal("Failed to resize through moving slider: ", err)
	}

	if _, err := terminalapp.Launch(ctx, tconn); err != nil {
		s.Fatal("Failed to launch terminal: ", err)
	}

	if err := terminalApp.Close()(ctx); err != nil {
		s.Fatal("Failed to close terminal: ", err)
	}

	if err := st.VerifyResizeResults(ctx, cont, sizeOnSlider, size); err != nil {
		s.Fatal("Failed to verify resize results: ", err)
	}

	// Resize back to the default value.
	sizeOnSlider, size, err = st.Resize(ctx, curSize)
	if err != nil {
		s.Fatal("Failed to resize back to the default value: ", err)
	}

	if err := st.VerifyResizeResults(ctx, cont, sizeOnSlider, size); err != nil {
		s.Fatal("Failed to verify resize results: ", err)
	}
}
