// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"go.chromium.org/tast-tests/cros/common/perf"
	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/crostini/perfutil"
	"go.chromium.org/tast-tests/cros/local/cryptohome"
	"go.chromium.org/tast-tests/cros/local/disk"
	"go.chromium.org/tast-tests/cros/local/vm"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         SSHFSPerf,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Performance test for guest file sharing over sshfs",
		Contacts:     []string{"cros-virt-devices-guests@google.com", "chibar@google.com"},
		BugComponent: "b:1248538",
		Attr:         []string{"group:crosbolt", "crosbolt_perbuild"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBullseye",
				Timeout:           10 * time.Minute,
			}, {
				Name:              "bookworm",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBookworm",
				Timeout:           10 * time.Minute,
			},
		},
	})
}

func SSHFSPerf(ctx context.Context, s *testing.State) {
	const (
		numberOfIterations = 10
		fileSize           = 1024 * 1024 * 128
	)
	cr := s.FixtValue().(crostini.FixtureData).Chrome
	cont := s.FixtValue().(crostini.FixtureData).Cont
	var totalTime time.Duration

	if err := cont.Cleanup(ctx, "."); err != nil {
		s.Fatal("Failed to cleanup the home directory before the test: ", err)
	}

	pv := perf.NewValues()

	errFile, err := os.Create(filepath.Join(s.OutDir(), "error_log.txt"))
	if err != nil {
		s.Fatal("Failed to create error log: ", err)
	}
	defer errFile.Close()

	filePath, err := createFileOnCrostini(ctx, cr, fileSize, errFile)
	if err != nil {
		s.Fatal("Failed to create a test file: ", err)
	}
	defer os.Remove(filePath)

	for i := 0; i < numberOfIterations; i++ {
		t, err := copyFileFromGuestToHost(ctx, cr, cont, filePath, errFile)
		if err != nil {
			s.Fatalf("Failed at %d-th copy: %v", i, err)
		}
		s.Logf("Amount of time taken to copy: %f [s], Throughput: %f [MB/s]",
			float64(t.Seconds()), float64(fileSize)/float64(t.Microseconds()))
		totalTime += t
	}

	avgTime := totalTime / numberOfIterations
	avgThroughput := float64(fileSize) / float64(avgTime.Microseconds())

	pv.Set(perf.Metric{
		Name:      "guest_to_host_throughput_128mb_2",
		Unit:      "bytesPerSecond",
		Direction: perf.BiggerIsBetter,
	}, avgThroughput*1000000)
	if err := pv.Save(s.OutDir()); err != nil {
		s.Error("Failed to save average copy time due to: ", err)
	}
}

func createFileOnCrostini(ctx context.Context, cr *chrome.Chrome, fileSize uint, errFile *os.File) (string, error) {
	const blockSize = 4096

	userHash, err := cryptohome.UserHash(ctx, cr.NormalizedUser())
	if err != nil {
		return "", errors.Wrap(err, "failed to get user's hash")
	}

	// Home directory of a user on crostini is mounted to
	// /media/fuse/crostini_<user hash>_<vm name>_<container name> on host
	srcDirHostPath := fmt.Sprintf("/media/fuse/crostini_%s_%s_%s", userHash, vm.DefaultVMName, vm.DefaultContainerName)
	if _, err := os.Stat(srcDirHostPath); err != nil {
		return "", errors.Wrapf(err, "failed to find sshfs mount path %v", srcDirHostPath)
	}
	testFile := fmt.Sprintf("test_%s.bin", time.Now().Format("2006-01-02-15-04-05"))
	testFileHostPath := filepath.Join(srcDirHostPath, testFile)

	// Create a random-content file on crostini from host through sshfs
	numBlocks := fileSize / blockSize
	_, err = perfutil.RunCmd(ctx, testexec.CommandContext(ctx,
		"dd", "if=/dev/urandom", fmt.Sprintf("of=%s", testFileHostPath),
		fmt.Sprintf("bs=%d", blockSize), fmt.Sprintf("count=%d", numBlocks)), errFile)
	if err != nil {
		return "", errors.Wrap(err, "failed to create a test file")
	}

	return testFileHostPath, nil
}

func dropGuestCaches(ctx context.Context, cont *vm.Container) error {
	cmd := cont.VM.Command(ctx, "sync")
	_, err := cmd.Output(testexec.DumpLogOnError)
	if err != nil {
		return errors.Wrap(err, "failed to sync on guest")
	}

	cmd = cont.VM.CommandAsRoot(ctx, "/bin/bash", "-c", `echo 3 > /proc/sys/vm/drop_caches`)
	_, err = cmd.Output(testexec.DumpLogOnError)
	if err != nil {
		return errors.Wrap(err, "failed to drop guest caches")
	}

	return nil
}

func copyFileFromGuestToHost(ctx context.Context, cr *chrome.Chrome, cont *vm.Container, testFileHostPath string, errFile *os.File) (time.Duration, error) {
	dstDirHostPath, err := cryptohome.DownloadsPath(ctx, cr.NormalizedUser())
	if err != nil {
		return 0, errors.Wrap(err, "failed to get user's Download path")
	}

	// Pre-process for stable performance measurement
	// Drop host caches
	err = disk.DropCaches(ctx)
	if err != nil {
		return 0, errors.Wrap(err, "failed to drop host caches")
	}
	// Drop guest caches
	err = dropGuestCaches(ctx, cont)
	if err != nil {
		return 0, errors.Wrap(err, "failed to drop guest caches")
	}

	// Copy the file from crostini to host
	start := time.Now()
	_, err = perfutil.RunCmd(ctx, testexec.CommandContext(ctx, "cp", testFileHostPath, dstDirHostPath), errFile)
	elapsed := time.Since(start)
	os.Remove(filepath.Join(dstDirHostPath, filepath.Base(testFileHostPath)))
	if err != nil {
		return 0, errors.Wrap(err, "failed to copy a file from guest to host")
	}

	return elapsed, nil
}
