// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"strings"

	"time"

	"golang.org/x/exp/slices"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/common/usbdevice"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/crostini/ui/settings"
	"go.chromium.org/tast-tests/cros/local/vm"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         USBShareMassStorage,
		LacrosStatus: testing.LacrosVariantExists,
		Desc:         "Share and unshare a virtual usb mass storage device with Crostini",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline", "informational"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_lowperf",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniLowPerf,
				Fixture:           "crostiniBullseyeWithoutArc",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bookworm_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBookworm",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bookworm_lowperf",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniLowPerf,
				Fixture:           "crostiniBookwormWithoutArc",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func USBShareMassStorage(ctx context.Context, s *testing.State) {
	cr := s.FixtValue().(crostini.FixtureData).Chrome
	cont := s.FixtValue().(crostini.FixtureData).Cont
	tconn := s.FixtValue().(crostini.FixtureData).Tconn

	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	handler := faillog.DumpUITreeWithScreenshotHandler(cleanupCtx, tconn, "ui_tree")
	s.AttachErrorHandlers(handler, handler)

	usbMassStorage := usbdevice.NewUSBMassStorage()
	defer usbMassStorage.CleanUp(cleanupCtx)
	if err := usbMassStorage.Init(ctx, 10 /*sizeInMb*/); err != nil {
		s.Fatal("Failed to initialise a mass storage device: ", err)
	}
	if err := usbMassStorage.PlugIn(ctx, false /*readOnly*/); err != nil {
		s.Fatal("Failed to plug in a mass storage device: ", err)
	}

	settings, err := settings.OpenLinuxSettings(ctx, tconn, cr, settings.ManageUSBDevices)
	if err != nil {
		s.Fatal("Failed to find Manage USB devices: ", err)
	}
	defer settings.Close(ctx)
	devices, err := settings.GetUSBDevices(ctx)
	if err != nil {
		s.Fatal("Unable to get devices: ", err)
	}
	deviceName := "Mass Storage Gadget"
	deviceID := fmt.Sprintf("%04x:%04x", usbdevice.VendorIDNetchip, usbdevice.ProductIDNetchipMassStorage)
	if !slices.Contains(devices, deviceName) {
		s.Fatalf("Device %q is not found on the list: %v", deviceName, devices)
	}

	if err := settings.ShareUSBDevice(ctx, deviceName); err != nil {
		s.Fatal("Unable to share a mass storage device: ", err)
	}
	if err := assertDeviceSharedState(ctx, cont, deviceID, true); err != nil {
		s.Fatal("Mass storage device is not present in the container: ", err)
	}

	if err := settings.UnshareUSBDevice(ctx, deviceName); err != nil {
		s.Fatal("Unable to unshare a mass storage device: ", err)
	}
	if err := assertDeviceSharedState(ctx, cont, deviceID, false); err != nil {
		s.Fatal("Mass storage device is still present in the container: ", err)
	}
}

func assertDeviceSharedState(ctx context.Context, cont *vm.Container, deviceID string, expectedSharedState bool) error {
	if err := testing.Poll(ctx, func(ctx context.Context) error {
		out, err := cont.Command(ctx, "lsusb").CombinedOutput(testexec.DumpLogOnError)
		if err != nil {
			errors.Wrapf(err, "failed to run lsusb in the container: %q", string(out))
		}
		if strings.Contains(string(out), deviceID) != expectedSharedState {
			errors.Errorf("device %q shared state in lsusb output does not match the expectation, want %t, got %t, lsusb output: %q", deviceID, expectedSharedState, !expectedSharedState, string(out))
		}
		return nil
	}, &testing.PollOptions{Interval: 3 * time.Second, Timeout: 10 * time.Second}); err != nil {
		return errors.Wrapf(err, "failed to assert device shared state is %t", expectedSharedState)
	}
	return nil
}
