// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome/vmc"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         VmcStart,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Starts Crostini via vmc commands",
		Contacts:     []string{"clumptini+oncall@google.com"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		Attr:         []string{"group:mainline"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bookworm_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBookworm",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func VmcStart(ctx context.Context, s *testing.State) {

	hash, err := vmc.UserIDHash(ctx)
	if err != nil {
		s.Fatal("Failed to get CROS_USER_ID_HASH: ", err)
	}

	const vmName = "tast_vmc_start_vm"

	// Run `vmc create $vmName`
	if err := vmc.Command(ctx, hash, "create", vmName).Run(testexec.DumpLogOnError); err != nil {
		s.Fatalf("Failed to create %s VM: %v", vmName, err)
	}
	defer func() {
		if err := vmc.Command(ctx, hash, "destroy", "-y", vmName).Run(testexec.DumpLogOnError); err != nil {
			s.Errorf("Failed to destroy %s VM: %v", vmName, err)
		}
	}()

	// Run `echo exit | vmc start $vmName`
	// First, start the vmc command.
	cmd := vmc.Command(ctx, hash, "start", vmName)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		s.Fatal("Failed to open stdin pipe: ", err)
	}
	if err := cmd.Start(); err != nil {
		s.Fatalf("Failed to start %s VM: %v", vmName, err)
	}
	// Then, send "exit" to the VM shell.
	if _, err := stdin.Write([]byte("exit\n")); err != nil {
		s.Fatal("Failed to write 'exit' to stdin pipe: ", err)
	}
	if err := cmd.Wait(testexec.DumpLogOnError); err != nil {
		s.Fatal("Failed to wait for exiting from the VM shell: ", err)
	}

	// Run `vmc stop $vmName`
	if err := vmc.Command(ctx, hash, "stop", vmName).Run(testexec.DumpLogOnError); err != nil {
		s.Fatalf("Failed to stop %s VM: %v", vmName, err)
	}
}
