// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"io"
	"os"
	"regexp"
	"strings"
	"time"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/chrome/vmc"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast/core/testing"
)

const testScript string = "test-extra-disk.sh"

func init() {
	testing.AddTest(&testing.Test{
		Func:         VmcExtraDisk,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Starts Crostini with an extra disk image",
		Contacts:     []string{"clumptini+oncall@google.com"},
		SoftwareDeps: []string{"chrome", "vm_host", "untrusted_vm"},
		Attr:         []string{"group:mainline"},
		Data:         []string{testScript},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bookworm_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniOptimalPerf,
				Fixture:           "crostiniBookworm",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func VmcExtraDisk(ctx context.Context, s *testing.State) {

	hash, err := vmc.UserIDHash(ctx)
	if err != nil {
		s.Fatal("Failed to get CROS_USER_ID_HASH: ", err)
	}

	// Run `vmc extra-disk-create`
	vmcCmd := vmc.Command(ctx, hash, "create-extra-disk", "--size", "256M", "extra.img")
	vmcOutput, err := vmcCmd.Output(testexec.DumpLogOnError)
	if err != nil {
		s.Fatal("Failed to create an extra disk image: ", err)
	}

	// Extract the created disk path from the message.
	diskCreatedRe := regexp.MustCompile(`^A raw disk is created at (.*)\.\n$`)
	matches := diskCreatedRe.FindSubmatch(vmcOutput)
	if len(matches) != 2 {
		s.Fatalf("Didn't find extra disk creation message in '%q'", vmcOutput)
	}
	extraDisk := string(matches[1])

	defer os.Remove(extraDisk)

	const vmName = "tast_extra_disk_vm"

	// Run `vmc create $vmName`
	if err := vmc.Command(ctx, hash, "create", vmName).Run(testexec.DumpLogOnError); err != nil {
		s.Fatalf("Failed to create %s VM: %v", vmName, err)
	}
	defer func() {
		if err := vmc.Command(ctx, hash, "destroy", "-y", vmName).Run(testexec.DumpLogOnError); err != nil {
			s.Errorf("Failed to destroy %s VM: %v", vmName, err)
		}
	}()

	// Run `vmc start $vmName --extra-disk $extraDisk`.
	cmd := vmc.Command(ctx, hash, "start", vmName, "--extra-disk", extraDisk)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		s.Fatal("Failed to open stdin pipe: ", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		s.Fatal("Failed to open stdout pipe: ", err)
	}
	if err := cmd.Start(); err != nil {
		s.Fatalf("Failed to start %s VM with %s: %v", vmName, extraDisk, err)
	}

	// Write the content of testScript to the VM's stdin.
	f, err := os.Open(s.DataPath(testScript))
	if err != nil {
		s.Fatalf("Failed to open %s: %v", testScript, err)
	}
	defer f.Close()
	if _, err := io.Copy(stdin, f); err != nil {
		s.Fatal("Failed to write a test script to stdin pipe: ", err)
	}
	// Close stdin explicitly to get outputs.
	if err := stdin.Close(); err != nil {
		s.Fatal("Failed to close stdin pipe: ", err)
	}

	buf := new(strings.Builder)
	if _, err := io.Copy(buf, stdout); err != nil {
		s.Fatal("Failed to get the VM output: ", err)
	}
	output := string(buf.String())

	if err := cmd.Wait(testexec.DumpLogOnError); err != nil {
		s.Fatal("Failed to wait for exiting from the VM shell: ", err)
	}

	// Check if the test script ran successfully.
	// Use strings.Contains instead of "==", as output contains ANSI escape sequences.
	if !strings.Contains(output, "TAST_OK") {
		s.Error("Test script didn't run successfully: ", output)
	}

	// Run `vmc stop $vmName`
	if err := vmc.Command(ctx, hash, "stop", vmName).Run(testexec.DumpLogOnError); err != nil {
		s.Errorf("Failed to stop %s VM: %v", vmName, err)
	}
}
