// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package cellularui

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/cellular"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/lockscreen"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/ossettings"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/quicksettings"
	"go.chromium.org/tast-tests/cros/local/diagnosticsutils"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/testing/hwdep"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:           HotspotEnableDisableInLockScreen,
		LifeCycleStage: testing.LifeCycleInDevelopment,
		Desc:           "Test hotspot can be accessed and controled in lock screen through Quick Settings",
		Contacts: []string{
			"alfredyu@cienet.com",
			"chromeos-connectivity-cienet-external@google.com",
		},
		BugComponent: "b:1578688", // ChromeOS > External > Cienet > Manual Test Automation > Test stabilization
		// TODO(b/542029943): Re-enable once the test is stable.
		// Attr:         []string{"group:cellular", "cellular_unstable", "cellular_sim_active", "cellular_carrier_dependent"},
		HardwareDeps: hwdep.D(hwdep.WifiSAP()),
		SoftwareDeps: []string{"chrome", "hotspot"},
		Fixture:      "cellularEnforceConnectionLocal",
		Timeout:      5 * time.Minute,
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.

			{
				Name: "",
				Val:  "",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_local"},
			},
			{
				Name: "att",
				Val:  "att",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_att"},
			},
			{
				Name: "tmobile",
				Val:  "tmobile",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_tmobile"},
			},
			{
				Name: "softbank",
				Val:  "softbank",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_softbank"},
			},
			{
				Name: "amarisoft",
				Val:  "amarisoft",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_amarisoft"},
			},
			{
				Name: "vodafone",
				Val:  "vodafone",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_vodafone"},
			},
			{
				Name: "rakuten",
				Val:  "rakuten",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_rakuten"},
			},
			{
				Name: "ee",
				Val:  "ee",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_ee"},
			},
			{
				Name: "kddi",
				Val:  "kddi",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_kddi"},
			},
			{
				Name: "docomo",
				Val:  "docomo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_docomo"},
			},
			{
				Name: "fi",
				Val:  "fi",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_fi"},
			},
			{
				Name: "bell",
				Val:  "bell",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_bell"},
			},
			{
				Name: "roger",
				Val:  "roger",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_roger"},
			},
			{
				Name: "telus",
				Val:  "telus",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_telus"},
			},
			{
				Name: "cbrs",
				Val:  "cbrs",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_cbrs"},
			},
			{
				Name: "linemo",
				Val:  "linemo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_linemo"},
			},
			{
				Name: "povo",
				Val:  "povo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_povo"},
			},
			{
				Name: "hanshin",
				Val:  "hanshin",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_hanshin"},
			},
		},
	})
}

func HotspotEnableDisableInLockScreen(ctx context.Context, s *testing.State) {
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 10*time.Second)
	defer cancel()

	cr, err := chrome.New(ctx, chrome.EnableFeatures("TetheringExperimentalFunctionality"))
	if err != nil {
		s.Fatal("Failed to create a new instance of Chrome: ", err)
	}
	defer cr.Close(cleanupCtx)

	helper := s.FixtValue().(*cellular.FixtData).Helper
	if _, err := helper.Connect(ctx); err != nil {
		s.Fatal("Failed to connect cellular service: ", err)
	}

	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed to create Test API connection: ", err)
	}

	// Making sure DUT is in clamshell mode to prevent virtual keyboard from popping up in lock screen.
	cleanUp, err := diagnosticsutils.EnsureClamshellMode(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to ensure DUT in clamshell mode: ", err)
	}
	defer cleanUp(cleanupCtx)

	hs, err := ossettings.LaunchAtHotspotSubpage(ctx, tconn, cr)
	if err != nil {
		s.Fatal("Failed to open hotspot subpage: ", err)
	}
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "ui_tree")

	// Toggle on and off hotspot in order to make it appear in Quick Settings.
	if err := hs.ToggleHotspot(ctx, tconn, cr, true); err != nil {
		s.Fatal("Failed to toggle on hotspot: ", err)
	}
	if err := hs.ToggleHotspot(ctx, tconn, cr, false); err != nil {
		s.Fatal("Failed to toggle off hotspot: ", err)
	}

	if hasHotspotTile, err := quicksettings.IsHotspotTileShown(ctx, tconn); err != nil {
		s.Fatal("Failed to show hotspot tile in quick settings: ", err)
	} else if !hasHotspotTile {
		s.Fatal("Failed to show hotspot tile in quick settings:")
	}

	if err := lockscreen.Lock(ctx, tconn); err != nil {
		s.Fatal("Failed to lock the screen on ChromeOS: ", err)
	}

	if err := quicksettings.NavigateToHotspotDetailedView(ctx, tconn); err != nil {
		s.Fatal("Failed to navigate to hotspot detailed view: ", err)
	}

	ui := uiauto.New(tconn)
	if err := uiauto.Combine("Toggle on and off hotspot in Hotspot detailed view",
		ui.EnsureGoneFor(quicksettings.HotspotOnNoDeviceConnectedText, 3*time.Second),
		ui.LeftClick(quicksettings.HotspotDetailedViewToggle),
		ui.WaitUntilExists(quicksettings.HotspotOnNoDeviceConnectedText),
		ui.LeftClick(quicksettings.HotspotDetailedViewToggle),
		ui.WaitUntilGone(quicksettings.HotspotOnNoDeviceConnectedText),
		ui.EnsureGoneFor(quicksettings.HotspotOnNoDeviceConnectedText, 5*time.Second),
	)(ctx); err != nil {
		s.Fatal("Failed to toggle on and off hotspot in Hotspot detailed view: ", err)
	}
}
