// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package cellularui

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/local/cellular"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/ossettings"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/testing/hwdep"
)

func init() {
	testing.AddTest(&testing.Test{
		Func: HotspotAbortEnable,
		Desc: "Test hotspot enable operation can be aborted",
		Contacts: []string{
			"alfredyu@cienet.com",
			"chromeos-connectivity-cienet-external@google.com",
		},
		BugComponent:   "b:1578688", // ChromeOS > External > Cienet > Manual Test Automation > Test stabilization
		LifeCycleStage: testing.LifeCycleOwnerMonitored,
		// TODO(b/542029943): Re-enable once the test is stable.
		// Attr:           []string{"group:cellular", "cellular_sim_active", "cellular_carrier_dependent"},
		HardwareDeps: hwdep.D(hwdep.WifiSAP()),
		SoftwareDeps: []string{"chrome", "hotspot"},
		Fixture:      "cellularEnforceConnectionLocal",
		Timeout:      5 * time.Minute,
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.

			{
				Name: "",
				Val:  "",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_local"},
			},
			{
				Name: "att",
				Val:  "att",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_att"},
			},
			{
				Name: "tmobile",
				Val:  "tmobile",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_tmobile"},
			},
			{
				Name: "softbank",
				Val:  "softbank",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_softbank"},
			},
			{
				Name: "amarisoft",
				Val:  "amarisoft",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_amarisoft"},
			},
			{
				Name: "vodafone",
				Val:  "vodafone",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_vodafone"},
			},
			{
				Name: "rakuten",
				Val:  "rakuten",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_rakuten"},
			},
			{
				Name: "ee",
				Val:  "ee",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_ee"},
			},
			{
				Name: "kddi",
				Val:  "kddi",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_kddi"},
			},
			{
				Name: "docomo",
				Val:  "docomo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_docomo"},
			},
			{
				Name: "fi",
				Val:  "fi",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_fi"},
			},
			{
				Name: "bell",
				Val:  "bell",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_bell"},
			},
			{
				Name: "roger",
				Val:  "roger",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_roger"},
			},
			{
				Name: "telus",
				Val:  "telus",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_telus"},
			},
			{
				Name: "cbrs",
				Val:  "cbrs",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_cbrs"},
			},
			{
				Name: "linemo",
				Val:  "linemo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_linemo"},
			},
			{
				Name: "povo",
				Val:  "povo",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_povo"},
			},
			{
				Name: "hanshin",
				Val:  "hanshin",
				// TODO(b/542029943): Re-enable once the test is stable.
				// ExtraAttr: []string{"cellular_carrier_hanshin"},
			},
		},
	})
}

func HotspotAbortEnable(ctx context.Context, s *testing.State) {
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 10*time.Second)
	defer cancel()

	cr, err := chrome.New(ctx, chrome.EnableFeatures("TetheringExperimentalFunctionality"))
	if err != nil {
		s.Fatal("Failed to create a new instance of Chrome: ", err)
	}

	helper := s.FixtValue().(*cellular.FixtData).Helper
	if _, err := helper.Connect(ctx); err != nil {
		s.Fatal("Failed to connect cellular service: ", err)
	}

	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed to create Test API connection: ", err)
	}

	networkPage, err := ossettings.LaunchAtPage(ctx, tconn, ossettings.Internet)
	if err != nil {
		s.Fatal("Failed to launch Network page: ", err)
	}
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "ui_tree")

	const toggleName = "Hotspot"
	if enabled, err := networkPage.IsToggleOptionEnabled(ctx, cr, toggleName); err != nil {
		s.Fatal("Hotspot toggle should not be enabled: ", err)
	} else if enabled {
		s.Fatal("Hotspot toggle should not be enabled")
	}

	ui := uiauto.New(tconn)
	// Specify the ancestor, since elements in main settings page might have the same attribute with elements in the navigation list.
	mainPage := nodewith.Role(role.Main).Ancestor(ossettings.WindowFinder)
	if err := uiauto.Combine("Toggle on hotspot",
		ui.LeftClick(ossettings.HotspotToggle.Ancestor(mainPage)),
		ui.WaitUntilExists(ossettings.HotspotTurningOnSublabel.Ancestor(mainPage)),
	)(ctx); err != nil {
		s.Fatal("Failed to toggle on hotspot and see turning on sublabel: ", err)
	}

	// GoBigSleepLint: simulate a short delay before user toggle off hotspot.
	testing.Sleep(ctx, 500*time.Millisecond)

	if err := uiauto.Combine("Abort enable hotspot",
		ui.LeftClick(ossettings.HotspotToggle.Ancestor(mainPage)),
		ui.WaitUntilExists(ossettings.HotspotOffSublabel.Ancestor(mainPage)),
	)(ctx); err != nil {
		s.Fatal("Failed to abort enable hotspot: ", err)
	}

	// Make sure hotspot can still be turned on and off successfully.
	if err := networkPage.ToggleHotspot(ctx, tconn, cr, true); err != nil {
		s.Fatal("Failed to start hotspot: ", err)
	}
	if err := networkPage.ToggleHotspot(ctx, tconn, cr, false); err != nil {
		s.Fatal("Failed to end hotspot: ", err)
	}
}
