// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"path/filepath"
	"time"

	"chromiumos/tast/ctxutil"
	"chromiumos/tast/local/chrome/uiauto"
	"chromiumos/tast/local/chrome/uiauto/faillog"
	"chromiumos/tast/local/chrome/uiauto/filesapp"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/terminalapp"
	"chromiumos/tast/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         OpenWithTerminal,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Open directory in FilesApp with terminal",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline"},
		SoftwareDeps: []string{"chrome"},
		BugComponent: "b:1122570",
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "buster_stable",
				ExtraSoftwareDeps: []string{"vm_host", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "buster_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"vm_host", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"vm_host", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"vm_host", "dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "buster_stable_manatee",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc", "manatee"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func OpenWithTerminal(ctx context.Context, s *testing.State) {
	pre := s.FixtValue().(crostini.FixtureData)

	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 15*time.Second)
	defer cancel()
	recorder := uiauto.CreateAndStartScreenRecorder(ctx, pre.Tconn)
	defer uiauto.StopAndSaveOnError(cleanupCtx, recorder, filepath.Join(s.OutDir(), "screen_recording.webm"), s.HasError)
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, pre.Chrome, "ui_tree")

	// Launch Files app and open Downloads with terminal.
	filesApp, err := filesapp.Launch(ctx, pre.Tconn)
	if err != nil {
		s.Fatal("Failed to open Files app: ", err)
	}

	if err := filesApp.ClickContextMenuItemRegex("Downloads", "Terminal")(ctx); err != nil {
		s.Fatal("Open with Terminal failed: ", err)
	}

	// Find terminal window.
	_, err = terminalapp.Find(ctx, pre.Tconn)
	if err != nil {
		s.Fatal("Failed to find terminal window: ", err)
	}
}
