// Copyright 2023 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.wwcb;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/wwcb";

// ExternalStorageService allows basic remote operations on files.
service ExternalStorageService {
  // EjectAll ejects all present USB Drives.
  rpc EjectAll(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}