syntax = "proto3";

package tast.common.power.powerpb;

option go_package = "go.chromium.org/tast-tests/cros/common/power/powerpb";

message DeviceInfo {
  string board = 1;
  string platform = 2;
  bool has_hammer = 3;
  string hardware_revision = 4;
  string chromeos_release_milestone = 5;
  string chromeos_release_version = 6;
  string firmware_version = 7;
  optional string chromeos_channel = 8;
  string ec_version = 9;
  string kernel_version = 10;
  string dashboard_note = 11;
  string cpu_name = 12;
  int64 memory_size = 13;
  int64 disk_size = 14;
  string screen_resolution = 15;
  string hardware_id = 16;
  int32 cpu_count = 17;
  int32 core_count = 18;
  int32 thread_count_per_cpu = 19;
  string cpu_vendor = 20;
  double cpu_cache_size = 21;
  string gpu_model = 22;
  string memory_type = 23;
  int32 memory_frequency = 24;
  string storage_type = 25;
  string screen_size = 26;
  int32 screen_refresh_rate = 27;
  optional double battery_shutdown_percent = 28;
  optional double battery_size = 29;
}