// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package network

import (
	"context"
	"time"

	"chromiumos/tast/common/shillconst"
	"chromiumos/tast/common/testexec"
	"chromiumos/tast/ctxutil"
	"chromiumos/tast/errors"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/network/routing"
	"chromiumos/tast/local/vm"
	"chromiumos/tast/testing"
)

type crostiniConnectivityTestParams struct {
	v6Only bool
}

func init() {
	testing.AddTest(&testing.Test{
		Func:         CrostiniConnectivity,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Checks IPv4 and IPv6 connectivity inside penguin container",
		Contacts:     []string{"taoyl@google.com", "cros-networking@google.com"},
		Attr:         []string{"group:network"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		HardwareDeps: crostini.CrostiniMinDiskSize,
		Params: []testing.Param{
			// Parameters generated by crostini_connectivity_test.go. DO NOT EDIT.
			{
				Name:              "dualstack_buster",
				ExtraSoftwareDeps: []string{"dlc"},
				Fixture:           "crostiniBuster",
				Timeout:           10 * time.Minute,
				Val:               crostiniConnectivityTestParams{},
			}, {
				Name:              "dualstack_bullseye",
				ExtraSoftwareDeps: []string{"dlc"},
				Fixture:           "crostiniBullseye",
				Timeout:           10 * time.Minute,
				Val:               crostiniConnectivityTestParams{},
			}, {
				Name:              "v6only_buster",
				ExtraSoftwareDeps: []string{"dlc"},
				Fixture:           "crostiniBuster",
				Timeout:           10 * time.Minute,
				Val:               crostiniConnectivityTestParams{v6Only: true},
			}, {
				Name:              "v6only_bullseye",
				ExtraSoftwareDeps: []string{"dlc"},
				Fixture:           "crostiniBullseye",
				Timeout:           10 * time.Minute,
				Val:               crostiniConnectivityTestParams{v6Only: true},
			},
		},
	})
}

func CrostiniConnectivity(ctx context.Context, s *testing.State) {
	cont := s.FixtValue().(crostini.FixtureData).Cont
	v6only := s.Param().(crostiniConnectivityTestParams).v6Only

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 10*time.Second)
	defer cancel()

	// Set up test topology.
	testEnv := routing.NewSimpleNetworkEnv(!v6only, true, !v6only, true)
	if err := testEnv.SetUp(ctx); err != nil {
		s.Fatal("Failed to set up routing test env: ", err)
	}
	defer func(ctx context.Context) {
		if err := testEnv.TearDown(ctx); err != nil {
			s.Error("Failed to tear down routing test env: ", err)
		}
	}(cleanupCtx)

	// Wait for online and verify topology in host.
	if err := testEnv.ShillService.WaitForProperty(ctx, shillconst.ServicePropertyState, shillconst.ServiceStateOnline, 10*time.Second); err != nil {
		s.Error("Failed to wait for service online: ", err)
	}
	routerAddrs, err := testEnv.Router.WaitForVethInAddrs(ctx, !v6only, true)
	if err != nil {
		s.Fatal("Failed to get inner addrs from router env: ", err)
	}
	serverAddrs, err := testEnv.Server.WaitForVethInAddrs(ctx, !v6only, true)
	if err != nil {
		s.Fatal("Failed to get inner addrs from server env: ", err)
	}
	var pingAddrs []string
	if !v6only {
		pingAddrs = append(pingAddrs, routerAddrs.IPv4Addr.String())
		pingAddrs = append(pingAddrs, serverAddrs.IPv4Addr.String())
	}
	for _, ip := range routerAddrs.IPv6Addrs {
		pingAddrs = append(pingAddrs, ip.String())
	}
	for _, ip := range serverAddrs.IPv6Addrs {
		pingAddrs = append(pingAddrs, ip.String())
	}
	if !v6only {
		pingAddrs = append(pingAddrs, routing.TestDomainNameV4)
	}
	pingAddrs = append(pingAddrs, routing.TestDomainNameV6)
	for _, target := range pingAddrs {
		if err := routing.ExpectPingSuccessWithTimeout(ctx, target, "chronos", 10*time.Second); err != nil {
			s.Errorf("Network verification failed: %v is not reachable as user %s on host: %v", target, "chronos", err)
		}
	}

	// Check if testEnv prefix propagated into Crostini, and log it for debugging.
	const addressPollTimeout = 5 * time.Second
	if err := testing.Poll(ctx, func(ctx context.Context) error {
		out, err := cont.Command(ctx, "/usr/bin/ip", "addr", "show", "scope", "global").Output(testexec.DumpLogOnError)
		if err != nil {
			return err
		}
		testing.ContextLog(ctx, "Crostini address information: ", string(out))
		return nil
	}, &testing.PollOptions{Timeout: addressPollTimeout}); err != nil {
		s.Fatal("Failed to get address information in Crostini: ", err)
	}

	for _, ip := range pingAddrs {
		if err := crostiniRetriedPingWithTimeout(ctx, cont, ip, 10*time.Second); err != nil {
			s.Errorf("Failed to ping %s from Crostini: %v", ip, err)
		} else {
			testing.ContextLogf(ctx, "Succeeded to ping %s from Crostini", ip)
		}
	}
}

func crostiniRetriedPingWithTimeout(ctx context.Context, cont *vm.Container, addr string, timeout time.Duration) error {
	numRetries := 0
	if err := testing.Poll(ctx, func(ctx context.Context) error {
		output, err := cont.Command(ctx, "/bin/ping", "-c1", "-w2", addr).Output()
		if err == nil {
			return nil
		}
		numRetries++
		return errors.Wrapf(err, "failed to ping %s with %d retries: output %s", addr, numRetries, output)
	}, &testing.PollOptions{Timeout: timeout, Interval: 500 * time.Millisecond}); err != nil {
		return errors.Wrap(err, "failed to ping with polling")
	}
	return nil
}
