syntax = "proto3";

package tast.cros.uwb;

option go_package = "go.chromium.org/tast-tests/cros/common/uwb";

message AngleReading {
    double reading = 1;
    uint32 fom = 2;
}

message RangingResult {
    uint32 total_report_count = 1;
    uint32 successful_report_count = 2;
    repeated uint32 distance_readings = 3;
    repeated AngleReading azimuth_readings = 4;
    repeated AngleReading destination_azimuth_readings = 5;
    repeated AngleReading elevation_readings = 6;
    repeated AngleReading destination_elevation_readings = 7;
    map<int32, uint64> status_codes = 8;
}