// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package gscdevboard

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/common/firmware/ti50"
	"go.chromium.org/tast-tests/cros/remote/bundles/cros/gscdevboard/utils"
	"go.chromium.org/tast-tests/cros/remote/firmware/ti50/fixture"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:    Ti50TCG,
		Desc:    "Run TCG Compliance tests against a remote Ti50",
		Timeout: 60 * time.Minute,
		Contacts: []string{
			"cros-hwsec@google.com", // CrOS GSC Developers
			"granaghan@google.com",  // Test Author
		},
		BugComponent: "b:715469", // ChromeOS > Platform > System > Hardware Security > HwSec GSC > Ti50
		Attr: []string{"group:gsc",
			"gsc_dt_ab", "gsc_dt_shield", "gsc_ot_shield",
			"gsc_image_ti50",
			"gsc_tcg"},
		Fixture: fixture.GSCOpenCCD,
		Params: []testing.Param{{
			Name:      "se__test_simulated_smart_card",
			Val:       "SE_TestSimulatedSmartCard",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_activate",
			Val:       "TestActivate",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_activate_ecdh",
			Val:       "TestActivateEcdh",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_activate_hmac",
			Val:       "TestActivateHmac",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_auth_dec_session",
			Val:       "TestAuthDecSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_auth_enc_dec_session",
			Val:  "TestAuthEncDecSession",
		}, {
			Name:      "test_bad_handles",
			Val:       "TestBadHandles",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_bad_sessions",
			Val:       "TestBadSessions",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_bogus_hash_ticket",
			Val:       "TestBogusHashTicket",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_bound_audit_session",
			Val:       "TestBoundAuditSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_bound_auth_enc_dec_session",
			Val:       "TestBoundAuthEncDecSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_cancel",
			Val:       "TestCancel",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_certify_creation",
			Val:       "TestCertifyCreation",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_certify_creation_primary",
			Val:       "TestCertifyCreationPrimary",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_certify_key",
			Val:       "TestCertifyKey",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_certify_key_without_nv__certify",
			Val:       "TestCertifyKeyWithoutNv_Certify",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_continue_session_attr",
			Val:       "TestContinueSessionAttr",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_create_ecc_primary",
			Val:       "TestCreateEccPrimary",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_create_errors",
			Val:       "TestCreateErrors",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_create_primary_faults",
			Val:       "TestCreatePrimaryFaults",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_create_sign_quote",
			Val:       "TestCreateSignQuote",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_da_exemption",
			Val:       "TestDAExemption",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_duplicate_errors",
			Val:  "TestDuplicateErrors",
		}, {
			Name: "test_duplicate_import",
			Val:  "TestDuplicateImport",
		}, {
			Name: "test_ecc",
			Val:  "TestEcc",
		}, {
			Name:      "test_ecc_sig",
			Val:       "TestEccSig",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_ecc_sig2",
			Val:       "TestEccSig2",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_ec_schnorr_coverage",
			Val:       "TestEcSchnorrCoverage",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_empty_sensitive",
			Val:       "TestEmptySensitive",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_evict_control",
			Val:       "TestEvictControl",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_evict_control_transient",
			Val:       "TestEvictControlTransient",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_export_attribs",
			Val:       "TestExportAttribs",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_external_key_import",
			Val:       "TestExternalKeyImport",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_firmware_read",
			Val:       "TestFirmwareRead",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_gen_new_symm",
			Val:       "TestGenNewSymm",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_get_capability_context",
			Val:       "TestGetCapabilityContext",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_get_capability_pcr",
			Val:       "TestGetCapabilityPCR",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_get_cap_commands",
			Val:  "TestGetCapCommands",
		}, {
			Name:      "test_get_cap_coverage",
			Val:       "TestGetCapCoverage",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_get_random",
			Val:       "TestGetRandom",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_get_test_results",
			Val:       "TestGetTestResults",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_gratuitous_auth",
			Val:       "TestGratuitousAuth",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hash",
			Val:       "TestHash",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hierarchy_control_owner_access",
			Val:       "TestHierarchyControlOwnerAccess",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac2",
			Val:       "TestHmac2",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac_errors",
			Val:       "TestHmacErrors",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac_pub_priv_mismatch",
			Val:       "TestHmacPubPrivMismatch",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac_quote",
			Val:       "TestHmacQuote",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac_session",
			Val:       "TestHmacSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_hmac_signing",
			Val:       "TestHmacSigning",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_import",
			Val:       "TestImport",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_import_data_object",
			Val:       "TestImportDataObject",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_import_ecdh",
			Val:       "TestImportEcdh",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_import_export",
			Val:       "TestImportExport",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_inner_wrapper_dup",
			Val:  "TestInnerWrapperDup",
		}, {
			Name:      "test_key_creation",
			Val:       "TestKeyCreation",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_key_gen",
			Val:       "TestKeyGen",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_load_errors",
			Val:       "TestLoadErrors",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_normalized_policies",
			Val:       "TestNormalizedPolicies",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv",
			Val:       "TestNv",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv2",
			Val:       "TestNv2",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_nv3",
			Val:  "TestNv3",
		}, {
			Name:      "test_nv_counter",
			Val:       "TestNvCounter",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_counter2",
			Val:       "TestNvCounter2",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_define_space",
			Val:       "TestNvDefineSpace",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_extend",
			Val:       "TestNvExtend",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_owner_clear",
			Val:       "TestNvOwnerClear",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_nv_partial_write",
			Val:  "TestNvPartialWrite",
		}, {
			Name:      "test_nv_set_bits",
			Val:       "TestNvSetBits",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_stress",
			Val:       "TestNvStress",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_nv_with_policy",
			Val:       "TestNvWithPolicy",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch_410162",
			Val:       "TestPatch_410162",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch_411165",
			Val:       "TestPatch_411165",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_336067",
			Val:       "TestPatch_R88_336067",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_374194",
			Val:       "TestPatch_R88_374194",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_391785",
			Val:       "TestPatch_R88_391785",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_392304",
			Val:       "TestPatch_R88_392304",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_398735",
			Val:       "TestPatch_R88_398735",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_405740",
			Val:       "TestPatch_R88_405740",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_patch__r88_898154",
			Val:       "TestPatch_R88_898154",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_persistent_transient_object",
			Val:       "TestPersistentTransientObject",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_pin",
			Val:       "TestPin",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_plaintext_import_export",
			Val:       "TestPlaintextImportExport",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_policy_auth",
			Val:       "TestPolicyAuth",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_policy_auth_bound",
			Val:       "TestPolicyAuthBound",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_policy_auth_bound_da",
			Val:  "TestPolicyAuthBoundDA",
		}, {
			Name:      "test_policy_pcr_raw_commands",
			Val:       "TestPolicyPCRRawCommands",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_policy_secret",
			Val:       "TestPolicySecret",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_policy_secret_bad_auth",
			Val:       "TestPolicySecretBadAuth",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_policy_signed",
			Val:  "TestPolicySigned",
		}, {
			Name:      "test_public_private_mismatch_ecc",
			Val:       "TestPublicPrivateMismatchEcc",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_public_private_mismatch_rsa",
			Val:       "TestPublicPrivateMismatchRsa",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_public_private_mismatch_sym",
			Val:       "TestPublicPrivateMismatchSym",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_pub_only_bind_object",
			Val:       "TestPubOnlyBindObject",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_random",
			Val:       "TestRandom",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_certify_creation",
			Val:       "TestRawCertifyCreation",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_define_space",
			Val:       "TestRawNVDefineSpace",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_increment",
			Val:       "TestRawNVIncrement",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_read",
			Val:       "TestRawNVRead",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_read_lock",
			Val:       "TestRawNVReadLock",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_read_public",
			Val:       "TestRawNVReadPublic",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_undefine_space",
			Val:       "TestRawNVUndefineSpace",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_nv_write",
			Val:       "TestRawNVWrite",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_raw_sign",
			Val:       "TestRawSign",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_reserved_bits",
			Val:       "TestReservedBits",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_rsaes",
			Val:       "TestRsaes",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_rsa_exponents",
			Val:       "TestRsaExponents",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_rsa_extrema",
			Val:       "TestRsaExtrema",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_rsa_sign_pss",
			Val:       "TestRsaSignPss",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_salted_auth_session_errors",
			Val:       "TestSaltedAuthSessionErrors",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_salted_auth_session_sym",
			Val:       "TestSaltedAuthSessionSym",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_salted_auth_session_xor",
			Val:       "TestSaltedAuthSessionXor",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_salted_bound_auth_session",
			Val:       "TestSaltedBoundAuthSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_seal_unseal",
			Val:       "TestSealUnseal",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_seal_unseal_persisted_object",
			Val:       "TestSealUnsealPersistedObject",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_self_test",
			Val:       "TestSelfTest",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_serialization",
			Val:       "TestSerialization",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_session_encryption",
			Val:       "TestSessionEncryption",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_session_encryption_other_algs",
			Val:       "TestSessionEncryptionOtherAlgs",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_sign",
			Val:       "TestSign",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_sign_object_attributes",
			Val:       "TestSignObjectAttributes",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_sign_restricted",
			Val:       "TestSignRestricted",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_sign_verify",
			Val:  "TestSignVerify",
		}, {
			Name:      "test_simple_duplicate_import",
			Val:       "TestSimpleDuplicateImport",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_simple_duplicate_import_rsa",
			Val:       "TestSimpleDuplicateImportRsa",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_simple_sign",
			Val:  "TestSimpleSign",
		}, {
			Name:      "test_start_auth_session_bound",
			Val:       "TestStartAuthSessionBound",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_start_auth_session_hmac",
			Val:       "TestStartAuthSessionHMAC",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_start_auth_session_max_session",
			Val:       "TestStartAuthSessionMaxSession",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_start_auth_session_policy",
			Val:       "TestStartAuthSessionPolicy",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_start_auth_session_seed",
			Val:       "TestStartAuthSessionSeed",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_sw_signing",
			Val:       "TestSWSigning",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name: "test_sym_parent",
			Val:  "TestSymParent",
		}, {
			Name: "test_sym_primary",
			Val:  "TestSymPrimary",
		}, {
			Name:      "test_temporary_object",
			Val:       "TestTemporaryObject",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_test_parms",
			Val:       "TestTestParms",
			ExtraAttr: []string{"gsc_h1_shield"},
		}, {
			Name:      "test_vendor_specific",
			Val:       "TestVendorSpecific",
			ExtraAttr: []string{"gsc_h1_shield"},
		},
		},
	})
}

func Ti50TCG(ctx context.Context, s *testing.State) {
	b := utils.NewDevboardHelper(s, s.FixtValue().(*fixture.Value))
	i := ti50.MustOpenCrOSImage(ctx, b, s, b.TestbedType)
	defer i.Close(ctx)

	th := utils.FirmwareTestingHelper{FirmwareTestingHelperDelegate: s}

	s.Log("Restarting ti50 with SPI straps")
	b.ResetAndTpmStartupForBus(ctx, i, ti50.TpmBusSpi, ti50.CCDModeOff, ti50.FfClamshell)

	s.Log("Starting TCG tests")
	testSuite := s.Param().(string)

	err := b.RunTcgTests(ctx, s.OutDir(), testSuite)

	// The test starts with a GSC power-on reset. If sysinfo shows GSC did a
	// hard reset, that means GSC crashed during the test.
	sysinfo, sysinfoErr := i.Sysinfo(ctx)
	if sysinfoErr != nil {
		s.Error("Failed to get sysinfo", sysinfoErr)
	} else if sysinfo.ResetFlags&ti50.GscResetFlagHard != 0 {
		s.Error("GSC crashed during test")
	}

	th.MustSucceed(err, "Tests failed.")
}
