// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package gscdevboard

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/common/firmware/ti50"
	"go.chromium.org/tast-tests/cros/remote/bundles/cros/gscdevboard/utils"
	"go.chromium.org/tast-tests/cros/remote/firmware/ti50/fixture"

	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:    Ti50Tcg,
		Desc:    "Run TCG Compliance tests against a remote Ti50",
		Timeout: 30 * time.Minute,
		Contacts: []string{
			"chromeos-faft@google.com", // CrOS Firmware Developers
			"granaghan@google.com",     // Test Author
		},
		BugComponent: "b:715469", // ChromeOS > Platform > System > Hardware Security > HwSec GSC > Ti50
		Attr:         []string{"group:gsc", "gsc_dt_ab", "gsc_image_ti50"},
		Fixture:      fixture.Ti50CcdOpen,
		Params: []testing.Param{{
			Name: "niap_policy_test",
			Val:  "NiapPolicyTest",
		}, {
			Name: "policy_pcr_multi_branch",
			Val:  "PolicyPCRMultiBranch",
		}, {
			Name: "se__test_data_at_rest",
			Val:  "SE_TestDataAtRest",
		}, {
			Name: "se__test_data_at_rest2",
			Val:  "SE_TestDataAtRest2",
		}, {
			Name: "se__test_data_at_rest3",
			Val:  "SE_TestDataAtRest3",
		}, {
			Name: "se__test_simulated_smart_card",
			Val:  "SE_TestSimulatedSmartCard",
		}, {
			Name: "test_act",
			Val:  "TestAct",
		}, {
			Name: "test_activate",
			Val:  "TestActivate",
		}, {
			Name: "test_activate_aik",
			Val:  "TestActivateAik",
		}, {
			Name: "test_activate_ecdh",
			Val:  "TestActivateEcdh",
		}, {
			Name: "test_activate_hmac",
			Val:  "TestActivateHmac",
		}, {
			Name: "test_activate_make_credential",
			Val:  "TestActivateMakeCredential",
		}, {
			Name: "test_activate_make_credential_ecc",
			Val:  "TestActivateMakeCredentialEcc",
		}, {
			Name: "test_audit",
			Val:  "TestAudit",
		}, {
			Name: "test_audit2",
			Val:  "TestAudit2",
		}, {
			Name: "test_audit_coverage",
			Val:  "TestAuditCoverage",
		}, {
			Name: "test_auth_clear_behavior",
			Val:  "TestAuthClearBehavior",
		}, {
			Name: "test_auth_dec_session",
			Val:  "TestAuthDecSession",
		}, {
			Name: "test_auth_enc_dec_session",
			Val:  "TestAuthEncDecSession",
		}, {
			Name: "test_auth_state_behavior",
			Val:  "TestAuthStateBehavior",
		}, {
			Name: "test_automatic_auth",
			Val:  "TestAutomaticAuth",
		}, {
			Name: "test_bad_handles",
			Val:  "TestBadHandles",
		}, {
			Name: "test_bad_policy_sessions",
			Val:  "TestBadPolicySessions",
		}, {
			Name: "test_bad_sessions",
			Val:  "TestBadSessions",
		}, {
			Name: "test_bogus_hash_ticket",
			Val:  "TestBogusHashTicket",
		}, {
			Name: "test_bound_audit_session",
			Val:  "TestBoundAuditSession",
		}, {
			Name: "test_bound_auth_enc_dec_session",
			Val:  "TestBoundAuthEncDecSession",
		}, {
			Name: "test_cancel",
			Val:  "TestCancel",
		}, {
			Name: "test_capability_handles",
			Val:  "TestCapabilityHandles",
		}, {
			Name: "test_certify_creation",
			Val:  "TestCertifyCreation",
		}, {
			Name: "test_certify_creation_primary",
			Val:  "TestCertifyCreationPrimary",
		}, {
			Name: "test_certify_key",
			Val:  "TestCertifyKey",
		}, {
			Name: "test_certify_key_without_nv__certify",
			Val:  "TestCertifyKeyWithoutNv_Certify",
		}, {
			Name: "test_certify_x509",
			Val:  "TestCertifyX509",
		}, {
			Name: "test_clear",
			Val:  "TestClear",
		}, {
			Name: "test_clock",
			Val:  "TestClock",
		}, {
			Name: "test_clock_rate",
			Val:  "TestClockRate",
		}, {
			Name: "test_cmac",
			Val:  "TestCmac",
		}, {
			Name: "test_cmac_kat",
			Val:  "TestCmacKAT",
		}, {
			Name: "test_commit",
			Val:  "TestCommit",
		}, {
			Name: "test_context_clear",
			Val:  "TestContextClear",
		}, {
			Name: "test_context_load",
			Val:  "TestContextLoad",
		}, {
			Name: "test_context_load_save",
			Val:  "TestContextLoadSave",
		}, {
			Name: "test_context_load_save_sequences",
			Val:  "TestContextLoadSaveSequences",
		}, {
			Name: "test_context_save",
			Val:  "TestContextSave",
		}, {
			Name: "test_continue_session_attr",
			Val:  "TestContinueSessionAttr",
		}, {
			Name: "test_create_ecc_primary",
			Val:  "TestCreateEccPrimary",
		}, {
			Name: "test_create_errors",
			Val:  "TestCreateErrors",
		}, {
			Name: "test_create_loaded",
			Val:  "TestCreateLoaded",
		}, {
			Name: "test_create_primary_faults",
			Val:  "TestCreatePrimaryFaults",
		}, {
			Name: "test_create_sign_ecdsa",
			Val:  "TestCreateSignEcdsa",
		}, {
			Name: "test_create_sign_quote",
			Val:  "TestCreateSignQuote",
		}, {
			Name: "test_da_exemption",
			Val:  "TestDAExemption",
		}, {
			Name: "test_da_logic",
			Val:  "TestDALogic",
		}, {
			Name: "test_derivation_katsha1",
			Val:  "TestDerivationKATSHA1",
		}, {
			Name: "test_derivation_katsha256",
			Val:  "TestDerivationKATSHA256",
		}, {
			Name: "test_derivation_katsha384",
			Val:  "TestDerivationKATSHA384",
		}, {
			Name: "test_derivation_parent",
			Val:  "TestDerivationParent",
		}, {
			Name: "test_drtm",
			Val:  "TestDrtm",
		}, {
			Name: "test_duplicate_errors",
			Val:  "TestDuplicateErrors",
		}, {
			Name: "test_duplicate_import",
			Val:  "TestDuplicateImport",
		}, {
			Name: "test_duplicate_import__all_non_rsa_objects",
			Val:  "TestDuplicateImport_AllNonRsaObjects",
		}, {
			Name: "test_duplicate_import__all_objects",
			Val:  "TestDuplicateImport_AllObjects",
		}, {
			Name: "test_duplicate_import__basic",
			Val:  "TestDuplicateImport_Basic",
		}, {
			Name: "test_ecc",
			Val:  "TestEcc",
		}, {
			Name: "test_ecc_encrypt_decrypt",
			Val:  "TestEccEncryptDecrypt",
		}, {
			Name: "test_ecc_sig",
			Val:  "TestEccSig",
		}, {
			Name: "test_ecc_sig2",
			Val:  "TestEccSig2",
		}, {
			Name: "test_ecdaa_coverage",
			Val:  "TestEcdaaCoverage",
		}, {
			Name: "test_ecdaa_sign",
			Val:  "TestEcdaaSign",
		}, {
			Name: "test_ec_schnorr_coverage",
			Val:  "TestEcSchnorrCoverage",
		}, {
			Name: "test_empty_sensitive",
			Val:  "TestEmptySensitive",
		}, {
			Name: "test_encrypt_decrypt",
			Val:  "TestEncryptDecrypt",
		}, {
			Name: "test_encrypt_decrypt2",
			Val:  "TestEncryptDecrypt2",
		}, {
			Name: "test_encrypt_decrypt_errors",
			Val:  "TestEncryptDecryptErrors",
		}, {
			Name: "test_error_reporting",
			Val:  "TestErrorReporting",
		}, {
			Name: "test_event_sequence",
			Val:  "TestEventSequence",
		}, {
			Name: "test_evict_control",
			Val:  "TestEvictControl",
		}, {
			Name: "test_evict_control_hash_sequence",
			Val:  "TestEvictControlHashSequence",
		}, {
			Name: "test_evict_control_transient",
			Val:  "TestEvictControlTransient",
		}, {
			Name: "test_export_attribs",
			Val:  "TestExportAttribs",
		}, {
			Name: "test_external_key_import",
			Val:  "TestExternalKeyImport",
		}, {
			Name: "test_failure_mode",
			Val:  "TestFailureMode",
		}, {
			Name: "test_firmware_read",
			Val:  "TestFirmwareRead",
		}, {
			Name: "test_gen_new_symm",
			Val:  "TestGenNewSymm",
		}, {
			Name: "test_get_capability_context",
			Val:  "TestGetCapabilityContext",
		}, {
			Name: "test_get_capability_pcr",
			Val:  "TestGetCapabilityPCR",
		}, {
			Name: "test_get_cap_auth_policies",
			Val:  "TestGetCapAuthPolicies",
		}, {
			Name: "test_get_cap_commands",
			Val:  "TestGetCapCommands",
		}, {
			Name: "test_get_cap_coverage",
			Val:  "TestGetCapCoverage",
		}, {
			Name: "test_get_random",
			Val:  "TestGetRandom",
		}, {
			Name: "test_get_test_results",
			Val:  "TestGetTestResults",
		}, {
			Name: "test_get_time",
			Val:  "TestGetTime",
		}, {
			Name: "test_gratuitous_auth",
			Val:  "TestGratuitousAuth",
		}, {
			Name: "test_hash",
			Val:  "TestHash",
		}, {
			Name: "test_hash2",
			Val:  "TestHash2",
		}, {
			Name: "test_hash_seq",
			Val:  "TestHashSeq",
		}, {
			Name: "test_hash_tickets",
			Val:  "TestHashTickets",
		}, {
			Name: "test_hierarchy",
			Val:  "TestHierarchy",
		}, {
			Name: "test_hierarchy_control",
			Val:  "TestHierarchyControl",
		}, {
			Name: "test_hierarchy_control_owner_access",
			Val:  "TestHierarchyControlOwnerAccess",
		}, {
			Name: "test_hierarchy_control_platform_access",
			Val:  "TestHierarchyControlPlatformAccess",
		}, {
			Name: "test_hierarchy_control_resource_management",
			Val:  "TestHierarchyControlResourceManagement",
		}, {
			Name: "test_hmac",
			Val:  "TestHmac",
		}, {
			Name: "test_hmac2",
			Val:  "TestHmac2",
		}, {
			Name: "test_hmac_errors",
			Val:  "TestHmacErrors",
		}, {
			Name: "test_hmac_pub_priv_mismatch",
			Val:  "TestHmacPubPrivMismatch",
		}, {
			Name: "test_hmac_quote",
			Val:  "TestHmacQuote",
		}, {
			Name: "test_hmac_session",
			Val:  "TestHmacSession",
		}, {
			Name: "test_hmac_session2",
			Val:  "TestHmacSession2",
		}, {
			Name: "test_hmac_signing",
			Val:  "TestHmacSigning",
		}, {
			Name: "test_import",
			Val:  "TestImport",
		}, {
			Name: "test_import_data_object",
			Val:  "TestImportDataObject",
		}, {
			Name: "test_import_ecdh",
			Val:  "TestImportEcdh",
		}, {
			Name: "test_import_export",
			Val:  "TestImportExport",
		}, {
			Name: "test_import_export_duplication_select",
			Val:  "TestImportExportDuplicationSelect",
		}, {
			Name: "test_incremental_self_test",
			Val:  "TestIncrementalSelfTest",
		}, {
			Name: "test_inner_wrapper_dup",
			Val:  "TestInnerWrapperDup",
		}, {
			Name: "test_key_creation",
			Val:  "TestKeyCreation",
		}, {
			Name: "test_key_gen",
			Val:  "TestKeyGen",
		}, {
			Name: "test_load_errors",
			Val:  "TestLoadErrors",
		}, {
			Name: "test_lockout_policy_auth",
			Val:  "TestLockoutPolicyAuth",
		}, {
			Name: "test_normalized_policies",
			Val:  "TestNormalizedPolicies",
		}, {
			Name: "test_nv",
			Val:  "TestNv",
		}, {
			Name: "test_nv2",
			Val:  "TestNv2",
		}, {
			Name: "test_nv3",
			Val:  "TestNv3",
		}, {
			Name: "test_nv_counter",
			Val:  "TestNvCounter",
		}, {
			Name: "test_nv_counter2",
			Val:  "TestNvCounter2",
		}, {
			Name: "test_nv_define_space",
			Val:  "TestNvDefineSpace",
		}, {
			Name: "test_nv_extend",
			Val:  "TestNvExtend",
		}, {
			Name: "test_nv_global_write_lock",
			Val:  "TestNvGlobalWriteLock",
		}, {
			Name: "test_nv_not_avail",
			Val:  "TestNvNotAvail",
		}, {
			Name: "test_nv_orderly_counter",
			Val:  "TestNvOrderlyCounter",
		}, {
			Name: "test_nv_owner_clear",
			Val:  "TestNvOwnerClear",
		}, {
			Name: "test_nv_partial_write",
			Val:  "TestNvPartialWrite",
		}, {
			Name: "test_nv_persistence",
			Val:  "TestNvPersistence",
		}, {
			Name: "test_nv_set_bits",
			Val:  "TestNvSetBits",
		}, {
			Name: "test_nv_stress",
			Val:  "TestNvStress",
		}, {
			Name: "test_nv_with_policy",
			Val:  "TestNvWithPolicy",
		}, {
			Name: "test_object_change_auth",
			Val:  "TestObjectChangeAuth",
		}, {
			Name: "test_patch_410162",
			Val:  "TestPatch_410162",
		}, {
			Name: "test_patch_411165",
			Val:  "TestPatch_411165",
		}, {
			Name: "test_patch__r88_336067",
			Val:  "TestPatch_R88_336067",
		}, {
			Name: "test_patch__r88_374194",
			Val:  "TestPatch_R88_374194",
		}, {
			Name: "test_patch__r88_391785",
			Val:  "TestPatch_R88_391785",
		}, {
			Name: "test_patch__r88_392304",
			Val:  "TestPatch_R88_392304",
		}, {
			Name: "test_patch__r88_398735",
			Val:  "TestPatch_R88_398735",
		}, {
			Name: "test_patch__r88_405740",
			Val:  "TestPatch_R88_405740",
		}, {
			Name: "test_patch__r88_898154",
			Val:  "TestPatch_R88_898154",
		}, {
			Name: "test_pcr1",
			Val:  "TestPcr1",
		}, {
			Name: "test_pcr_auth",
			Val:  "TestPcrAuth",
		}, {
			Name: "test_pcr_extend",
			Val:  "TestPCRExtend",
		}, {
			Name: "test_pcr_extend_all_localities",
			Val:  "TestPCRExtendAllLocalities",
		}, {
			Name: "test_pcr_locality",
			Val:  "TestPCRLocality",
		}, {
			Name: "test_pcr_reset",
			Val:  "TestPCRReset",
		}, {
			Name: "test_persistent_transient_object",
			Val:  "TestPersistentTransientObject",
		}, {
			Name: "test_physical_presence",
			Val:  "TestPhysicalPresence",
		}, {
			Name: "test_pin",
			Val:  "TestPin",
		}, {
			Name: "test_plaintext_import_export",
			Val:  "TestPlaintextImportExport",
		}, {
			Name: "test_policy",
			Val:  "TestPolicy",
		}, {
			Name: "test_policy1",
			Val:  "TestPolicy1",
		}, {
			Name: "test_policy3",
			Val:  "TestPolicy3",
		}, {
			Name: "test_policy4_1",
			Val:  "TestPolicy4_1",
		}, {
			Name: "test_policy4_10",
			Val:  "TestPolicy4_10",
		}, {
			Name: "test_policy4_11",
			Val:  "TestPolicy4_11",
		}, {
			Name: "test_policy4_12",
			Val:  "TestPolicy4_12",
		}, {
			Name: "test_policy4_13",
			Val:  "TestPolicy4_13",
		}, {
			Name: "test_policy4_14",
			Val:  "TestPolicy4_14",
		}, {
			Name: "test_policy4_2",
			Val:  "TestPolicy4_2",
		}, {
			Name: "test_policy4_3",
			Val:  "TestPolicy4_3",
		}, {
			Name: "test_policy4_4",
			Val:  "TestPolicy4_4",
		}, {
			Name: "test_policy4_5",
			Val:  "TestPolicy4_5",
		}, {
			Name: "test_policy4_6",
			Val:  "TestPolicy4_6",
		}, {
			Name: "test_policy4_7",
			Val:  "TestPolicy4_7",
		}, {
			Name: "test_policy4_8",
			Val:  "TestPolicy4_8",
		}, {
			Name: "test_policy4_9",
			Val:  "TestPolicy4_9",
		}, {
			Name: "test_policy5",
			Val:  "TestPolicy5",
		}, {
			Name: "test_policy_auth",
			Val:  "TestPolicyAuth",
		}, {
			Name: "test_policy_auth_bound",
			Val:  "TestPolicyAuthBound",
		}, {
			Name: "test_policy_auth_bound_da",
			Val:  "TestPolicyAuthBoundDA",
		}, {
			Name: "test_policy_auth_branches",
			Val:  "TestPolicyAuthBranches",
		}, {
			Name: "test_policy_authorize",
			Val:  "TestPolicyAuthorize",
		}, {
			Name: "test_policy_authorize_nv",
			Val:  "TestPolicyAuthorizeNV",
		}, {
			Name: "test_policy_capability_digest",
			Val:  "TestPolicyCapabilityDigest",
		}, {
			Name: "test_policy_counter_timer",
			Val:  "TestPolicyCounterTimer",
		}, {
			Name: "test_policy_counter_timer2",
			Val:  "TestPolicyCounterTimer2",
		}, {
			Name: "test_policy_counter_timer_offset",
			Val:  "TestPolicyCounterTimerOffset",
		}, {
			Name: "test_policy_name_hash",
			Val:  "TestPolicyNameHash",
		}, {
			Name: "test_policy_nv",
			Val:  "TestPolicyNv",
		}, {
			Name: "test_policy_nv_offset",
			Val:  "TestPolicyNvOffset",
		}, {
			Name: "test_policy_nv_written",
			Val:  "TestPolicyNvWritten",
		}, {
			Name: "test_policy_parameters_digest",
			Val:  "TestPolicyParametersDigest",
		}, {
			Name: "test_policy_pcr",
			Val:  "TestPolicyPCR",
		}, {
			Name: "test_policy_pcr2",
			Val:  "TestPolicyPCR2",
		}, {
			Name: "test_policy_pcr_bad_input",
			Val:  "TestPolicyPCRBadInput",
		}, {
			Name: "test_policy_pcr_raw_commands",
			Val:  "TestPolicyPCRRawCommands",
		}, {
			Name: "test_policy_physical_presence",
			Val:  "TestPolicyPhysicalPresence",
		}, {
			Name: "test_policy_secret",
			Val:  "TestPolicySecret",
		}, {
			Name: "test_policy_secret_bad_auth",
			Val:  "TestPolicySecretBadAuth",
		}, {
			Name: "test_policy_secret_errors",
			Val:  "TestPolicySecretErrors",
		}, {
			Name: "test_policy_signed",
			Val:  "TestPolicySigned",
		}, {
			Name: "test_policy_template",
			Val:  "TestPolicyTemplate",
		}, {
			Name: "test_public_private_mismatch_ecc",
			Val:  "TestPublicPrivateMismatchEcc",
		}, {
			Name: "test_public_private_mismatch_rsa",
			Val:  "TestPublicPrivateMismatchRsa",
		}, {
			Name: "test_public_private_mismatch_sym",
			Val:  "TestPublicPrivateMismatchSym",
		}, {
			Name: "test_pub_only_bind_object",
			Val:  "TestPubOnlyBindObject",
		}, {
			Name: "test_random",
			Val:  "TestRandom",
		}, {
			Name: "test_raw_certify_creation",
			Val:  "TestRawCertifyCreation",
		}, {
			Name: "test_raw_nv_change_auth",
			Val:  "TestRawNVChangeAuth",
		}, {
			Name: "test_raw_nv_define_space",
			Val:  "TestRawNVDefineSpace",
		}, {
			Name: "test_raw_nv_increment",
			Val:  "TestRawNVIncrement",
		}, {
			Name: "test_raw_nv_read",
			Val:  "TestRawNVRead",
		}, {
			Name: "test_raw_nv_read_lock",
			Val:  "TestRawNVReadLock",
		}, {
			Name: "test_raw_nv_read_public",
			Val:  "TestRawNVReadPublic",
		}, {
			Name: "test_raw_nv_undefine_space",
			Val:  "TestRawNVUndefineSpace",
		}, {
			Name: "test_raw_nv_write",
			Val:  "TestRawNVWrite",
		}, {
			Name: "test_raw_nv_write_lock",
			Val:  "TestRawNVWriteLock",
		}, {
			Name: "test_raw_sign",
			Val:  "TestRawSign",
		}, {
			Name: "test_reserved_bits",
			Val:  "TestReservedBits",
		}, {
			Name: "test_rewrap",
			Val:  "TestRewrap",
		}, {
			Name: "test_rsa_crypto",
			Val:  "TestRsaCrypto",
		}, {
			Name: "test_rsa_dp_ep",
			Val:  "TestRsaDpEp",
		}, {
			Name: "test_rsa_dp_ep2",
			Val:  "TestRsaDpEp2",
		}, {
			Name: "test_rsaes",
			Val:  "TestRsaes",
		}, {
			Name: "test_rsa_exponents",
			Val:  "TestRsaExponents",
		}, {
			Name: "test_rsa_extrema",
			Val:  "TestRsaExtrema",
		}, {
			Name: "test_rsa_sign_pss",
			Val:  "TestRsaSignPss",
		}, {
			Name: "test_salted_auth_session_errors",
			Val:  "TestSaltedAuthSessionErrors",
		}, {
			Name: "test_salted_auth_session_sym",
			Val:  "TestSaltedAuthSessionSym",
		}, {
			Name: "test_salted_auth_session_xor",
			Val:  "TestSaltedAuthSessionXor",
		}, {
			Name: "test_salted_bound_auth_session",
			Val:  "TestSaltedBoundAuthSession",
		}, {
			Name: "test_seal_unseal",
			Val:  "TestSealUnseal",
		}, {
			Name: "test_seal_unseal_persisted_object",
			Val:  "TestSealUnsealPersistedObject",
		}, {
			Name: "test_self_test",
			Val:  "TestSelfTest",
		}, {
			Name: "test_serialization",
			Val:  "TestSerialization",
		}, {
			Name: "test_server_created_child",
			Val:  "TestServerCreatedChild",
		}, {
			Name: "test_session_context",
			Val:  "TestSessionContext",
		}, {
			Name: "test_session_context_gap",
			Val:  "TestSessionContextGap",
		}, {
			Name: "test_session_context_no_replay",
			Val:  "TestSessionContextNoReplay",
		}, {
			Name: "test_session_ctx_lifetime",
			Val:  "TestSessionCtxLifetime",
		}, {
			Name: "test_session_encryption",
			Val:  "TestSessionEncryption",
		}, {
			Name: "test_session_encryption_other_algs",
			Val:  "TestSessionEncryptionOtherAlgs",
		}, {
			Name: "test_session_errors",
			Val:  "TestSessionErrors",
		}, {
			Name: "test_session_lifetime",
			Val:  "TestSessionLifetime",
		}, {
			Name: "test_sign",
			Val:  "TestSign",
		}, {
			Name: "test_sign_object_attributes",
			Val:  "TestSignObjectAttributes",
		}, {
			Name: "test_sign_restricted",
			Val:  "TestSignRestricted",
		}, {
			Name: "test_sign_sm2dsa",
			Val:  "TestSignSm2dsa",
		}, {
			Name: "test_sign_verify",
			Val:  "TestSignVerify",
		}, {
			Name: "test_simple_duplicate_import",
			Val:  "TestSimpleDuplicateImport",
		}, {
			Name: "test_simple_duplicate_import_rsa",
			Val:  "TestSimpleDuplicateImportRsa",
		}, {
			Name: "test_simple_sign",
			Val:  "TestSimpleSign",
		}, {
			Name: "test_sm2_encrypt_decrypt",
			Val:  "TestSm2EncryptDecrypt",
		}, {
			Name: "test_sm4",
			Val:  "TestSm4",
		}, {
			Name: "test_start_auth_session_bound",
			Val:  "TestStartAuthSessionBound",
		}, {
			Name: "test_start_auth_session_hmac",
			Val:  "TestStartAuthSessionHMAC",
		}, {
			Name: "test_start_auth_session_max_session",
			Val:  "TestStartAuthSessionMaxSession",
		}, {
			Name: "test_start_auth_session_policy",
			Val:  "TestStartAuthSessionPolicy",
		}, {
			Name: "test_start_auth_session_seed",
			Val:  "TestStartAuthSessionSeed",
		}, {
			Name: "test_startup_faults",
			Val:  "TestStartupFaults",
		}, {
			Name: "test_startup_idempotence",
			Val:  "TestStartupIdempotence",
		}, {
			Name: "test_startup_locality",
			Val:  "TestStartupLocality",
		}, {
			Name: "test_startup_locality_hcrtm",
			Val:  "TestStartupLocalityHCRTM",
		}, {
			Name: "test_stir_random",
			Val:  "TestStirRandom",
		}, {
			Name: "test_sw_signing",
			Val:  "TestSWSigning",
		}, {
			Name: "test_sym_parent",
			Val:  "TestSymParent",
		}, {
			Name: "test_sym_primary",
			Val:  "TestSymPrimary",
		}, {
			Name: "test_temporary_object",
			Val:  "TestTemporaryObject",
		}, {
			Name: "test_test_parms",
			Val:  "TestTestParms",
		}, {
			Name: "test_tpm_state_portability_phase1",
			Val:  "TestTpmStatePortabilityPhase1",
		}, {
			Name: "test_tpm_state_portability_phase2",
			Val:  "TestTpmStatePortabilityPhase2",
		}, {
			Name: "test_trial_policy",
			Val:  "TestTrialPolicy",
		}, {
			Name: "test_undefine_space_special",
			Val:  "TestUndefineSpaceSpecial",
		}, {
			Name: "test_unorderly_da",
			Val:  "TestUnorderlyDA",
		}, {
			Name: "test_vendor_specific",
			Val:  "TestVendorSpecific",
		}, {
			Name: "test_z_gen2_phase",
			Val:  "TestZGen2Phase",
		},
		},
	})
}

func Ti50Tcg(ctx context.Context, s *testing.State) {
	f := s.FixtValue().(*fixture.Value)

	b := utils.NewDevboardHelper(f.DevBoard(), s)
	i := ti50.NewCrOSImage(b)

	th := utils.FirmwareTestingHelper{FirmwareTestingHelperDelegate: s}

	s.Log("Restarting ti50 with SPI straps")
	b.GpioApplyStrap(ctx, ti50.TpmSpi)
	th.MustSucceed(b.Reset(ctx), "Reset board")
	th.MustSucceed(i.WaitUntilBooted(ctx), "Ti50 revives after reboot")

	// Tell Ti50 that the AP came out of reset.  This will cause Ti50 to start responding to
	// TPM commands.
	b.GpioSet(ctx, ti50.GpioTi50PltRstL, true)

	s.Log("Starting TCG tests")
	testSuite := s.Param().(string)
	th.MustSucceed(b.RunTcgTests(ctx, s.OutDir(), testSuite), "Tests failed.")
}
