// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: service.proto

package typec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The service modifies the device policy while logging in to enable peripheral data access. In order to do
// this, we need to send the file path of a stub test service private key which is required by session_manager
// to store the modified policy (and which should be copied over to the target device by the test code).
type KeyPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SetMode     bool   `protobuf:"varint,2,opt,name=setMode,proto3" json:"setMode,omitempty"`
	DisplayInfo int64  `protobuf:"varint,3,opt,name=displayInfo,proto3" json:"displayInfo,omitempty"`
	AudioNode   string `protobuf:"bytes,4,opt,name=audioNode,proto3" json:"audioNode,omitempty"`
}

func (x *KeyPath) Reset() {
	*x = KeyPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPath) ProtoMessage() {}

func (x *KeyPath) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPath.ProtoReflect.Descriptor instead.
func (*KeyPath) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *KeyPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KeyPath) GetSetMode() bool {
	if x != nil {
		return x.SetMode
	}
	return false
}

func (x *KeyPath) GetDisplayInfo() int64 {
	if x != nil {
		return x.DisplayInfo
	}
	return 0
}

func (x *KeyPath) GetAudioNode() string {
	if x != nil {
		return x.AudioNode
	}
	return ""
}

type TypecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadsPath string `protobuf:"bytes,1,opt,name=DownloadsPath,proto3" json:"DownloadsPath,omitempty"`
	Info          string `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	DeviceName    string `protobuf:"bytes,3,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	DeviceType    string `protobuf:"bytes,4,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	DisplayName   string `protobuf:"bytes,5,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
}

func (x *TypecResponse) Reset() {
	*x = TypecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypecResponse) ProtoMessage() {}

func (x *TypecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypecResponse.ProtoReflect.Descriptor instead.
func (*TypecResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *TypecResponse) GetDownloadsPath() string {
	if x != nil {
		return x.DownloadsPath
	}
	return ""
}

func (x *TypecResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *TypecResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *TypecResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *TypecResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a,
	0x07, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0d, 0x54, 0x79, 0x70, 0x65, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x73, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x32, 0xfc, 0x08, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5c, 0x0a, 0x26, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73,
	0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79,
	0x50, 0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4a,
	0x0a, 0x14, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72,
	0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x15, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4f, 0x6e, 0x44, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x74,
	0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x50,
	0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72,
	0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x2e, 0x74, 0x61,
	0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65,
	0x79, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x45, 0x64, 0x70, 0x50, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x79, 0x55, 0x49, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x73,
	0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79,
	0x50, 0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e,
	0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e,
	0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63,
	0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x1d, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x43, 0x72, 0x61, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x72, 0x6f, 0x6d,
	0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x19, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x61, 0x73, 0x74, 0x2d, 0x74, 0x65, 0x73, 0x74,
	0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x63, 0x72, 0x6f, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []interface{}{
	(*KeyPath)(nil),       // 0: tast.cros.typec.KeyPath
	(*TypecResponse)(nil), // 1: tast.cros.typec.TypecResponse
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: tast.cros.typec.Service.NewChromeLoginWithPeripheralDataAccess:input_type -> tast.cros.typec.KeyPath
	0,  // 1: tast.cros.typec.Service.SetMirrorModeDisplay:input_type -> tast.cros.typec.KeyPath
	0,  // 2: tast.cros.typec.Service.VerifyWindowOnDisplay:input_type -> tast.cros.typec.KeyPath
	0,  // 3: tast.cros.typec.Service.PlayLocalVideo:input_type -> tast.cros.typec.KeyPath
	2,  // 4: tast.cros.typec.Service.DownloadsPath:input_type -> google.protobuf.Empty
	2,  // 5: tast.cros.typec.Service.VerifyMirrorMode:input_type -> google.protobuf.Empty
	0,  // 6: tast.cros.typec.Service.PlayVideo:input_type -> tast.cros.typec.KeyPath
	2,  // 7: tast.cros.typec.Service.VerifyEdpPrimary:input_type -> google.protobuf.Empty
	0,  // 8: tast.cros.typec.Service.SetActiveNodeByUI:input_type -> tast.cros.typec.KeyPath
	0,  // 9: tast.cros.typec.Service.DisplayName:input_type -> tast.cros.typec.KeyPath
	2,  // 10: tast.cros.typec.Service.AudioCrasSelectedOutputDevice:input_type -> google.protobuf.Empty
	0,  // 11: tast.cros.typec.Service.VerifyFirstRunningDevice:input_type -> tast.cros.typec.KeyPath
	2,  // 12: tast.cros.typec.Service.NewChromeLogin:input_type -> google.protobuf.Empty
	2,  // 13: tast.cros.typec.Service.ReconnectChromeConnection:input_type -> google.protobuf.Empty
	2,  // 14: tast.cros.typec.Service.NewConnectionForTarget:input_type -> google.protobuf.Empty
	2,  // 15: tast.cros.typec.Service.NewChromeLoginWithPeripheralDataAccess:output_type -> google.protobuf.Empty
	2,  // 16: tast.cros.typec.Service.SetMirrorModeDisplay:output_type -> google.protobuf.Empty
	2,  // 17: tast.cros.typec.Service.VerifyWindowOnDisplay:output_type -> google.protobuf.Empty
	2,  // 18: tast.cros.typec.Service.PlayLocalVideo:output_type -> google.protobuf.Empty
	1,  // 19: tast.cros.typec.Service.DownloadsPath:output_type -> tast.cros.typec.TypecResponse
	2,  // 20: tast.cros.typec.Service.VerifyMirrorMode:output_type -> google.protobuf.Empty
	2,  // 21: tast.cros.typec.Service.PlayVideo:output_type -> google.protobuf.Empty
	2,  // 22: tast.cros.typec.Service.VerifyEdpPrimary:output_type -> google.protobuf.Empty
	2,  // 23: tast.cros.typec.Service.SetActiveNodeByUI:output_type -> google.protobuf.Empty
	1,  // 24: tast.cros.typec.Service.DisplayName:output_type -> tast.cros.typec.TypecResponse
	1,  // 25: tast.cros.typec.Service.AudioCrasSelectedOutputDevice:output_type -> tast.cros.typec.TypecResponse
	2,  // 26: tast.cros.typec.Service.VerifyFirstRunningDevice:output_type -> google.protobuf.Empty
	2,  // 27: tast.cros.typec.Service.NewChromeLogin:output_type -> google.protobuf.Empty
	2,  // 28: tast.cros.typec.Service.ReconnectChromeConnection:output_type -> google.protobuf.Empty
	2,  // 29: tast.cros.typec.Service.NewConnectionForTarget:output_type -> google.protobuf.Empty
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	NewChromeLoginWithPeripheralDataAccess(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetMirrorModeDisplay(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VerifyWindowOnDisplay(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PlayLocalVideo(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DownloadsPath(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TypecResponse, error)
	VerifyMirrorMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PlayVideo(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VerifyEdpPrimary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetActiveNodeByUI(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DisplayName(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*TypecResponse, error)
	AudioCrasSelectedOutputDevice(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TypecResponse, error)
	VerifyFirstRunningDevice(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewChromeLogin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReconnectChromeConnection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewConnectionForTarget(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) NewChromeLoginWithPeripheralDataAccess(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/NewChromeLoginWithPeripheralDataAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetMirrorModeDisplay(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/SetMirrorModeDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) VerifyWindowOnDisplay(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/VerifyWindowOnDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) PlayLocalVideo(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/PlayLocalVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DownloadsPath(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TypecResponse, error) {
	out := new(TypecResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/DownloadsPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) VerifyMirrorMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/VerifyMirrorMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) PlayVideo(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/PlayVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) VerifyEdpPrimary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/VerifyEdpPrimary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetActiveNodeByUI(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/SetActiveNodeByUI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DisplayName(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*TypecResponse, error) {
	out := new(TypecResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/DisplayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AudioCrasSelectedOutputDevice(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TypecResponse, error) {
	out := new(TypecResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/AudioCrasSelectedOutputDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) VerifyFirstRunningDevice(ctx context.Context, in *KeyPath, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/VerifyFirstRunningDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NewChromeLogin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/NewChromeLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ReconnectChromeConnection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/ReconnectChromeConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NewConnectionForTarget(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.typec.Service/NewConnectionForTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	NewChromeLoginWithPeripheralDataAccess(context.Context, *KeyPath) (*emptypb.Empty, error)
	SetMirrorModeDisplay(context.Context, *KeyPath) (*emptypb.Empty, error)
	VerifyWindowOnDisplay(context.Context, *KeyPath) (*emptypb.Empty, error)
	PlayLocalVideo(context.Context, *KeyPath) (*emptypb.Empty, error)
	DownloadsPath(context.Context, *emptypb.Empty) (*TypecResponse, error)
	VerifyMirrorMode(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PlayVideo(context.Context, *KeyPath) (*emptypb.Empty, error)
	VerifyEdpPrimary(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	SetActiveNodeByUI(context.Context, *KeyPath) (*emptypb.Empty, error)
	DisplayName(context.Context, *KeyPath) (*TypecResponse, error)
	AudioCrasSelectedOutputDevice(context.Context, *emptypb.Empty) (*TypecResponse, error)
	VerifyFirstRunningDevice(context.Context, *KeyPath) (*emptypb.Empty, error)
	NewChromeLogin(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ReconnectChromeConnection(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	NewConnectionForTarget(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) NewChromeLoginWithPeripheralDataAccess(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewChromeLoginWithPeripheralDataAccess not implemented")
}
func (*UnimplementedServiceServer) SetMirrorModeDisplay(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMirrorModeDisplay not implemented")
}
func (*UnimplementedServiceServer) VerifyWindowOnDisplay(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyWindowOnDisplay not implemented")
}
func (*UnimplementedServiceServer) PlayLocalVideo(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayLocalVideo not implemented")
}
func (*UnimplementedServiceServer) DownloadsPath(context.Context, *emptypb.Empty) (*TypecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadsPath not implemented")
}
func (*UnimplementedServiceServer) VerifyMirrorMode(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMirrorMode not implemented")
}
func (*UnimplementedServiceServer) PlayVideo(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayVideo not implemented")
}
func (*UnimplementedServiceServer) VerifyEdpPrimary(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEdpPrimary not implemented")
}
func (*UnimplementedServiceServer) SetActiveNodeByUI(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetActiveNodeByUI not implemented")
}
func (*UnimplementedServiceServer) DisplayName(context.Context, *KeyPath) (*TypecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisplayName not implemented")
}
func (*UnimplementedServiceServer) AudioCrasSelectedOutputDevice(context.Context, *emptypb.Empty) (*TypecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AudioCrasSelectedOutputDevice not implemented")
}
func (*UnimplementedServiceServer) VerifyFirstRunningDevice(context.Context, *KeyPath) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyFirstRunningDevice not implemented")
}
func (*UnimplementedServiceServer) NewChromeLogin(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewChromeLogin not implemented")
}
func (*UnimplementedServiceServer) ReconnectChromeConnection(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconnectChromeConnection not implemented")
}
func (*UnimplementedServiceServer) NewConnectionForTarget(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewConnectionForTarget not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_NewChromeLoginWithPeripheralDataAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NewChromeLoginWithPeripheralDataAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/NewChromeLoginWithPeripheralDataAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NewChromeLoginWithPeripheralDataAccess(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetMirrorModeDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetMirrorModeDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/SetMirrorModeDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetMirrorModeDisplay(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_VerifyWindowOnDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).VerifyWindowOnDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/VerifyWindowOnDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).VerifyWindowOnDisplay(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_PlayLocalVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).PlayLocalVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/PlayLocalVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).PlayLocalVideo(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DownloadsPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DownloadsPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/DownloadsPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DownloadsPath(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_VerifyMirrorMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).VerifyMirrorMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/VerifyMirrorMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).VerifyMirrorMode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_PlayVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).PlayVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/PlayVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).PlayVideo(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_VerifyEdpPrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).VerifyEdpPrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/VerifyEdpPrimary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).VerifyEdpPrimary(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetActiveNodeByUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetActiveNodeByUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/SetActiveNodeByUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetActiveNodeByUI(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/DisplayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DisplayName(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AudioCrasSelectedOutputDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AudioCrasSelectedOutputDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/AudioCrasSelectedOutputDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AudioCrasSelectedOutputDevice(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_VerifyFirstRunningDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).VerifyFirstRunningDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/VerifyFirstRunningDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).VerifyFirstRunningDevice(ctx, req.(*KeyPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NewChromeLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NewChromeLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/NewChromeLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NewChromeLogin(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ReconnectChromeConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ReconnectChromeConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/ReconnectChromeConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ReconnectChromeConnection(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NewConnectionForTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NewConnectionForTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.typec.Service/NewConnectionForTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NewConnectionForTarget(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.typec.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewChromeLoginWithPeripheralDataAccess",
			Handler:    _Service_NewChromeLoginWithPeripheralDataAccess_Handler,
		},
		{
			MethodName: "SetMirrorModeDisplay",
			Handler:    _Service_SetMirrorModeDisplay_Handler,
		},
		{
			MethodName: "VerifyWindowOnDisplay",
			Handler:    _Service_VerifyWindowOnDisplay_Handler,
		},
		{
			MethodName: "PlayLocalVideo",
			Handler:    _Service_PlayLocalVideo_Handler,
		},
		{
			MethodName: "DownloadsPath",
			Handler:    _Service_DownloadsPath_Handler,
		},
		{
			MethodName: "VerifyMirrorMode",
			Handler:    _Service_VerifyMirrorMode_Handler,
		},
		{
			MethodName: "PlayVideo",
			Handler:    _Service_PlayVideo_Handler,
		},
		{
			MethodName: "VerifyEdpPrimary",
			Handler:    _Service_VerifyEdpPrimary_Handler,
		},
		{
			MethodName: "SetActiveNodeByUI",
			Handler:    _Service_SetActiveNodeByUI_Handler,
		},
		{
			MethodName: "DisplayName",
			Handler:    _Service_DisplayName_Handler,
		},
		{
			MethodName: "AudioCrasSelectedOutputDevice",
			Handler:    _Service_AudioCrasSelectedOutputDevice_Handler,
		},
		{
			MethodName: "VerifyFirstRunningDevice",
			Handler:    _Service_VerifyFirstRunningDevice_Handler,
		},
		{
			MethodName: "NewChromeLogin",
			Handler:    _Service_NewChromeLogin_Handler,
		},
		{
			MethodName: "ReconnectChromeConnection",
			Handler:    _Service_ReconnectChromeConnection_Handler,
		},
		{
			MethodName: "NewConnectionForTarget",
			Handler:    _Service_NewConnectionForTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
