// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.arc;

import "google/protobuf/empty.proto";

option go_package = "chromiumos/tast/services/cros/arc";

// DexOptCacheService provides DEX code compilation artifacts.
service DexOptCacheService {
  // Generate generates DEX code compilation artifacts.
  rpc Generate (google.protobuf.Empty) returns (DexOptCacheResponse) {}
}

message DexOptCacheResponse {
  // Path to directory with DexOpt cache.
  string target_dir = 1;
  // Name of the tar file that DEX code compilation artifacts are packed into.
  string dex_opt_cache_name = 2;
}
