// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package input

// EventName provides a human-readable name for the given EventCode.
// If the code is not recognized, it returns a generic string representation.
func EventName(code EventCode) string {
	switch code {
	// Keyboard events
	case 0x0:
		return "KEY_RESERVED"
	case 0x1:
		return "KEY_ESC"
	case 0x2:
		return "KEY_1"
	case 0x3:
		return "KEY_2"
	case 0x4:
		return "KEY_3"
	case 0x5:
		return "KEY_4"
	case 0x6:
		return "KEY_5"
	case 0x7:
		return "KEY_6"
	case 0x8:
		return "KEY_7"
	case 0x9:
		return "KEY_8"
	case 0xa:
		return "KEY_9"
	case 0xb:
		return "KEY_0"
	case 0xc:
		return "KEY_MINUS"
	case 0xd:
		return "KEY_EQUAL"
	case 0xe:
		return "KEY_BACKSPACE"
	case 0xf:
		return "KEY_TAB"
	case 0x10:
		return "KEY_Q"
	case 0x11:
		return "KEY_W"
	case 0x12:
		return "KEY_E"
	case 0x13:
		return "KEY_R"
	case 0x14:
		return "KEY_T"
	case 0x15:
		return "KEY_Y"
	case 0x16:
		return "KEY_U"
	case 0x17:
		return "KEY_I"
	case 0x18:
		return "KEY_O"
	case 0x19:
		return "KEY_P"
	case 0x1a:
		return "KEY_LEFTBRACE"
	case 0x1b:
		return "KEY_RIGHTBRACE"
	case 0x1c:
		return "KEY_ENTER"
	case 0x1d:
		return "KEY_LEFTCTRL"
	case 0x1e:
		return "KEY_A"
	case 0x1f:
		return "KEY_S"
	case 0x20:
		return "KEY_D"
	case 0x21:
		return "KEY_F"
	case 0x22:
		return "KEY_G"
	case 0x23:
		return "KEY_H"
	case 0x24:
		return "KEY_J"
	case 0x25:
		return "KEY_K"
	case 0x26:
		return "KEY_L"
	case 0x27:
		return "KEY_SEMICOLON"
	case 0x28:
		return "KEY_APOSTROPHE"
	case 0x29:
		return "KEY_GRAVE"
	case 0x2a:
		return "KEY_LEFTSHIFT"
	case 0x2b:
		return "KEY_BACKSLASH"
	case 0x2c:
		return "KEY_Z"
	case 0x2d:
		return "KEY_X"
	case 0x2e:
		return "KEY_C"
	case 0x2f:
		return "KEY_V"
	case 0x30:
		return "KEY_B"
	case 0x31:
		return "KEY_N"
	case 0x32:
		return "KEY_M"
	case 0x33:
		return "KEY_COMMA"
	case 0x34:
		return "KEY_DOT"
	case 0x35:
		return "KEY_SLASH"
	case 0x36:
		return "KEY_RIGHTSHIFT"
	case 0x37:
		return "KEY_KPASTERISK"
	case 0x38:
		return "KEY_LEFTALT"
	case 0x39:
		return "KEY_SPACE"
	case 0x3a:
		return "KEY_CAPSLOCK"
	case 0x3b:
		return "KEY_F1"
	case 0x3c:
		return "KEY_F2"
	case 0x3d:
		return "KEY_F3"
	case 0x3e:
		return "KEY_F4"
	case 0x3f:
		return "KEY_F5"
	case 0x40:
		return "KEY_F6"
	case 0x41:
		return "KEY_F7"
	case 0x42:
		return "KEY_F8"
	case 0x43:
		return "KEY_F9"
	case 0x44:
		return "KEY_F10"
	case 0x45:
		return "KEY_NUMLOCK"
	case 0x46:
		return "KEY_SCROLLLOCK"
	case 0x47:
		return "KEY_KP7"
	case 0x48:
		return "KEY_KP8"
	case 0x49:
		return "KEY_KP9"
	case 0x4a:
		return "KEY_KPMINUS"
	case 0x4b:
		return "KEY_KP4"
	case 0x4c:
		return "KEY_KP5"
	case 0x4d:
		return "KEY_KP6"
	case 0x4e:
		return "KEY_KPPLUS"
	case 0x4f:
		return "KEY_KP1"
	case 0x50:
		return "KEY_KP2"
	case 0x51:
		return "KEY_KP3"
	case 0x52:
		return "KEY_KP0"
	case 0x53:
		return "KEY_KPDOT"
	case 0x55:
		return "KEY_ZENKAKUHANKAKU"
	case 0x56:
		return "KEY_102ND"
	case 0x57:
		return "KEY_F11"
	case 0x58:
		return "KEY_F12"
	case 0x59:
		return "KEY_RO"
	case 0x5a:
		return "KEY_KATAKANA"
	case 0x5b:
		return "KEY_HIRAGANA"
	case 0x5c:
		return "KEY_HENKAN"
	case 0x5d:
		return "KEY_KATAKANAHIRAGANA"
	case 0x5e:
		return "KEY_MUHENKAN"
	case 0x5f:
		return "KEY_KPJPCOMMA"
	case 0x60:
		return "KEY_KPENTER"
	case 0x61:
		return "KEY_RIGHTCTRL"
	case 0x62:
		return "KEY_KPSLASH"
	case 0x63:
		return "KEY_SYSRQ"
	case 0x64:
		return "KEY_RIGHTALT"
	case 0x65:
		return "KEY_LINEFEED"
	case 0x66:
		return "KEY_HOME"
	case 0x67:
		return "KEY_UP"
	case 0x68:
		return "KEY_PAGEUP"
	case 0x69:
		return "KEY_LEFT"
	case 0x6a:
		return "KEY_RIGHT"
	case 0x6b:
		return "KEY_END"
	case 0x6c:
		return "KEY_DOWN"
	case 0x6d:
		return "KEY_PAGEDOWN"
	case 0x6e:
		return "KEY_INSERT"
	case 0x6f:
		return "KEY_DELETE"
	case 0x70:
		return "KEY_MACRO"
	case 0x71:
		return "KEY_MUTE"
	case 0x72:
		return "KEY_VOLUMEDOWN"
	case 0x73:
		return "KEY_VOLUMEUP"
	case 0x74:
		return "KEY_POWER"
	case 0x75:
		return "KEY_KPEQUAL"
	case 0x76:
		return "KEY_KPPLUSMINUS"
	case 0x77:
		return "KEY_PAUSE"
	case 0x78:
		return "KEY_SCALE"
	case 0x79:
		return "KEY_KPCOMMA"
	case 0x7a:
		return "KEY_HANGEUL"
	case 0x7b:
		return "KEY_HANJA"
	case 0x7c:
		return "KEY_YEN"
	case 0x7d:
		return "KEY_LEFTMETA"
	case 0x7e:
		return "KEY_RIGHTMETA"
	case 0x7f:
		return "KEY_COMPOSE"
	case 0x80:
		return "KEY_STOP"
	case 0x81:
		return "KEY_AGAIN"
	case 0x82:
		return "KEY_PROPS"
	case 0x83:
		return "KEY_UNDO"
	case 0x84:
		return "KEY_FRONT"
	case 0x85:
		return "KEY_COPY"
	case 0x86:
		return "KEY_OPEN"
	case 0x87:
		return "KEY_PASTE"
	case 0x88:
		return "KEY_FIND"
	case 0x89:
		return "KEY_CUT"
	case 0x8a:
		return "KEY_HELP"
	case 0x8b:
		return "KEY_MENU"
	case 0x8c:
		return "KEY_CALC"
	case 0x8d:
		return "KEY_SETUP"
	case 0x8e:
		return "KEY_SLEEP"
	case 0x8f:
		return "KEY_WAKEUP"
	case 0x90:
		return "KEY_FILE"
	case 0x91:
		return "KEY_SENDFILE"
	case 0x92:
		return "KEY_DELETEFILE"
	case 0x93:
		return "KEY_XFER"
	case 0x94:
		return "KEY_PROG1"
	case 0x95:
		return "KEY_PROG2"
	case 0x96:
		return "KEY_WWW"
	case 0x97:
		return "KEY_MSDOS"
	case 0x98:
		return "KEY_COFFEE"
	case 0x99:
		return "KEY_ROTATE_DISPLAY"
	case 0x9a:
		return "KEY_CYCLEWINDOWS"
	case 0x9b:
		return "KEY_MAIL"
	case 0x9c:
		return "KEY_BOOKMARKS"
	case 0x9d:
		return "KEY_COMPUTER"
	case 0x9e:
		return "KEY_BACK"
	case 0x9f:
		return "KEY_FORWARD"
	case 0xa0:
		return "KEY_CLOSECD"
	case 0xa1:
		return "KEY_EJECTCD"
	case 0xa2:
		return "KEY_EJECTCLOSECD"
	case 0xa3:
		return "KEY_NEXTSONG"
	case 0xa4:
		return "KEY_PLAYPAUSE"
	case 0xa5:
		return "KEY_PREVIOUSSONG"
	case 0xa6:
		return "KEY_STOPCD"
	case 0xa7:
		return "KEY_RECORD"
	case 0xa8:
		return "KEY_REWIND"
	case 0xa9:
		return "KEY_PHONE"
	case 0xaa:
		return "KEY_ISO"
	case 0xab:
		return "KEY_CONFIG"
	case 0xac:
		return "KEY_HOMEPAGE"
	case 0xad:
		return "KEY_REFRESH"
	case 0xae:
		return "KEY_EXIT"
	case 0xaf:
		return "KEY_MOVE"
	case 0xb0:
		return "KEY_EDIT"
	case 0xb1:
		return "KEY_SCROLLUP"
	case 0xb2:
		return "KEY_SCROLLDOWN"
	case 0xb3:
		return "KEY_KPLEFTPAREN"
	case 0xb4:
		return "KEY_KPRIGHTPAREN"
	case 0xb5:
		return "KEY_NEW"
	case 0xb6:
		return "KEY_REDO"
	case 0xb7:
		return "KEY_F13"
	case 0xb8:
		return "KEY_F14"
	case 0xb9:
		return "KEY_F15"
	case 0xba:
		return "KEY_F16"
	case 0xbb:
		return "KEY_F17"
	case 0xbc:
		return "KEY_F18"
	case 0xbd:
		return "KEY_F19"
	case 0xbe:
		return "KEY_F20"
	case 0xbf:
		return "KEY_F21"
	case 0xc0:
		return "KEY_F22"
	case 0xc1:
		return "KEY_F23"
	case 0xc2:
		return "KEY_F24"
	case 0xc8:
		return "KEY_PLAYCD"
	case 0xc9:
		return "KEY_PAUSECD"
	case 0xca:
		return "KEY_PROG3"
	case 0xcb:
		return "KEY_PROG4"
	case 0xcc:
		return "KEY_ALL_APPLICATIONS"
	case 0xcd:
		return "KEY_SUSPEND"
	case 0xce:
		return "KEY_CLOSE"
	case 0xcf:
		return "KEY_PLAY"
	case 0xd0:
		return "KEY_FASTFORWARD"
	case 0xd1:
		return "KEY_BASSBOOST"
	case 0xd2:
		return "KEY_PRINT"
	case 0xd3:
		return "KEY_HP"
	case 0xd4:
		return "KEY_CAMERA"
	case 0xd5:
		return "KEY_SOUND"
	case 0xd6:
		return "KEY_QUESTION"
	case 0xd7:
		return "KEY_EMAIL"
	case 0xd8:
		return "KEY_CHAT"
	case 0xd9:
		return "KEY_SEARCH"
	case 0xda:
		return "KEY_CONNECT"
	case 0xdb:
		return "KEY_FINANCE"
	case 0xdc:
		return "KEY_SPORT"
	case 0xdd:
		return "KEY_SHOP"
	case 0xde:
		return "KEY_ALTERASE"
	case 0xdf:
		return "KEY_CANCEL"
	case 0xe0:
		return "KEY_BRIGHTNESSDOWN"
	case 0xe1:
		return "KEY_BRIGHTNESSUP"
	case 0xe2:
		return "KEY_MEDIA"
	case 0xe3:
		return "KEY_SWITCHVIDEOMODE"
	case 0xe4:
		return "KEY_KBDILLUMTOGGLE"
	case 0xe5:
		return "KEY_KBDILLUMDOWN"
	case 0xe6:
		return "KEY_KBDILLUMUP"
	case 0xe7:
		return "KEY_SEND"
	case 0xe8:
		return "KEY_REPLY"
	case 0xe9:
		return "KEY_FORWARDMAIL"
	case 0xea:
		return "KEY_SAVE"
	case 0xeb:
		return "KEY_DOCUMENTS"
	case 0xec:
		return "KEY_BATTERY"
	case 0xed:
		return "KEY_BLUETOOTH"
	case 0xee:
		return "KEY_WLAN"
	case 0xef:
		return "KEY_UWB"
	case 0xf0:
		return "KEY_UNKNOWN"
	case 0xf1:
		return "KEY_VIDEO_NEXT"
	case 0xf2:
		return "KEY_VIDEO_PREV"
	case 0xf3:
		return "KEY_BRIGHTNESS_CYCLE"
	case 0xf4:
		return "KEY_BRIGHTNESS_AUTO"
	case 0xf5:
		return "KEY_DISPLAY_OFF"
	case 0xf6:
		return "KEY_WWAN"
	case 0xf7:
		return "KEY_RFKILL"
	case 0xf8:
		return "KEY_MICMUTE"
	case 0x160:
		return "KEY_OK"
	case 0x161:
		return "KEY_SELECT"
	case 0x162:
		return "KEY_GOTO"
	case 0x163:
		return "KEY_CLEAR"
	case 0x164:
		return "KEY_POWER2"
	case 0x165:
		return "KEY_OPTION"
	case 0x166:
		return "KEY_INFO"
	case 0x167:
		return "KEY_TIME"
	case 0x168:
		return "KEY_VENDOR"
	case 0x169:
		return "KEY_ARCHIVE"
	case 0x16a:
		return "KEY_PROGRAM"
	case 0x16b:
		return "KEY_CHANNEL"
	case 0x16c:
		return "KEY_FAVORITES"
	case 0x16d:
		return "KEY_EPG"
	case 0x16e:
		return "KEY_PVR"
	case 0x16f:
		return "KEY_MHP"
	case 0x170:
		return "KEY_LANGUAGE"
	case 0x171:
		return "KEY_TITLE"
	case 0x172:
		return "KEY_SUBTITLE"
	case 0x173:
		return "KEY_ANGLE"
	case 0x174:
		return "KEY_FULL_SCREEN"
	case 0x175:
		return "KEY_MODE"
	case 0x176:
		return "KEY_KEYBOARD"
	case 0x177:
		return "KEY_ASPECT_RATIO"
	case 0x178:
		return "KEY_PC"
	case 0x179:
		return "KEY_TV"
	case 0x17a:
		return "KEY_TV2"
	case 0x17b:
		return "KEY_VCR"
	case 0x17c:
		return "KEY_VCR2"
	case 0x17d:
		return "KEY_SAT"
	case 0x17e:
		return "KEY_SAT2"
	case 0x17f:
		return "KEY_CD"
	case 0x180:
		return "KEY_TAPE"
	case 0x181:
		return "KEY_RADIO"
	case 0x182:
		return "KEY_TUNER"
	case 0x183:
		return "KEY_PLAYER"
	case 0x184:
		return "KEY_TEXT"
	case 0x185:
		return "KEY_DVD"
	case 0x186:
		return "KEY_AUX"
	case 0x187:
		return "KEY_MP3"
	case 0x188:
		return "KEY_AUDIO"
	case 0x189:
		return "KEY_VIDEO"
	case 0x18a:
		return "KEY_DIRECTORY"
	case 0x18b:
		return "KEY_LIST"
	case 0x18c:
		return "KEY_MEMO"
	case 0x18d:
		return "KEY_CALENDAR"
	case 0x18e:
		return "KEY_RED"
	case 0x18f:
		return "KEY_GREEN"
	case 0x190:
		return "KEY_YELLOW"
	case 0x191:
		return "KEY_BLUE"
	case 0x192:
		return "KEY_CHANNELUP"
	case 0x193:
		return "KEY_CHANNELDOWN"
	case 0x194:
		return "KEY_FIRST"
	case 0x195:
		return "KEY_LAST"
	case 0x196:
		return "KEY_AB"
	case 0x197:
		return "KEY_NEXT"
	case 0x198:
		return "KEY_RESTART"
	case 0x199:
		return "KEY_SLOW"
	case 0x19a:
		return "KEY_SHUFFLE"
	case 0x19b:
		return "KEY_BREAK"
	case 0x19c:
		return "KEY_PREVIOUS"
	case 0x19d:
		return "KEY_DIGITS"
	case 0x19e:
		return "KEY_TEEN"
	case 0x19f:
		return "KEY_TWEN"
	case 0x1a0:
		return "KEY_VIDEOPHONE"
	case 0x1a1:
		return "KEY_GAMES"
	case 0x1a2:
		return "KEY_ZOOMIN"
	case 0x1a3:
		return "KEY_ZOOMOUT"
	case 0x1a4:
		return "KEY_ZOOMRESET"
	case 0x1a5:
		return "KEY_WORDPROCESSOR"
	case 0x1a6:
		return "KEY_EDITOR"
	case 0x1a7:
		return "KEY_SPREADSHEET"
	case 0x1a8:
		return "KEY_GRAPHICSEDITOR"
	case 0x1a9:
		return "KEY_PRESENTATION"
	case 0x1aa:
		return "KEY_DATABASE"
	case 0x1ab:
		return "KEY_NEWS"
	case 0x1ac:
		return "KEY_VOICEMAIL"
	case 0x1ad:
		return "KEY_ADDRESSBOOK"
	case 0x1ae:
		return "KEY_MESSENGER"
	case 0x1af:
		return "KEY_DISPLAYTOGGLE"
	case 0x1b0:
		return "KEY_SPELLCHECK"
	case 0x1b1:
		return "KEY_LOGOFF"
	case 0x1b2:
		return "KEY_DOLLAR"
	case 0x1b3:
		return "KEY_EURO"
	case 0x1b4:
		return "KEY_FRAMEBACK"
	case 0x1b5:
		return "KEY_FRAMEFORWARD"
	case 0x1b6:
		return "KEY_CONTEXT_MENU"
	case 0x1b7:
		return "KEY_MEDIA_REPEAT"
	case 0x1b8:
		return "KEY_10CHANNELSUP"
	case 0x1b9:
		return "KEY_10CHANNELSDOWN"
	case 0x1ba:
		return "KEY_IMAGES"
	case 0x1bc:
		return "KEY_NOTIFICATION_CENTER"
	case 0x1bd:
		return "KEY_PICKUP_PHONE"
	case 0x1be:
		return "KEY_HANGUP_PHONE"
	case 0x1c0:
		return "KEY_DEL_EOL"
	case 0x1c1:
		return "KEY_DEL_EOS"
	case 0x1c2:
		return "KEY_INS_LINE"
	case 0x1c3:
		return "KEY_DEL_LINE"
	case 0x1d0:
		return "KEY_FN"
	case 0x1d1:
		return "KEY_FN_ESC"
	case 0x1d2:
		return "KEY_FN_F1"
	case 0x1d3:
		return "KEY_FN_F2"
	case 0x1d4:
		return "KEY_FN_F3"
	case 0x1d5:
		return "KEY_FN_F4"
	case 0x1d6:
		return "KEY_FN_F5"
	case 0x1d7:
		return "KEY_FN_F6"
	case 0x1d8:
		return "KEY_FN_F7"
	case 0x1d9:
		return "KEY_FN_F8"
	case 0x1da:
		return "KEY_FN_F9"
	case 0x1db:
		return "KEY_FN_F10"
	case 0x1dc:
		return "KEY_FN_F11"
	case 0x1dd:
		return "KEY_FN_F12"
	case 0x1de:
		return "KEY_FN_1"
	case 0x1df:
		return "KEY_FN_2"
	case 0x1e0:
		return "KEY_FN_D"
	case 0x1e1:
		return "KEY_FN_E"
	case 0x1e2:
		return "KEY_FN_F"
	case 0x1e3:
		return "KEY_FN_S"
	case 0x1e4:
		return "KEY_FN_B"
	case 0x1e5:
		return "KEY_FN_RIGHT_SHIFT"
	case 0x1f1:
		return "KEY_BRL_DOT1"
	case 0x1f2:
		return "KEY_BRL_DOT2"
	case 0x1f3:
		return "KEY_BRL_DOT3"
	case 0x1f4:
		return "KEY_BRL_DOT4"
	case 0x1f5:
		return "KEY_BRL_DOT5"
	case 0x1f6:
		return "KEY_BRL_DOT6"
	case 0x1f7:
		return "KEY_BRL_DOT7"
	case 0x1f8:
		return "KEY_BRL_DOT8"
	case 0x1f9:
		return "KEY_BRL_DOT9"
	case 0x1fa:
		return "KEY_BRL_DOT10"
	case 0x200:
		return "KEY_NUMERIC_0"
	case 0x201:
		return "KEY_NUMERIC_1"
	case 0x202:
		return "KEY_NUMERIC_2"
	case 0x203:
		return "KEY_NUMERIC_3"
	case 0x204:
		return "KEY_NUMERIC_4"
	case 0x205:
		return "KEY_NUMERIC_5"
	case 0x206:
		return "KEY_NUMERIC_6"
	case 0x207:
		return "KEY_NUMERIC_7"
	case 0x208:
		return "KEY_NUMERIC_8"
	case 0x209:
		return "KEY_NUMERIC_9"
	case 0x20a:
		return "KEY_NUMERIC_STAR"
	case 0x20b:
		return "KEY_NUMERIC_POUND"
	case 0x20c:
		return "KEY_NUMERIC_A"
	case 0x20d:
		return "KEY_NUMERIC_B"
	case 0x20e:
		return "KEY_NUMERIC_C"
	case 0x20f:
		return "KEY_NUMERIC_D"
	case 0x210:
		return "KEY_CAMERA_FOCUS"
	case 0x211:
		return "KEY_WPS_BUTTON"
	case 0x212:
		return "KEY_TOUCHPAD_TOGGLE"
	case 0x213:
		return "KEY_TOUCHPAD_ON"
	case 0x214:
		return "KEY_TOUCHPAD_OFF"
	case 0x215:
		return "KEY_CAMERA_ZOOMIN"
	case 0x216:
		return "KEY_CAMERA_ZOOMOUT"
	case 0x217:
		return "KEY_CAMERA_UP"
	case 0x218:
		return "KEY_CAMERA_DOWN"
	case 0x219:
		return "KEY_CAMERA_LEFT"
	case 0x21a:
		return "KEY_CAMERA_RIGHT"
	case 0x21b:
		return "KEY_ATTENDANT_ON"
	case 0x21c:
		return "KEY_ATTENDANT_OFF"
	case 0x21d:
		return "KEY_ATTENDANT_TOGGLE"
	case 0x21e:
		return "KEY_LIGHTS_TOGGLE"
	case 0x230:
		return "KEY_ALS_TOGGLE"
	case 0x231:
		return "KEY_ROTATE_LOCK_TOGGLE"
	case 0x240:
		return "KEY_BUTTONCONFIG"
	case 0x241:
		return "KEY_TASKMANAGER"
	case 0x242:
		return "KEY_JOURNAL"
	case 0x243:
		return "KEY_CONTROLPANEL"
	case 0x244:
		return "KEY_APPSELECT"
	case 0x245:
		return "KEY_SCREENSAVER"
	case 0x246:
		return "KEY_VOICECOMMAND"
	case 0x247:
		return "KEY_ASSISTANT"
	case 0x248:
		return "KEY_KBD_LAYOUT_NEXT"
	case 0x249:
		return "KEY_EMOJI_PICKER"
	case 0x24a:
		return "KEY_DICTATE"
	case 0x250:
		return "KEY_BRIGHTNESS_MIN"
	case 0x251:
		return "KEY_BRIGHTNESS_MAX"
	case 0x260:
		return "KEY_KBDINPUTASSIST_PREV"
	case 0x261:
		return "KEY_KBDINPUTASSIST_NEXT"
	case 0x262:
		return "KEY_KBDINPUTASSIST_PREVGROUP"
	case 0x263:
		return "KEY_KBDINPUTASSIST_NEXTGROUP"
	case 0x264:
		return "KEY_KBDINPUTASSIST_ACCEPT"
	case 0x265:
		return "KEY_KBDINPUTASSIST_CANCEL"
	case 0x266:
		return "KEY_RIGHT_UP"
	case 0x267:
		return "KEY_RIGHT_DOWN"
	case 0x268:
		return "KEY_LEFT_UP"
	case 0x269:
		return "KEY_LEFT_DOWN"
	case 0x26a:
		return "KEY_ROOT_MENU"
	case 0x26b:
		return "KEY_MEDIA_TOP_MENU"
	case 0x26c:
		return "KEY_NUMERIC_11"
	case 0x26d:
		return "KEY_NUMERIC_12"
	case 0x26e:
		return "KEY_AUDIO_DESC"
	case 0x26f:
		return "KEY_3D_MODE"
	case 0x270:
		return "KEY_NEXT_FAVORITE"
	case 0x271:
		return "KEY_STOP_RECORD"
	case 0x272:
		return "KEY_PAUSE_RECORD"
	case 0x273:
		return "KEY_VOD"
	case 0x274:
		return "KEY_UNMUTE"
	case 0x275:
		return "KEY_FASTREVERSE"
	case 0x276:
		return "KEY_SLOWREVERSE"
	case 0x277:
		return "KEY_DATA"
	case 0x278:
		return "KEY_ONSCREEN_KEYBOARD"
	case 0x279:
		return "KEY_PRIVACY_SCREEN_TOGGLE"
	case 0x27a:
		return "KEY_SELECTIVE_SCREENSHOT"
	case 0x290:
		return "KEY_MACRO1"
	case 0x291:
		return "KEY_MACRO2"
	case 0x292:
		return "KEY_MACRO3"
	case 0x293:
		return "KEY_MACRO4"
	case 0x294:
		return "KEY_MACRO5"
	case 0x295:
		return "KEY_MACRO6"
	case 0x296:
		return "KEY_MACRO7"
	case 0x297:
		return "KEY_MACRO8"
	case 0x298:
		return "KEY_MACRO9"
	case 0x299:
		return "KEY_MACRO10"
	case 0x29a:
		return "KEY_MACRO11"
	case 0x29b:
		return "KEY_MACRO12"
	case 0x29c:
		return "KEY_MACRO13"
	case 0x29d:
		return "KEY_MACRO14"
	case 0x29e:
		return "KEY_MACRO15"
	case 0x29f:
		return "KEY_MACRO16"
	case 0x2a0:
		return "KEY_MACRO17"
	case 0x2a1:
		return "KEY_MACRO18"
	case 0x2a2:
		return "KEY_MACRO19"
	case 0x2a3:
		return "KEY_MACRO20"
	case 0x2a4:
		return "KEY_MACRO21"
	case 0x2a5:
		return "KEY_MACRO22"
	case 0x2a6:
		return "KEY_MACRO23"
	case 0x2a7:
		return "KEY_MACRO24"
	case 0x2a8:
		return "KEY_MACRO25"
	case 0x2a9:
		return "KEY_MACRO26"
	case 0x2aa:
		return "KEY_MACRO27"
	case 0x2ab:
		return "KEY_MACRO28"
	case 0x2ac:
		return "KEY_MACRO29"
	case 0x2ad:
		return "KEY_MACRO30"
	case 0x2b0:
		return "KEY_MACRO_RECORD_START"
	case 0x2b1:
		return "KEY_MACRO_RECORD_STOP"
	case 0x2b2:
		return "KEY_MACRO_PRESET_CYCLE"
	case 0x2b3:
		return "KEY_MACRO_PRESET1"
	case 0x2b4:
		return "KEY_MACRO_PRESET2"
	case 0x2b5:
		return "KEY_MACRO_PRESET3"
	case 0x2b8:
		return "KEY_KBD_LCD_MENU1"
	case 0x2b9:
		return "KEY_KBD_LCD_MENU2"
	case 0x2ba:
		return "KEY_KBD_LCD_MENU3"
	case 0x2bb:
		return "KEY_KBD_LCD_MENU4"
	case 0x2bc:
		return "KEY_KBD_LCD_MENU5"
	case 0x2ff:
		return "KEY_MAX"
	}
	return "Unrecoginized key event"
}
