// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package filemanager

import (
	"context"
	"path/filepath"
	"time"

	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/filesapp"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/filemanager"
	"go.chromium.org/tast-tests/cros/local/input"
	"go.chromium.org/tast-tests/cros/local/onedrive"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:           OdfsAutomatedIntegrationThirdParty,
		LifeCycleStage: testing.LifeCycleOwnerMonitored,
		Desc:           "Verifies that the automated Microsoft OneDrive integration works for non-Microsoft IdPs, in this case Gaia",
		BugComponent:   "b:1401215", // ChromeOS > Software > Commercial (Enterprise) > Identity > 3P IdP > Enterprise Clippy
		Timeout:        5 * time.Minute,
		Contacts: []string{
			"cros-commercial-clippy-eng@google.com",
			"lmasopust@google.com",
		},
		SoftwareDeps: []string{
			"chrome",
			"chrome_internal",
		},
		Attr: []string{
			"group:hw_agnostic",
			"group:golden_tier",
		},
		VarDeps: []string{
			"onedrive.googlemanagedusername",
			"onedrive.googlemanagedpassword",
			"ui.signinProfileTestExtensionManifestKey",
		},
	})
}

func OdfsAutomatedIntegrationThirdParty(ctx context.Context, s *testing.State) {
	username := s.RequiredVar("onedrive.googlemanagedusername")
	password := s.RequiredVar("onedrive.googlemanagedpassword")

	odfsDevPath := onedrive.OdfsUnpackedLocation.Value()
	isOdfsDev := len(odfsDevPath) > 0

	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	opts := []chrome.Option{
		chrome.LoadSigninProfileExtension(s.RequiredVar("ui.signinProfileTestExtensionManifestKey")),
		chrome.EnableFeatures("UploadOfficeToCloud"),
		chrome.ExtraArgs("--disable-sync", "--vmodule=cloud_upload*=3", "--extension-force-channel=dev"),
		chrome.GAIALogin(chrome.Creds{User: username, Pass: password}),
	}
	if isOdfsDev {
		opts = append(opts, chrome.UnpackedExtension(odfsDevPath))
	}

	// Sign in with a real Gaia account as we can't use a managedchrome account and thus can't use a fake DM server.
	cr, err := chrome.New(
		ctx,
		opts...,
	)
	if err != nil {
		s.Fatal("Chrome Gaia login failed: ", err)
	}
	defer cr.Close(cleanupCtx)

	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed creating test API connection: ", err)
	}

	files, err := filesapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to launch Files app: ", err)
	}
	defer files.Close(cleanupCtx)
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "odfs_file_crud")

	// During the third party SSO flow, the OneDrive will first appear in an
	// unauthenticated state and will later be replaced if the authentication
	// was successful. Thus, we retry creating the folder until it's successful.
	var odfsToken, uniqueTargetFolder, fullPathForTargetFolder string
	po := &testing.PollOptions{Timeout: 3 * time.Minute, Interval: 2 * time.Second}
	if err := testing.Poll(ctx, func(ctx context.Context) error {
		if err = files.Exists(nodewith.Name(filesapp.OneDrive).Role(role.TreeItem))(ctx); err != nil {
			return errors.Wrap(err, "failed to find OneDrive folder in files app")
		}

		odfsToken, err = files.GetOdfsFuseboxToken(ctx, cr)
		if err != nil {
			return errors.Wrap(err, "failed to get ODFS key")
		}

		// Create a target folder for all files/folders generated by the test.
		uniqueTargetFolder = filemanager.GenerateTestFileName("_odfs_OdfsFileCrud")
		fullPathForTargetFolder, err = filemanager.CreateFolderInFusebox(odfsToken, uniqueTargetFolder)
		if err != nil {
			return errors.Wrap(err, "failed to create target folder in ODFS")
		}

		return nil
	}, po); err != nil {
		s.Fatal("Failed to authenticate for OneDrive integration: ", err)
	}
	defer filemanager.RemovePathInFusebox(cleanupCtx, fullPathForTargetFolder, 5*time.Second)

	// Create a file in ODFS via fusebox (no UI to create file in ODFS).
	fileName := "_odfs_test.txt"
	fileContent := "test"
	_, err = filemanager.CreateFileInFusebox(odfsToken, filepath.Join(uniqueTargetFolder, fileName), fileContent)
	if err != nil {
		s.Fatal("Failed to create text file in ODFS: ", err)
	}

	// Check file existence and file content.
	kb, err := input.Keyboard(ctx)
	if err != nil {
		s.Fatal("Failed to get Keyboard: ", err)
	}
	if err := uiauto.Combine("Check the file is available in Files app",
		files.OpenOneDrive(),
		files.Search(kb, uniqueTargetFolder),
		files.WaitForFile(uniqueTargetFolder),
		files.OpenFile(uniqueTargetFolder),
		files.WaitForTitle(filesapp.FilesTitlePrefix+uniqueTargetFolder),
		files.WaitForFile(fileName),
	)(ctx); err != nil {
		s.Fatal("Failed to find the newly created file in Files app: ", err)
	}
}
