// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package filemanager

import (
	"context"
	"path/filepath"
	"time"

	"go.chromium.org/tast-tests/cros/common/fixture"
	"go.chromium.org/tast-tests/cros/common/pci"
	"go.chromium.org/tast-tests/cros/common/policy"
	"go.chromium.org/tast-tests/cros/common/policy/fakedms"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/filesapp"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/nodewith"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/role"
	"go.chromium.org/tast-tests/cros/local/filemanager"
	"go.chromium.org/tast-tests/cros/local/input"
	"go.chromium.org/tast-tests/cros/local/onedrive"
	"go.chromium.org/tast-tests/cros/local/saml"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         OdfsAutomatedIntegration,
		LacrosStatus: testing.LacrosVariantNeeded,
		Desc:         "Verifies that the automated Microsoft OneDrive integration works",
		BugComponent: "b:1401215", // ChromeOS > Software > Commercial (Enterprise) > Identity > 3P IdP > Enterprise Clippy
		Timeout:      5 * time.Minute,
		Contacts: []string{
			"cros-commercial-clippy-eng@google.com",
			"lmasopust@google.com",
		},
		SoftwareDeps: []string{
			"chrome",
			"chrome_internal",
		},
		Attr: []string{
			"group:hw_agnostic",
			"group:golden_tier",
		},
		VarDeps: []string{
			"onedrive.managedusernamegoogle",
			"onedrive.managedusernamemicrosoft",
			"onedrive.managedpassword",
			"ui.signinProfileTestExtensionManifestKey",
		},
		Fixture: fixture.FakeDMS,
		SearchFlags: []*testing.StringPair{
			pci.SearchFlag(&policy.MicrosoftOneDriveMount{}, pci.VerifiedValue),
			pci.SearchFlag(&policy.MicrosoftOneDriveAccountRestrictions{}, pci.VerifiedValue),
			pci.SearchFlag(&policy.MicrosoftOfficeCloudUpload{}, pci.Served),
		},
	})
}

func OdfsAutomatedIntegration(ctx context.Context, s *testing.State) {
	usernameGoogle := s.RequiredVar("onedrive.managedusernamegoogle")
	usernameMicrosoft := s.RequiredVar("onedrive.managedusernamemicrosoft")
	password := s.RequiredVar("onedrive.managedpassword")

	odfsDevPath := onedrive.OdfsUnpackedLocation.Value()
	isOdfsDev := len(odfsDevPath) > 0

	fdms, ok := s.FixtValue().(*fakedms.FakeDMS)
	if !ok {
		s.Fatal("Failed to launch fakeDMS")
	}

	// Apply automated OneDrive policies & account restrictions to the Microsoft tenant of the account.
	pb := policy.NewBlob()
	pb.PolicyUser = usernameGoogle
	pb.AddPolicies([]policy.Policy{
		&policy.MicrosoftOneDriveMount{Val: "automated"},
		&policy.MicrosoftOneDriveAccountRestrictions{Val: []string{"a92a173f-0725-428b-a8ee-353d3dbd0313"}},
		&policy.MicrosoftOfficeCloudUpload{Val: "automated"},
	})
	if err := fdms.WritePolicyBlob(pb); err != nil {
		s.Fatal("Failed to write policies to FakeDMS: ", err)
	}

	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	opts := []chrome.Option{
		chrome.LoadSigninProfileExtension(s.RequiredVar("ui.signinProfileTestExtensionManifestKey")),
		chrome.DMSPolicy(fdms.URL),
		chrome.EnableFeatures("UploadOfficeToCloud"),
		chrome.ExtraArgs("--disable-sync", "--vmodule=cloud_upload*=3", "--extension-force-channel=dev"),
	}
	if isOdfsDev {
		opts = append(opts, chrome.UnpackedExtension(odfsDevPath))
	}

	// Sign in with a real SAML account
	cr, err := saml.LoginWithSAMLAccount(
		ctx,
		usernameGoogle,
		saml.HandleMicrosoftLogin(usernameMicrosoft, password),
		opts...,
	)
	if err != nil {
		s.Fatal("Chrome SAML login failed: ", err)
	}
	defer cr.Close(cleanupCtx)

	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed creating test API connection: ", err)
	}

	files, err := filesapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to launch Files app: ", err)
	}
	defer files.Close(cleanupCtx)
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "odfs_file_crud")

	if err = files.WaitUntilExists(nodewith.Name(filesapp.OneDrive).Role(role.TreeItem))(ctx); err != nil {
		s.Fatal("Failed to find OneDrive folder in files app: ", err)
	}

	odfsToken, err := files.GetOdfsFuseboxToken(ctx, cr)
	if err != nil {
		s.Fatal("Failed to get ODFS key: ", err)
	}

	// Create a target folder for all files/folders generated by the test.
	uniqueTargetFolder := filemanager.GenerateTestFileName("_odfs_OdfsFileCrud")
	fullPathForTargetFolder, err := filemanager.CreateFolderInFusebox(odfsToken, uniqueTargetFolder)
	if err != nil {
		s.Fatal("Failed to create target folder in ODFS: ", err)
	}
	defer filemanager.RemovePathInFusebox(cleanupCtx, fullPathForTargetFolder, 5*time.Second)

	// Create a file in ODFS via fusebox (no UI to create file in ODFS).
	fileName := "_odfs_test.txt"
	fileContent := "test"
	_, err = filemanager.CreateFileInFusebox(odfsToken, filepath.Join(uniqueTargetFolder, fileName), fileContent)
	if err != nil {
		s.Fatal("Failed to create text file in ODFS: ", err)
	}

	// Check file existence and file content.
	kb, err := input.Keyboard(ctx)
	if err != nil {
		s.Fatal("Failed to get Keyboard: ", err)
	}
	if err := uiauto.Combine("Check the file is available in Files app",
		files.OpenOneDrive(),
		files.Search(kb, uniqueTargetFolder),
		files.WaitForFile(uniqueTargetFolder),
		files.OpenFile(uniqueTargetFolder),
		files.WaitForTitle(filesapp.FilesTitlePrefix+uniqueTargetFolder),
		files.WaitForFile(fileName),
	)(ctx); err != nil {
		s.Fatal("Failed to find the newly created file in Files app: ", err)
	}
}
