// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.peripherals;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/peripherals";

// PeriphService provides RPC methods to be used by Peripherals remote test.
service PeriphService {
  // NewCitrix creates a new instance of Citrix and launches the Citrix app.
  rpc NewCitrix(NewCitrixRequest) returns (google.protobuf.Empty) {}

  // LoginCitrix logins the Citrix app and connects to desktop.
  rpc LoginCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // OpenCitrix launches the Citrix app.
  rpc OpenCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // CloseCitrix closes the Citrix app.
  rpc CloseCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // ConnectUSBDeviceInCitrix connects USB device.
  rpc ConnectUSBDeviceInCitrix(ConnectUSBDeviceInCitrixRequest)
      returns (google.protobuf.Empty) {}

  // OpenCitrixApp opens app in Citrix.
  rpc OpenCitrixApp(OpenCitrixAppRequest) returns (google.protobuf.Empty) {}

  // CloseCitrixApp closes app in Citrix.
  rpc CloseCitrixApp(CloseCitrixAppRequest) returns (google.protobuf.Empty) {}

  // DeleteFile deletes the signature.
  rpc DeleteFile(DeleteFileRequest) returns (google.protobuf.Empty) {}

  // DeleteFileIfExists deletes the file if it exists.
  rpc DeleteFileIfExists(DeleteFileRequest) returns (google.protobuf.Empty) {}

  // SaveCropScreenshot saves the crop screenshot.
  rpc SaveCropScreenshot(SaveCropScreenshotRequest)
      returns (google.protobuf.Empty) {}

  // VerifyTwoImagesSimilarity verifies two images are same or not.
  rpc VerifyTwoImagesSimilarity(VerifyTwoImagesSimilarityRequest)
      returns (google.protobuf.Empty) {}

  // WaitUntilIconExists waits for the icon to exist.
  rpc WaitUntilIconExists(WaitUntilIconExistsRequest)
      returns (google.protobuf.Empty) {}

  // SetupFootPedalTest sets up the foot pedal test.
  rpc SetupFootPedalTest(google.protobuf.Empty)
      returns (google.protobuf.Empty) {}

  // VerifyFootPedalButtonPressed verifies the foot pedal button is pressed.
  rpc VerifyFootPedalButtonPressed(VerifyFootPedalButtonPressedRequest)
      returns (google.protobuf.Empty) {}

  // StartSignature starts the sign process.
  rpc StartSignature(StartSignatureRequest) returns (google.protobuf.Empty) {}

  // SaveSignature saves the signature.
  rpc SaveSignature(SignatureRequest) returns (google.protobuf.Empty) {}

  // LoadSignature loads the signature.
  rpc LoadSignature(SignatureRequest) returns (google.protobuf.Empty) {}

  // ClearSignature clears the signature.
  rpc ClearSignature(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // Dictation services.

  // NewDictationSupport creates a new instance of Dictation support.
  rpc NewDictationSupport(google.protobuf.Empty)
      returns (google.protobuf.Empty) {}

  // CloseDictation closes the dictation support page.
  rpc CloseDictation(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // ConnectToDictationDevice connects to the dictation device with the given
  // device name.
  rpc ConnectToDictationDevice(ConnectToDictationDeviceRequest)
      returns (google.protobuf.Empty) {}

  // GetDictationDevices returns the dictation devices.
  rpc GetDictationDevices(google.protobuf.Empty)
      returns (GetDictationDevicesResponse) {}

  // WaitDictationNewEvent waits for new event from dictation.
  rpc WaitDictationNewEvent(WaitDictationNewEventRequest)
      returns (google.protobuf.Empty) {}

  // prepareKeyboardEvent prepares the precondition for a keyboard event.
  rpc prepareKeyboardEvent(KeyboardEventRequest)
      returns (google.protobuf.Empty) {}

  // VerifyKeyboardEvent verifies that the given keyboard event is triggered.
  rpc VerifyKeyboardEvent(KeyboardEventRequest)
      returns (google.protobuf.Empty) {}

  // CleanupKeyboardEvent cleans up by performing necessary actions like
  // closing windows.
  rpc CleanupKeyboardEvent(KeyboardEventRequest)
      returns (google.protobuf.Empty) {}

  // SetDictationEventMode sets the event mode to the given state.
  rpc SetDictationEventMode(SetDictationEventModeRequest)
      returns (google.protobuf.Empty) {}

  // GetDictationEventMode returns the event mode.
  rpc GetDictationEventMode(google.protobuf.Empty)
      returns (GetDictationEventModeResponse) {}

  // SetDictationSimpleLEDState sets the simple LED state to the given state.
  rpc SetDictationSimpleLEDState(SetDictationSimpleLEDStateRequest)
      returns (google.protobuf.Empty) {}

  // SetDictationLEDState sets the LED state with given index and mode.
  rpc SetDictationLEDState(SetDictationLEDStateRequest)
      returns (google.protobuf.Empty) {}

  // NewSmartCard launches Chrome, creates a new SmartCard instance and
  // navigates to the PIN entry page.
  rpc NewSmartCard(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // CleanupSmartCard cleanups smart card.
  rpc CleanupSmartCard(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // SetPIN sets PIN with given PIN code.
  rpc SetPIN(SetPINRequest) returns (SetPINResponse) {}

  // SmartCardSignIn signs in smart card.
  rpc SmartCardSignIn(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // SmartCardSignOut signs out smart card.
  rpc SmartCardSignOut(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // ReAuthentication signs out and signs in with the smart card.
  rpc ReAuthentication(ReAuthenticationRequest)
      returns (google.protobuf.Empty) {}

  // SmartCardRemovalAndInsertionTesting tests whether the UI during smart
  // card removal and insertion is as expected.
  rpc SmartCardRemovalAndInsertionTesting(
      SmartCardRemovalAndInsertionTestingRequest)
      returns (google.protobuf.Empty) {}

  // AddPerson adds person.
  rpc AddPerson(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // LockScreen locks screen.
  rpc LockScreen(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // SetSecurityTokenRemoval sets security policy and removal notification
  // duration.
  rpc SetSecurityTokenRemoval(SetSecurityTokenRemovalRequest)
      returns (google.protobuf.Empty) {}

  // WaitForAutoLockOrLogOut waits for auto lock or log out.
  rpc WaitForAutoLockOrLogOut(SetSecurityTokenRemovalRequest)
      returns (google.protobuf.Empty) {}

  // WebApplicationAuthentication performs web application authentication
  // with a smart card.
  rpc WebApplicationAuthentication(WebApplicationAuthenticationRequest)
      returns (google.protobuf.Empty) {}

  // DriveLockCSSIAppTesting opens Drivelock CSSI app and recognizes
  // the smart card.
  rpc DriveLockCSSIAppTesting(SetPINRequest) returns (google.protobuf.Empty) {}

  // VerifyCertificate verifies the account's certificate.
  rpc VerifyCertificate(VerifyCertificateRequest)
      returns (google.protobuf.Empty) {}
}

// NewCitrixRequest contains the information needed to create a new Citrix
// instance.
message NewCitrixRequest {
  string ota_username = 1;
  string ota_password = 2;
  string data_path = 3;
}

// ConnectUSBDeviceInCitrixRequest contains the information needed to connect
// USB device.
message ConnectUSBDeviceInCitrixRequest { string device_name = 1; }

// OpenCitrixAppRequest contains the information needed to open app in Citrix.
message OpenCitrixAppRequest {
  string app_name = 1;
  string app_title = 2;
  string app_icon = 3;
}

// CloseCitrixAppRequest contains the information needed to close app in Citrix.
message CloseCitrixAppRequest { string app_title = 1; }

// DeleteFileRequest contains the information needed to delete the file.
message DeleteFileRequest { string file_name = 1; }

// SaveCropScreenshotRequest contains the information needed to save the crop
// screenshot.
message SaveCropScreenshotRequest { string file_name = 1; }

// VerifyTwoImagesSimilarityRequest contains the information needed to verify
// two images are same or not.
message VerifyTwoImagesSimilarityRequest {
  string file_name1 = 1;
  string file_name2 = 2;
  bool expected_same = 3;
}

// WaitUntilIconExistsRequest contains the information needed to wait for the
// icon to exist.
message WaitUntilIconExistsRequest { string icon_name = 1; }

// FootPedalButton is the type of foot pedal button.
enum FootPedalButton {
  CENTER = 0;
  LEFT = 1;
  RIGHT = 2;
  TOP = 3;
}

// VerifyFootPedalButtonPressedRequest contains the information needed to verify
// the foot pedal button is pressed.
message VerifyFootPedalButtonPressedRequest { FootPedalButton button = 1; }

// StartSignature starts the sign process.
message StartSignatureRequest { string app_name = 1; }

// SignatureRequest contains the information needed to save/load/clear the
// signature.
message SignatureRequest { string file_name = 1; }

// ConnectToDictationDeviceRequest contains the information needed to connect to
// the dictation device.
message ConnectToDictationDeviceRequest { string device_name = 1; }

// GetDictationDevicesResponse contains the response of getting the devices.
message GetDictationDevicesResponse { string devices = 1; }

// WaitDictationNewEventRequest contains the information needed to wait for new
// event.
message WaitDictationNewEventRequest {
  string event = 1;
  int64 timeout = 2;
}

// KeyboardEventRequest contains the information needed to prepare and verify
// keyboard event.
message KeyboardEventRequest { string event = 1; }

// SetDictationEventModeRequest contains the information needed to set the event
// mode.
message SetDictationEventModeRequest { string event_mode = 1; }

// GetDictationEventModeResponse contains the response of getting the event
// mode.
message GetDictationEventModeResponse { string event_mode = 1; }

// SetDictationSimpleLEDStateRequest contains the information needed to set the
// simple LED state.
message SetDictationSimpleLEDStateRequest { string simple_led_state = 1; }

// SetDictationLEDStateRequest contains the information needed to set the LED
// state.
message SetDictationLEDStateRequest {
  string led_index = 1;
  string led_mode = 2;
}

// SetPINRequest contains the information needed to set PIN.
message SetPINRequest { string pin_code = 1; }

// SetPINResponse contains the response of setting PIN.
message SetPINResponse { string err = 1; }

// ReAuthenticationRequest contains the information needed to
// re-authentication.
message ReAuthenticationRequest {
  bool offline = 1;
  string pin_code = 2;
}

// SmartCardRemovalAndInsertionTestingRequest contains the information
// needed to test whether the UI during smart card removal and insertion
// is as expected.
message SmartCardRemovalAndInsertionTestingRequest {
  bool offline = 1;
  string wrong_pin_code = 2;
  string correct_pin_code = 3;
}

// SetSecurityTokenRemoval contains the information needed to set
// security token removal.
message SetSecurityTokenRemovalRequest {
  string security_policy_option = 1;
  int64 duration = 2;
}

// WebApplicationAuthenticationRequest contains the information needed
// to perform web application authentication.
message WebApplicationAuthenticationRequest {
  string email = 1;
  string pin_code = 2;
}

// VerifyCertificateRequest contains the information needed to verify
// certificate.
message VerifyCertificateRequest { string username = 1; }