// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package tast.cros.peripherals;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/peripherals";

// PeriphService provides RPC methods to be used by Peripherals remote test.
service PeriphService {
  // NewCitrix creates a new instance of Citrix and launches the Citrix app.
  rpc NewCitrix(NewCitrixRequest) returns (google.protobuf.Empty) {}

  // LoginCitrix logins the Citrix app and connects to desktop.
  rpc LoginCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // OpenCitrix launches the Citrix app.
  rpc OpenCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // CloseCitrix closes the Citrix app.
  rpc CloseCitrix(google.protobuf.Empty) returns (google.protobuf.Empty) {}

  // ConnectUSBDeviceInCitrix connects USB device.
  rpc ConnectUSBDeviceInCitrix(ConnectUSBDeviceInCitrixRequest)
      returns (google.protobuf.Empty) {}

  // OpenCitrixApp opens app in Citrix.
  rpc OpenCitrixApp(OpenCitrixAppRequest) returns (google.protobuf.Empty) {}

  // CloseCitrixApp closes app in Citrix.
  rpc CloseCitrixApp(CloseCitrixAppRequest) returns (google.protobuf.Empty) {}

  // DeleteFile deletes the signature.
  rpc DeleteFile(DeleteFileRequest) returns (google.protobuf.Empty) {}

  // DeleteFileIfExists deletes the file if it exists.
  rpc DeleteFileIfExists(DeleteFileRequest) returns (google.protobuf.Empty) {}

  // SaveCropScreenshot saves the crop screenshot.
  rpc SaveCropScreenshot(SaveCropScreenshotRequest)
      returns (google.protobuf.Empty) {}

  // VerifyTwoImagesSimilarity verifies two images are same or not.
  rpc VerifyTwoImagesSimilarity(VerifyTwoImagesSimilarityRequest)
      returns (google.protobuf.Empty) {}

  // WaitUntilIconExists waits for the icon to exist.
  rpc WaitUntilIconExists(WaitUntilIconExistsRequest)
      returns (google.protobuf.Empty) {}

  // SetupFootPedalTest sets up the foot pedal test.
  rpc SetupFootPedalTest(google.protobuf.Empty)
      returns (google.protobuf.Empty) {}

  // VerifyFootPedalButtonPressed verifies the foot pedal button is pressed.
  rpc VerifyFootPedalButtonPressed(VerifyFootPedalButtonPressedRequest)
      returns (google.protobuf.Empty) {}

  // StartSignature starts the sign process.
  rpc StartSignature(StartSignatureRequest) returns (google.protobuf.Empty) {}

  // SaveSignature saves the signature.
  rpc SaveSignature(SignatureRequest) returns (google.protobuf.Empty) {}

  // LoadSignature loads the signature.
  rpc LoadSignature(SignatureRequest) returns (google.protobuf.Empty) {}

  // ClearSignature clears the signature.
  rpc ClearSignature(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

// NewCitrixRequest contains the information needed to create a new Citrix
// instance.
message NewCitrixRequest {
  string ota_username = 1;
  string ota_password = 2;
  string data_path = 3;
}

// ConnectUSBDeviceInCitrixRequest contains the information needed to connect
// USB device.
message ConnectUSBDeviceInCitrixRequest { string device_name = 1; }

// OpenCitrixAppRequest contains the information needed to open app in Citrix.
message OpenCitrixAppRequest {
  string app_name = 1;
  string app_title = 2;
  string app_icon = 3;
}

// CloseCitrixAppRequest contains the information needed to close app in Citrix.
message CloseCitrixAppRequest { string app_title = 1; }

// DeleteFileRequest contains the information needed to delete the file.
message DeleteFileRequest { string file_name = 1; }

// SaveCropScreenshotRequest contains the information needed to save the crop
// screenshot.
message SaveCropScreenshotRequest { string file_name = 1; }

// VerifyTwoImagesSimilarityRequest contains the information needed to verify
// two images are same or not.
message VerifyTwoImagesSimilarityRequest {
  string file_name1 = 1;
  string file_name2 = 2;
  bool expected_same = 3;
}

// WaitUntilIconExistsRequest contains the information needed to wait for the
// icon to exist.
message WaitUntilIconExistsRequest { string icon_name = 1; }

// FootPedalButton is the type of foot pedal button.
enum FootPedalButton {
  CENTER = 0;
  LEFT = 1;
  RIGHT = 2;
  TOP = 3;
}

// VerifyFootPedalButtonPressedRequest contains the information needed to verify
// the foot pedal button is pressed.
message VerifyFootPedalButtonPressedRequest { FootPedalButton button = 1; }

// StartSignature starts the sign process.
message StartSignatureRequest { string app_name = 1; }

// SignatureRequest contains the information needed to save/load/clear the
// signature.
message SignatureRequest { string file_name = 1; }