// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.3
// source: periph_service.proto

package peripherals

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FootPedalButton is the type of foot pedal button.
type FootPedalButton int32

const (
	FootPedalButton_CENTER FootPedalButton = 0
	FootPedalButton_LEFT   FootPedalButton = 1
	FootPedalButton_RIGHT  FootPedalButton = 2
	FootPedalButton_TOP    FootPedalButton = 3
)

// Enum value maps for FootPedalButton.
var (
	FootPedalButton_name = map[int32]string{
		0: "CENTER",
		1: "LEFT",
		2: "RIGHT",
		3: "TOP",
	}
	FootPedalButton_value = map[string]int32{
		"CENTER": 0,
		"LEFT":   1,
		"RIGHT":  2,
		"TOP":    3,
	}
)

func (x FootPedalButton) Enum() *FootPedalButton {
	p := new(FootPedalButton)
	*p = x
	return p
}

func (x FootPedalButton) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FootPedalButton) Descriptor() protoreflect.EnumDescriptor {
	return file_periph_service_proto_enumTypes[0].Descriptor()
}

func (FootPedalButton) Type() protoreflect.EnumType {
	return &file_periph_service_proto_enumTypes[0]
}

func (x FootPedalButton) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FootPedalButton.Descriptor instead.
func (FootPedalButton) EnumDescriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{0}
}

// NewCitrixRequest contains the information needed to create a new Citrix
// instance.
type NewCitrixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtaUsername string `protobuf:"bytes,1,opt,name=ota_username,json=otaUsername,proto3" json:"ota_username,omitempty"`
	OtaPassword string `protobuf:"bytes,2,opt,name=ota_password,json=otaPassword,proto3" json:"ota_password,omitempty"`
	DataPath    string `protobuf:"bytes,3,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`
}

func (x *NewCitrixRequest) Reset() {
	*x = NewCitrixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCitrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCitrixRequest) ProtoMessage() {}

func (x *NewCitrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCitrixRequest.ProtoReflect.Descriptor instead.
func (*NewCitrixRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{0}
}

func (x *NewCitrixRequest) GetOtaUsername() string {
	if x != nil {
		return x.OtaUsername
	}
	return ""
}

func (x *NewCitrixRequest) GetOtaPassword() string {
	if x != nil {
		return x.OtaPassword
	}
	return ""
}

func (x *NewCitrixRequest) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

// ConnectUSBDeviceInCitrixRequest contains the information needed to connect
// USB device.
type ConnectUSBDeviceInCitrixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
}

func (x *ConnectUSBDeviceInCitrixRequest) Reset() {
	*x = ConnectUSBDeviceInCitrixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectUSBDeviceInCitrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUSBDeviceInCitrixRequest) ProtoMessage() {}

func (x *ConnectUSBDeviceInCitrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUSBDeviceInCitrixRequest.ProtoReflect.Descriptor instead.
func (*ConnectUSBDeviceInCitrixRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectUSBDeviceInCitrixRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// OpenCitrixAppRequest contains the information needed to open app in Citrix.
type OpenCitrixAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName  string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppTitle string `protobuf:"bytes,2,opt,name=app_title,json=appTitle,proto3" json:"app_title,omitempty"`
	AppIcon  string `protobuf:"bytes,3,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
}

func (x *OpenCitrixAppRequest) Reset() {
	*x = OpenCitrixAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenCitrixAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCitrixAppRequest) ProtoMessage() {}

func (x *OpenCitrixAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCitrixAppRequest.ProtoReflect.Descriptor instead.
func (*OpenCitrixAppRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{2}
}

func (x *OpenCitrixAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *OpenCitrixAppRequest) GetAppTitle() string {
	if x != nil {
		return x.AppTitle
	}
	return ""
}

func (x *OpenCitrixAppRequest) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

// CloseCitrixAppRequest contains the information needed to close app in Citrix.
type CloseCitrixAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppTitle string `protobuf:"bytes,1,opt,name=app_title,json=appTitle,proto3" json:"app_title,omitempty"`
}

func (x *CloseCitrixAppRequest) Reset() {
	*x = CloseCitrixAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseCitrixAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCitrixAppRequest) ProtoMessage() {}

func (x *CloseCitrixAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCitrixAppRequest.ProtoReflect.Descriptor instead.
func (*CloseCitrixAppRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{3}
}

func (x *CloseCitrixAppRequest) GetAppTitle() string {
	if x != nil {
		return x.AppTitle
	}
	return ""
}

// DeleteFileRequest contains the information needed to delete the file.
type DeleteFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// SaveCropScreenshotRequest contains the information needed to save the crop
// screenshot.
type SaveCropScreenshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *SaveCropScreenshotRequest) Reset() {
	*x = SaveCropScreenshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveCropScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCropScreenshotRequest) ProtoMessage() {}

func (x *SaveCropScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCropScreenshotRequest.ProtoReflect.Descriptor instead.
func (*SaveCropScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{5}
}

func (x *SaveCropScreenshotRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// VerifyTwoImagesSimilarityRequest contains the information needed to verify
// two images are same or not.
type VerifyTwoImagesSimilarityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName1    string `protobuf:"bytes,1,opt,name=file_name1,json=fileName1,proto3" json:"file_name1,omitempty"`
	FileName2    string `protobuf:"bytes,2,opt,name=file_name2,json=fileName2,proto3" json:"file_name2,omitempty"`
	ExpectedSame bool   `protobuf:"varint,3,opt,name=expected_same,json=expectedSame,proto3" json:"expected_same,omitempty"`
}

func (x *VerifyTwoImagesSimilarityRequest) Reset() {
	*x = VerifyTwoImagesSimilarityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTwoImagesSimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTwoImagesSimilarityRequest) ProtoMessage() {}

func (x *VerifyTwoImagesSimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTwoImagesSimilarityRequest.ProtoReflect.Descriptor instead.
func (*VerifyTwoImagesSimilarityRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTwoImagesSimilarityRequest) GetFileName1() string {
	if x != nil {
		return x.FileName1
	}
	return ""
}

func (x *VerifyTwoImagesSimilarityRequest) GetFileName2() string {
	if x != nil {
		return x.FileName2
	}
	return ""
}

func (x *VerifyTwoImagesSimilarityRequest) GetExpectedSame() bool {
	if x != nil {
		return x.ExpectedSame
	}
	return false
}

// WaitUntilIconExistsRequest contains the information needed to wait for the
// icon to exist.
type WaitUntilIconExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IconName string `protobuf:"bytes,1,opt,name=icon_name,json=iconName,proto3" json:"icon_name,omitempty"`
}

func (x *WaitUntilIconExistsRequest) Reset() {
	*x = WaitUntilIconExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitUntilIconExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitUntilIconExistsRequest) ProtoMessage() {}

func (x *WaitUntilIconExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitUntilIconExistsRequest.ProtoReflect.Descriptor instead.
func (*WaitUntilIconExistsRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{7}
}

func (x *WaitUntilIconExistsRequest) GetIconName() string {
	if x != nil {
		return x.IconName
	}
	return ""
}

// VerifyFootPedalButtonPressedRequest contains the information needed to verify
// the foot pedal button is pressed.
type VerifyFootPedalButtonPressedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Button FootPedalButton `protobuf:"varint,1,opt,name=button,proto3,enum=tast.cros.peripherals.FootPedalButton" json:"button,omitempty"`
}

func (x *VerifyFootPedalButtonPressedRequest) Reset() {
	*x = VerifyFootPedalButtonPressedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyFootPedalButtonPressedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyFootPedalButtonPressedRequest) ProtoMessage() {}

func (x *VerifyFootPedalButtonPressedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyFootPedalButtonPressedRequest.ProtoReflect.Descriptor instead.
func (*VerifyFootPedalButtonPressedRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyFootPedalButtonPressedRequest) GetButton() FootPedalButton {
	if x != nil {
		return x.Button
	}
	return FootPedalButton_CENTER
}

// StartSignature starts the sign process.
type StartSignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *StartSignatureRequest) Reset() {
	*x = StartSignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignatureRequest) ProtoMessage() {}

func (x *StartSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignatureRequest.ProtoReflect.Descriptor instead.
func (*StartSignatureRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{9}
}

func (x *StartSignatureRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// SignatureRequest contains the information needed to save/load/clear the
// signature.
type SignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *SignatureRequest) Reset() {
	*x = SignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_periph_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRequest) ProtoMessage() {}

func (x *SignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_periph_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRequest.ProtoReflect.Descriptor instead.
func (*SignatureRequest) Descriptor() ([]byte, []int) {
	return file_periph_service_proto_rawDescGZIP(), []int{10}
}

func (x *SignatureRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_periph_service_proto protoreflect.FileDescriptor

var file_periph_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f,
	0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x10, 0x4e, 0x65,
	0x77, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x74, 0x61, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x74, 0x61, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x74, 0x61, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x42, 0x0a, 0x1f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x53, 0x42, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x14, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x69, 0x74,
	0x72, 0x69, 0x78, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x70,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x63, 0x6f, 0x6e,
	0x22, 0x34, 0x0a, 0x15, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x70,
	0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70,
	0x70, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x19, 0x53, 0x61, 0x76, 0x65,
	0x43, 0x72, 0x6f, 0x70, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x20, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x77, 0x6f,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x31, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x32, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x5f, 0x73, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x1a, 0x57, 0x61,
	0x69, 0x74, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x49, 0x63, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x63, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x23, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46,
	0x6f, 0x6f, 0x74, 0x50, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x06,
	0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x74,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x73, 0x2e, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x15,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2f, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x2a, 0x3b, 0x0a, 0x0f, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x65, 0x64, 0x61, 0x6c, 0x42, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49,
	0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x4f, 0x50, 0x10, 0x03, 0x32, 0xa7,
	0x0c, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x69, 0x70, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4e, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x12, 0x27, 0x2e,
	0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x6c, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x53, 0x42,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x12, 0x36,
	0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x53,
	0x42, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x56, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x41, 0x70,
	0x70, 0x12, 0x2b, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65,
	0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x69,
	0x74, 0x72, 0x69, 0x78, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0e, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x41, 0x70, 0x70, 0x12, 0x2c, 0x2e, 0x74, 0x61, 0x73,
	0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61,
	0x6c, 0x73, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x69, 0x74, 0x72, 0x69, 0x78, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x50, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x28, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x66, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x74, 0x61, 0x73,
	0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61,
	0x6c, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x60,
	0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x43, 0x72, 0x6f, 0x70, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x30, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73,
	0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x43, 0x72, 0x6f, 0x70, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x6e, 0x0a, 0x19, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x77, 0x6f, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x37, 0x2e,
	0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x77, 0x6f, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x62, 0x0a, 0x13, 0x57, 0x61, 0x69, 0x74, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x49, 0x63, 0x6f,
	0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x31, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63,
	0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x49, 0x63, 0x6f, 0x6e, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x75, 0x70, 0x46, 0x6f, 0x6f,
	0x74, 0x50, 0x65, 0x64, 0x61, 0x6c, 0x54, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x1c,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x65, 0x64, 0x61, 0x6c, 0x42,
	0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x3a, 0x2e, 0x74,
	0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x61, 0x6c, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x6f, 0x6f, 0x74, 0x50,
	0x65, 0x64, 0x61, 0x6c, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x2c, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73,
	0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d,
	0x53, 0x61, 0x76, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x27, 0x2e,
	0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x27, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x65,
	0x72, 0x69, 0x70, 0x68, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x6f, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x61, 0x73, 0x74,
	0x2d, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_periph_service_proto_rawDescOnce sync.Once
	file_periph_service_proto_rawDescData = file_periph_service_proto_rawDesc
)

func file_periph_service_proto_rawDescGZIP() []byte {
	file_periph_service_proto_rawDescOnce.Do(func() {
		file_periph_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_periph_service_proto_rawDescData)
	})
	return file_periph_service_proto_rawDescData
}

var file_periph_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_periph_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_periph_service_proto_goTypes = []interface{}{
	(FootPedalButton)(0),                        // 0: tast.cros.peripherals.FootPedalButton
	(*NewCitrixRequest)(nil),                    // 1: tast.cros.peripherals.NewCitrixRequest
	(*ConnectUSBDeviceInCitrixRequest)(nil),     // 2: tast.cros.peripherals.ConnectUSBDeviceInCitrixRequest
	(*OpenCitrixAppRequest)(nil),                // 3: tast.cros.peripherals.OpenCitrixAppRequest
	(*CloseCitrixAppRequest)(nil),               // 4: tast.cros.peripherals.CloseCitrixAppRequest
	(*DeleteFileRequest)(nil),                   // 5: tast.cros.peripherals.DeleteFileRequest
	(*SaveCropScreenshotRequest)(nil),           // 6: tast.cros.peripherals.SaveCropScreenshotRequest
	(*VerifyTwoImagesSimilarityRequest)(nil),    // 7: tast.cros.peripherals.VerifyTwoImagesSimilarityRequest
	(*WaitUntilIconExistsRequest)(nil),          // 8: tast.cros.peripherals.WaitUntilIconExistsRequest
	(*VerifyFootPedalButtonPressedRequest)(nil), // 9: tast.cros.peripherals.VerifyFootPedalButtonPressedRequest
	(*StartSignatureRequest)(nil),               // 10: tast.cros.peripherals.StartSignatureRequest
	(*SignatureRequest)(nil),                    // 11: tast.cros.peripherals.SignatureRequest
	(*emptypb.Empty)(nil),                       // 12: google.protobuf.Empty
}
var file_periph_service_proto_depIdxs = []int32{
	0,  // 0: tast.cros.peripherals.VerifyFootPedalButtonPressedRequest.button:type_name -> tast.cros.peripherals.FootPedalButton
	1,  // 1: tast.cros.peripherals.PeriphService.NewCitrix:input_type -> tast.cros.peripherals.NewCitrixRequest
	12, // 2: tast.cros.peripherals.PeriphService.LoginCitrix:input_type -> google.protobuf.Empty
	12, // 3: tast.cros.peripherals.PeriphService.OpenCitrix:input_type -> google.protobuf.Empty
	12, // 4: tast.cros.peripherals.PeriphService.CloseCitrix:input_type -> google.protobuf.Empty
	2,  // 5: tast.cros.peripherals.PeriphService.ConnectUSBDeviceInCitrix:input_type -> tast.cros.peripherals.ConnectUSBDeviceInCitrixRequest
	3,  // 6: tast.cros.peripherals.PeriphService.OpenCitrixApp:input_type -> tast.cros.peripherals.OpenCitrixAppRequest
	4,  // 7: tast.cros.peripherals.PeriphService.CloseCitrixApp:input_type -> tast.cros.peripherals.CloseCitrixAppRequest
	5,  // 8: tast.cros.peripherals.PeriphService.DeleteFile:input_type -> tast.cros.peripherals.DeleteFileRequest
	5,  // 9: tast.cros.peripherals.PeriphService.DeleteFileIfExists:input_type -> tast.cros.peripherals.DeleteFileRequest
	6,  // 10: tast.cros.peripherals.PeriphService.SaveCropScreenshot:input_type -> tast.cros.peripherals.SaveCropScreenshotRequest
	7,  // 11: tast.cros.peripherals.PeriphService.VerifyTwoImagesSimilarity:input_type -> tast.cros.peripherals.VerifyTwoImagesSimilarityRequest
	8,  // 12: tast.cros.peripherals.PeriphService.WaitUntilIconExists:input_type -> tast.cros.peripherals.WaitUntilIconExistsRequest
	12, // 13: tast.cros.peripherals.PeriphService.SetupFootPedalTest:input_type -> google.protobuf.Empty
	9,  // 14: tast.cros.peripherals.PeriphService.VerifyFootPedalButtonPressed:input_type -> tast.cros.peripherals.VerifyFootPedalButtonPressedRequest
	10, // 15: tast.cros.peripherals.PeriphService.StartSignature:input_type -> tast.cros.peripherals.StartSignatureRequest
	11, // 16: tast.cros.peripherals.PeriphService.SaveSignature:input_type -> tast.cros.peripherals.SignatureRequest
	11, // 17: tast.cros.peripherals.PeriphService.LoadSignature:input_type -> tast.cros.peripherals.SignatureRequest
	12, // 18: tast.cros.peripherals.PeriphService.ClearSignature:input_type -> google.protobuf.Empty
	12, // 19: tast.cros.peripherals.PeriphService.NewCitrix:output_type -> google.protobuf.Empty
	12, // 20: tast.cros.peripherals.PeriphService.LoginCitrix:output_type -> google.protobuf.Empty
	12, // 21: tast.cros.peripherals.PeriphService.OpenCitrix:output_type -> google.protobuf.Empty
	12, // 22: tast.cros.peripherals.PeriphService.CloseCitrix:output_type -> google.protobuf.Empty
	12, // 23: tast.cros.peripherals.PeriphService.ConnectUSBDeviceInCitrix:output_type -> google.protobuf.Empty
	12, // 24: tast.cros.peripherals.PeriphService.OpenCitrixApp:output_type -> google.protobuf.Empty
	12, // 25: tast.cros.peripherals.PeriphService.CloseCitrixApp:output_type -> google.protobuf.Empty
	12, // 26: tast.cros.peripherals.PeriphService.DeleteFile:output_type -> google.protobuf.Empty
	12, // 27: tast.cros.peripherals.PeriphService.DeleteFileIfExists:output_type -> google.protobuf.Empty
	12, // 28: tast.cros.peripherals.PeriphService.SaveCropScreenshot:output_type -> google.protobuf.Empty
	12, // 29: tast.cros.peripherals.PeriphService.VerifyTwoImagesSimilarity:output_type -> google.protobuf.Empty
	12, // 30: tast.cros.peripherals.PeriphService.WaitUntilIconExists:output_type -> google.protobuf.Empty
	12, // 31: tast.cros.peripherals.PeriphService.SetupFootPedalTest:output_type -> google.protobuf.Empty
	12, // 32: tast.cros.peripherals.PeriphService.VerifyFootPedalButtonPressed:output_type -> google.protobuf.Empty
	12, // 33: tast.cros.peripherals.PeriphService.StartSignature:output_type -> google.protobuf.Empty
	12, // 34: tast.cros.peripherals.PeriphService.SaveSignature:output_type -> google.protobuf.Empty
	12, // 35: tast.cros.peripherals.PeriphService.LoadSignature:output_type -> google.protobuf.Empty
	12, // 36: tast.cros.peripherals.PeriphService.ClearSignature:output_type -> google.protobuf.Empty
	19, // [19:37] is the sub-list for method output_type
	1,  // [1:19] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_periph_service_proto_init() }
func file_periph_service_proto_init() {
	if File_periph_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_periph_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCitrixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectUSBDeviceInCitrixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenCitrixAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseCitrixAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveCropScreenshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTwoImagesSimilarityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitUntilIconExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyFootPedalButtonPressedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_periph_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_periph_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_periph_service_proto_goTypes,
		DependencyIndexes: file_periph_service_proto_depIdxs,
		EnumInfos:         file_periph_service_proto_enumTypes,
		MessageInfos:      file_periph_service_proto_msgTypes,
	}.Build()
	File_periph_service_proto = out.File
	file_periph_service_proto_rawDesc = nil
	file_periph_service_proto_goTypes = nil
	file_periph_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PeriphServiceClient is the client API for PeriphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeriphServiceClient interface {
	// NewCitrix creates a new instance of Citrix and launches the Citrix app.
	NewCitrix(ctx context.Context, in *NewCitrixRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LoginCitrix logins the Citrix app and connects to desktop.
	LoginCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// OpenCitrix launches the Citrix app.
	OpenCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CloseCitrix closes the Citrix app.
	CloseCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ConnectUSBDeviceInCitrix connects USB device.
	ConnectUSBDeviceInCitrix(ctx context.Context, in *ConnectUSBDeviceInCitrixRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// OpenCitrixApp opens app in Citrix.
	OpenCitrixApp(ctx context.Context, in *OpenCitrixAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CloseCitrixApp closes app in Citrix.
	CloseCitrixApp(ctx context.Context, in *CloseCitrixAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteFile deletes the signature.
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteFileIfExists deletes the file if it exists.
	DeleteFileIfExists(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SaveCropScreenshot saves the crop screenshot.
	SaveCropScreenshot(ctx context.Context, in *SaveCropScreenshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// VerifyTwoImagesSimilarity verifies two images are same or not.
	VerifyTwoImagesSimilarity(ctx context.Context, in *VerifyTwoImagesSimilarityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// WaitUntilIconExists waits for the icon to exist.
	WaitUntilIconExists(ctx context.Context, in *WaitUntilIconExistsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SetupFootPedalTest sets up the foot pedal test.
	SetupFootPedalTest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// VerifyFootPedalButtonPressed verifies the foot pedal button is pressed.
	VerifyFootPedalButtonPressed(ctx context.Context, in *VerifyFootPedalButtonPressedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// StartSignature starts the sign process.
	StartSignature(ctx context.Context, in *StartSignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SaveSignature saves the signature.
	SaveSignature(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LoadSignature loads the signature.
	LoadSignature(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ClearSignature clears the signature.
	ClearSignature(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type periphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeriphServiceClient(cc grpc.ClientConnInterface) PeriphServiceClient {
	return &periphServiceClient{cc}
}

func (c *periphServiceClient) NewCitrix(ctx context.Context, in *NewCitrixRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/NewCitrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) LoginCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/LoginCitrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) OpenCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/OpenCitrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) CloseCitrix(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/CloseCitrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) ConnectUSBDeviceInCitrix(ctx context.Context, in *ConnectUSBDeviceInCitrixRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/ConnectUSBDeviceInCitrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) OpenCitrixApp(ctx context.Context, in *OpenCitrixAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/OpenCitrixApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) CloseCitrixApp(ctx context.Context, in *CloseCitrixAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/CloseCitrixApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) DeleteFileIfExists(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/DeleteFileIfExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) SaveCropScreenshot(ctx context.Context, in *SaveCropScreenshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/SaveCropScreenshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) VerifyTwoImagesSimilarity(ctx context.Context, in *VerifyTwoImagesSimilarityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/VerifyTwoImagesSimilarity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) WaitUntilIconExists(ctx context.Context, in *WaitUntilIconExistsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/WaitUntilIconExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) SetupFootPedalTest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/SetupFootPedalTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) VerifyFootPedalButtonPressed(ctx context.Context, in *VerifyFootPedalButtonPressedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/VerifyFootPedalButtonPressed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) StartSignature(ctx context.Context, in *StartSignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/StartSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) SaveSignature(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/SaveSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) LoadSignature(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/LoadSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periphServiceClient) ClearSignature(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.peripherals.PeriphService/ClearSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeriphServiceServer is the server API for PeriphService service.
type PeriphServiceServer interface {
	// NewCitrix creates a new instance of Citrix and launches the Citrix app.
	NewCitrix(context.Context, *NewCitrixRequest) (*emptypb.Empty, error)
	// LoginCitrix logins the Citrix app and connects to desktop.
	LoginCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// OpenCitrix launches the Citrix app.
	OpenCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// CloseCitrix closes the Citrix app.
	CloseCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// ConnectUSBDeviceInCitrix connects USB device.
	ConnectUSBDeviceInCitrix(context.Context, *ConnectUSBDeviceInCitrixRequest) (*emptypb.Empty, error)
	// OpenCitrixApp opens app in Citrix.
	OpenCitrixApp(context.Context, *OpenCitrixAppRequest) (*emptypb.Empty, error)
	// CloseCitrixApp closes app in Citrix.
	CloseCitrixApp(context.Context, *CloseCitrixAppRequest) (*emptypb.Empty, error)
	// DeleteFile deletes the signature.
	DeleteFile(context.Context, *DeleteFileRequest) (*emptypb.Empty, error)
	// DeleteFileIfExists deletes the file if it exists.
	DeleteFileIfExists(context.Context, *DeleteFileRequest) (*emptypb.Empty, error)
	// SaveCropScreenshot saves the crop screenshot.
	SaveCropScreenshot(context.Context, *SaveCropScreenshotRequest) (*emptypb.Empty, error)
	// VerifyTwoImagesSimilarity verifies two images are same or not.
	VerifyTwoImagesSimilarity(context.Context, *VerifyTwoImagesSimilarityRequest) (*emptypb.Empty, error)
	// WaitUntilIconExists waits for the icon to exist.
	WaitUntilIconExists(context.Context, *WaitUntilIconExistsRequest) (*emptypb.Empty, error)
	// SetupFootPedalTest sets up the foot pedal test.
	SetupFootPedalTest(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// VerifyFootPedalButtonPressed verifies the foot pedal button is pressed.
	VerifyFootPedalButtonPressed(context.Context, *VerifyFootPedalButtonPressedRequest) (*emptypb.Empty, error)
	// StartSignature starts the sign process.
	StartSignature(context.Context, *StartSignatureRequest) (*emptypb.Empty, error)
	// SaveSignature saves the signature.
	SaveSignature(context.Context, *SignatureRequest) (*emptypb.Empty, error)
	// LoadSignature loads the signature.
	LoadSignature(context.Context, *SignatureRequest) (*emptypb.Empty, error)
	// ClearSignature clears the signature.
	ClearSignature(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedPeriphServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPeriphServiceServer struct {
}

func (*UnimplementedPeriphServiceServer) NewCitrix(context.Context, *NewCitrixRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCitrix not implemented")
}
func (*UnimplementedPeriphServiceServer) LoginCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginCitrix not implemented")
}
func (*UnimplementedPeriphServiceServer) OpenCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenCitrix not implemented")
}
func (*UnimplementedPeriphServiceServer) CloseCitrix(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseCitrix not implemented")
}
func (*UnimplementedPeriphServiceServer) ConnectUSBDeviceInCitrix(context.Context, *ConnectUSBDeviceInCitrixRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUSBDeviceInCitrix not implemented")
}
func (*UnimplementedPeriphServiceServer) OpenCitrixApp(context.Context, *OpenCitrixAppRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenCitrixApp not implemented")
}
func (*UnimplementedPeriphServiceServer) CloseCitrixApp(context.Context, *CloseCitrixAppRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseCitrixApp not implemented")
}
func (*UnimplementedPeriphServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (*UnimplementedPeriphServiceServer) DeleteFileIfExists(context.Context, *DeleteFileRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFileIfExists not implemented")
}
func (*UnimplementedPeriphServiceServer) SaveCropScreenshot(context.Context, *SaveCropScreenshotRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCropScreenshot not implemented")
}
func (*UnimplementedPeriphServiceServer) VerifyTwoImagesSimilarity(context.Context, *VerifyTwoImagesSimilarityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTwoImagesSimilarity not implemented")
}
func (*UnimplementedPeriphServiceServer) WaitUntilIconExists(context.Context, *WaitUntilIconExistsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitUntilIconExists not implemented")
}
func (*UnimplementedPeriphServiceServer) SetupFootPedalTest(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupFootPedalTest not implemented")
}
func (*UnimplementedPeriphServiceServer) VerifyFootPedalButtonPressed(context.Context, *VerifyFootPedalButtonPressedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyFootPedalButtonPressed not implemented")
}
func (*UnimplementedPeriphServiceServer) StartSignature(context.Context, *StartSignatureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSignature not implemented")
}
func (*UnimplementedPeriphServiceServer) SaveSignature(context.Context, *SignatureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSignature not implemented")
}
func (*UnimplementedPeriphServiceServer) LoadSignature(context.Context, *SignatureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSignature not implemented")
}
func (*UnimplementedPeriphServiceServer) ClearSignature(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSignature not implemented")
}

func RegisterPeriphServiceServer(s *grpc.Server, srv PeriphServiceServer) {
	s.RegisterService(&_PeriphService_serviceDesc, srv)
}

func _PeriphService_NewCitrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCitrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).NewCitrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/NewCitrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).NewCitrix(ctx, req.(*NewCitrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_LoginCitrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).LoginCitrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/LoginCitrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).LoginCitrix(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_OpenCitrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).OpenCitrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/OpenCitrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).OpenCitrix(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_CloseCitrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).CloseCitrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/CloseCitrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).CloseCitrix(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_ConnectUSBDeviceInCitrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectUSBDeviceInCitrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).ConnectUSBDeviceInCitrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/ConnectUSBDeviceInCitrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).ConnectUSBDeviceInCitrix(ctx, req.(*ConnectUSBDeviceInCitrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_OpenCitrixApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenCitrixAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).OpenCitrixApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/OpenCitrixApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).OpenCitrixApp(ctx, req.(*OpenCitrixAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_CloseCitrixApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCitrixAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).CloseCitrixApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/CloseCitrixApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).CloseCitrixApp(ctx, req.(*CloseCitrixAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_DeleteFileIfExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).DeleteFileIfExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/DeleteFileIfExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).DeleteFileIfExists(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_SaveCropScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCropScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).SaveCropScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/SaveCropScreenshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).SaveCropScreenshot(ctx, req.(*SaveCropScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_VerifyTwoImagesSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTwoImagesSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).VerifyTwoImagesSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/VerifyTwoImagesSimilarity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).VerifyTwoImagesSimilarity(ctx, req.(*VerifyTwoImagesSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_WaitUntilIconExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitUntilIconExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).WaitUntilIconExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/WaitUntilIconExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).WaitUntilIconExists(ctx, req.(*WaitUntilIconExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_SetupFootPedalTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).SetupFootPedalTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/SetupFootPedalTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).SetupFootPedalTest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_VerifyFootPedalButtonPressed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyFootPedalButtonPressedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).VerifyFootPedalButtonPressed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/VerifyFootPedalButtonPressed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).VerifyFootPedalButtonPressed(ctx, req.(*VerifyFootPedalButtonPressedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_StartSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).StartSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/StartSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).StartSignature(ctx, req.(*StartSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_SaveSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).SaveSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/SaveSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).SaveSignature(ctx, req.(*SignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_LoadSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).LoadSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/LoadSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).LoadSignature(ctx, req.(*SignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriphService_ClearSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriphServiceServer).ClearSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.peripherals.PeriphService/ClearSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriphServiceServer).ClearSignature(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PeriphService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.peripherals.PeriphService",
	HandlerType: (*PeriphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewCitrix",
			Handler:    _PeriphService_NewCitrix_Handler,
		},
		{
			MethodName: "LoginCitrix",
			Handler:    _PeriphService_LoginCitrix_Handler,
		},
		{
			MethodName: "OpenCitrix",
			Handler:    _PeriphService_OpenCitrix_Handler,
		},
		{
			MethodName: "CloseCitrix",
			Handler:    _PeriphService_CloseCitrix_Handler,
		},
		{
			MethodName: "ConnectUSBDeviceInCitrix",
			Handler:    _PeriphService_ConnectUSBDeviceInCitrix_Handler,
		},
		{
			MethodName: "OpenCitrixApp",
			Handler:    _PeriphService_OpenCitrixApp_Handler,
		},
		{
			MethodName: "CloseCitrixApp",
			Handler:    _PeriphService_CloseCitrixApp_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _PeriphService_DeleteFile_Handler,
		},
		{
			MethodName: "DeleteFileIfExists",
			Handler:    _PeriphService_DeleteFileIfExists_Handler,
		},
		{
			MethodName: "SaveCropScreenshot",
			Handler:    _PeriphService_SaveCropScreenshot_Handler,
		},
		{
			MethodName: "VerifyTwoImagesSimilarity",
			Handler:    _PeriphService_VerifyTwoImagesSimilarity_Handler,
		},
		{
			MethodName: "WaitUntilIconExists",
			Handler:    _PeriphService_WaitUntilIconExists_Handler,
		},
		{
			MethodName: "SetupFootPedalTest",
			Handler:    _PeriphService_SetupFootPedalTest_Handler,
		},
		{
			MethodName: "VerifyFootPedalButtonPressed",
			Handler:    _PeriphService_VerifyFootPedalButtonPressed_Handler,
		},
		{
			MethodName: "StartSignature",
			Handler:    _PeriphService_StartSignature_Handler,
		},
		{
			MethodName: "SaveSignature",
			Handler:    _PeriphService_SaveSignature_Handler,
		},
		{
			MethodName: "LoadSignature",
			Handler:    _PeriphService_LoadSignature_Handler,
		},
		{
			MethodName: "ClearSignature",
			Handler:    _PeriphService_ClearSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "periph_service.proto",
}
