// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package audio

import (
	"context"
	"os"

	"go.chromium.org/tast-tests/cros/common/chameleon"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

// DefaultChameleonUtilGeneratedAudioFormat describe audio format generated by default in GenerateTestRawDataChameleon
var DefaultChameleonUtilGeneratedAudioFormat = &TestRawData{
	BitsPerSample: 16,
	Channels:      2,
	Rate:          48000,
	Duration:      30,
	Frequencies:   []int{440, 440},
}

// GenerateTestRawDataForChameleon create a temp golden file and copy the audio
// file to Chameleon. This util needs to be local because create temp file and
// generate audio is to be done on DUT.
// A token is then returned to the user to be use to play audio.
// Check PlayFileByPortType function to get more info about how to play audio.
func GenerateTestRawDataForChameleon(
	ctx context.Context,
	chameleond chameleon.Chameleond,
	audioFormat *TestRawData,
) (goldenFile *os.File, token string, err error) {
	if audioFormat == nil {
		audioFormat = DefaultChameleonUtilGeneratedAudioFormat
	}

	goldenFile, err = os.CreateTemp("", "30SEC_*.raw")
	if err != nil {
		err = errors.Wrap(err, "failed to create golden file")
		return nil, "", err
	}
	if err := goldenFile.Close(); err != nil {
		err = errors.Wrap(err, "failed to close golden file")
		return nil, "", err
	}
	rawFile := TestRawData{
		Path:          goldenFile.Name(),
		BitsPerSample: audioFormat.BitsPerSample,
		Channels:      audioFormat.Channels,
		Rate:          audioFormat.Rate,
		Frequencies:   audioFormat.Frequencies,
		Volume:        0.05,
		Duration:      audioFormat.Duration,
	}
	if err := GenerateTestRawData(ctx, rawFile); err != nil {
		err = errors.Wrap(err, "failed to generate audio test data")
		return nil, "", err
	}

	bytes, err := os.ReadFile(rawFile.Path)
	if err != nil {
		err = errors.Wrap(err, "failed to read audio test data and convert to binary form")
		return nil, "", err
	}

	filename := "audio_example.raw"

	testing.ContextLog(ctx, "Copying audio file from DUT to Chameleon")
	token, err = chameleond.CopyFileToChameleon(ctx, bytes, filename)
	if err != nil {
		err = errors.Wrapf(err, "fail to copy sound file %s from DUT to chameleon", filename)
		return nil, "", err
	}

	return goldenFile, token, nil
}
