// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


syntax = "proto3";

package tast.cros.kiosk;

import "google/protobuf/empty.proto";

option go_package = "go.chromium.org/tast-tests/cros/services/cros/kiosk";

// Kiosk provides functions to perform on kiosk.
service KioskService {
  rpc InitSyslogReader(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc ConfirmKioskStartedWithReader(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc ConfirmKioskStarted(ConfirmKioskStartedRequest) returns (google.protobuf.Empty) {}
  rpc StartKiosk(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc UpdatePolicies(UpdatePoliciesRequest) returns (google.protobuf.Empty) {}
  rpc CloseKiosk(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message ConfirmKioskStartedRequest {
}

message UpdatePoliciesRequest {
  bytes policy_json = 1;
}
