// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package network

import (
	"context"
	"time"

	"go.chromium.org/tast-tests/cros/common/pci"
	"go.chromium.org/tast-tests/cros/common/policy"
	"go.chromium.org/tast-tests/cros/common/policy/fakedms"
	"go.chromium.org/tast-tests/cros/local/cellular"
	"go.chromium.org/tast-tests/cros/local/chrome"
	"go.chromium.org/tast-tests/cros/local/policyutil"
	"go.chromium.org/tast-tests/cros/local/policyutil/fixtures"

	"go.chromium.org/tast-tests/cros/local/chrome/ash"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/faillog"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/ossettings"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/quicksettings"
	"go.chromium.org/tast-tests/cros/local/chrome/uiauto/restriction"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/testing"
	"go.chromium.org/tast/core/testing/hwdep"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         HotspotPolicy,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Test hotspot policy will turn off active hotspot and restrict user from using hotspot properly",
		Contacts: []string{
			"cros-connectivity@google.com",
			"jiajunz@google.com",
		},
		BugComponent: "b:1281224", // ChromeOS > Software > System Services > Connectivity > Hotspot
		Attr:         []string{"group:cellular", "cellular_unstable", "cellular_sim_active", "cellular_run_isolated"},
		HardwareDeps: hwdep.D(hwdep.WifiSAP()),
		SoftwareDeps: []string{"chrome"},
		Fixture:      "cellularWithFakeDMSEnrolled",
		Timeout:      5 * time.Minute,
		SearchFlags: []*testing.StringPair{
			pci.SearchFlag(&policy.DeviceOpenNetworkConfiguration{}, pci.VerifiedFunctionalityOS),
		},
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.

			{
				Name:      "",
				Val:       "",
				ExtraAttr: []string{"cellular_carrier_local"},
			},
			{
				Name:      "tmobile",
				Val:       "tmobile",
				ExtraAttr: []string{"cellular_carrier_tmobile"},
			},
			{
				Name:      "docomo",
				Val:       "docomo",
				ExtraAttr: []string{"cellular_carrier_docomo"},
			},
			{
				Name:      "softbank",
				Val:       "softbank",
				ExtraAttr: []string{"cellular_carrier_softbank"},
			},
		},
	})
}

func HotspotPolicy(ctx context.Context, s *testing.State) {
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 10*time.Second)
	defer cancel()

	fdms := s.FixtValue().(fakedms.HasFakeDMS).FakeDMS()

	// Start a Chrome instance that will fetch policies from the FakeDMS.
	cr, err := chrome.New(ctx,
		chrome.FakeLogin(chrome.Creds{User: fixtures.Username, Pass: fixtures.Password}),
		chrome.EnableFeatures("Hotspot"),
		chrome.DMSPolicy(fdms.URL),
		chrome.KeepEnrollment())
	if err != nil {
		s.Fatal("Chrome login failed: ", err)
	}
	defer func(ctx context.Context) {
		policyutil.ResetChrome(ctx, fdms, cr)
		cr.Close(ctx)
	}(cleanupCtx)

	helper := s.FixtValue().(*cellular.FixtData).Helper
	if _, err := helper.Connect(ctx); err != nil {
		s.Fatal("Failed to connect to cellular service: ", err)
	}

	tconn, err := cr.TestAPIConn(ctx)
	if err != nil {
		s.Fatal("Failed to create Test API connection: ", err)
	}

	hs, err := ossettings.LaunchAtPage(ctx, tconn, ossettings.Network)
	if err != nil {
		s.Fatal("Failed to launch network page: ", err)
	}
	defer faillog.DumpUITreeWithScreenshotOnError(cleanupCtx, s.OutDir(), s.HasError, cr, "ui_tree")

	if err := hs.ToggleHotspot(ctx, tconn, cr, true); err != nil {
		s.Fatal("Failed to toggle on hotspot: ", err)
	}

	globalConfig := &policy.ONCGlobalNetworkConfiguration{
		AllowCellularHotspot: false,
	}

	deviceNetworkPolicy := &policy.DeviceOpenNetworkConfiguration{
		Val: &policy.ONC{
			GlobalNetworkConfiguration: globalConfig,
			NetworkConfigurations:      []*policy.ONCNetworkConfiguration{},
		},
	}

	// Apply Global Network Configuration.
	if err := policyutil.ServeAndRefresh(ctx, fdms, cr, []policy.Policy{deviceNetworkPolicy}); err != nil {
		s.Fatal("Failed to ServeAndRefresh ONC policy: ", err)
	}

	const title = "Hotspot is off"
	const message = "Your administrator has turned Hotspot off."
	if _, err := ash.WaitForNotification(ctx, tconn, 5*time.Second, ash.WaitTitle(title), ash.WaitMessageContains(message)); err != nil {
		s.Fatal("Failed to wait for the notification with title: Hotspot is off, err: ", err)
	}

	ui := uiauto.New(tconn)
	if err := uiauto.Combine("Verify hotspot is off and toggle disabled",
		ui.WaitUntilExists(ossettings.HotspotOffSublabel),
		ui.CheckRestriction(ossettings.HotspotToggle, restriction.Disabled),
	)(ctx); err != nil {
		s.Fatal("Failed to verify hotspot is off and toggle disabled: ", err)
	}

	if err := quicksettings.NavigateToHotspotDetailedView(ctx, tconn); err != nil {
		s.Fatal("Failed to navigate to hotspot detailed view: ", err)
	}

	if err := uiauto.Combine("Verify policy icon is shown and no response when clicking on toggle",
		ui.WaitUntilExists(quicksettings.HotspotPolicyImage),
		ui.LeftClick(quicksettings.HotspotDetailedViewToggle),
		ui.EnsureGoneFor(quicksettings.HotspotTurningOnText, 3*time.Second),
	)(ctx); err != nil {
		s.Fatal("Failed to see policy icon or toggle is not disabled: ", err)
	}
}
