// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package network

import (
	"context"
	"encoding/hex"
	"fmt"
	"io/ioutil"
	"math/rand"
	"net"
	"net/http"
	"os/user"
	"strconv"
	"strings"
	"syscall"
	"time"

	pp "go.chromium.org/chromiumos/system_api/patchpanel_proto"

	"go.chromium.org/tast-tests/cros/common/shillconst"
	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast-tests/cros/local/arc"
	"go.chromium.org/tast-tests/cros/local/crostini"
	"go.chromium.org/tast-tests/cros/local/network"
	arcnet "go.chromium.org/tast-tests/cros/local/network/arc"
	patchpanel "go.chromium.org/tast-tests/cros/local/network/patchpanel_client"
	"go.chromium.org/tast-tests/cros/local/network/virtualnet"
	"go.chromium.org/tast-tests/cros/local/network/virtualnet/env"
	"go.chromium.org/tast-tests/cros/local/network/virtualnet/httpserver"
	"go.chromium.org/tast-tests/cros/local/network/virtualnet/l4server"
	"go.chromium.org/tast-tests/cros/local/network/virtualnet/subnet"
	"go.chromium.org/tast-tests/cros/local/network/vpn"
	"go.chromium.org/tast-tests/cros/local/shill"
	"go.chromium.org/tast/core/ctxutil"
	"go.chromium.org/tast/core/errors"
	"go.chromium.org/tast/core/testing"
)

type tcSourceType int

const (
	tcSourceTypeUsers tcSourceType = iota
	tcSourceTypeVPN
	tcSourceTypeCrostini
	tcSourceTypeARC
)

type tcIPFamily int

const (
	tcIPv4 tcIPFamily = iota
	tcIPv6
)

func (f tcIPFamily) ppTrafficCounterFamily() pp.TrafficCounter_IpFamily {
	return []pp.TrafficCounter_IpFamily{pp.TrafficCounter_IPV4, pp.TrafficCounter_IPV6}[f]
}

func (f tcIPFamily) String() string {
	return []string{"ipv4", "ipv6"}[f]
}

type tcParams struct {
	source   tcSourceType
	ipFamily tcIPFamily
}

func init() {
	testing.AddTest(&testing.Test{
		Func:         TrafficCounters,
		Desc:         "Verify patchpanel traffic counters",
		Contacts:     []string{"cros-networking@google.com", "jiejiang@google.com"},
		BugComponent: "b:1493959",
		Attr:         []string{"group:mainline", "informational"},
		Timeout:      5 * time.Minute,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Params: []testing.Param{{
			Name: "users_ipv4",
			Val: tcParams{
				source:   tcSourceTypeUsers,
				ipFamily: tcIPv4,
			},
		}, {
			Name: "users_ipv6",
			Val: tcParams{
				source:   tcSourceTypeUsers,
				ipFamily: tcIPv6,
			},
		}, {
			Name: "vpn_ipv4",
			Val: tcParams{
				source:   tcSourceTypeVPN,
				ipFamily: tcIPv4,
			},
			ExtraSoftwareDeps: []string{"wireguard"},
		}, {
			Name: "crostini_ipv4",
			Val: tcParams{
				source:   tcSourceTypeCrostini,
				ipFamily: tcIPv4,
			},
			Fixture: "crostiniBullseye",
		}, {
			Name: "arc_ipv4",
			Val: tcParams{
				source:   tcSourceTypeARC,
				ipFamily: tcIPv4,
			},
			Fixture: "arcBooted",
		}}})
}

type server struct {
	rtEnv  *env.Env
	svrEnv *env.Env
	fam    l4server.Family
	port   int
	addr   net.IP
}

func (s server) dst() string {
	addr := s.addr.String()
	if len(s.addr) == net.IPv6len {
		addr = fmt.Sprintf("[%v]", addr)
	}
	return fmt.Sprintf("%v:%v", addr, s.port)
}

func (s *server) cleanup(ctx context.Context) {
	s.rtEnv.Cleanup(ctx)
	s.svrEnv.Cleanup(ctx)
}

type counters struct {
	tx, rx uint64
}

func ipFamily(f l4server.Family) pp.TrafficCounter_IpFamily {
	if f == l4server.UDP6 {
		return pp.TrafficCounter_IPV6
	}
	return pp.TrafficCounter_IPV4
}

// TrafficCounters verifies the patchpanel TrafficCounter API and behavior
// for network traffic generated by certain user IDs, when connected to a
// host VPN, and from ARC and Crostini.
// Verification is done "best effort" in the sense that this test will confirm
// that at-least as much traffic as sent and received is counter, but the actual
// amount may be higher.
// This test relies on virtualnet and checks both v4 and v6 networks. It expects
// the router on the v6 subnet to be reachable.
func TrafficCounters(ctx context.Context, s *testing.State) {
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 10*time.Second)
	defer cancel()

	param := s.Param().(tcParams)

	mgr, err := shill.NewManager(ctx)
	if err != nil {
		s.Fatal("Failed to create manager proxy: ", err)
	}
	restorePortal, err := mgr.DisablePortalDetectionWithRestore(ctx)
	if err != nil {
		s.Fatal("Failed to disable portal detection: ", err)
	}
	defer restorePortal(cleanupCtx)

	if param.source == tcSourceTypeARC {
		restoreEthernet, err := arcnet.HideUnusedEthernet(ctx, mgr)
		if err != nil {
			s.Fatal("Failed to hide unused ethernet: ", err)
		}
		defer restoreEthernet(cleanupCtx)
	}

	pc, err := patchpanel.New(ctx)
	if err != nil {
		s.Fatal("Failed to create patchpanel client: ", err)
	}

	pool := subnet.NewPool()
	svr, err := setup(ctx, mgr, pool, param.ipFamily)
	if err != nil {
		s.Fatal("Failed to setup router: ", err)
	}
	defer svr.cleanup(cleanupCtx)

	b := make([]byte, 128)
	rand.Seed(time.Now().UnixNano())
	rand.Read(b) // OK to elide error since its documented to return nil
	msg := hex.EncodeToString(b)
	msgLen := len(msg)

	key := func(dev string, src pp.TrafficCounter_Source, fam pp.TrafficCounter_IpFamily) string {
		return fmt.Sprintf("%v:%v:%v", dev, src.String(), fam.String())
	}

	// Retrieves counters from patchpanel, filtered to only those whose keys are
	// provided.
	getCounters := func(keys map[string]bool) map[string]*counters {
		ctrs := make(map[string]*counters)
		// GoBigSleepLint: Ensure the counters are flushed. There is some marginal
		// delay in when the updated values are ready; and while 2 seconds is an
		// arbitrary duration, it should be the case that this much time is more
		// than enough. The alternative to sleeping here is polling and managing
		// errors. This is much simpler to maintain and understand.
		testing.Sleep(ctx, 2*time.Second)
		resp, err := pc.GetTrafficCounters(ctx, []string{})
		if err != nil {
			s.Fatal("Failed to get traffic counters: ", err)
		}
		for _, tc := range resp.Counters {
			k := key(tc.GetDevice(), tc.GetSource(), tc.GetIpFamily())
			if _, ok := keys[k]; !ok {
				continue
			}
			ctrs[k] = &counters{tc.GetTxBytes(), tc.GetRxBytes()}
		}
		return ctrs
	}

	// Returns a slice of counter keys for the given traffic sources per device
	// and IP family.
	counterKeys := func(srcs []pp.TrafficCounter_Source) map[string]bool {
		keys := make(map[string]bool)
		for _, src := range srcs {
			keys[key(svr.rtEnv.VethOutName, src, ipFamily(svr.fam))] = true
		}
		return keys
	}

	// Generates traffic for each source on each server and returns map keyed by
	// the counters we expect to find based on the servers and sources provided.
	runIO := func(users []string) {
		for _, u := range users {
			if err := txrx(ctx, svr, msg, u); err != nil {
				s.Fatalf("Failed to run i/o test for %v:%v:%v: %v", u, svr.fam.String(), svr.dst(), err)
			}
		}
	}

	// Tests that traffic counters increase by at least an expected amount across
	// two consecutive runs. Only counters that map to keys are considered.
	// genTraffic is expected to generate traffic where both tx and rx should
	// larger than msgLen.
	test := func(keys map[string]bool, genTraffic func()) {
		// Generate initial set of counters.
		testing.ContextLog(ctx, "Generating traffic to get counters for baseline")
		genTraffic()
		base := getCounters(keys)
		// Verify we have all expected counters.
		for k := range keys {
			if _, ok := base[k]; !ok {
				s.Errorf("Expected baseline counter missing: %s", k)
			}
		}

		// Generate comparison set. Generate traffic a few times to make sure the
		// signal-to-noise ratio is large enough to reduce the chance of false
		// positive.
		testing.ContextLog(ctx, "Generating traffic to get counters for comparison")
		const iterations = 20
		for i := 0; i < iterations; i++ {
			genTraffic()
		}
		expectedDiff := uint64(iterations * msgLen)
		comp := getCounters(keys)
		for k, b := range base {
			c, ok := comp[k]
			if !ok {
				s.Errorf("Expected comparable counter missing: %s", k)
				continue
			}
			if c.tx < (b.tx + expectedDiff) {
				s.Errorf("Unexpected counter result for %v tx: got diff=%v-%v=%v, want diff>=%v", k, c.tx, b.tx, (c.tx - b.tx), expectedDiff)
			}
			if c.rx < (b.rx + expectedDiff) {
				s.Errorf("Unexpected counter result for %v rx: got diff=%v-%v=%v, want diff>=%v", k, c.rx, b.rx, (c.rx - b.rx), expectedDiff)
			}
		}
	}

	// Test traffic counted by user ID.
	if param.source == tcSourceTypeUsers {
		expected := counterKeys([]pp.TrafficCounter_Source{
			pp.TrafficCounter_SYSTEM,
			pp.TrafficCounter_USER,
			pp.TrafficCounter_CHROME,
		})
		test(
			expected,
			func() {
				runIO([]string{
					"kerberosd", // SYSTEM
					"debugd",    // USER
					"chronos",   // CHROME
				})
			})
	}

	// Test traffic counted for host VPN.
	if param.source == tcSourceTypeVPN {
		// Connect the VPN.
		conn, err := vpn.StartConnection(
			ctx, svr.svrEnv, vpn.TypeWireGuard,
			// l4server is only listening on underlay address now.
			vpn.WithAllowingReachUnderlayIP(),
		)
		if err != nil {
			s.Fatal("Failed to connect vpn: ", err)
		}
		defer conn.Cleanup(cleanupCtx)

		expected := counterKeys([]pp.TrafficCounter_Source{
			pp.TrafficCounter_VPN,
		})
		// Inject the counter we expect to see for chrome traffic on
		// the vpn device.
		expected[key("vpn", pp.TrafficCounter_CHROME, param.ipFamily.ppTrafficCounterFamily())] = true
		test(
			expected,
			func() {
				runIO([]string{"chronos"})
			})
	}

	vmTest := func(srcs []pp.TrafficCounter_Source, f func(addr net.IP) error) {
		handler := func(resp http.ResponseWriter, req *http.Request) {
			// Request payload is unused. Log any error on failure though to help
			// debug if the test fails.
			if _, err := ioutil.ReadAll(req.Body); err != nil {
				testing.ContextLog(ctx, "Failed to read HTTP request: ", err)
			}
			resp.Header().Set("content-type", "application/octet-stream")
			resp.Header().Set("content-length", strconv.Itoa(msgLen))
			if _, err := resp.Write([]byte(msg)); err != nil {
				testing.ContextLog(ctx, "Failed to write HTTP reply: ", err)
			}
		}

		expected := counterKeys(srcs)

		// Spin up an HTTP server to handle the request.
		if err := svr.svrEnv.StartServer(ctx, "http", httpserver.New(httpserver.TCP4, "80", handler, nil)); err != nil {
			s.Fatal("Failed to start HTTP server: ", err)
		}
		test(expected,
			func() {
				if err := f(svr.addr); err != nil {
					s.Fatalf("Failed to run HTTP i/o test for %v:%v: %v", param.ipFamily.String(), svr.dst(), err)
				}
			})
	}

	// Test traffic originating from Crostini.
	if param.source == tcSourceTypeCrostini {
		cros := s.FixtValue().(crostini.FixtureData).Cont

		vmTest(
			[]pp.TrafficCounter_Source{pp.TrafficCounter_CROSTINI_VM},
			func(addr net.IP) error {
				// Use curl to generate some traffic to/from the HTTP server.
				args := []string{
					"curl",
					"-X", "PUT",
					"http://" + addr.String(),
					"--connect-timeout", "5",
					"-d", fmt.Sprintf(`{"msg":%s}`, msg),
				}
				return cros.Command(ctx, args...).Run(testexec.DumpLogOnError)
			})
	}

	// Test traffic originating from ARC++.
	if param.source == tcSourceTypeARC {
		a := s.FixtValue().(*arc.PreData).ARC

		vmTest(
			[]pp.TrafficCounter_Source{pp.TrafficCounter_ARC},
			func(addr net.IP) error {
				// Use dumpsys to generate some traffic to/from the HTTP server.
				// - "host_default" to force using the default network on the host since
				//   the network selection in ARC might not be the same as the host on
				//   T+. See b/265877162.
				// - Note that we cannot control the tx packet length here. We should
				//   consider switching to use the QoS test app which can send and
				//   receive UDP packets directly.
				args := []string{
					"wifi",
					"tools", "http", "host_default",
					"http://" + addr.String(),
				}
				return a.Command(ctx, "dumpsys", args...).Run(testexec.DumpLogOnError)
			})
	}
}

func setup(ctx context.Context, mgr *shill.Manager, pool *subnet.Pool, fam tcIPFamily) (*server, error) {
	opts := virtualnet.EnvOptions{
		Priority:   1,
		EnableDHCP: fam == tcIPv4,
		RAServer:   fam == tcIPv6,
	}
	svc, rtEnv, svrEnv, err := virtualnet.CreateRouterServerEnv(ctx, mgr, pool, opts)
	if err != nil {
		return nil, errors.Wrap(err, "failed to set up network env")
	}
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()
	defer func() {
		if rtEnv != nil {
			rtEnv.Cleanup(cleanupCtx)
		}
		if svrEnv != nil {
			svrEnv.Cleanup(cleanupCtx)
		}
	}()
	if err := svc.WaitForProperty(ctx, shillconst.ServicePropertyState, shillconst.ServiceStateOnline, 10*time.Second); err != nil {
		return nil, errors.Wrapf(err, "failed to wait for %s service", fam)
	}

	addrs, err := svrEnv.WaitForVethInAddrs(ctx, fam == tcIPv4, fam == tcIPv6)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to get %s server addrs: ", fam)
	}
	var addr net.IP
	var l4family l4server.Family
	if fam == tcIPv6 {
		addr = addrs.IPv6Addrs[0]
		l4family = l4server.UDP6
	} else {
		addr = addrs.IPv4Addr
		l4family = l4server.UDP4
	}
	port := network.UnusedOrRandomPort(ctx, l4family)
	udp := l4server.New(l4family, port, l4server.WithAddr(addr.String()), l4server.WithMsgHandler(l4server.Reflector()))
	if err := svrEnv.StartServer(ctx, fam.String(), udp); err != nil {
		return nil, errors.Wrapf(err, "failed to start %s server", fam)
	}
	svr := &server{
		rtEnv:  rtEnv,
		svrEnv: svrEnv,
		fam:    l4family,
		port:   port,
		addr:   addr,
	}
	rtEnv = nil
	svrEnv = nil
	return svr, nil
}

func txrx(ctx context.Context, svr *server, msg, usr string) error {
	// This bit is necessary to correctly run the i/o as the desired user (su/sudo do not).
	u, err := user.Lookup(usr)
	if err != nil {
		return errors.Errorf("failed to resolve user %s", usr)
	}
	uid, err := strconv.Atoi(u.Uid)
	if err != nil {
		return errors.Wrap(err, "invalid uid")
	}
	gid, err := strconv.Atoi(u.Gid)
	if err != nil {
		return errors.Wrap(err, "invalid gid")
	}

	args := []string{
		"echo",
		msg,
		"|",
		"socat",
		"-",
		fmt.Sprintf("%v:%v,sp=%v,reuseaddr", svr.fam.String(), svr.dst(), network.UnusedOrRandomPort(ctx, svr.fam)),
	}
	cmd := testexec.CommandContext(ctx, "bash", "-c", strings.Join(args, " "))
	cmd.Cmd.SysProcAttr = &syscall.SysProcAttr{
		Credential: &syscall.Credential{
			Uid: uint32(uid),
			Gid: uint32(gid),
		},
	}
	return cmd.Run(testexec.DumpLogOnError)
}
