// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.3
// source: stylus_evtest_capture_service.proto

package inputs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StylusEvtestCaptureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StylusLogPath    string `protobuf:"bytes,1,opt,name=StylusLogPath,proto3" json:"StylusLogPath,omitempty"`
	WidthResolution  uint32 `protobuf:"varint,2,opt,name=WidthResolution,proto3" json:"WidthResolution,omitempty"`
	HeightResolution uint32 `protobuf:"varint,3,opt,name=HeightResolution,proto3" json:"HeightResolution,omitempty"`
}

func (x *StylusEvtestCaptureResponse) Reset() {
	*x = StylusEvtestCaptureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stylus_evtest_capture_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StylusEvtestCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StylusEvtestCaptureResponse) ProtoMessage() {}

func (x *StylusEvtestCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stylus_evtest_capture_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StylusEvtestCaptureResponse.ProtoReflect.Descriptor instead.
func (*StylusEvtestCaptureResponse) Descriptor() ([]byte, []int) {
	return file_stylus_evtest_capture_service_proto_rawDescGZIP(), []int{0}
}

func (x *StylusEvtestCaptureResponse) GetStylusLogPath() string {
	if x != nil {
		return x.StylusLogPath
	}
	return ""
}

func (x *StylusEvtestCaptureResponse) GetWidthResolution() uint32 {
	if x != nil {
		return x.WidthResolution
	}
	return 0
}

func (x *StylusEvtestCaptureResponse) GetHeightResolution() uint32 {
	if x != nil {
		return x.HeightResolution
	}
	return 0
}

type GetScreenSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float32 `protobuf:"fixed32,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height float32 `protobuf:"fixed32,2,opt,name=Height,proto3" json:"Height,omitempty"`
}

func (x *GetScreenSizeResponse) Reset() {
	*x = GetScreenSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stylus_evtest_capture_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScreenSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenSizeResponse) ProtoMessage() {}

func (x *GetScreenSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stylus_evtest_capture_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenSizeResponse.ProtoReflect.Descriptor instead.
func (*GetScreenSizeResponse) Descriptor() ([]byte, []int) {
	return file_stylus_evtest_capture_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetScreenSizeResponse) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetScreenSizeResponse) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_stylus_evtest_capture_service_proto protoreflect.FileDescriptor

var file_stylus_evtest_capture_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x74, 0x79, 0x6c, 0x75, 0x73, 0x5f, 0x65, 0x76, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73,
	0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x1b, 0x53, 0x74, 0x79, 0x6c, 0x75, 0x73, 0x45,
	0x76, 0x74, 0x65, 0x73, 0x74, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74, 0x79, 0x6c, 0x75, 0x73, 0x4c, 0x6f,
	0x67, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x74, 0x79,
	0x6c, 0x75, 0x73, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x57, 0x69, 0x64, 0x74, 0x68, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x45, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0xdb, 0x02, 0x0a, 0x1a, 0x53, 0x74, 0x79, 0x6c,
	0x75, 0x73, 0x45, 0x76, 0x74, 0x65, 0x73, 0x74, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x74, 0x79, 0x6c, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2d, 0x2e, 0x74, 0x61, 0x73, 0x74, 0x2e,
	0x63, 0x72, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x79, 0x6c,
	0x75, 0x73, 0x45, 0x76, 0x74, 0x65, 0x73, 0x74, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x15, 0x53, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x79, 0x6c, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x27, 0x2e,
	0x74, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x07, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x55, 0x70, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x74, 0x61, 0x73, 0x74, 0x2d, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stylus_evtest_capture_service_proto_rawDescOnce sync.Once
	file_stylus_evtest_capture_service_proto_rawDescData = file_stylus_evtest_capture_service_proto_rawDesc
)

func file_stylus_evtest_capture_service_proto_rawDescGZIP() []byte {
	file_stylus_evtest_capture_service_proto_rawDescOnce.Do(func() {
		file_stylus_evtest_capture_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stylus_evtest_capture_service_proto_rawDescData)
	})
	return file_stylus_evtest_capture_service_proto_rawDescData
}

var file_stylus_evtest_capture_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stylus_evtest_capture_service_proto_goTypes = []interface{}{
	(*StylusEvtestCaptureResponse)(nil), // 0: tast.cros.inputs.StylusEvtestCaptureResponse
	(*GetScreenSizeResponse)(nil),       // 1: tast.cros.inputs.GetScreenSizeResponse
	(*emptypb.Empty)(nil),               // 2: google.protobuf.Empty
}
var file_stylus_evtest_capture_service_proto_depIdxs = []int32{
	2, // 0: tast.cros.inputs.StylusEvtestCaptureService.StartStylusDataCapture:input_type -> google.protobuf.Empty
	2, // 1: tast.cros.inputs.StylusEvtestCaptureService.StopStylusDataCapture:input_type -> google.protobuf.Empty
	2, // 2: tast.cros.inputs.StylusEvtestCaptureService.GetScreenSize:input_type -> google.protobuf.Empty
	2, // 3: tast.cros.inputs.StylusEvtestCaptureService.CleanUp:input_type -> google.protobuf.Empty
	0, // 4: tast.cros.inputs.StylusEvtestCaptureService.StartStylusDataCapture:output_type -> tast.cros.inputs.StylusEvtestCaptureResponse
	2, // 5: tast.cros.inputs.StylusEvtestCaptureService.StopStylusDataCapture:output_type -> google.protobuf.Empty
	1, // 6: tast.cros.inputs.StylusEvtestCaptureService.GetScreenSize:output_type -> tast.cros.inputs.GetScreenSizeResponse
	2, // 7: tast.cros.inputs.StylusEvtestCaptureService.CleanUp:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stylus_evtest_capture_service_proto_init() }
func file_stylus_evtest_capture_service_proto_init() {
	if File_stylus_evtest_capture_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stylus_evtest_capture_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StylusEvtestCaptureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stylus_evtest_capture_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScreenSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stylus_evtest_capture_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stylus_evtest_capture_service_proto_goTypes,
		DependencyIndexes: file_stylus_evtest_capture_service_proto_depIdxs,
		MessageInfos:      file_stylus_evtest_capture_service_proto_msgTypes,
	}.Build()
	File_stylus_evtest_capture_service_proto = out.File
	file_stylus_evtest_capture_service_proto_rawDesc = nil
	file_stylus_evtest_capture_service_proto_goTypes = nil
	file_stylus_evtest_capture_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StylusEvtestCaptureServiceClient is the client API for StylusEvtestCaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StylusEvtestCaptureServiceClient interface {
	StartStylusDataCapture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StylusEvtestCaptureResponse, error)
	StopStylusDataCapture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetScreenSize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetScreenSizeResponse, error)
	CleanUp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type stylusEvtestCaptureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStylusEvtestCaptureServiceClient(cc grpc.ClientConnInterface) StylusEvtestCaptureServiceClient {
	return &stylusEvtestCaptureServiceClient{cc}
}

func (c *stylusEvtestCaptureServiceClient) StartStylusDataCapture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StylusEvtestCaptureResponse, error) {
	out := new(StylusEvtestCaptureResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.inputs.StylusEvtestCaptureService/StartStylusDataCapture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stylusEvtestCaptureServiceClient) StopStylusDataCapture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.inputs.StylusEvtestCaptureService/StopStylusDataCapture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stylusEvtestCaptureServiceClient) GetScreenSize(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetScreenSizeResponse, error) {
	out := new(GetScreenSizeResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.inputs.StylusEvtestCaptureService/GetScreenSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stylusEvtestCaptureServiceClient) CleanUp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.inputs.StylusEvtestCaptureService/CleanUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StylusEvtestCaptureServiceServer is the server API for StylusEvtestCaptureService service.
type StylusEvtestCaptureServiceServer interface {
	StartStylusDataCapture(context.Context, *emptypb.Empty) (*StylusEvtestCaptureResponse, error)
	StopStylusDataCapture(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetScreenSize(context.Context, *emptypb.Empty) (*GetScreenSizeResponse, error)
	CleanUp(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedStylusEvtestCaptureServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStylusEvtestCaptureServiceServer struct {
}

func (*UnimplementedStylusEvtestCaptureServiceServer) StartStylusDataCapture(context.Context, *emptypb.Empty) (*StylusEvtestCaptureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStylusDataCapture not implemented")
}
func (*UnimplementedStylusEvtestCaptureServiceServer) StopStylusDataCapture(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStylusDataCapture not implemented")
}
func (*UnimplementedStylusEvtestCaptureServiceServer) GetScreenSize(context.Context, *emptypb.Empty) (*GetScreenSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScreenSize not implemented")
}
func (*UnimplementedStylusEvtestCaptureServiceServer) CleanUp(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanUp not implemented")
}

func RegisterStylusEvtestCaptureServiceServer(s *grpc.Server, srv StylusEvtestCaptureServiceServer) {
	s.RegisterService(&_StylusEvtestCaptureService_serviceDesc, srv)
}

func _StylusEvtestCaptureService_StartStylusDataCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StylusEvtestCaptureServiceServer).StartStylusDataCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.inputs.StylusEvtestCaptureService/StartStylusDataCapture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StylusEvtestCaptureServiceServer).StartStylusDataCapture(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StylusEvtestCaptureService_StopStylusDataCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StylusEvtestCaptureServiceServer).StopStylusDataCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.inputs.StylusEvtestCaptureService/StopStylusDataCapture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StylusEvtestCaptureServiceServer).StopStylusDataCapture(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StylusEvtestCaptureService_GetScreenSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StylusEvtestCaptureServiceServer).GetScreenSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.inputs.StylusEvtestCaptureService/GetScreenSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StylusEvtestCaptureServiceServer).GetScreenSize(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StylusEvtestCaptureService_CleanUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StylusEvtestCaptureServiceServer).CleanUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.inputs.StylusEvtestCaptureService/CleanUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StylusEvtestCaptureServiceServer).CleanUp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _StylusEvtestCaptureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.inputs.StylusEvtestCaptureService",
	HandlerType: (*StylusEvtestCaptureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStylusDataCapture",
			Handler:    _StylusEvtestCaptureService_StartStylusDataCapture_Handler,
		},
		{
			MethodName: "StopStylusDataCapture",
			Handler:    _StylusEvtestCaptureService_StopStylusDataCapture_Handler,
		},
		{
			MethodName: "GetScreenSize",
			Handler:    _StylusEvtestCaptureService_GetScreenSize_Handler,
		},
		{
			MethodName: "CleanUp",
			Handler:    _StylusEvtestCaptureService_CleanUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stylus_evtest_capture_service.proto",
}
