// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package wifi

import (
	"context"
	"io/ioutil"
	"path/filepath"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast/core/errors"
)

// SaveDebugData saves the debug data generated by |command| to test's output
// directory named as "<outDir>/<outputFile>"".
func SaveDebugData(ctx context.Context, outDir, outputFile, command string) error {
	output, err := testexec.CommandContext(ctx, "bash", "-c", command).Output(testexec.DumpLogOnError)
	if err != nil {
		return errors.Wrapf(err, "failed to execute command %s", command)
	}
	err = ioutil.WriteFile(filepath.Join(outDir, outputFile), output, 0644)
	if err != nil {
		return errors.Wrapf(err, "failed to save debug data to %s", outputFile)
	}
	return nil
}
