// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package wifi

import (
	"context"
	"io/ioutil"
	"path/filepath"

	"go.chromium.org/tast-tests/cros/common/testexec"
	"go.chromium.org/tast/core/testing"
)

// SaveDebugData saves the debug data generated by |command| to test's output
// directory named as |outputFile|.
func SaveDebugData[T testing.State | testing.FixtState | testing.FixtTestState, PT interface {
	*T
	OutDir() string
	Errorf(format string, args ...interface{})
}](ctx context.Context, state *T, outputFile, command string) {
	s := PT(state)
	output, err := testexec.CommandContext(ctx, "bash", "-c", command).Output(testexec.DumpLogOnError)
	if err != nil {
		s.Errorf("Failed to execute command %s: %v", command, err)
	}
	err = ioutil.WriteFile(filepath.Join(s.OutDir(), outputFile), output, 0644)
	if err != nil {
		s.Errorf("Failed to save debug data to %s: %v", outputFile, err)
	}
}
